### ISSUE TITLE
TabNine doesnt properly predict when automatic closing parenthesis

### ISSUE THREAD

**Issue by roangel** [codota/TabNine#100]
So, I use TabNine beta with Emacs, and I noticed that when I try to predict sentences that Emacs automatically closes when you open them, like parenthesis, quotation marks, etc. Then TabNine either doesn't predict, or doesn't take into account in the prediction that I already have the closing part of the sentence. Is there a fix for it?

Thanks!

**Comment by zxqfl** [comment]
Could you give an example?

**Comment by roangel** [comment]
So, lets say I get this prediction: 
![image](https://user-images.githubusercontent.com/21340299/61940953-c2394880-af96-11e9-9043-db3c14452872.png)
Now when I insert the closing parenthesis, the prediction dissapears:
![image](https://user-images.githubusercontent.com/21340299/61940985-d8470900-af96-11e9-89cd-37b7246a3dad.png)

It would be nice if the tool didn't get confused by Emacs adding the closing parenthesis in this case.

**Comment by zxqfl** [comment]
So it never shows a predication after you just typed a character which had an automatic matching closing character inserted by Emacs?

**Comment by roangel** [comment]
Exactly.
