### ISSUE TITLE
Suggestion: Visual Studio Support

### ISSUE THREAD

**Issue by delizin** [codota/TabNine#101]
When I am working on Windows systems, I use Visual Studio 2017 most of the time. VS Code isn't bad, but I find it lacks quite a few of the features that I like, especially when using python. 

I'd love to see Visual Studio support sometime in the future if it isn't too big of an issue. Thanks.

**Comment by Doggie52** [comment]
+1 ! I bet there's quite a few more of us who would want VS support.

**Comment by ckizziar** [comment]
+1 from me as well!

**Comment by CfirTsabari** [comment]
+1!!! i am sure that only because this issues is hard to find  you don't have a lot of traffic here:-)

**Comment by 99dneyleta** [comment]
+1 from me as well!

**Comment by opencai** [comment]
+100

**Comment by Meetsch** [comment]
+1

**Comment by meniku** [comment]
yes please!

**Comment by mhtvsSFrpHdE** [comment]
I here using .NET Core 3 and WinForms, it's forged with Visual Studio and unlikely able to use any of current supported IDEs.

**Comment by atticdweller** [comment]
+1

**Comment by lukasz-chmielewski** [comment]
+1

**Comment by ortizgames** [comment]
+1!

**Comment by tianxingyang** [comment]
+3000!!!

**Comment by avichay77** [comment]
All - this request is popular for a good reason! Actually it's already high on our backlog. 
 We will let you know once we start working on it.

Of course - if anyone volunteer to do this before we are able to : https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md

**Comment by yoshiask** [comment]
It's been two months, any updates?

**Comment by F-Unction** [comment]
It's been three months, any updates?

**Comment by lunmatu101** [comment]
It's been many months, any updates?

**Comment by Meetsch** [comment]
The status is closed, so I assume there will be no updates...

**Comment by avichay77** [comment]
We still have no updated on this issue. We did start to evaluate demand.

**Comment by boaz-codota** [comment]
We are trying to gauge community demand, so anyone wanting visual studio plugin, please star the dedicated repository:
https://github.com/codota/tabnine-visual-studio

**Comment by yoshiask** [comment]
![image](https://user-images.githubusercontent.com/7549325/102295877-e2620280-3f11-11eb-91dc-175a59f3ada5.png)
Just curious, was this not enough?

**Comment by oold** [comment]
> 
> 
> We are trying to gauge community demand, so anyone wanting visual studio plugin, please star the dedicated repository:
> https://github.com/codota/tabnine-visual-studio

Don't think that gauging demand by requiring people to star a GitHub repo nobody knows about is a good way of doing this. You guys should really have something like a UserVoice page.

**Comment by Valmirius** [comment]
This would be a fantastic addition, and guys in game development using a huge codebase like Unreal 4 would love this tool. It's much better than Intellicode and would complement Visual Assist very well.

**Comment by enkeyz** [comment]
Is this planned in the future?

**Comment by LukePoga** [comment]
why would it be hard to add VS 2019 support? its the most popular editor in the world?

**Comment by yoshiask** [comment]
We're approaching 12 months since this was said:
> Actually it's already high on our backlog.

I'm beginning to think it's not high on the backlog at all.

**Comment by enkeyz** [comment]
> We're approaching 12 months since this was said:
> 
> > Actually it's already high on our backlog.
> 
> I'm beginning to think it's not high on the backlog at all.

Visual Studio has the worst API for making extensions. Probably one of the reason why they don't waste their time making this happen.

**Comment by koloramax** [comment]
I want to use tabnine for unreal engine game development!!! (Rider for unreal engine will be PAID after public preview stage)

**Comment by shaigeva** [comment]
I'm Happy to announce that Tabnine for Visual Studio has been released!

Marketplace page: https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-visual-studio
Installation instructions: https://www.tabnine.com/install/visualstudio
Repo for feedback / issues: https://github.com/tabnine/tabnine-visual-studio/
