### ISSUE TITLE
Qt Creator Support

### ISSUE THREAD

**Issue by isgursoy** [codota/TabNine#103]
It would be great if you can support Qt Creator. It is defacto cpp IDE on Linux and quite common among developers for other platforms as well.

**Comment by isgursoy** [comment]
Can we speed up process by some donation?

**Comment by isgursoy** [comment]
Please see https://bugreports.qt.io/browse/QTCREATORBUG-22892
We need help about TabNine internals @zxqfl

**Comment by isgursoy** [comment]
I have a prototype, testing. I will drop its link I am done.

**Comment by isgursoy** [comment]
https://gitlab.com/isgursoy/qtc-tabnine

**Comment by ScottYang1982** [comment]
> https://gitlab.com/isgursoy/qtc-tabnine

Hi isgursoy,
   The link you gave does not exist , could you check it again ,thank you!!

**Comment by isgursoy** [comment]
Hi @ScottYang1982,
I made repo public again and added 4.11 support. Please try again and feel free to contribute.

**Comment by amircodota** [comment]
Hi @ScottYang1982 

Did it work?

**Comment by desert** [comment]
> Did it work?

Not for me, 4.11.2. Just got a bunch of UI errors that several plugins were unavailable because `libTextEditor` was not there.

**Comment by isgursoy** [comment]
libTextEditor is in the repository, I am distributing it for each qtc version. Installation is as simple as replacing your libTextEditor with mine. 

It is pretty much complete, yesterday I fixed language server use case and released 4.13 binary.

**Comment by isgursoy** [comment]
@amircodota good to list qtc port on the readme. So people can see and contribute.

**Comment by desert** [comment]
> > Did it work?
> 
> Not for me, 4.11.2. Just got a bunch of UI errors that several plugins were unavailable because `libTextEditor` was not there.

will try again this afternoon :)

**Comment by desert** [comment]
> libTextEditor is in the repository, I am distributing it for each qtc version. Installation is as simple as replacing your libTextEditor with mine.
> 
> It is pretty much complete, yesterday I fixed language server use case and released 4.13 binary.

Will try again this afternoon :)

**Comment by isgursoy** [comment]
Will be waiting for help to make it work, in GitLab issues.

**Comment by kelteseth** [comment]
@isgursoy your link is dead again...

**Comment by slitcch** [comment]
@isgursoy link is still dead
