### ISSUE TITLE
PowerShell support

### ISSUE THREAD

**Issue by dfinke** [codota/TabNine#114]
Was looking at how to wire up the PowerShell auto completion.

Here is how it was wired into `vim`.

There is no install component for it, need to get it from the GitHub repo.

Happy to try to wire it up, need some direction though.

https://github.com/yatli/coc-powershell/blob/307e00f8df36e462fdb08a4647cc50e35beea218/plugin/coc-powershell.vim#L27

**Comment by amircodota** [comment]
Hi @dfinke 

To get started writeing a TabNine client, you can follow [this guide](https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md)

Let us know if you need any assistance
