### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by asg0451** [codota/TabNine#115]
Ubuntu 18.04, 16G ram
I notice that over a couple days (I leave my laptop on), TabNine's memory footprint will grow to several GB. On kill-9 and restart it goes back to <1G.

**Comment by asg0451** [comment]
![image](https://user-images.githubusercontent.com/4358545/62714549-ccaf0580-b9cc-11e9-9e8a-9b96b36a3ffe.png)

this is TabNine using more RAM than Chrome after 2 days of uptime.

**Comment by Artoria-0x04** [comment]
Seems same to me. My Webstorm TabNine process consumed 8G memory after repeating ctrl-space for some times.

**Comment by pftbest** [comment]
Mine just ate 22GB of RAM. I had to kill the TabNine process because my system became quite slow.

**Comment by arye-dov-eidelman** [comment]
I already ordered more Ram before discovering that this is taking 1.4 GB of ram

**Comment by drorweiss** [comment]
Hi All, we have a fix in beta (version 2.3.4) for excessive CPU and memory consumption by TabNine.
We'd appreciate it if you try it out and let us know if it solves the issue for you.
To try the fix, you have to enable the beta version. Just open TabNine's config by typing TabNine::config in your editor, and then check both **Update TabNine automatically** and **Receive beta releases of TabNine** Then, restart your editor, and press TabNine::confiig to verify you have TabNine 2.3.4. or newer.  Please let us know if this version solves the problem for you. We plan to make it available to all users in a couple of weeks.

**Comment by jcassee** [comment]
@drorweiss I have been running 2.3.4 for a while, leaving Sublime Text running with it, and I have not been seeing the same memory usage as before. So it seems to work. Thanks!

**Comment by jcassee** [comment]
It seems I spoke too soon. But maybe it's not a memory leak but just using a lot of memory, period. I just booted my system and started Sublime Text with TabNine. It's immediately the most memory-hungry process. Maybe it is a different issue?

![Schermafdruk van 2020-02-19 17-27-18](https://user-images.githubusercontent.com/20749/74852811-658be980-533d-11ea-87b6-b5a3f495bae2.png)

/home/joost/.config/TabNine/tabnine_config.json:
```
{
  "version": "1.0.7",
  "hide_promotional_message": false,
  "beta_enabled": "Yes",
  "ignore_all_lsp": false,
  "creation_time": "2019-08-23T12:33:25.304771769Z",
  "semantic_status": {
    "javascript": "Enabled",
    "python": "Enabled"
  },
  "disable_auto_update": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": false,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "api_key": null,
  "api_key_service_level": null,
  "api_base_url": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": true,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null
}
```

Is this expected? If not, create a new issue? Can I do more debugging?

**Comment by asg0451** [comment]
I see TabNine using a lot of memory still, but thats not necessarily unexpected. yet to see it grow far beyond this though. I'll update back once i have a few days of uptime

![image](https://user-images.githubusercontent.com/4358545/74854404-4b3a1780-530d-11ea-947b-9fbca3812511.png)

**Comment by asg0451** [comment]
![image](https://user-images.githubusercontent.com/4358545/75160742-94f97800-56e8-11ea-8397-81d2da97902d.png)

after several days of uptime, tabnine's memory usage has grown, but this is definitely an improvement over the last version.

**Comment by amircodota** [comment]
A memory consumption of 1.5G-2.5G is expected, especially for large projects, with TabNine local enabled.

Closing this issue.
Please re-open if you see it grow far beyond 2.5G.

**Comment by jcassee** [comment]
@amircodota Good to know. Thanks!
