### ISSUE TITLE
install problem - MacOS - SEGV on first try

### ISSUE THREAD

**Issue by rdaniel** [codota/TabNine#117]
Hi,

Just tried Deep Tab9 but got memory error:

$ vi foo*
2 files to edit
Vim: Caught deadly signal SEGV

Error detected while processing function <SNR>24_PollServerReady[7]..<SNR>24_Pyeval:Vim: Finished.

line    4:
Exception MemoryError: MemoryError() in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
Segmentation fault: 11

I installed vundle, which I have not used before so that may be part of the problem.
Hardware is 2017 MacBook Pro 13"
OS is Mojave - 10.14.3
vim is 8.0.1283

**Comment by zxqfl** [comment]
Could you please provide steps to reproduce the issue?

**Comment by amircodota** [comment]
Cannot reproduce
