### ISSUE TITLE
Support LaTeX/BibTeX in deep TabNine

### ISSUE THREAD

**Issue by notano** [codota/TabNine#123]
I have no idea how hard it is to add the support for them, but I would love to see the support for LaTeX/BibTeX in deep TabNine.

Deep TabNine is a very awesome project! Thank you for providing it to us.

**Comment by zuxfoucault** [comment]
Use https://texlab.netlify.com/#download as Language Server Protocol?

**Comment by avichay77** [comment]
close as duplication of [#144]([https://github.com/codota/TabNine/issues/144])
