### ISSUE TITLE
Performance issue of TabNine Sublime extension

### ISSUE THREAD

**Issue by vbaranov** [codota/TabNine#124]
Sublime Text Version 3.2.1, Build 3207
TabNine v1.0.5

Worked on Elixir && JS project during the day and at the end of the day discovered that TabNine occupied 93% CPU

![Screenshot 2019-08-06 at 21 36 32](https://user-images.githubusercontent.com/4341812/62566948-cc125400-b892-11e9-86a6-e5be353a43d8.png)

**Comment by amircodota** [comment]
We have since made a lot of improvements to TabNine in terms of CPU and memory consumption.

Can you check the latest version? It should be fixed.

**Comment by Gabriel-p** [comment]
I just opened a new issue related to this one: #292. In my case the CPU usage is reasonable, but memory usage is ridiculous.
