### ISSUE TITLE
Getting weird suggestions

### ISSUE THREAD

**Issue by IOriens** [codota/TabNine#132]
I'm a JavaScript developer. When I'm writing Typescript or pure JavasScript, TabNine always suggest variable names with underscore joint. What I actually want is Camel-Cased variable. You could see an example from the image bellow.

![image](https://user-images.githubusercontent.com/8137136/63212077-19fc4700-c132-11e9-8b33-2ef03411465d.png)

TabNine should suggest `downloadHtml` rather than `download_html` .

**Comment by suzdalnitski** [comment]
I'm facing the same issue, both JavaScript and Elm. This is very annoying and makes an otherwise amazing product worthless...

**Comment by pastuh** [comment]
How to disable this?
At this moment i write +50% slower with this annoying underscore.
