### ISSUE TITLE
Way to exclude sensitive data

### ISSUE THREAD

**Issue by prein** [codota/TabNine#135]
Hi, I started using Vim plugin. I'm seeing suggestions based on sensitive data (passwords / secrets) that appeared in some other files I must have opened with Vim I guess. For example if there would be a password starting with "fo" I would see it appear as suggestion when I start typing "foo" (for a variable name for example).
Is there a way to prevent strings that look like they could be passwords from being remembered?

**Comment by logankopas** [comment]
I've also noticed that other people's emails can be leaked through autocompletion (cloud beta)

**Comment by amircodota** [comment]
Currently, there's no way to exclude specific tokens from being indexed by TabNine.

TabNine does not index files that are in `.gitignore`, `.hgignore` etc.
Usually sensitive data is not committed to vcs, and so it resides in specific files which are in the vcs ignore file, and so will be ignored by TabNine.
If that is not the case, you can define a `.tabnineignore` file, which will cause the relevant files to be ignored by TabNine.
