### ISSUE TITLE
Log to find semantic problem

### ISSUE THREAD

**Issue by ai** [codota/TabNine#136]
Thanks for amazing extension. I found a problem with enabling semantic autocomplete. 

TabNine can’t start `flow` binary, but I install it to the system and it is available by `flow lsp` command in terminal. It could be the problem of my environment (for instance, Flatpak container restrictions).

But I need some debug information to fix it. Where I can find TabNine log?

**Comment by meotimdihia** [comment]
I have the same problem, but with Typescript. 
And followed https://tabnine.com/semantic, still can't enable samantic.
```
[language.typescript]
command = "C:\\Users\\meoti\\AppData\\Roaming\\npm\\typescript-language-server"
args = ["--stdio"]
install = [["npm", "install", "-g", "typescript-language-server"]]
```

**Comment by mattiasw** [comment]
I'm using nvm and have the same issue if that gives any clues. I have followed the instructions on tabnine.com/semantic but it did not help.

**Comment by haakemon** [comment]
Try to append ".cmd" to the command in TabNine.toml as suggested here: https://github.com/zxqfl/tabnine-vscode/issues/45

Had the same issues, and this fixed it for me as well.

**Comment by Cy-Tek** [comment]
I tried appending ".cmd" but that did not resolve my issue. Even after running TabNine::restart, it still gives the error code.

**Comment by jcpeterson** [comment]
@Cy-Tek it worked for me

**Comment by stared** [comment]
@Cy-Tek Are you sure you edit `TabNine.toml` (NOT `TabNineExample.toml`)? The solution from https://github.com/codota/tabnine-vscode/issues/45 worked for me.
