### ISSUE TITLE
Expected resource usage

### ISSUE THREAD

**Issue by superDuperCyberTechno** [codota/TabNine#143]
So, right now my local TabNine process is at 30% CPU usage and 1 GB RAM (increasing).

Is this expected resource usage? If not, what is?

**Comment by zxqfl** [comment]
This sounds normal as long as it's indexing. It should eventually stabilize at 0% CPU.

**Comment by superDuperCyberTechno** [comment]
Ah. I thought so. Any rule-of-thumb about how long this will last as a function of project size?

**Comment by lopopolo** [comment]
Editing [this codebase](https://github.com/artichoke/artichoke) in vim with tabnine-vim resulted in two tabnine processes each consuming 10GB of RAM.

**Comment by vincentdesmares** [comment]
I recently discovered that after working a few hours using TabNine, it started to take a huge amount of memory.

<img width="957" alt="Screen Shot 2019-09-06 at 3 49 29 PM" src="https://user-images.githubusercontent.com/321162/64433138-297e0880-d0be-11e9-8a82-ba2b1a2e2372.png">

**Comment by fisle** [comment]
Yeah this has recently got out of hand, I just experienced system running out of memory, seeing Tabnine (via deoplete vim plugin) eating over 6G of ram.

**Comment by amircodota** [comment]
We've made several fixes lately, that improve TabNine's cpu and memory consumption.

With TabNine local enabled, a 1.5G-2.5GB of RAM is expected, but much higher than that is not.
Would appreciate your help in verifying that indeed memory does not grow without bounds in your use case.

If the above memory requirement is still too high, you can consider the following:
1. Disable TabNine local
2. Use TabNince cloud instead (a paid service)
