### ISSUE TITLE
Add LaTeX as a supported language?

### ISSUE THREAD

**Issue by alonzochurch** [codota/TabNine#144]
Feature request: adding LaTeX as one of the languages supported.

I don't know much Latex code is available on github, but arxiv.org provides a huge corpus of publicly available Latex files that could be trained on. (People most commonly use it to access papers in pdf form, but the arxiv also provides the Latex source for virtually all the papers it hosts.)

Also, there are Latex-specific IDEs like Texmaker, Texstudio, etc., but there are also Latex plugins for editors you already support, like VS Code and Atom, so this wouldn't necessarily require supporting additional editors.

Thanks!

**Comment by williamjameshandley** [comment]
I would very much appreciate this extension. I have been using TabNine in all my projects and have found it an invaluable and very impressive autocompleter, leagues ahead of the rest for the codes it supports. However, through the vim interface it does seem that YouCompleteMe's native autocompletion for LaTeX was slightly better than TabNine's current performance. I'm sure this would be reversed if TabNine officially supported LaTeX. I agree that arXiv would be a good corpus, but there are also [plenty of TeX](https://githut.info/) repositories on GitHub (apparently more than the number of Rust repos).

**Comment by yahave** [comment]
dup #123

**Comment by avichay77** [comment]
TabNine DeepCompletions - if trained with LaTeX - can help for sure. 
So far we have not trained TabNine Deep on Latex - but I will add it as a request for the coming training of the model.
