### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by andresespinosapc** [codota/TabNine#147]
How can I uninstall the TabNine backend? I'm using Ubuntu 18.04.

**Comment by breck7** [comment]
I would also like complete uninstall instructions.

Given that the CPU spikes are unbearable, and there's been zero communication from TabNine team in months about anything.

Pretty bad experience for paying customers.

I no longer recommend TabNine.

**Comment by LazarPetrovic1** [comment]
I completely agree! No one will ever write code in all languages, as no one speaks every human language. And for specific purposes (like web/software/game/etc dev), TabNine performs incredibly poorly; I was actually astounded by how bad it is.
Write your own snippets, it ain't that hard

**Comment by drorweiss** [comment]
@breck7 TabNine’s resource consumption has been greatly improved in recent updates. Issues are being handled at a higher velocity, as a larger team is working on maintaining and improving TabNine. I encourage you to try the product again, but if you’re unhappy with it you can get a refund by contacting support@tabnine.com
To uninstall TabNine, type TabNine::config in your editor to find the installation directory, then uninstall the TabNine plugin from your editor, and finally delete the TabNine directory.

**Comment by drorweiss** [comment]
@LazarPetrovic1 thanks for your feedback. Can you be more specific where it performed poorly (language, editor, purpose, size of project) and whether or not you enabled deep completions?

**Comment by JaMarcusLucio** [comment]
tabnine consumes too much memory :(.. thought it would easier for me to code..

**Comment by 1j01** [comment]
```sh
# Uninstall VS Code extension
code --uninstall-extension TabNine.tabnine-vscode
# Then reload the VS Code Window or make sure VS Code is closed
# (so the extension is unloaded and won't keep starting up TabNine processes) and run:
rm -rf /home/io/.config/Code/User/globalStorage/tabnine.tabnine-vscode/

# Uninstall TabNine (remove known TabNine folders)
rm -rf /home/io/.local/share/TabNine/
rm -rf /home/io/.config/TabNine/

# This should give no output:
pidof TabNine
```

**Comment by fritzfr** [comment]
For macOS:

```
rm -rf ~/Library/Application\ Support/Code/User/globalStorage/tabnine.tabnine-vscode
rm -rf ~/Library/Application\ Support/TabNine
```

**Comment by devjah** [comment]
🤦 this is a disaster

**Comment by VirtualBrotasticAdventures** [comment]
This program is garbage.  I've never had a plugin sink it's teeth so hard into my computer.  I would never recommend this to anyone!

**Comment by barcovanrhijn** [comment]
I use Ubuntu 20.04. The core issue for me has been that TabNine uses resources unpredictably and at times can even crash my machine by using every ounce of available resources. Resource usage can be as low as 1% CPU and 100mb Ram but at times can spike for 30+ min to 2GB Ram and more than 75% CPU. There's no way to plan capacity for such type of usage.

I use Jetbrains IDEs so the uninstall was rather painless just like the install. I think if the Devs of this TabNine can get a handle on runaway resource usage (by making the app more controlled in how it consumes resources) it may be a great asset for our dev team. Until then we'd have to do without it.

**Comment by xueweiwujxw** [comment]
I uninstalled this plugin, but I fount the intellisense of vscode has crashed. I think the reason is that I used this plugin when I edited a c++ file. 
This plugin is totally garbage.

**Comment by hamedpa** [comment]
solve this problem you can use following commands
first go to setting.json on vscode and remove all tabnine configs 

second close vscode application
then remove extra files

`
rm -rf  ~/.config/TabNine/
rm -rf ~/.local/share/TabNine/
rm -rf  /home/username/.vscode/extensions/svipas.code-autocomplete
`

**Comment by StoneMoe** [comment]
and `~/.tabnine` for macOS

**Comment by SteveC00k** [comment]
I have this crap code in my system and it will not go away. :( 
I have already uninstalled it and its still there. Keeps asking me if I would recommend it. 
Its now on my list of apps I do not want to bother with as the developer has it deep rooted and not easily uninstalled.
Horrible practice if you ask me.

**Comment by sugix** [comment]
Gosh.  Is this a malware or deamon which can never be killed from my Ubuntu system? I uninstalled, removed all but the process keeps popping up. How to clean uninstall this crap?

**Comment by dongqing7** [comment]
Use vscode to remotely connect to Centos, I am prompted to install tabnine. After installation, I found that tabnine is occupying too much system resources. Closed the process and delete it with cmd below:
Ps - ef | grep TabNine | awk '{print $2}' | xargs kill -9
Find all relevant files and folders in the home directory through the following command:
Find~/- name * TabNine*

After closing the tabnine process, if its executable file is still present, it will automatically start and try multiple times before completely deleting it.

**Comment by Aetherinox** [comment]
You guys definitely need a better way to clean this up.

I noticed the other day, TabNine was running roughly 8 processes. I've been using it less and less, so I decided to clean it out. Uninstalling it from VSCode didn't kill it, or remove the binaries. 

I had to locate the binaries via task manager, shut down vscode, manually delete the binaries, and then finally could re-load vscode without tabnine trying to load up.

**Comment by highfillgoods** [comment]
sudo netstat -napt | grep 1123
tcp        0      0 127.0.0.1:1123          0.0.0.0:*               LISTEN      13270/TabNine 

Had to remove TabNine extension from the Visual Studio Code installed from the snap store.  Now port 1123 is closed.
