### ISSUE TITLE
Severe perfomance issues once Deep TabNine Local is enabled in VS Code

### ISSUE THREAD

**Issue by cstuder** [codota/TabNine#148]
For a week or two now, I am experiencing severe performance issues on my TabNine installation once Deep TabNine Local is enabled. 

_System_

Windows 10 Pro, Version	10.0.17763 Build 17763
Intel i7 @ 1.80Ghz with 4 cores, 16 GB RAM, SSD
Visual Studio Code 1.38.0
TabNine 2.1.17

Working on a React app running an un-ejected `create-react-app` with Webpack watching the directories.

_Scenario_

Once I enable Deep TabNine Local, for the first couple of minutes everything is ok. After indexing the current project the CPU usage is 0%, the RAM usage is as expected (See #143).

After a couple of minutes however, my entire machine (Visual Studio Code, Firefox, Explorer etc.) is slowing down. I can see two `TabNine.exe` processes running, one consuming normal amounts of RAM but 25% of CPU power. I assume that it completely takes up the ressources of one of the cores.

The resource consumption is constant, it doesn't go down after I stop typing.

Strange enough if I kill the two `TabNine.exe` processes, I still experience the slowdown and I have to reboot to get my machine into a workable state again.

_Notes_

- I do not experience this on my MacBook Pro running Mac OS Mojave.
- This problem only cropped up for a week or two, I am unable to pin down the exact moment.
- Enabling/Disabling semantic completion doesn't have any effect.
- I have multiple instances of VSCode open.
- Seems to happen on all repos I'm working on. (Example: https://github.com/cstuder/QuoBikeIs/)
- I really love Deep TabNine Local and would like to continue using it.

Might be the same as #110 and #124, probably not the same as #24 (That issue is pre-Deep TabNine-time)

What else do you need to know?

**Comment by cstuder** [comment]
Some more observations during a slowdown:

- Nothing suspicious in the TabNine logs.
- No significant disc activity.
- I've checked the handles count with Process Explorer, looks ok (500 handles open) (Relates to #69):

![grafik](https://user-images.githubusercontent.com/288493/64418131-c038ce00-d09a-11e9-9af2-7b005239bc9f.png)

**Comment by Baflag** [comment]
Same here, have the same issue happened couple of times. Both CPU and RAM are highly loaded. Killing the TabNine process and starting VS Code again helps, and no slow downs after.

**Comment by martifenosa** [comment]
I'm working with a macbook pro Mojave 10.14.6 and TabNine reaches up to 80% of cpu usage. 
Using Visual studio and Deep mode, with local as well. 
<img width="277" alt="Screenshot 2019-09-17 at 16 13 59" src="https://user-images.githubusercontent.com/12196520/65049645-666fb800-d966-11e9-9733-e3d8ea77d3a2.png">

**Comment by keenahn** [comment]
Came here to say this.

Typing is noticeably slower when tabnine local is enabled. My HUNCH is that this could be fixed by debouncing requests to the engine are only fired after a certain delay (say 200ms). I can't confirm this, though.

**Comment by carlos-wong** [comment]
My macbook sometimes eat 600% CPU, I like this tool, but 600% will cause very slow to type

this is my laptop info:

![image](https://user-images.githubusercontent.com/1055130/70767532-a8a96980-1d9c-11ea-88a5-6df44f32c44f.png)

**Comment by drorweiss** [comment]
Adding here solution from in #24 

Hi All, we have a fix in beta (version 2.3.4) for excessive CPU and memory consumption by TabNine.
We'd appreciate it if you try it out and let us know if it solves the issue for you.
To try the fix, you have to enable the beta version. Just open TabNine's config by typing TabNine::config in your editor, and then check both **Update TabNine automatically** and **Receive beta releases of TabNine** Then, restart your editor, and press TabNine::config to verify you have TabNine 2.3.4. or newer.  Please let us know if this version solves the problem for you. We plan to make it available to all users in a couple of weeks.

**Comment by carlos-wong** [comment]
hi @drorweiss， I am using 2.3.5.  The freeze issue still their even I am disable the local modal.

**Comment by drorweiss** [comment]
@carlos-wong can you add more detail about the freeze so we can address it?

Specifically, please specify:
* what exactly freezes, how often and what causes it
* what editor you're using
* which OS.

**Comment by carlos-wong** [comment]
@drorweiss I am use macos 10.15.3.  The freezes will happen after I edit large project which maybe have hundreds source codes. I am wirte java,javascirpt,python,emacs lisp. They all have the same issue. It is ok for some minutes after I am restart tabnine. I am use emacs and https://github.com/TommyX12/company-tabnine.

**Comment by drorweiss** [comment]
@carlos-wong kindly try with beta updates enabled and let us know if it's solved (it will be the same version number, but some performance-related code is activated just for beta users)

**Comment by carlos-wong** [comment]
@drorweiss the issue is still exist

**Comment by cstuder** [comment]
I haven't experienced this issue for some time now.

**Comment by carlos-wong** [comment]
I am upgrade my mabook pro to 16G RAM , TabNine is work smooth now.

**Comment by almatkai** [comment]
In my case, the issue was caused by an extension called Jupiter by Nwat Vu, which uses Tabnine binaries. If you're unsure which extension is causing the problem, you can follow these steps to identify it:
1. Open Task Manager.
2. Look for a process named Tabnine.exe (or something similar).
3. Expand the process tree to see all related processes.
4. Right-click on one of them and select Open file location.
5. This will open the file in File Explorer.
6. Carefully inspect the files and identify the extension or app associated with it. In my case, I did not care which extension is this and just deleted one of those .exe files and stopped that process.
