### ISSUE TITLE
How can tabnine be globally disabled?

### ISSUE THREAD

**Issue by International** [codota/TabNine#155]
Sometimes it uses too much CPU. I'd like to know how I could disable it for all editors. Thanks

**Comment by amircodota** [comment]
Hi.

We've made several fixes lately that improve TabNine's cpu and memory consumption.
TabNine should now require less resources, especially when idle in the background, so I suspect this request might be less relevant for the latest version.

Can you try out the latest (2.5.1), and let us know if you think it might still be relevant?

**Comment by International** [comment]
Ok, will check. In the meantime, can it be disabled globally? For my knowledge :)

**Comment by amircodota** [comment]
No way to disable it globally currently, I'm afraid. You have to do it one by one
