### ISSUE TITLE
Verify binary

### ISSUE THREAD

**Issue by sQVe** [codota/TabNine#156]
Hey :wave:,

I'm one of the maintainers of `coc-tabnine` (https://github.com/neoclide/coc-tabnine) and we've seen issues where the binary is corrupted once downloaded. Is there a way to verify, with a sha512sum or similar, that the binary is correct?

Also, how does the automatic updates actually work? Are the updated binaries also verified?

Most importantly, a big thank you for an awesome tool - I've loved deep tabnine so far! :pray:

**Comment by amircodota** [comment]
Hi,

Every time we release a binary, we also sign it using [ed25519-dalek](https://github.com/dalek-cryptography/ed25519-dalek), and publish the signature.

If you download the binary from https://update.tabnine.com/2.5.1/x86_64-unknown-linux-musl/TabNine, then https://update.tabnine.com/2.5.1/x86_64-unknown-linux-musl/sig will get you the relevant signature.

This is how we validate downloaded updates before we install them.

You can use the above library to verify the signature (I can provide the public key), or I can provide you with a compiled binary that you can run to verify, whichever you prefer.

**Comment by sQVe** [comment]
@amircodota Awesome. I'll look into getting the downloaded binaries verified in our plugin.

🙏

**Comment by amircodota** [comment]
Great!

Let me know if you prefer to use the binary to verify. Might be simpler than to start writing rust, unless you are familiar with it :-)
