### ISSUE TITLE
Does TabNine support http proxy, If so how do I set one?

### ISSUE THREAD

**Issue by QiBaobin** [codota/TabNine#160]
Our team just heard about this exciting tool, but we have to use a proxy to access the internet in our firm. 

Could you tell me if I can set up a proxy for it? @zxqfl 

Thanks.

**Comment by MotoRZR** [comment]
Same exact question here.

**Comment by Shougo** [comment]
http_proxy and https_proxy seems work.
Note: I don't use cloud Tabnine in the proxy environment.

**Comment by Eric-Guo** [comment]
I use Tabnine in cloud and via proxy (http_proxy/https_proxy), it's not working, FYI
