### ISSUE TITLE
tabnine ram usage is too high

### ISSUE THREAD

**Issue by WoodenPC** [codota/TabNine#166]
My PC spec:
cpu: ryzen r6 1600
gpu: asus gtx 1050ti
ram: patriot viper 16gb
motherboard: asus b350 prime plus
I am using VS Code
![tabnine_ram](https://user-images.githubusercontent.com/25397745/66052299-d460d580-e549-11e9-8e0b-6973193ef303.PNG)
tab nine consumes almost 12 gigs of ram, wtf :D ?

**Comment by enkeyz** [comment]
Blame Window's memory managment. I never went over 2GB on Linux, no matter how big is my project is.

**Comment by light4** [comment]
Archlinux with vscode, used almost 2G memory.

**Comment by jc00ke** [comment]
I'm seeing 2GB usage on Regolith Linux (Ubuntu + i3) and I'm surprised it's using that much.

**Comment by seletskiy** [comment]
21.6g RAM usage on linux machine:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
30403 operator  20   0   21.7g  21.6g   1.4m S 109.2  68.9  20:29.32 /home/operator/.config/coc/extensions/coc-tabnine-data/binaries/2.1.17/x86_64-unknown-linux-musl/TabNine 
```

**Comment by wizonesolutions** [comment]
Manjaro with PhpStorm was using something like 20 GB of RAM. I have 32 GB. I killed it, but should I send a log of some sort now or next tiem it happens?

**Comment by fisle** [comment]
I'm seeing 6GB+ memory usage after having editor open for half a day. Few months ago did not run any issues, but now I've had to increase swap size just so I can run TN. Only 16GB on my system.
Ubuntu 19.04 / deoplete-tabnine / neovim 0.5.0-dev

**Comment by batisteo** [comment]
I now have 3 instances of VS Code open, and thus 3 instances of TabNine, taking 1.4GB, 1.4GB and 1.7GB. It’s a bit high indeed.

**Comment by jaydorsey** [comment]
You might be able to cut this by 1/3 by disabling Deep TabNine Local. Type `TabNine::config` in your editor and disable it via the checkbox. Would quit all editors and kill TabNine process (if it doesn't disable on it's own) before restarting editor

**Comment by seletskiy** [comment]
@jaydorsey won't this cause TabNine to go to remote server for each completion request?

**Comment by jaydorsey** [comment]
> @jaydorsey won't this cause TabNine to go to remote server for each completion request?

Whether it's enabled or disabled, it shouldn't send it to a remote server. I'm suggesting that disabling it will reduce RAM usage.

One of the semi-recent releases changed the behavior so that Deep TabNine Local was enabled by default (causing the RAM usage). From the docs:

> [Deep] TabNine Local uses your machine's CPU to run a deep learning model for providing completions. Your code stays on your machine.

Deep TabNine Cloud is the service that sends your code to the cloud. I would suggest trying to disable both to see if RAM usage improves.

Screenshot of the settings:

![image](https://user-images.githubusercontent.com/191564/68323039-9435cb00-0092-11ea-878f-9c4b881482a3.png)

**Comment by drorweiss** [comment]
Hi All, we have a fix in beta (version 2.3.4) for excessive CPU and memory consumption by TabNine.
We'd appreciate it if you try it out and let us know if it solves the issue for you.
To try the fix, you have to enable the beta version. Just open TabNine's config by typing TabNine::config in your editor, and then check both **Update TabNine automatically** and **Receive beta releases of TabNine** Then, restart your editor, and press TabNine::confiig to verify you have TabNine 2.3.4. or newer.  Please let us know if this version solves the problem for you. We plan to make it available to all users in a couple of weeks.

**Comment by jc00ke** [comment]
Testing now...

**Comment by jc00ke** [comment]
![image](https://user-images.githubusercontent.com/18191/74608638-c72b2a00-5097-11ea-9979-a0711888c52f.png)

_A lot_ of processes... but memory seems to have stabilized at 20% (1.6GB)

**Comment by jc00ke** [comment]
The integration w/coc.nvim is kinda wonky, so I've disabled TabNine for now. Can try to test more later.

**Comment by amircodota** [comment]
Hi, everyone.

Based on the response here, I conclude that the basic issue of __very high__ memory usage is resolved. A memory usage of 1.5G-2.0G is to be expected with tabnine local enabled.

@jc00ke if you have specific issues with coc.nvim, please open relevant issues here or at coc.nvim repo.
