### ISSUE TITLE
[Feature Request] Fish/Zsh etc.. Auto-completion 

### ISSUE THREAD

**Issue by williamluke4** [codota/TabNine#171]
Would be great to have contextual autocomplete in shells

**Comment by zzh1996** [comment]
It would be great to have a zsh autocomplete plugin powered by TabNine, learning from my zsh_history

**Comment by Titaniumtown** [comment]
Would be super cool to have this!

**Comment by l0nax** [comment]
yeah, this would be really awesome!

**Comment by Titaniumtown** [comment]
It would take up a lot of ram though, everytime you open a shell

**Comment by pirate** [comment]
@Titaniumtown maybe it could share one daemon between code editors, shells, etc. to reduce ram?

**Comment by Titaniumtown** [comment]
that's a good idea

**Comment by l0nax** [comment]
A "completion daemon" would help not also to reduce RAM usage but also to improve the startup time when opening a new shell.

**Comment by Titaniumtown** [comment]
it would have the model just in ram 24/7

**Comment by l0nax** [comment]
And 600MB or even 1GB are justifiable, I think.

**Comment by qiuwei** [comment]
This is a cool idea. 
Programmers spend a lot of time in the terminal!

**Comment by marbergq** [comment]
Bump! Any updates on this?

**Comment by pirate** [comment]
bump

**Comment by pirate** [comment]
bump

**Comment by abc2192233** [comment]
up

**Comment by pirate** [comment]
bump

**Comment by shuxiao9058** [comment]
bump

**Comment by cxwx** [comment]
bump

**Comment by pirate** [comment]
Blop

**Comment by pirate** [comment]
buuump

**Comment by cxwx** [comment]
waiting
