### ISSUE TITLE
Please support PROXY

### ISSUE THREAD

**Issue by jqknono0** [codota/TabNine#181]
As some companys' IT strategy, much of us may need a Proxy to access the model or to active, please support **PROXY**.

**Comment by iBug** [comment]
As per a maintainer's comment (<https://github.com/codota/TabNine/issues/285#issuecomment-669153890>), setting the environment variables `http_proxy` and `https_proxy` should work.

For Windows users, the TabNine client doesn't respect Windows' proxy settings (in Control Panel or Settings Metro app), at least until August 2020, but **does** detect and use the two environment variables mentioned above, so you can try setting those environment variables in *This PC → Properties → Advanced system settings → Environment variables* and add them, as shown below:

![image](https://user-images.githubusercontent.com/7273074/89718055-cba12180-d9ee-11ea-8aa0-a5056df4ae13.png)

**Comment by Eric-Guo** [comment]
I'm MacOS and Sublime user, I hope TabNine can support setting in user json file

/Users/EricGuo/Library/Application Support/Sublime Text 3/Packages/User/TabNine.sublime-settings

```json
{
  "max_num_results": 7,
  "http_proxy": "http://127.0.0.1:6152/"
}
```

**Comment by sannamalai76** [comment]
is this issue resolved?

**Comment by acelemore** [comment]
I use wireshark to capture the packet
found that tabnine use https protocal to communicate with cloud (.heroku.com)
So I add rule *.heroku.com to my proxy tool ( I use Shadowsocks) and it looks works

**Comment by sannamalai76** [comment]
thanks can you post an example to do this setup in windows 10

**Comment by Kunjinkao0** [comment]
Any updates? Really need this for enterprise usage

**Comment by NtkArt** [comment]
Still with the same problem

**Comment by dbsxdbsx** [comment]
Mine:  I use tabnine in remote Ubuntu  virtual machine(vm) within vmware. And this vm use proxy from host machine to connect to Internet.   Then, when I tried to connect code to this vm from host machine through vscode SSH extension, tabnine warned me that cannot download dependencies.....

**Comment by sheigel** [comment]
> I use wireshark to capture the packet found that tabnine use https protocal to communicate with cloud service heroku.com So I add rule *.heroku.com to my proxy tool ( I use Shadowsocks) and it looks works

I don't think that I can ask for the networking team to whitelist the entire heroku.com domain. Is there a plan to move away from this generic domain to something specific that I can ask the networking team to whitelist?
