### ISSUE TITLE
TabNine indexing things outside my project

### ISSUE THREAD

**Issue by emilk** [codota/TabNine#184]
I am using TabNine with Sublime. Working on a project at `/Users/emilk/code/my_project/` I notice TabNine using 100% CPU. I type `TabNine::config` and see a bunch of errors like this:

`[2019-11-04][11:08:16][server::pipeline::document_tracker][ERROR] Error reading "/Users/emilk/code/different_project/foo.png": stream did not contain valid UTF-8`

Why is TabNine indexing a different folder than the one I am working on? How can I diagnose and fix that?

**Comment by dimacodota** [comment]
hey @emilk - is `my_project` is  a git repository (contains .git) as explained [here](https://www.tabnine.com/faq#nongit) ?

**Comment by emilk** [comment]
Yes, it is.
