### ISSUE TITLE
TabNine trying to index binary files

### ISSUE THREAD

**Issue by emilk** [codota/TabNine#185]
I found this error in the logs: `[server::pipeline::document_tracker][ERROR] Error reading "/Users/emilk/foo.png": stream did not contain valid UTF-8`

It seems we could save some CPU by not trying to open `.png` files and other binary files. The obvious approach is to only open files that matches some whitelist of code files. In fact, since I only use TabNine with Rust, it should ONLY touch `.rs` files!

**Comment by jaydorsey** [comment]
Have you tried creating the `.tabnineignore` file in your project root to ignore these? I _think_ it works. I don't see any mechanism to see what it will/will not index so I'm just trusting that it works

**Comment by emilk** [comment]
Actually, the files aren't even in the project (https://github.com/zxqfl/TabNine/issues/184) but even if they were it seems strange to have to blacklist all file endings that are NOT `.rs` (counting to infinity is such a chore).

**Comment by jaydorsey** [comment]
Have you checked to see if Deep TabNine Local or Cloud is enabled? I seem to recall the Cloud settings have an option to whitelist which folders it searches but I don't recall what the defaults are

**Comment by emilk** [comment]
Cloud is off, Local is on.

**Comment by jaydorsey** [comment]
If you test with local off, do you see those same messages?

There's a couple other issues about excessive memory usage (16-20GB of RAM), so if Local was excessively indexing that might explain the memory usage. I didn't see any settings for it, and I haven't seen the _super_ excessive usage (mine caps out around 1.5GB of RAM) but I have a limited number of repos on my machine and I don't watch the log files very closely

**Comment by MeGaPk** [comment]
same for *.pyc files

**Comment by dimacodota** [comment]
TabNine uses .gitignore ( or [other](https://www.tabnine.com/faq#nongit)) files for deciding which files to ignore from the indexing process.
in case that your binary files are committed and you want to exclude them from the indexing, you can use  the `. tabnineignore` file, this file follows the .git convention, so to ignore anything besides `.rs` files you can add the following in your `. tabnineignore` file
```
*.*
!*.rs
```
