### ISSUE TITLE
CPU does not support FMA instructions

### ISSUE THREAD

**Issue by JoveYu** [codota/TabNine#192]
when i open config, there erro in `Deep TabNine Local`

> TabNine Local is unavailable because your CPU does not support FMA instructions.

so, i can not use tabnine local anyhow?

**Comment by Titaniumtown** [comment]
Same issue, please fix.

**Comment by BrunoGomesCoelho** [comment]
Same issue here;

I believe currently there's no way for them to fix it since it would require re-writing the (probably) optimized code that runs with FMA. I guess we will just have to use the cloud version.

PS: You can check if you PC supports FMA with `grep fma < /proc/cpuinfo`.

**Comment by yijunwu** [comment]
Same issue

**Comment by amircodota** [comment]
I'm afraid this cannot be easily fixed, and is out of scope for the time being.

**Comment by amircodota** [comment]
You can use TabNine cloud if your local cpu does not support it
