### ISSUE TITLE
Update changelogs

### ISSUE THREAD

**Issue by lovesegfault** [codota/TabNine#195]
There have been releases but not updates on the changelog.

**Comment by lovesegfault** [comment]
@zxqfl?

**Comment by superDuperCyberTechno** [comment]
So, Codota does the updating now, but the changelog is still really outdated...?

**Comment by lovesegfault** [comment]
Yeah, cc. @amircodota @nimrod-codota

**Comment by nimrod-codota** [comment]
Hey @lovesegfault, thanks for heads up on this one
See https://github.com/codota/TabNine#230---235-febuary-10-2020 for the updated changelogs

**Comment by superDuperCyberTechno** [comment]
The changelog hasn't been updated since this was closed.

**Comment by danisevas** [comment]
please update the changelog.
