### ISSUE TITLE
emacs lisp auto complete cost 700% CPU usage

### ISSUE THREAD

**Issue by carlos-wong** [codota/TabNine#198]
Js,Python,C,Java is work fine.

I remember the 2.1.15 is work fine with emacs lisp

**Comment by carlos-wong** [comment]
Updated: 2.3.6 still have the cpu usage issue

**Comment by drorweiss** [comment]
@carlos-wong can you enable the option to receive beta updates in TabNine::config and then tell us if the problem is solved? We have a fix that has solved issues for many users in the beta, very soon we'll release it to all users

**Comment by carlos-wong** [comment]
@drorweiss I am already enable beta version. Now the version is 2.3.6 but the issue still exist

**Comment by amircodota** [comment]
Hi, @carlos-wong 

A few questions - 

1. Does the cpu go up to 700% while you are typing? Does it remain so even after you stop typing?
2. Can you disable deep TabNine local and see if the issue persists?
3. Can you send the tabnine log file? Can be found by opening tabnine::config

Thanks
Amir

**Comment by carlos-wong** [comment]
@amircodota 

1. yes, and it's remain a while after I am stop typing
2. I am aways disable tabnine local
3. how to dump the log file? copy and paste? or where can i find the log file?

**Comment by carlos-wong** [comment]
```
[2020-03-09][15:50:23][updater][INFO] Making API request to https://api.tabnine.com/version/v1
[2020-03-09][15:50:23][lunar_transport::controller][INFO] Creating lunar client...
[2020-03-09][15:50:23][lunar_transport::controller][INFO] TabNine Cloud is disabled, communication thread is sleeping until configuration change...
[2020-03-09][15:50:23][frontend][INFO] Started.
[2020-03-09][15:50:23][lunar_local::bridge][INFO] TabNine Local communication thread started.
[2020-03-09][15:50:23][lunar_local::bridge][INFO] TabNine Local is disabled; message forwarder is sleeping until config change...
[2020-03-09][15:50:23][server][DEBUG] [autocomplete] 5 ms
[2020-03-09][15:50:23][core::patch][ERROR] error patching document: UpdateTooShort
[2020-03-09][15:50:23][core::patch][ERROR] error patching document: UpdateTooShort
[2020-03-09][15:50:23][core::patch][ERROR] error patching document: UpdateTooShort
[2020-03-09][15:50:23][core::patch][ERROR] error patching document: UpdateTooShort
```
does this little log help?

**Comment by amircodota** [comment]
@carlos-wong Yes, the error seems suspicious. Looking into it

**Comment by carlos-wong** [comment]
@amircodota and there is another error when scanning jar or png file. the log notify it's not a utf-8 encode file. It is certainly not, why not filter this files to ignore scan?

**Comment by amircodota** [comment]
Hi, @carlos-wong 

Regarding the utf-8 error - we are aware of it, and it is in our backlog to fix. It is not the reason for the high cpu you are experiencing.

Regarding the high cpu issue - it is not caused by the error in the log "error patching document: UpdateTooShort".

To move forward on this, it would be ideal if I could reproduce it.
Do you have some project you can share (maybe something open source) that may cause this issue to reproduce?

Thanks

**Comment by carlos-wong** [comment]
@amircodota I am just tested on the project https://github.com/opencv/opencv.git

**Comment by carlos-wong** [comment]
I am use emacs, and this package https://github.com/TommyX12/company-tabnine

**Comment by amircodota** [comment]
@carlos-wong Which file were you editing to get high cpu? 
Are there lisp files in this project? I see cpp.

Thanks

**Comment by carlos-wong** [comment]
samples/android/face-detection/src/org/opencv/samples/facedetect/FdActivity.java 

Basicly he cpu overload issue will happen when I editing all kinds of file t

**Comment by amircodota** [comment]
Thanks. Looking

**Comment by carlos-wong** [comment]
you are welcome

**Comment by carlos-wong** [comment]
@yahave 

Update:

1. (setq company-tabnine-context-radius 2048)
2. (setq company-minimum-prefix-length 2)

will make the CPU load decrease. But I think change the radius will cause the complete less perfect.
