### ISSUE TITLE
Dangling tabnine instances using 100% of a core

### ISSUE THREAD

**Issue by fake-name** [codota/TabNine#206]
So I had left sublime open while doing other things, and when doing something else noticed that tabnine was sitting using 100% of a core continually when I hadn't been interacting with the editor at all for some hours.

Closing sublime doesn't appear to cause it to close either. It's been dangling for about 5 minutes after I closed sublime as well. 

I have deep tabnine enabled.

**Comment by amircodota** [comment]
We have since released a fix.

Please install the latest tabnine, it should fix this issue.
Let us know if the issue persists.

**Comment by jaydorsey** [comment]
@amircodota the README only goes up to 2.3. Locally (coc-tabnine) I'm seeing 2.5.1

Which version is supposed to have these issue fixes?

**Comment by amircodota** [comment]
@jaydorsey 
Sorry for being a little behind on updating the release notes.
The relevant fixes were included in 2.3.* and 2.4.*.

So 2.5.1 includes all the relevant fixes
