### ISSUE TITLE
Can use tabnine at corporate network

### ISSUE THREAD

**Issue by tamer1an** [codota/TabNine#211]
Hello, i am trying to present plugin internally in the company 

In our organization working 5K+ employs, and local restrictions prohibit to download any .exe files or .exe that are packed by zip.

After the first download plugins is trying to update itself by downloading tabnine.exe and fails 

Is it possible to deliver plugin updates by sending .7-zip archive instead?

**Comment by amircodota** [comment]
Hi @tamer1an 

Sorry it took so long to get back to you.

While 7-zip archive might fix your issue, in other organizations they might still be blocked.
We are currently considering providing the user manual update instructions if the automatic download failed.

Does it make sense? Will you be able to download a binary from your browser given a link?
Can you check if you can download 
https://update.tabnine.com/2.2.1/x86_64-pc-windows-gnu/TabNine.exe? (Just an example)

Thanks
Amir

**Comment by tamer1an** [comment]
Hi Amir, I am working in Switzerland bank with a huge infrastructure and branches all over the world. Unfortunately there is no way to download ***.exe or ***.zip extension with browser or wget,  curl. It is blocked on the proxy level for all employees. I would like to find solution for us because I like tabNine and want to make an internal workshop about TabNIne pro version. And audience in the company would be for a hundreds of developers. Best regards,Andrii From: amircodotaSent: Tuesday, January 14, 2020 12:20 PMTo: zxqfl/TabNineCc: Andrii Trybynenko; MentionSubject: Re: [zxqfl/TabNine] Can use tabnine at corporate network (#211) Hi @tamer1anSorry it took so long to get back to you.While 7-zip archive might fix your issue, in other organizations they might still be blocked.We are currently considering providing the user manual update instructions if the automatic download failed.Does it make sense? Will you be able to download a binary from your browser given a link?Can you check if you can downloadhttps://update.tabnine.com/2.2.1/x86_64-pc-windows-gnu/TabNine.exe? (Just an example)ThanksAmir—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
