### ISSUE TITLE
tabnine It still interferes with normal advice

### ISSUE THREAD

**Issue by 2234839** [codota/TabNine#213]
![图片](https://user-images.githubusercontent.com/28727933/71538342-50f62b00-2964-11ea-90da-af4fb90fba3f.png)

As shown in the figure above, a very simple syntax completion is implemented

Once tabNine is enabled, the above extension will not work

**Comment by dimacodota** [comment]
hey @2234839, according to the API of the [DocumentFilter](https://code.visualstudio.com/api/references/vscode-api#DocumentFilter) - only the `pattern` property is  [GlobPattern](https://code.visualstudio.com/api/references/vscode-api#GlobPattern), the `language` and the `scheme`  properties are strings and hence the value of '*' will be addressed as string and not as pattern.

can you please try your example with the `pattern: "**"` or the `language` and the `scheme` with valid values? 

I've attached some examples: 

1 - with TabNine extension and `pattern: "**"` as the filter

**provider registration:**

![image](https://user-images.githubusercontent.com/60742964/74142036-be060d00-4c00-11ea-96ac-95e80a21d7e6.png)

**usage:**

![image](https://user-images.githubusercontent.com/60742964/74142065-cc542900-4c00-11ea-9089-5d0b77b67eda.png)

both extension are working


2 - without TabNine extension and the provider is registered with `language: "*", scheme:"*"`

**provider registration :**

![image](https://user-images.githubusercontent.com/60742964/74142252-2a810c00-4c01-11ea-9f40-0493ed819ad2.png)

**usage:**


![image](https://user-images.githubusercontent.com/60742964/74142259-2fde5680-4c01-11ea-9d2d-7e9518030a53.png)

the registered extension is not working

**Comment by dimacodota** [comment]
Closing as we need more info from the original poster
