### ISSUE TITLE
Configure max results to show

### ISSUE THREAD

**Issue by elkesrio** [codota/TabNine#220]
Is there a way to configure the max results to show for tabnine-vim ?

**Comment by avichay77** [comment]
at the moment it is not possible to configure the number of TabNine suggestions. 
However, this is a great idea and I'm adding it to our backlog. 
Out of curiosity - if you could set a max results - what would that number be ?
We will let you know once it's available.

**Comment by Shougo** [comment]
https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md#api-types

It is already implemented.
`max_num_results` API argument is here.

**Comment by elkesrio** [comment]
@avichay77 I think that i would set it to 5. I rarely choose a result that is further than the fifth

@Shougo Is it implemented for tabnine-vim ?

**Comment by Shougo** [comment]
I have read the code and `max_num_results` is not specified.
I think tabnine seems works as ycmd server.

If you really need the feature, you should use deoplete-tabnine instead.

```vim
call deoplete#custom#var('tabnine', {
\ 'line_limit': 500,
\ 'max_num_results': 20,
\ })
```
