### ISSUE TITLE
Take up too much RAM

### ISSUE THREAD

**Issue by hjl0903** [codota/TabNine#221]
<img width="907" alt="图片" src="https://user-images.githubusercontent.com/44921681/74604145-23bd3200-50f6-11ea-9073-1f456f0d12d5.png">

**Comment by drorweiss** [comment]
This issue is known, and 1.4GB is considered normal if TabNine Local is enabled. In any case, see issue #183 and my comment from Feb 16, 2020. Closing this as a duplicate.
