### ISSUE TITLE
When using with VSCode, I need to close and reopen fairly often ever since enabling Cloud functionality. 

### ISSUE THREAD

**Issue by MostHated** [codota/TabNine#224]
Hello,  
   I just wanted to report that when using TabNine with VSCode (which overall is working well), I often have to either do a Developer: Restart Extension Host, or close completely and reopen ever since enabling TabNine Cloud Beta. Normal tasks, such as scrolling or moving the cursor end up becoming delayed.

Thanks,
-MH

**Comment by drorweiss** [comment]
We have a fix in beta (version 2.3.4) for improving performance.
We'd appreciate it if you try it out and let us know if it solves the issue for you.
To try the fix, you have to enable the beta version. Just open TabNine's config by typing TabNine::config in your editor, and then check both **Update TabNine automatically** and **Receive beta releases of TabNine** Then, restart your editor, and press TabNine::config to verify you have TabNine 2.3.4. or newer.  Please let us know if this version solves the problem for you. We plan to make it available to all users in a couple of weeks.

**Comment by MostHated** [comment]
Sure thing, I will give it a go and report back.

**Comment by MostHated** [comment]
Just an update on this, I nearly forgot to reply, which is a good thing as I have not experience the issue since I performed the update. 👍

**Comment by Shougo** [comment]
So the issue can be closed.

**Comment by drorweiss** [comment]
OK, closing this, thanks @MostHated @Shougo
