### ISSUE TITLE
The autocomplete popup becomes very *large* when TabNine enabled in WebStorm

### ISSUE THREAD

**Issue by indefinitus** [codota/TabNine#227]
- with TabNine enabled: (very large popup)
<img width="1680" alt="Screen Shot 2020-03-05 at 19 00 28" src="https://user-images.githubusercontent.com/18642966/75975694-f359fe00-5f13-11ea-999e-529403bdc86d.png">

- disabled: (normal size)
<img width="798" alt="Screen Shot 2020-03-05 at 18 58 58" src="https://user-images.githubusercontent.com/18642966/75975700-f48b2b00-5f13-11ea-9a63-ed302ae6f8cd.png">

- WebStrom version: `2019.3.3`
- TabNine plugin version: `0.1.8`

**Comment by Eransho** [comment]
Fixed and released in plugin version `0.1.9`
