### ISSUE TITLE
why is tabnine sending data to facebook?

### ISSUE THREAD

**Issue by International** [codota/TabNine#229]
Noticed on my facebook offline activity data from tabnine. Why are you sending data to facebook? 
![4488C0F6-A98A-4397-A5CD-56965C0247B7](https://user-images.githubusercontent.com/1022918/76154573-4fc14700-60e7-11ea-9ef3-55d5cdd4dfa0.png)

**Comment by drorweiss** [comment]
We're running some promotion campaigns for TabNine on Facebook, and to measure their impact we're tracking installs. This happens only upon installation, in the post-install web page,  and not in the TabNine application itself. Our tracking doesn't reveal any personal information about you to TabNine,  it merely allows us to optimize our marketing efforts.
