### ISSUE TITLE
Support Notepad++ Products

### ISSUE THREAD

**Issue by linpengcheng** [codota/TabNine#23]
A lot of users = profit

**Comment by TheCre8r** [comment]
+1

**Comment by FallenSpaces** [comment]
+1

**Comment by avichay77** [comment]
Interesting idea. 
How popular is the usage of Notepad++ to code? in which languages?
We’ll add it to our backlog and will review and handle it by priority. We will let you know once we start working on it.
Demand here can push priority up.

**Comment by avichay77** [comment]
also, if anyone wants to help here: 
https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md.

**Comment by FallenSpaces** [comment]
> How popular is the usage of Notepad++ to code? in which languages?

Well, I'm just one person, but I love Notepad++

I use it to code in mostly bash and python. I like it because it's highly flexible and powerful, so I've customized it to look and do whatever I want. It's pretty flexible and powerful, and I'm pretty sure it's one of the top editors.

**Comment by finBitorg** [comment]
+1 Notepad++ is very popular and it supports tons of synthax Python, Javascript etc

**Comment by chasoft** [comment]
+1 for Notepad++

**Comment by fbuinosquy** [comment]
+1

**Comment by userbox020** [comment]
+1

**Comment by fbuinosquy** [comment]
+1

**Comment by pidgeon777** [comment]
I also vote for a Notepad++ plugin.

**Comment by meeebee** [comment]
+1 for notepad support.

**Comment by lyma** [comment]
+1 for Notepad!! :)

**Comment by modz2014** [comment]
> Interesting idea.
> How popular is the usage of Notepad++ to code? in which languages?
> We’ll add it to our backlog and will review and handle it by priority. We will let you know once we start working on it.
> Demand here can push priority up.

Should work on notepad++ it can be written in any languages but C# Python and batch scripts bash/shell scripts is the main ones I use it for but I’m sure others use for somethings else plus notepad++ is still getting updates

**Comment by RonnieCiou** [comment]
+1 for notepad++

**Comment by walterm128** [comment]
+1 for notepad++
