### ISSUE TITLE
TabNine was detected by Kaspersky IS

### ISSUE THREAD

**Issue by mcwnuq** [codota/TabNine#232]
![image](https://user-images.githubusercontent.com/11915730/76616113-a386c280-6523-11ea-8876-84ec4ab71007.png)
Kaspersky Internet Security is detecting Trojan-Dropper.Win32.Agent.testhz and .testiq in
Sublime Text 3 - TabNine 2.4.1 and 2.5.1

**Comment by cbogithub** [comment]
![image](https://user-images.githubusercontent.com/9572613/76659584-682ed700-65a9-11ea-8a58-074bfec18631.png)
me too

**Comment by mohmedxpmpa** [comment]
same problem

**Comment by amircodota** [comment]
This has been a false identification by Kaspersky. If you update Kaspersky to the latest definitions file TabNine.exe should not be flagged anymore.
We will really appreciate if you can verify that it is indeed solved.

We are working with Kaspersky to make sure that this does not repeat in future versions.

**Comment by amircodota** [comment]
A duplicate of [this one](https://github.com/codota/tabnine-vscode/issues/78), and was verified by the reporter that it is resolved.
