### ISSUE TITLE
Be transparent about the acquisition

### ISSUE THREAD

**Issue by JanPokorny** [codota/TabNine#234]
Currently, there is no info on the [TabNine blog](https://tabnine.com/blog/) or any other official channel on details of the acquisition and the future of TabNine. There is no info even on the Codota website.

Publishing more details has been promised [a long time ago](https://github.com/codota/TabNine/pull/163#issuecomment-571458398) and then [again](#228).

I believe that the community deserves more transparency -- given that TabNine has both paid customers and open-source contributors. Keeping silent about the acquisition except when explicitly asked in a buried GitHub comment, and excusing the utter lack of official communication by saying that (quote) "acquisition of TabNine by Codota has been published in many tech-business related news sites", is very unprofessional.

**Comment by drorweiss** [comment]
@JanPokorny Thank you for your patience. You can find the note from Jacob Jackson (here)[https://tabnine.com/blog/codota], and my note (here)[https://blog.codota.com/tabnine-part-of-codota/]. As more developers are now working on TabNine, we have been able to address many of the long-standing issues (notably CPU and memory consumption), and working in full force on the next round of improvements.
Thank you for supporting TabNine!
Dror (CEO @Codota)

**Comment by drorweiss** [comment]
@JanPokorny Thank you for your patience. You can find the note from Jacob Jackson [here](https://tabnine.com/blog/codota), and my note [here](https://blog.codota.com/tabnine-part-of-codota/). As more developers are now working on TabNine, we have been able to address many of the long-standing issues (notably CPU and memory consumption), and working in full force on the next round of improvements.
Thank you for supporting TabNine!
Dror (CEO @Codota)
