### ISSUE TITLE
I want to cancel my subscription! Please reply to my email.

### ISSUE THREAD

**Issue by tshu-w** [codota/TabNine#235]

**Comment by drorweiss** [comment]
Done.

**Comment by ulises-castro** [comment]
@drorweiss , I want to cancel my subscription and I can't, it seems like you do it on purpose...

**Comment by boaz-codota** [comment]
Hey @ulises-castro ,

We are surely not doing that on purpose. I've answered your support@tabnine.com inquiry, which was sent 7 hours ago. It was the middle of the night for us, so I believe our response time for cancelation is comprehensible.

We also provide users with the option of canceling themselves using the `Manage Subscription` option within Tabnine Hub.

Let me know if you need any more help.

**Comment by ulises-castro** [comment]
sorry my bad, but I was having this issue ![image](https://user-images.githubusercontent.com/17864276/113593635-419c6d80-95fc-11eb-97db-1b78be888d82.png)
