### ISSUE TITLE
TabNine Windows executable detected by VirusTotal

### ISSUE THREAD

**Issue by smrq** [codota/TabNine#237]
Version: 2.5.1

File: C:\Users\gregsm\AppData\Roaming\Sublime Text 3\Packages\TabNine\binaries\2.5.1\x86_64-pc-windows-gnu\TabNine.exe

Scan Results: https://www.virustotal.com/gui/file/36cf9a65a680f2a51a02cc3903110c4b3c9258544a958428185328392d10972f/detection

**Comment by smrq** [comment]
Also, McAfee Active Response throws a warning event for unusual application behavior because of code injection:

![screenshot](https://user-images.githubusercontent.com/400889/77576784-bb573280-6ea3-11ea-9dfe-3f434c5cf808.png)

**Comment by amircodota** [comment]
Thanks for reporting this.
We've had similar issues with Kaspersky anti virus.

We will look into it.
