### ISSUE TITLE
optimize suggestions

### ISSUE THREAD

**Issue by shuxiao9058** [codota/TabNine#238]
for what I know that TabNine runs as many instances as editor opens.
so do you have any plan to optimize that editors use only one TabNine instance.

**Comment by amircodota** [comment]
@shuxiao9058 

Are you talking about multiple documents in the same editor or multiple editors? Which ones?

In general - the communication with TabNine is done over standard input/output, so it cannot be easily shared between multiple processes, and that's not expected to change in the near future.

**Comment by shuxiao9058** [comment]
What I say is multiple editors can use single TabNine instance.

And the communication between TabNine and client can use tcp and so on ...

**Comment by amircodota** [comment]
Thank you.

I'm trying to better understand your use case.

What editors are you using?
Also, what is your concern with multiple tabnine instances? is memory? cpu? something else?

**Comment by shuxiao9058** [comment]
Mostly I using Sublime and Emacs, and what I concern with  multiple tabnine instances is the cost of memory.

And I think the models of Deep TabNine should only load by one instance ...

**Comment by amircodota** [comment]
Thank you for that feedback

**Comment by shuxiao9058** [comment]
> Thank you for that feedback

My pleasure.

**Comment by simonlindholm3** [comment]
Same for me, with vim. I frequently open new vim instances (e.g. git can open them when I do `git commit`), and every new instance is an out-of-memory-whole-system-freeze gamble :)

**Comment by uolot** [comment]
> Same for me, with vim. I frequently open new vim instances (e.g. git can open them when I do `git commit`), and every new instance is an out-of-memory-whole-system-freeze 

What I do is not enabling TabNine by default. I have this in my vimrc:
```
Plug 'zxqfl/tabnine-vim', { 'on': 'TN' }
nnoremap <Leader>tn :silent! TN<CR>
```
