### ISSUE TITLE
Deep TabNine Local could not download model

### ISSUE THREAD

**Issue by liyu34** [codota/TabNine#246]
Hello, I'm using TabNine in Intellij IDEA, here is my IDEA version info:
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, zielu.gittoolbox, training, com.tabnine.TabNine, com.tang, com.werfad

I tried to enable Deep TabNine Local, but it shows this error:
`The download failed: https://api.tabnine.com/model_metadata/v1: error trying to connect: unexpected EOF during handshake`

**Comment by Eransho** [comment]
Hi and thanks for reporting.
Can you attach tabnine log records? You can find them in the local website opened after you type tabnine::config

**Comment by liyu34** [comment]
Sorry that bother you, I was behind a proxy, and when I close the proxy software, all works fine.
