### ISSUE TITLE
Xcode-Swift

### ISSUE THREAD

**Issue by alireza12t** [codota/TabNine#247]
Do you have any plan for tabnine on Xcode?

**Comment by shaiahr** [comment]
@alireza12t Not at the moment, sorry. We do have support for AppCode if that helps.

**Comment by alireza12t** [comment]
Thanks

**Comment by MeGaPk** [comment]
+1, On my company only me used AppCode. Other people used xcode only... and they don't want to try it :D. 
On ios devs chat people don't like AppCode, because he has "freezed" scrolling and because he wrote on Java  :D

**Comment by alireza12t** [comment]
What are its benefits?
