### ISSUE TITLE
I have to stop using TabNine after reading the EULA

### ISSUE THREAD

**Issue by cabello** [codota/TabNine#250]
Hi 👋 

I've used TabNine for a couple years back when it was a side project by a Waterloo undergrad, I kept using it after it was bought. (also I was unaware that it was bought. 😞 )

There was a turning point where it stopped being snappy and handy and it started using a lot of CPU and RAM. This was when I started considering alternatives. I found [Kite](https://kite.com/) but is a complete distinct approach to auto-complete. I like TabNine's approach better.

The company I work for has a hard focus on improving security and "prevention is better than remediation". After informing them I was using TabNine for auto-complete, they gave me a big 🙅 . I can't argument against it after reading the EULA.

From: https://www.tabnine.com/eula/

> LIMITATION OF LIABILITY. In no event shall TabNine, Inc. be liable for any damages due to use of TabNine, to the maximum extent permitted by law. This includes without limitation, lost profits, business interruption, or lost information. In no event will TabNine, Inc. be liable for loss of data or for indirect, special, incidental, consequential (including lost profit), or other damages. TabNine, Inc. shall have no liability with respect to the content of TabNine or any part thereof, including but not limited to errors or omissions contained therein, libel, trademark rights, business interruption, **loss of privacy or the disclosure of confidential information**.

I am reporting this just because the terms may hinder your ability to grow, I don't expect it to change if this agreement is working for the company. As of right now I can't justify the risk of using TabNine in my computer.

Thank you for the hundreds of hours of awesome auto-completion. 💜 
I appreciate it 🙇

**Comment by drorweiss** [comment]
Hi @cabello,
Thanks for highlighting this and for the kind words about TabNine. 
I agree that our EULA needs further work, and I see why the language that you mentioned caused some eyebrows to be raised.
We're working to improve this - I will let you know once the new EULA is in place and hopefully you can start using TabNine for work again. Regardless of the language in the EULA, we're taking extreme care to keep the privacy and security of our users.
In addition, we've made some significant improvements in resource consumption, and this is still a very high priority for us to further reduce the amount of memory and CPU TabNine requires.
Stay tuned.

**Comment by crewone** [comment]
This is certainly a big issue, especially for $15/month.

**Comment by elovin** [comment]
Does the local version upload the code analysis ?

**Comment by fandy** [comment]
@drorweiss has this been revised? I see the current link https://www.tabnine.com/eula/ has been changed. Would love to keep using TabNine as a paid subscriber but the wording on your terms is a bit concerning.

**Comment by YossiSalomon** [comment]
@fandy , this has been revised. We have changed our EULA, specifically, we revised the limitation of liability section, and removed the term regarding “loss of privacy or the disclosure of confidential information”.
