### ISSUE TITLE
Using rust-analyzer instead of RLS for semantic complettions

### ISSUE THREAD

**Issue by zmanian** [codota/TabNine#251]
Generally rust analyzer is taking over the the Rust Language Server as the preferred LSP provider for the rust community.

Some documentation on how to rust analyzer with semantic completions would be appreciated.

**Comment by shaiahr** [comment]
Hi @zmanian 
Try following the instructions [here](https://www.tabnine.com/semantic)
Let me know if that helped or if you still need assistance.

Shai

**Comment by zmanian** [comment]
This instructions there are for RLS.

https://rust-analyzer.github.io/ is the newer better language server implementation for rust.

**Comment by shaiahr** [comment]
Hן @zmanian 
Maybe I misunderstood. Doesn't the 'Custom Configuration' section in that page explain what you require?
