### ISSUE TITLE
100% CPU Usage when typing

### ISSUE THREAD

**Issue by avillarubia** [codota/TabNine#253]
I was using version 2.8.1
For now, I uninstall this and solved the problem.

**Comment by dimacodota** [comment]
Hey @avillarubia,
A few questions:

- What OS are you using?
- What editor are you using?
- Do you have tabnine local enabled? If so, can you disable and see if it still reproduces?

**Comment by avillarubia** [comment]
@dimacodota thank you for the reply

OS: Windows 10 Pro
Editor: Visual Studio Code
for the third question is, I am not sure but what I did I only install one click away, no other things did, I guess No.

**Comment by dimacodota** [comment]
You can try to disable tabnine local and see if this still reproduced

To disable tabnine local, please follow these steps:
- open the command pallet (cmd + shift + p)
- type tabnine:config
- disable the Deep TabNine Local option

One more question, is your project open source by any chance? Would love to get the code and try to reproduce the issue?

**Comment by avillarubia** [comment]
@dimacodota it works like a charm. Big Thanks to you

**Comment by dimacodota** [comment]
hey, @avillarubia,  
you can try our deep tabnine cloud  https://www.tabnine.com/welcome/

**Comment by avillarubia** [comment]
@dimacodota yes I will and thank you again
