### ISSUE TITLE
[IntelliJ, Typescript]TabNine removes all suggestions inside method signatures

### ISSUE THREAD

**Issue by MichaelHindley** [codota/TabNine#258]
- OS version: [e.g. Win 10, Mac Catalina]	
Mac Catalina
 - Editor: [e.g. vscode, intelij, sublime]	
IntelliJ Ultimate
 - Editor version:	
2020.1.1
 - Programming language: [e.g. js, ts, c++]	
typescript
 - TabNine extension version:
 0.1.0
**Issue Details:**
When enabling TabNine, no suggestions appear in method signatures when invoking autocompletion in Intellij.

TabNine enabled:
![image](https://user-images.githubusercontent.com/1016639/81833805-71eca080-9540-11ea-840e-46b8082a6ac6.png)

TabNine disabled:
![image](https://user-images.githubusercontent.com/1016639/81834053-c2fc9480-9540-11ea-9aeb-fa12eb37b014.png)

**Comment by avichay77** [comment]
fixed in TabNine plugin for JetBrains 0.2.0
