### ISSUE TITLE
[Feature] - Apache NetBeans integration

### ISSUE THREAD

**Issue by Chris2011** [codota/TabNine#259]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: Apache NetBeans
 - Editor version: 11.3
 - Programming language: HTML, JS, CSS, PHP, Java, C/C++
 - TabNine extension version: - 
 
**Issue Details:**
It would be very cool, if you would like support NetBeans. IntelliJ, WebStorm and other JetBrains IDEs, are based on Java too, so I think it could be easy to reuse the generic code for that plugin to create a plugin for NetBeans as well :)

Cheers

Chris

**Comment by maya-tabnine** [comment]
Check out this placeholder repo: https://github.com/codota/tabnine-netbeans-ide 
You are welcome to develop it on your own using our guide: https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md
