### ISSUE TITLE
Skip waiting for LSP backend if we know it will be too slow

### ISSUE THREAD

**Issue by zxqfl** [codota/TabNine#26]
Eg. no need to wait 50ms every time user types `.` if the backend always takes at least 200ms

**Comment by albertorestifo** [comment]
By this you mean that eventually the LSP results will show up, but the first one will be the language-agnostic ones?

Or do you mean to skip the LSP results entirely?

**Comment by zxqfl** [comment]
Currently, if the text before the cursor ends in . or ::, we wait 50ms to see if the language server will reply, rather than being completely asynchronous like normal. This is nice when we're dealing with a fast language server like ocaml-language-server, but not so nice when dealing with a slow language server.
