### ISSUE TITLE
tabnine 使用一段时间后内存占用量很大

### ISSUE THREAD

**Issue by jhabc1314** [codota/TabNine#261]
**please complete the following information:**	
 - OS version: Linux 18.04 	
 - Editor: vscode
 - Editor version:1.45.1
 - Programming language: PHP
 - TabNine extension version:2.8.2
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

> tabnine 代码补全很好用。只是有个小问题：

使用一段时间以后电脑开始卡顿，内存占用有点大
    ![image](https://user-images.githubusercontent.com/17001740/82657522-11ecad00-9c58-11ea-9a3c-864bd7210e83.png)

**Comment by Eransho** [comment]
Hi and thanks for reporting.
Was this screenshot taken when your computer froze or had slow responsiveness? It looks like the CPU is idle, can you try to reproduce and share another screenshot from same time of the issue?
Also, can you provide us the hardware details of your computer? 1.7GB is not necessarily high

**Comment by h1ac0k** [comment]
作为这个产品的早期付费用户，且订阅了这项目的issue动态，基本上隔三差五就会有人反馈吃CPU、吃内存的问题。但是这问题压根就没有被很好地解决过，实在是太差劲了。
非常失望！！！
非常失望！！！
非常失望！！！

**Comment by jhabc1314** [comment]
目前倒是没有发现吃CPU的情况，内存占用量确实是最高的了，我现在电脑也就只开了vscode，chrome，firefox，wps几个软件。
因为感觉是从安装了tabnine以后开始有点卡顿的，所以觉得是不是占用内存过大导致内存不够用导致的。

电脑配置没啥问题：
![image](https://user-images.githubusercontent.com/17001740/82881294-196ec780-9f72-11ea-8177-12bded569d32.png)
固态硬盘，16G内存

内存占用量对比很明显：
![image](https://user-images.githubusercontent.com/17001740/82881380-35726900-9f72-11ea-9f67-8097b37df9ec.png)

其实使用也没问题，就过来反馈一下看看，哈哈

**Comment by FWangZil** [comment]
哎，吃内存是真的吃内存

**Comment by Eransho** [comment]
@jhabc1314 if you disable TabNine local (from the config page), will it improve your computer's memory consumption? 
Did you try the TabNine cloud? It's a free 14-days trial, I'm wondering if it will help you performance issue

**Comment by jhabc1314** [comment]
@Eransho  禁用以后tabnine进程直接消失，内存占用也少了点。
TabNine cloud 还没用过，后面我用用看。
也没啥大问题～
