### ISSUE TITLE
Improve quality of cloud TabNine completion with prettier preprocessing

### ISSUE THREAD

**Issue by seveibar** [codota/TabNine#264]
This is a feature request. I think TabNine's autocompletions could be dramatically improved if the source it's trained is first preprocessed by [prettier](https://prettier.io/), which is available for many languages but I'm particularly interested in javascript.

TabNine often suggestions prettier-incompatible autocompletions for me, which I never use. This minor change in the training process (note: could be flag-enabled) would also remove a lot of potential possibilities for completions. For example, usually typing...

```javascript
import React from 
```

Will suggest (default) prettier-incompatible

```javascript
import React from 'react'
```

When in my codebase I'll only ever use prettier-compatible

```javascript
import React from "react"
```

**Comment by boaz-codota** [comment]
Interesting. May I ask why does this matter to you, given that you can use the suggestion and then run prettier on save, giving it the flavour of your choice?

**Comment by seveibar** [comment]
The quality of the completions suffers, since you eliminate many semantically equivalent representations. The example above shows that. Since this is so common in javascript, I think it would dramatically reduce the number of possible solutions to any autocompletion, and probably give much better results.

I'm motivated to work on it but I think this part of the code is closed?

**Comment by boazberman** [comment]
Unfortunately it is in the closed source part of TabNine. 
We are discussing possible solutions to this, and we will hopefully address this in future versions, although not in the near future.

Thank you for using TabNine, we will continue to iterate on the product for you to have an ever improving experience.
