### ISSUE TITLE
Sort results by detail %

### ISSUE THREAD

**Issue by svipas** [codota/TabNine#266]
**please complete the following information:**	
 - OS version: macOS Catalina 10.15.4
 - Editor: VS Code
 - Editor version: 1.45.1
 - Programming language: TS
 - TabNine extension version: latest

**Issue Details:**

Sort results by `detail` which is for e.g. `34%` which means it's higher than `17%`, but still very often higher percent result is below lower result, not above all other lower result items or at the top.

If result doesn't contain `detail` with for e.g. `10%` sort it to be at the end of the list.

You can see below my output and `34%` is the highest result, but still it's third item instead of the first.

```
docs: []
old_prefix: "user"
results: Array(5)
0: {new_prefix: "userMessage = userMessage", old_suffix: "", new_suffix: "", detail: "17%"}
1: {new_prefix: "userMessage = userMessage.", old_suffix: "", new_suffix: "", detail: "15%"}
2: {new_prefix: "userMessage", old_suffix: "", new_suffix: "", detail: "34%"}
3: {new_prefix: "userMessage = user", old_suffix: "", new_suffix: "", detail: "17%"}
4: {new_prefix: "userMessage = userMessage.trim();", old_suffix: "", new_suffix: "", detail: " 6%"}
length: 5
__proto__: Array(0)
user_message: (3) ["TabNine Professional trial", "is expiring in 1 day,", "www.tabnine.com/buy to subscribe."]
```

**Comment by Eransho** [comment]
Hi @svipas, results are sorted by a combination of their length and detail value. 
The idea is is to promote results which save more characters to the user from typing in addition to their frequency. That explains your wondering over the attached response

**Comment by svipas** [comment]
@Eransho Thanks for info. My suggestion then would be to edit detail to match results order, because right now it's a little bit confusing why often I get higher detail items at the lower position. I mean now I know, but I guess some developers will have the same question.
