### ISSUE TITLE
Change config method to simple textfile instead of "webpage"

### ISSUE THREAD

**Issue by crash5** [codota/TabNine#268]
**Issue Details:**

On an editor without a gui (eg.: vim) it's a real pain to open the config panel (tabnine::config). Can you please switch to a simple text/json config file with default values?

**Comment by dimacodota** [comment]
hey @crash5 , you can paste `TabNine::config_dir` in you vim instance, this will display the configuration directory, which contains the tabnine_config.json configuration file
