### ISSUE TITLE
Annoying "Uninstall feedback"

### ISSUE THREAD

**Issue by itsnotvalid** [codota/TabNine#270]
I've just got an auto call to open a website using my default browser when TabNine self-updates via vscode's internal mechanism. Although I had no intenion to uninstall TabNine, this is the trigger now I really would uninstall as I really dislike the idea of nag screen.

This occurs as users are not able to opt-out from Google Analytics tracking nor Mixpanel tracking when loading your website involuntarily.

Nonetheless I write this here so that you guys would not nag more people into fear that you guys start tracking usage or record keystrokes etc. as a lot of us here are working in corporate environments and are required to maintain confidentiality to the code they write.

**Comment by drorweiss** [comment]
(Codota's CEO here)

Hi @itsnotvalid,
Thank you - we are aware of the issue of the uninstall feedback page loading on upgrade, and are deploying a fix ASAP.
It is important for us to understand *why* users decide to uninstall the product as a way to improve the most painful issues. We're not recording keystrokes, and keeping the confidentiality of the code you write with TabNine is the top priority for us. Absolutely [zero code leaves your machine unless you actively turn on TabNine cloud](https://www.tabnine.com/faq/#leak).
We will remove Mixpanel and Google Analytics tracking from the page that is loaded involuntarily - this is a really good point.
