### ISSUE TITLE
TabNine Webstorm plugin breaks suggestions when 0 characters are entered

### ISSUE THREAD

**Issue by DamodarSojka** [codota/TabNine#272]
- OS version: ubuntu 18
 - Editor: intelij (webstorm)
 - Editor version: 2019.2.3
 - Programming language: js, ts, graphql
 - TabNine extension version: 0.1.11

I am not entirely sure if that's TabNine's issue or some sort of configuration issue but when the plugin is enabled no suggestions are shown when 0 characters are entered. For example if I work within a graphql query and hit ctrl+space for "smart type" the prompt will show "No suggestions", same if I try to see whata fields are present on an object (typescript is used) and so on. Disabling TabNine plugin fixes that. It works properly if at least one character is written, all fields/methods starting with that character are then suggested properly.

Thank you

**Comment by shaiahr** [comment]
Hi @DamodarSojka 
Could you please paste a short code snippet where this happens and where exactly is the cursor placed when you type ctrl+space?

Thanks
Shai

**Comment by DamodarSojka** [comment]
With TabNine extension enabled, no characters written, ctrl+space typed (notice that the typing is defined here):
![image](https://user-images.githubusercontent.com/6706539/85321231-430d0700-b4bc-11ea-9d36-4350925d10a8.png)

Same as above but with one character written:
![image](https://user-images.githubusercontent.com/6706539/85321264-50c28c80-b4bc-11ea-8c50-135fa8ee1641.png)

With TabNine switched off:
![image](https://user-images.githubusercontent.com/6706539/85321335-751e6900-b4bc-11ea-94c4-ab5f40ca3d6e.png)

**Comment by shaiahr** [comment]
Thanks for the detailed description. We will look into it.

**Comment by avichay77** [comment]
fixed in TabNine plugin for JetBrains 0.2.0
