### ISSUE TITLE
Segmentation fault on Manjaro Linux (TN installed via coc-tabnine)

### ISSUE THREAD

**Issue by dkvasnicka** [codota/TabNine#277]
**please complete the following information:**	
 - OS version: Manjaro Linux 20
 - Editor: NeoVim (coc-tabnine)
 - Editor version: 0.4.3
 - Programming language: all (irrelevant)
 - TabNine extension version: current git HEAD
 
```
> ~/.config/coc/extensions/coc-tabnine-data/binaries/2.8.7/x86_64-unknown-linux-musl/TabNine
Segmentation fault
```

This is on `Linux x1 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64 GNU/Linux`. CoC either completely ignores TabNine or says "timed out after 5000ms".

**Comment by fiesh** [comment]
The same happens on our Gentoo installation.

**Comment by fiesh** [comment]
However, replacing the binary with the one manually downloaded using this repository's script works, so I guess it's something with `coc-tabnine`.
