### ISSUE TITLE
GPT-3 version of tabnine is possible?

### ISSUE THREAD

**Issue by deepgradient** [codota/TabNine#281]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

Can we expect the GPT-3 version of tabnine in the near future?! It would be great if we could get it instead of the current GPT-2 based version.

**Comment by LucasMatuszewski** [comment]
Totally agree! Today I was on a Webinar lead by Adam Cheyer (Siri co-founder and AI expert).
He said that GPT-3 is a total game-changer. So... what are your plans for the next months? ;)

**Comment by matthew-plusprogramming** [comment]
Agree here, GPT-3 version would be pretty amazing

**Comment by JacobDeuchert** [comment]
I am not an expert in GPT an ai in general but according to this Article [(ZDNet.com)](https://www.zdnet.com/article/these-11-programming-languages-now-work-with-kites-ai-code-completion-tool/)  GPT-3 is too heavy to run it on your normal PC or Laptop and running it cloud only will also result in high latency. Waiting several seconds for every completion is not worth it i think. 

Let's hope someone is able to do a lite version of GPT-3 or GPT-4?? will be more lightweight.

**Comment by Abitamim** [comment]
Unfortunately, that won't be possible. OpenAI is keeping GPT-3 closed source to make money.

**Comment by MoDerPo** [comment]
It's very unlikely that they will ever make it open source, since they have licensed it to microsoft. It is only possible to acces it by applying for API acces.

**Comment by Phaze1D** [comment]
How about using GPT-J which is an open source model similar to GPT-3 and apparently is better at writing code then GPT3 because it was train github repos and stackexchange.  
The article about GPT-J 

https://towardsdatascience.com/cant-access-gpt-3-here-s-gpt-j-its-open-source-cousin-8af86a638b11
