### ISSUE TITLE
ARM64 TabNine in Linux

### ISSUE THREAD

**Issue by reijovosu** [codota/TabNine#282]
**please complete the following information:**	
 - OS version: Linux	
 - Editor: NA	
 - Editor version: NA
 - Programming language: NA	
 - TabNine extension version: NA
 
**Issue Details:**

When Apple is coming out with arm64 processors perhaps its time to compile TabNine also to ARM.

For me personally, I cannot use TabNine when using VS Code remote in Linux dev server. And it seems there is no arm available in any platforms: https://github.com/codota/TabNine/blob/master/dl_binaries.sh

**Comment by suddenrushofsushi** [comment]
@yanir-codota Any movement on this front?

**Comment by xqliu** [comment]
I think this issue should be keep opening for tracking unless tannins don't intend to support arm linux arch.

**Comment by appcoders** [comment]
Please reopen. There are plenty of devs working on M1/M2 with devcontainers and need aarch64 support.

**Comment by davemackintosh** [comment]
This should be reopened- you have armv8a support for the Apple M series, providing a binary for Linux armv8a should be available too. How can the community support in getting this back on the roadmap?

**Comment by gjsmith66** [comment]
Yes please, we need a Linux ARM version to support Amazon Graviton.
