### ISSUE TITLE
Feature request: Allow manual licence activation and manual Deep TabNine Local download

### ISSUE THREAD

**Issue by cstuder** [codota/TabNine#285]
- OS version: Windows 10
 - Editor: VS Code
 - Editor version: 1.47.3
 - Programming language: *
 - TabNine extension version: 2.9.2
 
 **If the issue is related to TabNine failure, please provide log files:**	

```txt
Error saving your changes: there was an error contacting tabnine.com: https://api.tabnine.com/api_key_info/v2: error trying to connect: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig. (os error 10013)

[2020-08-05][08:53:51][lunar_local::downloader][ERROR] https://api.tabnine.com/model_metadata/v1: error trying to connect: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig. (os error 10013)
```

**Issue Details:**

Since the TabNine binary doesn't respect the local proxy settings (See #49 and #181), it would be a nice workaround to have the possibility of manually activating the licence and manually being able to download the deep learning model.

**Comment by yanir-codota** [comment]
hi @cstuder, 

TabNine should actually support the proxy settings in most environments.  
In most cases (standard proxies), setting up the `http_proxy` and `https_proxy` variables in the environment variables on your machine should solve your problem of downloading and working with the local model. 

can you please try set them, and let us know if that solved your problem?

Pending your feedback. 
Thanks!

**Comment by cstuder** [comment]
Thanks for the reply. I accidently had the environment variables mistyped (`proxy_http` instead of `http_proxy`). I've set them correctly, including username & password.

Downloading the model still doesn't work, does the TabNine binary respect proxy authorization?

```txt
[2020-08-05][14:31:00][lunar_local::downloader][INFO] Starting download (last_failure=Some("Could not download the model from https://update.tabnine.com/models/b8373e4b, status code: 407 Proxy Authentication Required")).
```

I can download the model manually, but can I enable it manually as well in the config file?

**Comment by cstuder** [comment]
I just noticed that on the command line the metadata-API-request seems to suceed, but not the download request itself. Maybe these two requests are handled differently:

```txt
[2020-08-05][15:19:17][updater][INFO] Making API request to https://api.tabnine.com/model_metadata/v1
[2020-08-05][15:19:17][lunar_local::downloader][INFO] Downloaded model metadata [hash=b8373e4b].
[2020-08-05][15:19:17][lunar_local::downloader][ERROR] Could not download the model from https://update.tabnine.com/models/b8373e4b, status code: 407 Proxy Authentication Required
```

Anyway, after manually downloading the model and placing it into `%APPDATA%\TabNine\models` and appending the suffix `.tabninemodel`, the model is now manually activated and running.

My interpretation is that only the download request of https://update.tabnine.com doesn't respect the proxy settings.

**Comment by yanir-codota** [comment]
Hi @cstuder 
Thanks for this input. we appreciate it, and we'll look into the points you've mentioned. 

I Just want to make sure that you're up and running with TabNine. 
please note, that the model might change from time to time to optimise results and user experience. so in the meantime if you rely on a manual download solution, stay tuned regarding updates in order to keep up with most current model. 

there's one more thing to consider, 
In cases where the metadata download works, but the model download doesn't, It may be reasonable to suspect that this is proxy policy related. it may be worthwhile to ask your network manager/IT regarding this.  

I hope this helps.
let us know. 
Thanks!

**Comment by iBug** [comment]
@yanir-codota Hi yanir. The standard proxy settings on Windows 10 is via ***Settings → Network & Internet → Proxy***, however my TabNine (installed through VSCode Extension Marketplace) doesn't appear to respect such settings.

![image](https://user-images.githubusercontent.com/7273074/89717924-9811c780-d9ed-11ea-948a-a0fd8bdef0eb.png)

Using cURL in WSL shows that my proxy is working:

```shell
ubuntu@MSI-GS73:~/Desktop $ https_proxy=socks5://127.0.0.1:1080 curl -vso /dev/null https://api.tabnine.com/model_metadata/v1
* Uses proxy env variable https_proxy == 'socks5://127.0.0.1:1080'
*   Trying 127.0.0.1:1080...
* TCP_NODELAY set
* SOCKS5 communication to api.tabnine.com:443
* SOCKS5 connect to IPv4 52.70.215.26:443 (locally resolved)
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 1080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [21 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2647 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [264 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=ps-tabnine-gateway.herokuapp.com
*  start date: Jun 12 23:28:13 2020 GMT
*  expire date: Sep 10 23:28:13 2020 GMT
*  subjectAltName: host "api.tabnine.com" matched cert's "api.tabnine.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
} [5 bytes data]
> GET /model_metadata/v1 HTTP/1.1
> Host: api.tabnine.com
> User-Agent: curl/7.68.0
> Accept: */*
>
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [130 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Length: 496
< Content-Type: text/html; charset=utf-8
< Date: Sat, 08 Aug 2020 19:06:09 GMT
< Server: Rocket
< Vary: Accept-Encoding
< Via: 1.1 spaces-router (2995ba6bec0f), 1.1 spaces-router (2995ba6bec0f)
< X-Powered-By: Express
<
{ [496 bytes data]
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by yanir-codota** [comment]
Hi @iBug, 

Thanks for the input! 
TabNine Binaries, are implemented in Rust, in which the support for windows features is not trivial. 

We're aware of this problem. 
A good workaround in this case will be exactly what you suggested, for the time being. 
I'll add this as a Bug to our backlog, 

Again, Thanks for pointing this out. 
Yanir.
