### ISSUE TITLE
TabNine trying to access network resources

### ISSUE THREAD

**Issue by uinstinct** [codota/TabNine#287]
- OS version: Windows 10	
 - Editor: Sublime Text
 - Editor version: 3
 - Programming language: js
 - TabNine extension version:  2.9.0
 
### Issue Details

TabNine is trying to access the internet via this api : https://api.tabnine.com/

I have **Norton Security** enabled which prevented this request. It then provided me the log which looked like this:

![tabnine access blocked by norton](https://user-images.githubusercontent.com/61635505/91753666-d6ae3280-ebe5-11ea-912b-a06344679fe5.png)

**I don't think you are supposed to access the internet to share our personal details.**

**Comment by yonip23** [comment]
Hi @uinstinct ,
We don't share any personal details, and we do not send your code anywhere. We do send some technical information on the availability of the product, and to check for updates.

**Comment by uinstinct** [comment]
@yonip23 I don't think this is fine because no **good** extension out there sends any details of the device the user is using or any such related info.

And regarding updates, I think _package control (in Sublime Text)_ does take care of that.

**Comment by yonip23** [comment]
We respect your opinion, however in order for us to provide the best service and optimize our users' experience we collect some minimal technical information.
Package Control does not update the TabNine binary which has its own mechanism which also updates the model.
