### ISSUE TITLE
TabNine makes shady requests

### ISSUE THREAD

**Issue by uyouthe** [codota/TabNine#288]
- OS version: OSX Catalina
 - Editor: VSCode
 - Programming language: Any
 - TabNine extension version: Latest
 
TabNine tried to send some data towards serene-waters-6626.morning-tundra-7160.herokuspace.com. I'm fine with your requests to api.tabnine.com but this...

**Comment by nircodota** [comment]
Hi @uyouthe,

Thank you for reporting this, the host that you reported is just where api.tabnine.com is hosted (on Heroku).
You can validate this with running "nslookup api.tabnine.com"
I wonder, where did you bump into this explicit hostname? can you please elaborate?

**Comment by uyouthe** [comment]
Firewall alerts.
