### ISSUE TITLE
TabNine Local installation guide

### ISSUE THREAD

**Issue by johnqiuwan** [codota/TabNine#289]
**please complete the following information:**	
 - OS version: Mac Catalina	
 - Editor: vscode	
 - Editor version:	1.48.2
 - Programming language: [ js, ts, php]	
 - TabNine extension version: 3.0.6
 
 **If the issue is related to TabNine failure, please provide log files:**

**Issue Details:**

I installed tabnine on vscode, however, I have no idea how I can enable tabnine local. I did not see the "Deep TabNine Local" settings.

does anyone know how to enable tabnine local?

**Comment by yanir-codota** [comment]
Hi @johnqiuwan, 
please try and type `TabNine::config` in your editor window. 
this should redirect your browser to the configuration page on a local server. 
you'll find the relevant settings under the 'Deep TabNine Local' section of the setting. 

please let me know if you require any further assistance or in case this is not what you meant.
