### ISSUE TITLE
VSCode Path Intellisense doesn't work when TabNine is on.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [codota/TabNine#291]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: vscode
 - Editor version:Version: 1.49.0-insider
 - Programming language: javascript
 - TabNine extension version:v3.0.0
 

**Issue Details:**

When TabNine is on the path IntelliSense of vscode doesn't work. When turned off, path IntelliSense works.

**HERE, TabNine is off and path IntelliSense works.**

![Screenshot (133)](https://user-images.githubusercontent.com/25576658/92388809-87ac5400-f135-11ea-9f98-52cdf12bb53d.png)

**HERE, TabNine is on and path IntelliSense does not works.**

![Screenshot (134)](https://user-images.githubusercontent.com/25576658/92388813-88dd8100-f135-11ea-9a30-f5096a2349ad.png)

**Comment by boaz-codota** [comment]
Hey @ShubhamVerma1811, this should be fixed in the beta version. Will be probably available to everyone today/tomorrow.

If you are a beta user (checkbox in `tabnine::config`) I would be grateful if you could validate the fix.

Thanks!

**Comment by ShubhamVerma1811** [comment]
Hello @boaz-codota, I am not a beta user. I will try it on the stable build and notify here.

**Comment by ShubhamVerma1811** [comment]
> 
> 
> Released, please check if fixed (validate you have version `3.1.8` first using `tabnine::config`).

I checked for Vscode extension updates, no update yet. It's on v.3.0.3
Where do I enter that command?

**Comment by ShubhamVerma1811** [comment]
The issue is still present :(

**Comment by boaz-codota** [comment]
Could you provide some screenshots so I can grasp what is happening? @ShubhamVerma1811

**Comment by ShubhamVerma1811** [comment]
It is exactly the same as it looks in the above pictures.

**Comment by boaz-codota** [comment]
@ShubhamVerma1811 I've just released 3.1.9 with a fix for this. Please confirm the behaviour once you get the new version (should be in the following hour). 🙏🏻

**Comment by ShubhamVerma1811** [comment]
This is weird.
It works on the `import` statements but not on `img` src ..?
![Screenshot (273)](https://user-images.githubusercontent.com/25576658/96207383-bd402a80-0f88-11eb-95d5-9f62a1393fa1.png)
![Screenshot (274)](https://user-images.githubusercontent.com/25576658/96207387-be715780-0f88-11eb-889c-ba501d9c5d93.png)

**Comment by boaz-codota** [comment]
On image src TabNine is not recognizing the fact that you are importing a path, so it goes to the deep model which gives you those suggestions.

This is not something easy to address and so it will take some time to fix it, but we will look into it.

Thanks for the feedback!
