### ISSUE TITLE
SublimeText 3, TabNine using up to 1Gb of RAM??

### ISSUE THREAD

**Issue by Gabriel-p** [codota/TabNine#292]
**please complete the following information:**	
 - OS version: elementary OS 5.1.7
 - Editor: SublimeText
 - Editor version: 3.2.2
 - Programming language: Python
 - TabNine extension version: 2.9.0
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

The TabNine plugin is using up to 1 Gb of RAM. Is this expected?

**Comment by amircodota** [comment]
Yes, this is expected.

By default, Tabnine deep local model is enabled, which requires roughly this amount of memory.

You can choose to disable it in `tabnine::config` - you will get completions that are not based on our deep model, the tradeoff being sacrifice quality to preserve memory.

Another option is to enable TabNine cloud if you choose (a paid option).
