### ISSUE TITLE
.tabnineignore not being honored

### ISSUE THREAD

**Issue by tnorthcutt** [codota/TabNine#293]
**please complete the following information:**	
 - OS version: macOS 10.15.6	
 - Editor: PhpStorm
 - Editor version: 2020.2
 - Programming language: Markdown
 - TabNine extension version: 3.0.8

**Issue Details:**
I added a `.tabnineignore` file to my project, with the following contents:
```
*.md
/docs/*.md
/docs/README.md
```
However, when I edit `/docs/README.md`, TabNine is still actively making suggestions. I tried restarting my editor, but that did not have any effect.

Is there some other thing I can do to get TabNine to ignore markdown files in my project? 

I am also interested in globally ignoring markdown files; is there a way to set that globally, vs. just in a `.tabnineignore` file?

Here is a gif showing what's happening:

![ezgif-4-7d337360daf4](https://user-images.githubusercontent.com/796639/92756990-8bfd8a80-f34a-11ea-9fd2-b0c5b12fb4af.gif)

**Comment by boaz-codota** [comment]
Tagging @avichay77 for prioritisation.

Thanks for pointing that out!
