### ISSUE TITLE
Tweaking the auto completion?

### ISSUE THREAD

**Issue by IPWright83** [codota/TabNine#297]
- OS version: Ubuntu 18.04	
 - Editor: Sublime Text
 - Editor version: 3 - Build 3210	
 - Programming language: JavaScript
 - TabNine extension version: 3.1.4?
 
**Issue Details:**
When working in JavaScript, whenever I do an import TabNine almost always adds the extension on the end, which isn't normal practise. This involves me deleting the last 3 characters after auto-complete each time. Is there a way to change/supress the suggestions?

e.g. instead of suggesting `require("./sampleLocation");` TabNine will suggest `require("./sampleLocation.js");`

**Comment by boaz-codota** [comment]
Thanks for the feedback Ian! 

We also hate that behaviour, and will make sure it is fixed ASAP. If anything else bothers you, please feel free to bring it up as well. 🤩

Thanks!!

**Comment by boaz-codota** [comment]
@IPWright83 This behaviour was fixed (or rather improved?) based on your suggestion. If you are a beta user (tap `tabnine::config` in your IDE to find out) you should have received the fix, it will be released to GA probably tomorrow.

Thanks again!

**Comment by IPWright83** [comment]
Thanks! I'm not a beta user, and currently TabNine is completely broken for me pending https://github.com/codota/tabnine-sublime/issues/69. I can't test it out till that's fixed I'm afraid as Tab doesn't work anymore (which is unfortunate given the name!)

**Comment by boaz-codota** [comment]
@dimacodota is working on a fix for that
