### ISSUE TITLE
[Feature] Customizable Model Path

### ISSUE THREAD

**Issue by 9S** [codota/TabNine#299]
System Information:
 - OS version: Windows 10 20H2
 - Editor: vscode
 - Editor version: 1.50.0
 - Programming language: any
 - TabNine extension version: 3.0.3

Since the Model is very large, it would be nice to be able to move it to a different partition on my hard drive. As is, it is always in %appdata%, filling up my User directory.

It would also be nice for portable VSCode installations on Flash Drives to not have to download the Model on each of my computers.

**Comment by boaz-codota** [comment]
Thanks for reaching out @9S, this seems like something we should to totally do.

Tagging @avichay77 for prioritisation on this.

Thanks!

**Comment by avichay77** [comment]
Thanks for this idea. Let's see if we have more demands for that.

**Comment by thanhnienaoke** [comment]
I vote for this feature request.

**Comment by sbwww** [comment]
Strongly recommend this feature.
The server that I'm using suffers from limited space of /home (which is the default model path). I want to move the model to another disk, but not sure which configs should I change.
I think it's better to choose a path before automatic downloading.

**Comment by wangzhuo2022** [comment]
I vote for this feature request.

**Comment by manukomalan** [comment]
Has there been any update regarding this?
