### ISSUE TITLE
Can't download TabNine binary

### ISSUE THREAD

**Issue by NathanLovato** [codota/TabNine#303]
**please complete the following information:**	
 - OS version: Linux Pop_OS! 20.10
 - Editor: Emacs
 - Editor version: 27.1	
 - Programming language: markdown	
 - TabNine extension version: 3.2.25

**Issue Details:**

Downloading the TabNine binary from the Emacs package fails since this morning. Trying to access update.tabnine.com returns a 403 error: forbidden instead of the binary. I tried to manually download it with wget, here's the response (same as what Emacs receives).

```sh
wget https://update.tabnine.com/3.2.25/x86_64-apple-darwin/TabNine
--2020-11-26 10:33:42--  https://update.tabnine.com/3.2.25/x86_64-apple-darwin/TabNine
Resolving update.tabnine.com (update.tabnine.com)... 143.204.151.77, 143.204.151.111, 143.204.151.8, ...
Connecting to update.tabnine.com (update.tabnine.com)|143.204.151.77|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-11-26 10:33:42 ERROR 403: Forbidden.
```

Is the server having a temporary issue perhaps?

**Comment by amircodota** [comment]
Apologies. It was an incorrect version. Thanks for bringing it to our attention.

The correct version is 3.2.22, and we've modified the server to return that.

**Comment by NathanLovato** [comment]
Thanks much!

**Comment by ffffaaasl** [comment]
Pyp
-@
