### ISSUE TITLE
Tabnine binary doesn't work on Apple M1 machines

### ISSUE THREAD

**Issue by talcodota** [codota/TabNine#308]
- OS version: Mac M1
 - Editor: All
 - Programming language: All
 - Tabnine extension version: 3.1.18
 
Help -> Toggle Developer Tools

Issue Details:
Tabnine was installed in MacBook pro with Apple Silicon M1, but it didn't work.
There are no error logs.

**Comment by smoothdvd** [comment]
@talcodota Check my post [Make Tabnine Great Again on Apple M1 Chip](https://smoothdvd.medium.com/make-tabnine-work-great-again-on-apple-silicon-m1-f889f728ca53)

**Comment by alanpearce** [comment]
The x86_64 binary works fine on Apple Silicon (as the link in the previous comment indicates)

Of course, a native binary would be even better.

**Comment by amircodota** [comment]
Hi folks

We are working on supporting Apple Silicon for Tabnine, and we are getting close to release.

We can provide a private plugin build for either vscode or intellij idea (and other jetbrains products).
If you are interested - contact support@tabnine.com

**Comment by lewoking** [comment]
how

**Comment by amircodota** [comment]
We have released plugins with m1 support for vscode, intellij (and other jetbrains products), sublime, vim.

If you update your plugin to the latest version, you should be able to work normally on an m1 machine.

Note that for vscode you should currently install vscode insiders build, until they formally release a version that supports m1 natively.

**Comment by alanpearce** [comment]
What's the first version that supports M1? I would like to update company-tabnine.

**Comment by amircodota** [comment]
I think it was 3.2.84' but since we already released some more versions.

I think if you update the `dl_binaries` script to be the same as [here](https://github.com/codota/TabNine/blob/master/dl_binaries.sh) and run it, it will update to the latest

**Comment by forresto** [comment]
> Note that for vscode you should currently install vscode insiders build, until they formally release a version that supports m1 natively.

This is also the message in the app:

> Apple M1 users, you can switch to the VSCode insiders build version to enable Tabnine's local deep completions. See details here.

But [VS Code supports M1 in the mainline since 1.54](https://code.visualstudio.com/updates/v1_54).

**Comment by 7sedam7** [comment]
Hi, 

versions `3.3.104` and `3.3.33` in vim when vim is ran inside of Alacritty are causing vim to be unusable. Non of the keys are responding. In normal terminal is fine. Does anybody have any ideas what happens when vim with TabNine is ran inside of Alacritty?

**Comment by dondeese** [comment]
Hi, is it possible to use Tabnine on a Macbook Pro m1 2020 in Jupyter Notebook?

**Comment by Ghasak** [comment]
just in case to anyone encountered with this problem using this fix 

cd ~.local/share/nvim/site/pack/packer/opt/cmp-tabnine
#then run the install.sh again in that directory, it fail for me when I run :PackerCompile, just run: 
./install.sh
