### ISSUE TITLE
Cpu not supported

### ISSUE THREAD

**Issue by P-Shakibafar** [codota/TabNine#310]
**please complete the following information:**	
 - OS version: Ubuntu 20.04
 - Editor: intelij	- phpstrom 2020.3
 - Editor version:	
 - Programming language: php	
 - TabNine extension version: 0.2.8
 
 **If the issue is related to TabNine failure, please provide log files:**	

 CPU:     Intel® Core™ i7-3770 CPU @ 3.40GHz 

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

{
  "version": "3.2.52",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "2020-12-25T09:35:45.316350472Z",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 2,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 35,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null
}
**Issue Details:**

**Comment by Eransho** [comment]
Please open Tabnine hub (click on tabnine in the status bar). You should have the option to use Tabnine Lite to overcome your CPU limitation

**Comment by P-Shakibafar** [comment]
@Eransho thanks for help.
