### ISSUE TITLE
VSCode - Cpu not supported

### ISSUE THREAD

**Issue by HwapX** [codota/TabNine#312]
**please complete the following information:**	
 - OS version: Win 10	
 - Editor: vscode
 - Editor version: 1.52.1
 - Programming language: php
 - TabNine extension version: 3.2.63-23
 
 **If the issue is related to TabNine failure, please provide log files:**	
I cant find log files location.

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

```
{
  "version": "3.1.1",
  "hide_promotional_message": false,
  "beta_enabled": "Yes",
  "ignore_all_lsp": false,
  "creation_time": "2020-10-08T15:37:09.658134900Z",
  "semantic_status": {},
  "enable_telemetry": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": false,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 5,
  "multiline_suggestions": false,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 23,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null
}
```

**Issue Details:**

Status bar shows "CPU not supported, click to solve", clicking opens tabnine hub, no more info is given.

Issue #310 tells about "Tabnine Lite" option, but i cant find anywhere.

**Comment by Pemidi** [comment]
Same issue in pycharm, after tabnine updating

**Comment by RangerCoder99** [comment]
Same here not got that option neither

**Comment by boaz-codota** [comment]
Hey all, sorry that you experience this issue. 

Tabnine uses several machine learning models under the hood, and one of them (the deep learning model) requires FMA instructions (see https://www.tabnine.com/faq/#FMA)

It has **always been this way**, we just started prompting you with that info, so you know that you do not get the full experience Tabnine has to offer.

There are 2 possible ways to resolve that:
* Join our free cloud plan (limited and experimental) using the message in Tabnine Hub.
* Join our Pro plan that include the Deep Completions Cloud (bigger model, GPU powered).

Tabnine was and will **function well without you doing anything**, it will just not provide you with the deep learning completions (which are a big part of the magic).

---

That said, we are aware that the messaging is too aggressive and that once the issue resolved using cloud completions the status bar is not changing (and also some state in the hub). This is a bug we addressing ASAP.

**Comment by garyking** [comment]
I've been using TabNine in VS Code for months, and suddenly, starting this morning, I see the message "CPU not supported, click to resolve" in the status bar. I already followed the instructions to download the model file and place it in the correct folder, but the message still remains.
