### ISSUE TITLE
Tabnine settings page stuck at "Initializing..." on work machine, autocomplete not working

### ISSUE THREAD

**Issue by UtkarshGpta** [codota/TabNine#313]
- OS version: Win 10	
 - Editor: vscode	
 - Editor version: 1.52.1	
 - Programming language: any language	
 - TabNine extension version: v3.2.63-35

**Issue Details:**
I'm trying to use Tabnine on my work machine after trying it out on my personal machine. I installed the extension on VSCode from the extension marketplace and restarted VSCode to finish the installation. I tried using it on a sample file stored on the machine, but I didn't receive any autosuggestions from Tabnine. I opened the Tabnine settings page, and on the top-left page, it said "Initializing..." instead of "Ready to use" like I saw when I used it on my personal machine.

You can find the log files below:

[tabnine_logs.txt](https://github.com/codota/TabNine/files/5757510/tabnine_logs.txt)

**Comment by frizzant** [comment]
How did you fix this? Does it just take some time on larger projects?

**Comment by axgalexander** [comment]
I'm having same issue when trying to run it remotely on vscode.
Locally it runs fine, but when I open a remote session it gets sucked on "Initializing". Tried several times uninstalling extension/removing all extension files/ installing again. I can't even open tabnine settings since it doesn't even start

**Comment by RitwickJoshi** [comment]
I am having the same issue, It's a great autocompletion AI but only when it fully works. Please DEVS I know you have created a great product. Just this one issue sticks for a long time. Please try and fix it.

**Comment by filasik** [comment]
same here

**Comment by pinchez254** [comment]
Having the same issue on mac os Big Sur. its really annoying because its blocking the terminal.

**Comment by Icy-cui** [comment]
Maybe this problem caused by the conflict between Vetur3.0 and Eslint. Reinstall the previous version of Tabnine may solve the initialization problem (cuz I solved through this way :) ).

**Comment by AvasDream** [comment]
I'm having the same issue. Tabnine is stuck at `initializing`. It previously worked, I could log in and use it, but after rebooting it got stuck again. 

VSCode: 1.58.2
TabNine: 3.4.17
macOS Big Sur: 11.4

Was someone able to fix this? I've already created exceptions for all firewalls and reinstalled everything a couple of times. This is really annoying.

**Comment by pinchez254** [comment]
I upgraded my VSCode and the issues Seams to be gone

**Comment by Lalan12** [comment]
![image](https://user-images.githubusercontent.com/69614610/128655898-34ca722d-1e3b-4f7e-8824-0468f24e6a42.png)
It's very large so it can happen

**Comment by AvasDream** [comment]
I updated to the latest version `3.4.22` of the VSCode Tabnine extension and the issue seems to be gone.

**Comment by Davidrigden** [comment]
I had the same problem. I got mine working by deleting the extension, restarting VS Code, then downloading the extension again.

**Comment by MouraCass** [comment]
Guys, when I recently downloaded tabnine, it was not working, but then I closed and restarted vscode, this problem here is gone. 
![image](https://user-images.githubusercontent.com/86990508/168176036-3d2eb59e-95cc-4e47-ac29-9152377916ac.png)

**Comment by TcNobo** [comment]
I am also receiving this issue. VSCode, VSCode Insider, all the same. I've downloaded everything, but still nothing useful.
![image](https://user-images.githubusercontent.com/10319195/190470739-972c078b-2aa9-4061-a788-18d2569fe8a0.png)

**Comment by fredericomattos** [comment]
Just to corroborate the topic, the exact same thing happens to me, even if I open 2 different VSCode windows it sometimes just finishes initializing the window that is in the foreground, the other one keeps showing the initializing alert.

But the normal thing is to be initializing both eternally.

**Comment by Betristor** [comment]
I'm not sure that my problem is the same as yours. But my tabnine on remote machine even didn't initialize at all. The binary didn't exist in the file location where it should be.

**Comment by JorgeT10** [comment]
This is still happening

**Comment by nikontos** [comment]
I have this issue. On the Tabnine output this is the loop its stuck on

`7:26:27 GMT+0200 (Eastern European Standard Time) [DEBUG]: Updating root paths for project Cloudon (Workspace): ["c:\\Users\\nikon\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\urllib3\\edapy","d:\\Cloudon\\fAnazitisi"] 

`
