### ISSUE TITLE
TabNine config incorrectly documented in IntelliJ.

### ISSUE THREAD

**Issue by DewiMorgan** [codota/TabNine#314]
- OS version: Win10
 - Editor: intelij
 - Editor version: Community 2020.3
 - Programming language: Lua
 - TabNine extension version: 0.2.9, TabNine 3.2.63-32
 
**Issue Details:**
In the text details for the IntelliJ TabNine plugin, the description seems to be for both a different platform (Mac?) and a different IDE (Microsoft?)

Examples:

"Installation Instructions
Press Cmd+,to open the Settings/Preferences dialog"

 - There is usually no "Cmd" key on a Windows machine. The hotkey is Ctrl-Alt-S.
 - There is no such thing as a "Settings/Preferences" dialog in Windows' IntelliJ, it's "File" menu -> "Settings" menu item -> "Plugins" section. 

"Trouble installing? Check out our FAQ page, or contact support@tabnine.com"

- The FAQ page contains no information on installing Tabnine in intelliJ.

"After Tabnine’s installation, navigate to the Tabnine Settings page (‘Tabnine: Open Settings’ from the Command Palette) and verify that Tabnine local model is successfully loaded (as shown in the following screenshots)"

 - There is no "Command Palette" in IntelliJ, and "Command Palette" is a link to the Visual Studio site.
 - There are no "following screenshots".
 - There appears to be no settings page for TabNine in IntelliJ. This is unfortunate, as if there were a way to stop it prioritizing its bad suggestions over the IDE's correct suggestions, I would likely continue using it.

**Comment by boaz-codota** [comment]
Thank you for reporting this! 

We will make sure to improve it!

Thanks!

**Comment by YotamFromCodota** [comment]
Hey @DewiMorgan,

Just letting you know we've updated the textual details you've mentioned. 
Thanks again for bringing this to our attention!

**Comment by DewiMorgan** [comment]
Looks good to me! :D Fast response!
