### ISSUE TITLE
Lua in IntelliJ gives fairly ludicrous suggestions.

### ISSUE THREAD

**Issue by DewiMorgan** [codota/TabNine#315]
- OS version: Win10
 - Editor: intelij
 - Editor version: Community 2020.3
 - Programming language: Lua
 - TabNine extension version: 0.2.9, TabNine 3.2.63-32
 
**Issue Details:**
Hitting the enter key at the end of typing the following lines:

```
while true do
    if 1==1 then
        -- this is an example.
    end
end
```

Gives this code:
```
    while true down
        if 1==1 blockTheAction
            -- this is an example. Must
        end
    end
```

If I type "do" or "then", or if I use a period at the end of a comment... I do not expect hitting that enter will replace my text with something so clearly wrong.
The IDE in each case gets the suggestion right ("do", "then", and nothing, respectively), and that suggestion is the first in the menu.
However, TabNine's suggestions are the ones selected, even when I have unchecked the setting File->Settings->Editor->General->"Code Completion"->"Sort completion suggestions based on machine learning".

TabNine sometimes makes some fairly smart suggestions, which could save me work. But with the current way of working, where the suggestions are not mere suggestions but are implemented if I try to go to the next line, I find am spending far more time correcting it, than it is saving me. I hope this will change in the future, but for now, I am disabling it until Lua and IntelliJ support have had a little more time to mature.

**Comment by boaz-codota** [comment]
That unfortunate to hear. 

We will look into it, and hopefully have a fix ready ASAP. 

This is a bit of a tricky situation, so it might take some time. I hope you'll bear patience and give us a change to fix this.

Thank you for letting us know!

**Comment by DewiMorgan** [comment]
Note that it is entirely possible that this is just user error on my part, perhaps a config setting I've missed or something. In which case, this could just be resolved by documentation telling people to tweak that setting when installing.
