### ISSUE TITLE
Tabnine hides other suggestions

### ISSUE THREAD

**Issue by exapsy** [codota/TabNine#318]
- OS version: Linux Manjaro 5.10.2-2
 - Editor: vscode
 - Editor version:	1.52.1
 - Programming language: Happens in many languages, but in VSCode's configurations it doesn't ever let other suggestions ever appear
 - TabNine extension version: 3.1.25

**Issue Details:**

There are two natures of the issue from what I've experienced. One is "bypassable" and one is not.

1. **The bypassable** - **Sometimes** (but not always) when you write, in any language (TS, JS and Golang) only tabnine's suggestions appear. You can go around this issue by just pressing `Ctrl+Space` twice. Then you'll get both Tabnine's suggestions and the other ones.
2. **The non fixable one** - In JSON documents inside VSCode's config, like keyboard settings or preference settings, VSCode's suggestions don't appear at all, **always**. It's like writing on a pure JSON config without any context. You can see what I mean below.

Tabnine disabled

![image](https://user-images.githubusercontent.com/9019120/104122299-edf7ec00-534c-11eb-9ff2-ee334ab08b49.png)

Tabnine enabled

![image](https://user-images.githubusercontent.com/9019120/104122316-05cf7000-534d-11eb-9f8c-da1cd3b11eed.png)

**Comment by shaiahr** [comment]
Thanks for reporting this to us. 
I wasn't able to reproduce the 'bypassable' issue you describe but I'll try again. If you manage to find a persistent way of reproducing this, that would be great. 
Anyway, we'll try to solve both issues.

**Comment by exapsy** [comment]
@shaiahr Last time I had the "bypassable" issue, I recall that I wanted to edit the description and that's because I was able to reproduce it but in a different way than I initially described.

Basically, I'm not sure 100% how to reproduce it with certainty, it's kinda random to me. But I think it had something to do with the period you place

```
log. // Sometimes gets only tabnine
log // Gets all
```

But yeah, take these words with a grain of salt as I'm not really confident in how to reproduce the issue either.

**Comment by tuan-lm** [comment]
Can confirm that this problem still occur recently. Some time it only show tabnine suggestion but hide others suggestion like emmet or typescript property. I occasionally see this happend in vue files(using vetur) and ts files

**Comment by bourquep** [comment]
Same thing happens for me with C# code. For example, when typing an opening parenthesis (e.g. for a function call), I'll see the Tabnine suggestions but not the parameter tooltip I'd usually get by vscode. Also, if I try to use the up/down arrows to navigate through the possible overloads of the method I'm calling, the Tabnine tooltip swallows those arrow keys so I have no choice but to use my mouse to click the up/down arrows in the tooltip:

<img width="960" alt="CleanShot 2021-02-19 at 09 54 32@2x" src="https://user-images.githubusercontent.com/65096/108520537-cc1d4d80-7298-11eb-9ae0-845147abab09.png">

**Comment by jdkula** [comment]
I notice that this happens when `editor.suggestOnTriggerCharacters` is set to `true` in `settings.json`. It seems to be the same issue that [this issue](https://github.com/codota/tabnine-vscode/issues/6) fixed? For me, it's not bypassable by hitting `^space`. Here's the relevant snippet of my configuration:

```
  "editor.suggestSelection": "recentlyUsedByPrefix",
  "editor.suggestOnTriggerCharacters": true,
  "editor.quickSuggestionsDelay": 0,
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  },
  "editor.suggest.localityBonus": true,
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
```

Turning `editor.suggestOnTriggerCharacters` to false appears to fix it, but then my suggestions don't appear on type (I have to hit `^space` to get any suggestions at all).

**Comment by NecipAkgz** [comment]
I have exactly same problem, it's hard to use this way. In this way tabnine giving 1 and getting 10 suggestion

**Comment by Tasen-pro** [comment]
> * OS version: Linux Manjaro 5.10.2-2
> * Editor: vscode
> * Editor version:	1.52.1
> * Programming language: Happens in many languages, but in VSCode's configurations it doesn't ever let other suggestions ever appear
> * TabNine extension version: 3.1.25
> 
> **Issue Details:**
> 
> There are two natures of the issue from what I've experienced. One is "bypassable" and one is not.
> 
> 1. **The bypassable** - **Sometimes** (but not always) when you write, in any language (TS, JS and Golang) only tabnine's suggestions appear. You can go around this issue by just pressing `Ctrl+Space` twice. Then you'll get both Tabnine's suggestions and the other ones.
> 2. **The non fixable one** - In JSON documents inside VSCode's config, like keyboard settings or preference settings, VSCode's suggestions don't appear at all, **always**. It's like writing on a pure JSON config without any context. You can see what I mean below.
> 
> Tabnine disabled
> 
> ![image](https://user-images.githubusercontent.com/9019120/104122299-edf7ec00-534c-11eb-9ff2-ee334ab08b49.png)
> 
> Tabnine enabled
> 
> ![image](https://user-images.githubusercontent.com/9019120/104122316-05cf7000-534d-11eb-9f8c-da1cd3b11eed.png)

Thats why i stopped using tabnine

**Comment by mh-firouzjaah** [comment]
Hello everybody. The problem is still there and its annoying, but instead of disabling the `editor.suggestOnTriggerCharacters`, there's another trick thats simple:
- When the tabnine's suggestion appears, first press `Esc`, then press `Ctrl+Space`, and now both the editor's and the tabnine's suggestions appears.

**Comment by dashcode** [comment]
Hi. Just saying that the problem still exists. Using `Ctrl+Space` every time is such a hassle.

**Comment by cindrmon** [comment]
Hi! Just letting future people know that this problem still exists to this day, and it is even overpowering emmet. I can't make emmet autocomplete properly thanks to tabnine suggestions.
