### ISSUE TITLE
TabNine is crashing my system with huge 100%+ CPU usage

### ISSUE THREAD

**Issue by chabad360** [codota/TabNine#320]
**please complete the following information:**	
 - OS version: Linux 5.10.7-arch1-1 
 - Editor: Goland (intellij)
 - Editor version: 2020.3.1
 - Programming language: Go
 - TabNine extension version: 0.2.9
 - TabNine engine version: 3.3.33-0
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

**Issue Details:**

I've been using TabNine for a while now (a year or two), and between yesterday and today (4 hrs total) I've had to force restart my computer 6-7 times after TabNine crashed my system. After the first or second time I started watching my CPU usage (on another monitor) with `htop` and every time my system crashed there were a lot of TabNine processes at the top, with one of them at over 100% CPU and the ones under it not much better. This is despite the fact that TabNine failed to provide any completions, so it both crashed my system and even then it still wasn't useful.

**Comment by amircodota** [comment]
@chabad360 Thanks for reporting this.

Can you describe what you mean by crashed the system? Did your ide crash?

Also, it would be great if you can configure tabnine to write to a log file.

Here's how to do it in intellij based ides:

1) Help -> Edit Custom Properties
2) In the opened editor, add the line

```
TABNINE_LOG_FILE_PATH={full-path-to-log}
```
3) restart your ide.

Let it run for a while, and then send us the log file for analysis.

Thanks
