### ISSUE TITLE
TabNine try to connect to different IPs everytime

### ISSUE THREAD

**Issue by miladr0** [codota/TabNine#327]
**please complete the following information:**	
 - OS version: Mac Mojave
 - Editor: vscode	
 - Editor version:	
 - Programming language: js	

**Issue Details:**
I am curious why every time TabNine tries to connect to different IPs? and which data will be sent to those IPs?

**Comment by boaz-codota** [comment]
That is weird. What IPs are you seeing Tabnine sending data to?

We use domain names for everything happening, so maybe you are seeing the ip of those?
