### ISSUE TITLE
Tabnine von Windows 10 in Virtualbox: "Initializing..."

### ISSUE THREAD

**Issue by simonmeggle** [codota/TabNine#328]
I am trying tabnine on a Windows 10 VM (virtualbox) with >8GB RAM and 4 Cores. 
Editor is VS Studio Code. 

**Problem**: "Local Model" cannot be activated, it keeps displaying "Initializing..."

Coreinfo (https://docs.microsoft.com/en-us/sysinternals/downloads/coreinfo) shows that **FMA is supported**: 

![image](https://user-images.githubusercontent.com/1897410/105487215-03a3d480-5cb0-11eb-8d3f-04f4d768c972.png)

Any help is appreciated!

**Comment by boaz-codota** [comment]
Hey @simonmeggle ,

Are you getting `partial support` messages? If not, this seems like connectivity issue. Maybe you have a proxy that is misconfigured or is blocking Tabnine to communicate to our servers?

**Comment by geovex** [comment]
Your screenshot shows that fma instruction set isn't supported. This is the issue with virtualbox. 
https://www.virtualbox.org/ticket/15471

**Comment by geovex** [comment]
however there is no way to disable it while it "initialising"
