### ISSUE TITLE
TabNine cannot download a local model, and documentation about the issue does not describe the current version of TabNine

### ISSUE THREAD

**Issue by StragaSevera** [codota/TabNine#329]
**please complete the following information:**	
 - OS version: Arch Linux
 - Editor: intelij
 - Editor version: 2020.3
 - Programming language: rust
 - TabNine extension version: 4.4-2020.3-517
 
 **If the issue is related to TabNine failure, please provide log files:**	
>  Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

There are no logs at the bottom of the page. It ends with "Installation Info".

**Issue Details:**
Tabnine tries to download the model, is unable to, then tries again, switching between `Retrieving model metadata...` and 
```We Can Help!
There seems to be an issue downloading the deep model.
please refer to the
Faq section
in our site, or contact support at:
support@tabnine.com
The download failed: Permission denied (os error 13)
```

The FAQ link provided says: "In Tabnine's configuration server, under "Deep Tabnine Local" section, click on "Download the deep model file from here" link.", but there is no "Deep Tabnine Local" section, nor there is any "Download the deep model file from here" links.

What should I do to stop this downloading madness? =-)

**Comment by boaz-codota** [comment]
Hey @StragaSevera 

Seems like Tabnine process is lacking the permissions it need to write to the folder in which it writes that model into.

You need to run your IDE (intellij) with higher privileges so Tabnine could write the downloaded model to the filesystem.

**Comment by StragaSevera** [comment]
When I try to run IntelliJ as root, I cannot open Tabnine settings: when I push the button in GUI, it says "Could not open default web-browser. IO error.", and when I type `TabNine::config`, nothing happens.

I would be very glad to have an option to just download files manually, figure out the permissions needed for the folder, put them in the folder and run tabnine. The FAQ said I can do that - did you remove this feature?

**Comment by Shougo** [comment]
TabNine::config works for me.

**Comment by boaz-codota** [comment]
> When I try to run IntelliJ as root, I cannot open Tabnine settings: when I push the button in GUI, it says "Could not open default web-browser. IO error.", and when I type `TabNine::config`, nothing happens.
> 
> I would be very glad to have an option to just download files manually, figure out the permissions needed for the folder, put them in the folder and run tabnine. The FAQ said I can do that - did you remove this feature?

You can download the model manually, and it should present you with manual download instructions similar to those:
![image](https://user-images.githubusercontent.com/69103343/105630877-2a9b0b80-5e54-11eb-8d2a-bdfd8b166f4e.png)

Can you post a picture of what you see in the Hub (as for my understanding you are not seeing the manual download instructions)? @StragaSevera

**Comment by StragaSevera** [comment]
Well, I enabled the beta-release of Tabnine, and now it shows the instructions - but the download link ( https://update.tabnine.com/models/null ) does not work and gives 403 error.

Screenshot:

![](https://imgur.com/vqsRgWq.png)

**Comment by boaz-codota** [comment]
This seems like a bug on our end. I will fix it.

In the meantime, there are instructions in: https://www.tabnine.com/faq/#manual_model_download

But I think that the best thing you can do, is give the models folder (described in the manual download instructions) permissions so that Tabnine process could write to it.

Let me know how it went.

**Comment by StragaSevera** [comment]
Fixed the problem with the models folder - it was on my end. Models auto-downloaded and all is OK now =-)

**Comment by hronro** [comment]
![CleanShot 2021-04-09 at 00 16 53@2x](https://user-images.githubusercontent.com/15059605/114061407-fec2ea00-98c8-11eb-9cda-a45c0dabde94.png)

For me the status stays on "Download pending...", how can I fix this?

**Comment by JamesApple** [comment]
This appears to have regressed. There's no download link or reason but "Initializing..." was stuck for more than 5 hours in this state.

![image](https://user-images.githubusercontent.com/12153188/127338301-4be1ccdb-7221-4dc5-a3ee-e9a99da5e5c3.png)

It appears Tabnine gets out of sync somehow and refuses to finish the download.

If this happens to anyone else try and delete the `~/.config/TabNine` and do a hard update in the editor  `CocCommand tabnine.updateTabNine` which resolved it for me.

**Comment by zendesk-thittesdorf** [comment]
For future people that end up here.  I had the same issue and had to delete ~/Library/Preferences/Tabnine/* and log back in to fix it.
