### ISSUE TITLE
Deep Completion Local section is not shown in the config page, in WSL

### ISSUE THREAD

**Issue by Stdev17** [codota/TabNine#330]
**please complete the following information:**	
 - OS version: Ubuntu-20.04 as WSL 2 in Windows 10
 - Editor: vscode
 - Editor version: 1.52
 - Programming language: (regardless with the issue)
 - TabNine extension version: v3.2.3

(the normal counterpart)
 - OS version: Ubuntu-18.04 (native)
 - Editor: vscode
 - Editor version: 1.52
 - Programming language: (regardless with the issue)
 - TabNine extension version: v3.2.3
 
 **If the issue is related to TabNine failure, please provide log files:**	

 Type `TabNine::config` in your editor, the logs are located at the bottom of the page.

I could not find the logs in the pages of both two machines.

**Issue Details:**

For my machines, the local mode of TabNine seems super heavy to run. So I got to turn off the feature. It worked smoothly in the native Linux machine, but in the WSL one. 1) The Deep Completion Local section is completely missing in config GUI(TabNine Hub). I tried to fix the setting by editing the setting file(tabnine_config.json.) After coercing it to fix the problem, 2) then the GUI got stuck(or froze) in any sense. Both two issues seem pretty unnatural.

**Comment by boaz-codota** [comment]
Hey @Stdev17 sorry for the troubles.

I think that:
1) Is it possible that you are using WSL 1 and not 2? See https://docs.microsoft.com/en-us/windows/wsl/compare-versions

2) I think it got stuck because it does not have write permissions to the config file (you can locate its path in the bottom of the Hub page)

**Comment by Stdev17** [comment]
@boaz-codota , Thank you for the support.

Of course, I had double-checked the version is 2 with ```wsl -l --all -v```. I wonder if this situation is reproducible, but I have no idea this time without further investigation.

It seems to edit the config file with vim fixed the write permission, and left TabNine unapproachable. I don't know what the original permission setting is. However, It would be solved with a proper one.

So I close the issue this time until someone(including me) reopens it for additional problems.
