### ISSUE TITLE
A weak suggestion relating to import/export modules in PyCharm

### ISSUE THREAD

**Issue by hazartilirot** [codota/TabNine#333]
PyCharm Pro 2020.3.3 (the latest)
TabNine::version3.3.39
Plugin in a store 0.3.1
Windows 10 x64 Pro
JavaScript/TypeScript

The issue:  a weak suggestion relating to import/export modules in PyCharm. TabNine seems to have not tracked files location.

Another issue irritating me is all those directories. If I'm using TabNine 3.3.39, why does it not delete 3.3.35 or switch to 3.3.41 since it's a newer version? Another day you open the TabNine's directory and find 5-7 directories. What the heck? Do we really need to collect them? I wonder....
```
C:\Users\USER\.tabnine>dir /B
.active
3.3.35
3.3.39
3.3.41
```

**Comment by boaz-codota** [comment]
Hey @hazartilirot ,

Regarding the older versions, we keep some of them to allow quick rollback incase of a faulty version. Each version is ~20mb so I'm not sure why that is so much irritating to you. I would love to further assist.

Regarding the `weak suggestion relating to import/export` - I'm not sure what you mean. I would love to see some examples (screenshots) to further assist.

**Comment by hazartilirot** [comment]
It looks like TabNine is unaware of importing modules since I'll make a guess it doesn't work with file system of a project. As you see in the snapshot the built-in autocomplete suggests exactly what I need. Here's an example (see the attachment).
![ts](https://user-images.githubusercontent.com/1349977/106121612-6c7fc680-6160-11eb-9a93-2adb60cd1f71.png)

**Comment by boaz-codota** [comment]
Yep Tabnine is not as aware you'd expect for modules. Why are working on some improvements in that area, but all in all Tabnine is a Machine Learning solution, so It will probably never be 100% correct.

Thank you for making us more aware of such use cases.

**Comment by dimacodota** [comment]
Hi @hazartilirot, is project1 a git project (contains a .git folder)?

**Comment by hazartilirot** [comment]
> Hi @hazartilirot, is project1 a git project (contains a .git folder)?

Oh, I didn't see you comment. 
Unfortunately it isn't . I just do some random examples. Have a go at working in the IDE.

Here's another one:
![PyCharm](https://user-images.githubusercontent.com/1349977/107373480-40186280-6aef-11eb-8bd9-cacbf8c71b45.png)

PyCharm 2020.3.3 (Professional Edition) build on January 27th
TabNine::Version 3.3.57
the plugin: 0.3.2

Typescript 4.1.3
Windows 10 Pro x64

**Comment by hazartilirot** [comment]
GitHub doesn't allow to upload archives in 7zip so I was forced to compressed it twice so that I was able to share it with you. Sorry, you should extract the content twice though. :)
[Strategy.zip](https://github.com/codota/TabNine/files/5951860/Strategy.zip)

**Comment by hazartilirot** [comment]
Here's a funny thing irritating me.
TabNine is doing a great job suggesting me to use **image**s, then **avatar**. 
I get in the end
`faker.images.avatar`
 It somehow knows that after image should be used **avatar** The thing is I get an error. I then go to the library's homepage [](https://github.com/marak/Faker.js/)
finding out that it should've been **image** not in plural.

![faker image avatar](https://user-images.githubusercontent.com/1349977/108544157-bc305880-72ee-11eb-917c-20091181631f.png)
