### ISSUE TITLE
[feature] Individual models depending on language

### ISSUE THREAD

**Issue by leonel-lordford** [codota/TabNine#335]
Hello there, amazing job with TabNine! Thanks a lot.

Some friends and I are wondering if is it possible to have like separated models (well trained) providing even better performance depending on the type of workspace/project/file you are working on... maybe this sounds ridiculous and maybe even is the current approach, but I just want to clarify or suggest this feature, I think can be good if you as a programmer can decide if you want to use a "big" general model or just a "smaller" and specialized model for one specific scenario.

Thanks again.

**Comment by yonip23** [comment]
Hi @leonel-lordford,
Always nice to receive a positive feedback, thanks for that :smiley: 

This is indeed a good idea, and features like what you're suggesting are currently being discussed in Tabnine's team.

Best regards

**Comment by leonel-lordford** [comment]
Thanks for your message! Looking forward to seeing more improvements. Great job and thanks a lot.
