### ISSUE TITLE
Tabnine's paid features are disabled when completing Rust code.

### ISSUE THREAD

**Issue by w01fb0ss** [codota/TabNine#336]
**please complete the following information:**	
 - OS version: Mac Big Sur	
 - Editor: vscode
 - Editor version:1.53.0
 - Programming language: rust
 - TabNine extension version:3.2.6
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

What language is Tabnine written in?
Tabnine is 14,000 lines of Rust.

In recognition of the fact that Tabnine could not exist without the Rust ecosystem, Tabnine's paid features are always enabled when completing Rust code.

But, this is a joke.

**Comment by YossiSalomon** [comment]
Dear @w01fb0ss ,

We'll be happy to give you a free Pro license - please contact support@tabnine.com and we'll assist you

**Comment by lukechu10** [comment]
> Dear @w01fb0ss ,
> 
> We'll be happy to give you a free Pro license - please contact [support@tabnine.com](mailto:support@tabnine.com) and we'll assist you

Wait, so anybody who codes in Rust gets a Pro license? What if they use it for other languages as well? I am a Rust programmer, can I get a free Pro license too? 😕
