### ISSUE TITLE
An issue downloading the deep model: error sending request for url

### ISSUE THREAD

**Issue by beiyuouo** [codota/TabNine#338]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: Pycharm
 - Editor version: PyCharm Community Edition 2020.1.4 x64
 - Programming language: Python
 - TabNine extension version: 0.3.2

**Issue Details:**
```
LocalModel: Initializing...
There seems to be an issue downloading the deep model:
error sending request for url (https://api.tabnine.com/model_metadata/v1): error trying to connect: unexpected EOF during handshake
If you fail to fix the error above, contact support at support@tabnine.com.
```
I opened `https://api.tabnine.com/model_metadata/v1` in my browser and got 404.

**Comment by dimacodota** [comment]
Hi @beiyuouo,

Using the browser won't work for this case, since it's a POST message and not a GET.

Are you using a proxy?
if so, please set the HTTP_PROXY and HTTPS_PROXY environment variables accordingly, and try again.

**Comment by beiyuouo** [comment]
Thank you for your patience, I solved this problem with your help.
