### ISSUE TITLE
TabNine makes too many sub processes and auto-completion doesn't work

### ISSUE THREAD

**Issue by zrma** [codota/TabNine#339]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: GoLand, CLion
 - Editor version: 2020.3.2	
 - Programming language: golang, rustlang
 - TabNine extension version: 0.3.2
 - Engine version (could be located within Tabnine Hub): 3.3.57-26

**Issue Details:**

TabNine makes too many sub processes(over thousands TabNine.exe and six TabNine-deep-cloud.exe).
And TabNine-deep-local.exe appears and disappears very soon repeatedly.
And then, auto-completion suggestion also works and doesn't work repeatedly.

![image](https://user-images.githubusercontent.com/4281810/107847868-5ba6a480-6e32-11eb-87b5-c47a79b9e26b.png)

![image](https://user-images.githubusercontent.com/4281810/107725147-e69b7800-6d28-11eb-8ac5-291724a04101.png)

Thank you for your help.

**Comment by yonip23** [comment]
Hi @zrma 
Thank you for reaching out with your issue - seems quite serious

Lets take a look at your idea & Tabnine's logs - 
- Ide logs: follow [this](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)
- Tabnine's logs: Go to `Help -> Edit Custom Properties...` and add to the properties file: `TABNINE_LOG_FILE_PATH={path to logfile}`

Best regards

**Comment by zrma** [comment]
Dear @yonip23
Thank you for helping me.

[log_file.zip](https://github.com/codota/TabNine/files/5977901/log_file.zip)

Log files are too big to upload, so I archive two files.
log_file.zip includes `idea.log` and `tabnine.log`.

I hope it's helpful to solve the problem.

Best wishes. :)

**Comment by yonip23** [comment]
Hi @zrma 
This is indeed helpful, we're investigating it as we speak, will let you know as soon as we will have something.

Best regards

**Comment by yonip23** [comment]
Hi @zrma 
We have released Intellij plugin v0.3.3 with a fix to your issue, please update your plugin and let us know if it solved the issue so we can close this pr :smiley:

**Comment by zrma** [comment]
> Hi @zrma
> We have released Intellij plugin v0.3.3 with a fix to your issue, please update your plugin and let us know if it solved the issue so we can close this issue 😃

Dear @yonip23

Thank you so much.
I installed v0.3.3 and test it.

At first, I found that tabnine doesn't make sub processes too many anymore. it solved.
But it's still repeatedly stopped to work auto-completion suggestion.

So I upload `ide log` and `tabnine log` again that I hope it's helpful to you.

[idea.log](https://github.com/codota/TabNine/files/6002632/idea.log)
[tabnine.log](https://github.com/codota/TabNine/files/6002633/tabnine.log)

Are there any additional steps I need to do for solving that problem(periodic stopping of working)?

Best regards.

**Comment by zrma** [comment]
In plugin v0.3.3, the bug that TabNine makes too many sub processes was fixed, so I close this issue and I will make other issue about **repeatedly stopped to work auto-completion suggestion in some condition**.

Thank you for your help.

**Comment by eduardoripio** [comment]
I don't think this issue was fixed!

I still have the same problem

![image](https://user-images.githubusercontent.com/101282922/186984930-55dc6702-10b9-4ca8-9235-dbbca6889bb9.png)

**Comment by AchwaqKhalid** [comment]
January 2024 and the issue is still persisting......
