### ISSUE TITLE
[Bug] Stopped working on VS Code on MacOS

### ISSUE THREAD

**Issue by fredsvanelli** [codota/TabNine#340]
**please complete the following information:**
 - OS version: MacOs Big Sur 11.0.1
 - Editor: VS Code
 - Editor version: 1.53.2 (most recent)	
 - Programming language: Any	
 - TabNine extension version: 3.2.7 (most recent)
 - Engine version (could be located within Tabnine Hub): TabNine Hub is not opening

**Issue Details:**
TabNine stopped working after upgrading to 3.2.7. No autocompletions. TabNine Hub show a blank page.

I already tried disable/enable and remove/reinstall.

**Comment by boaz-codota** [comment]
Hey @fredsvanelli ,

Sorry for the late response. Are you getting suggestions from Tabnine? Are you seeing Tabnine's in your status bar? Is there something special about your setup we need to know (to swiftly resolve the issue)?

**Comment by neo-cheung** [comment]
I have the sample problem 
OS: Mac 11.2.1 (intel)
VS code 
Version: 1.53.2
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

It also not working after upgrade TabNine to 3.2.7, but not affecting other IDE with non 3.2.7

The support team has following up on the problem but no solution yet

**Comment by neo-cheung** [comment]
I found a workaround for this problem, seems the binaries for vs code plugin are borken

install TabNine for sublime text first 

boken (vs code)
`~/.vscode/extensions/tabnine.tabnine-vscode-3.2.7/binaries/3.3.64/x86_64-apple-darwin`

sublime binaries
`~Library/Application Support/Sublime Text 3/Packages/Tabnine/binaries/3.3.65/x86_64-apple-darwin`

copy binaries TabNine and WD-TabNine from sublime directory and put them in vs code it resolves the problem

**Comment by daneelf** [comment]
I have the same problem too! Didn't try the workaround though.

OS: macOS Catalina v10.15.7

VS code: 
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron

**Comment by fredsvanelli** [comment]
> x86_64-apple-darwin

I did this and now **it's working** again! Thank you!

**Comment by fredsvanelli** [comment]
> I found a workaround for this problem, seems the binaries for vs code plugin are borken
> 
> install TabNine for sublime text first
> 
> boken (vs code)
> `~/.vscode/extensions/tabnine.tabnine-vscode-3.2.7/binaries/3.3.64/x86_64-apple-darwin`
> 
> sublime binaries
> `~Library/Application Support/Sublime Text 3/Packages/Tabnine/binaries/3.3.65/x86_64-apple-darwin`
> 
> copy binaries TabNine and WD-TabNine from sublime directory and put them in vs code it resolves the problem

I did this and now it's working again! Thank you! @neo-cheung

**Comment by daneelf** [comment]
Reinstalling vscode did it for me!
