### ISSUE TITLE
Exit code 2

### ISSUE THREAD

**Issue by lougreenwood** [codota/TabNine#341]
**please complete the following information:**	
 - OS version: MacOS Big Sur
 - Editor: neovim	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 3.2.28

**Issue Details:**

I'm attempting to get Tabnine running on Nvim using ["completion-tabnine"](https://github.com/aca/completion-tabnine) Neovim plugin. However, when I run the binary for Tabnine (or launch vim with the plugin enabled) I get an error code 2.

```
❯ ./binaries/3.2.28/arm64-apple-darwin/TabNine
./binaries/3.2.28/arm64-apple-darwin/TabNine: line 1: syntax error near unexpected token `newline'
./binaries/3.2.28/arm64-apple-darwin/TabNine: line 1: `<html>'
```

I'm on an M1 Mac mini. Tabnine works fine in VSCode on the same machine. Perhaps I need some config since I use Tabnine Pro in VSCode?

**Comment by amircodota** [comment]
@lougreenwood This looks like an issue with [completion-tabnine](https://github.com/aca/completion-tabnine).

They do not seems to have support for apple m1.

It seems they are attempting to download a "arm64-apple-darwin" distribution of tabnine which does not exist.
So instead they get a 404 html and saving it as the binary, then trying to execute it.

The correct distribution to download in such a case is "aarch64-apple-darwin". Should be pretty easy fox on the plugin side, hopefully :-).

I'm going to go ahead and close this issue - please open an issue on the plugin repo

**Comment by lougreenwood** [comment]
Thanks @amircodota - I do have a followup question though. Is there a reason that the `aarch64` was chosen as the prefix? It seems that if the Apple Silicon build used the `arm64` prefix, just like the `uname -m` command outputs on these machines, then the `completion-tabnine` script wouldn't need modifying. 

It also generally seems that using the `uname` reported prefix would be more consistent too?

**Comment by amircodota** [comment]
Tabnine is written in rust, and so we name our platform targets after the rust "target" name (see [rust platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html)).

Note that Tabnine is used on multiple OSes (also Windows, which does not have a `uname` utility at all), and is used by plugins written in multiple languages.
I do not think there was one name we could choose that would have made it simple for everyone.

Hope it makes sense :-)
