### ISSUE TITLE
Please stop advertising in my editor

### ISSUE THREAD

**Issue by rekmarks** [codota/TabNine#342]
- OS version: Mac
 - Editor: vscode
 - Editor version: latest
 - TabNine extension version: latest

Please stop advertising in the VS Code status bar or let me disable advertisements through settings. It's of course fine to advertise in update news or extension settings, but my workspace is not a billboard.

**Comment by boaz-codota** [comment]
Hi @rekmarks 
Tabnine has a Pro version, which gives you even more power, speed and accuracy. This is our way to make revenue, which then allows us to continue providing Tabnine’s Free version to so many developers.

So, from time to time, we will selectively offer Tabnine Pro.

We hope it doesn’t bother you too much, as we always try to make it subtle, not too frequent and not blocking.

By the way, I truly love MetaMask, and appreciate the work you do on it. I hope you enjoy our work enough to decide to support us one day in the future.

Thanks, Boaz.

**Comment by reflog** [comment]
The rate of the ad appearing is rather frequent :(

**Comment by boaz-codota** [comment]
@reflog Is it more than once an hour for 2 minutes?

**Comment by crewone** [comment]
Things like this make me regret I ever bought the pro version.

**Comment by bilucodota** [comment]
Upgrading to Tabnine Pro provides a much better experience. It also allows us to invest more resources in improving the product, and offer a Free version. It’s a standard freemium model.

**Comment by bobmagicii** [comment]
i see we gave up on this

![image](https://user-images.githubusercontent.com/881944/143961491-dabeffe1-1971-436a-ae40-ed9ece62c9e9.png)

literally the brightest thing on my screen

![image](https://user-images.githubusercontent.com/881944/143961548-069ac523-5419-40a8-97d5-fb94ae8ae2f7.png)

**Comment by avichay77** [comment]
Hi, 

Thanks for the feedback. 

We try to minimize these messages, but in the same time these promos enables us to offer a good Free plan for all our users. 
Having said that, we do want find the optimal way to balance between this need and your feedback. 

Can you elaborate of what bothered you the most?

1. The bright yellow color?
2. The fact that you cannot git rid of it unless you click?
3. The whole idea promoting in the status bar?

**Comment by crewone** [comment]
The fact that I already paid. What more do you want from me?

Op di 30 nov. 2021 08:03 schreef avichay ***@***.***>:

**Comment by avichay77** [comment]
You are right
Pro users should not get such message. 

@crewone - would appreciate if your help us by contacting support@tabnine.com with your specific details so we can investigate what went wrong?
