### ISSUE TITLE
How disable Tabnine in .scss?

### ISSUE THREAD

**Issue by kprodinfo** [codota/TabNine#346]
**Issue Details:**
How disable Tabnine in .scss? IDE: PhpStorm

**Comment by talcodota** [comment]
You can add a .Tabnineignore file in the root of your project and add *.scss into it.
Please refer to:
https://www.tabnine.com/faq#mercurial_repo

**Comment by talcodota** [comment]
Sorry, but we currently only support disabling Tabnine for certain files in vscode IDE.
Here is how you do it in vscode:
Go to vscode settings -> search 'tabnine' -> and in 'disable_file_regex' enter "[.]scss$"
This can also be done directly by editing the settings.json file.
