### ISSUE TITLE
Permanently get Warnings in Little Snitch Firewall 

### ISSUE THREAD

**Issue by kinglycodes** [codota/TabNine#347]
**please complete the following information:**	
 - OS version: Mac Big Sur 11.2.2
 - Editor: vscode 
 - Editor version: 1.53.2	
 - Programming language: [js, reactjs]	
 - TabNine extension version: v3.2.8
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
Code Helper Renderer : WD-TabNine is not signed and little snitch always shows up warning messages to allow the connection. I set it to permanently allow this url for the tabNine api, but little snitch determines the permanently allowed rule and starts again by showing up the warning dialog again, and again and again.
Without signing the wd tabNine it's frustrating to get this warnings every 5 - 10 minutes.

Little snitch v 5.1.1 (newest update)

Is there a fix for this problem?

**Comment by bilucodota** [comment]
HI @kinglycodes,

We're aware of the issue, and in the process of resolving it ASAP.

Thank you for understanding.

**Comment by mengdodo** [comment]
I have the same problem
