### ISSUE TITLE
TabNine is not using proxy

### ISSUE THREAD

**Issue by ZhiyuanChen** [codota/TabNine#348]
**please complete the following information:**	
 - OS version: Win10
 - Editor: (vscode, intelij)
 - Editor version: (1.54.0, 2021.1)
 - Programming language: python	
 - TabNine extension version: (3.2.8, 0.3.4)
 - Engine version (could be located within Tabnine Hub): 3.3.72-40

**Issue Details:**

There was an error contacting tabnine.com: error sending request for url (https://api.tabnine.com/api_key_info/v3): error trying to connect

TabNine is not using the system proxy

**Comment by bilucodota** [comment]
Hi @ZhiyuanChen any chance you try to set `https_proxy` env var?

**Comment by ZhiyuanChen** [comment]
> Hi @ZhiyuanChen any chance you try to set `https_proxy` env var?

............ Surprisingly it is working

**Comment by bilucodota** [comment]
Great!
