### ISSUE TITLE
A little bad work on TabNine

### ISSUE THREAD

**Issue by Gozya01** [codota/TabNine#349]
When I use the TabNine,it always completed with ⌬ .
Could someone tell me how to solve this bug?

**Comment by Gozya01** [comment]
I use the vscode .
OS:Windows 10

**Comment by boaz-codota** [comment]
Hey @Gozya01 we use that so you'd know that that completion originated in Tabnine.
Once you select that completion, you won't get the ⌬ symbol in your code.

**Comment by Gozya01** [comment]
Thanks for your answer.However,Whe I use tabnine,it will offer Autocomplete code，however in one piece ,sometimes it will offer duplicated two，After I pick this,it will  get ⌬ and the code.The examples are the follows.
![image](https://user-images.githubusercontent.com/76418912/109615386-d24fdb80-7b6e-11eb-87a6-583ae8fac0a8.png)
![image](https://user-images.githubusercontent.com/76418912/109615497-ec89b980-7b6e-11eb-98a0-16ead7621c06.png)
However，sometimes the code is only once.Then it will not get ⌬.
![image](https://user-images.githubusercontent.com/76418912/109615640-1fcc4880-7b6f-11eb-9c3b-8f6e06fe967b.png)

![image](https://user-images.githubusercontent.com/76418912/109615668-2ce93780-7b6f-11eb-86ea-09ff57f81b1e.png)
Could you understand me?How to solve it?Thanks.

**Comment by boaz-codota** [comment]
What IDE are you using? It looks like a bug in the IDE. Is it some form of hosted vscode compatible thing?

**Comment by Gozya01** [comment]
Probably it is.Before，I use it with no problem.Recently,I use it on two computers.It has this problem.Probably  the vscode is updated. And the bug happens.

**Comment by boaz-codota** [comment]
What is your exact setup? OS, IDE, version, tabnine version (pugin & engine, could be found in the Hub by clicking on the status bar)...

**Comment by Gozya01** [comment]
VSCodeUserSetup-x64-1.53.2
OS：Windows10
TabNine::version 3.3.82

**Comment by boaz-codota** [comment]
Could you please also add the plugin list?
Run `code --list-extensions`

**Comment by Gozya01** [comment]
2gua.rainbow-brackets
akamud.vscode-theme-onedark
azemoh.one-monokai
CodeInChinese.ChineseInputAssistant     
danielpinto8zz6.c-cpp-compile-run       
eamodio.gitlens
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons    
fisheva.eva-theme
formulahendry.code-runner
jeff-hykin.polacode-2019
LeetCode.vscode-leetcode
mqycn.huile8
MS-CEINTL.vscode-language-pack-zh-hans
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode.cpptools
PKief.material-icon-theme
pnp.polacode
shd101wyy.markdown-preview-enhanced
skacekachna.win-opacity
streetsidesoftware.code-spell-checker
TabNine.tabnine-vscode
teabyii.ayu
tht13.python
Xen.vscode-theme-cenhanced
zhuangtongfa.material-theme

**Comment by Gozya01** [comment]
Thanks for your help.I have found the problem and the solution.There is a plugin that is not compatible——CodeInChinese.ChineseInputAssistant.I'm so sorry for wasting your time.
