### ISSUE TITLE
Cloud Model enabled on Intel, not on Apple M1

### ISSUE THREAD

**Issue by dimitre** [codota/TabNine#351]
**please complete the following information:**	
 - OS version: macOS 11.2.2
 - Editor: VSCode 	
 - Editor version:	Version: 1.54.1 and Version: 1.54.0-insider
 - Programming language: c++
 - TabNine extension version: 3.2.8
 - Engine version (could be located within Tabnine Hub): 3.3.82-40

I've just noticed I can enable Cloud Model on an Intel computer, but not on Apple M1, 
testing both the latest VSCode released today and the Insiders version latest too.
Thank you

**Comment by Merovex** [comment]
I think I have the same issue.

**Comment by bilucodota** [comment]
Hi @dimitre @Merovex 
Are you guys using VSCode build for Apple Silicon?
(Screenshot taken from VSCode download page)

![image](https://user-images.githubusercontent.com/70566578/110240816-5b438a00-7f56-11eb-8067-9c5d29be7967.png)

**Comment by dimitre** [comment]
yes I'm using both Visual Studio Code - Insiders and Visual Studio Code for apple silicon
confirmed in finder and in about 
OS: Darwin arm64 20.3.0

**Comment by bilucodota** [comment]
@dimitre please send us the content of `/Users/Your-User/Library/Preferences/TabNine/tabnine_config.json` to support@tabnine.com

**Comment by dimitre** [comment]
@bilucodota can I just drop it here?
```
{
  "version": "3.3.57",
  "hide_promotional_message": false,
  "beta_enabled": "Yes",
  "ignore_all_lsp": false,
  "creation_time": "2021-02-22T17:46:45.346191Z",
  "guuid": "16a6e8351467346dfa63b14a66100c3abe74e6856bf498d53c64147eb2c85b5d",
  "semantic_status": {},
  "enable_telemetry": false,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 2,
  "multiline_suggestions": false,
  "api_key": "renhdfbioqicyhpdkknnwfgdlhddxm",
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 40,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null,
  "last_service_level": "Cloud"
}

```

**Comment by bilucodota** [comment]
Got it. Check your inbox.
