### ISSUE TITLE
Pro API Keep Switching to Free across Machines

### ISSUE THREAD

**Issue by c13y** [codota/TabNine#352]
- OS version: Linux and Mac
 - Editor: VSCode, Intellij, etc
 - Editor version:	
 - Programming language: Any
 - Engine version (could be located within Tabnine Hub): 3.3.82-40

Just purchased. I work on Linux and Mac OS. 

- Activated on Linux, set to Pro version
- Activated on Mac, set to Pro version
- Went back to Linux, now set to Free version with API key locked into the hub. 

Was looking forward to using the product, but if I can't use it across my dev machines, I will want a refund.

**Comment by bilucodota** [comment]
Closing this, as we discussed in detail via email.

**Comment by c13y** [comment]
The developer in me feels obligated to say that even though the issue has been closed for me, that it may still be an issue with how you register paid accounts for developers on multiple platforms :-)
