### ISSUE TITLE
failed: Cannot read property 'Light' of undefined on gitpods

### ISSUE THREAD

**Issue by gengjiawen** [codota/TabNine#353]
**please complete the following information:**	
Gitpods is popular cloud IDE based on theia. `Tabnine works good generally`.
But I can't config it.

Sample project: https://github.com/gengjiawen/monkey-rust

![image](https://user-images.githubusercontent.com/3759816/104888405-abb35800-59a7-11eb-875f-ee1c1c594984.png)

**Issue Details:**

Tabnine can't start correctly
![image](https://user-images.githubusercontent.com/3759816/110402247-07e84d80-80b6-11eb-9747-0e7d329cf3b4.png)

**Comment by bilucodota** [comment]
Hi @gengjiawen 
This is a known issue. Checkout gitpod team response [here](https://github.com/gitpod-io/gitpod/issues/3249).
