### ISSUE TITLE
Establishing connection to TabNine Cloud...

### ISSUE THREAD

**Issue by ckhatton** [codota/TabNine#355]
**please complete the following information:**	
 - OS version: Mac Big Sur 11.2.3
 - Editor: Atom
 - Editor version: 1.55.0
 - Programming language: vue
 - TabNine extension version: 3.0.2
 - Engine version (could be located within Tabnine Hub): 3.3.96-29

**Issue Details:**
I have signed up to TabNine Cloud, enabled it, and all I get in the editor suggestions is "Establishing connection to TabNine Cloud..."

I checked if it was my router blocking the connection, but it's not.

Do you know what is causing it not to connect?

:octocat:

**Comment by shaiahr** [comment]
Hi
Are you working from behind a proxy?

**Comment by shaiahr** [comment]
I think we will need some logs. Can you please contact our support at: support@tabnine.com

**Comment by ckhatton** [comment]
Even though I didn't get any response/feedback from support@tabnine.com, the issue resolved itself since the new updates to TabNine :octocat:
