### ISSUE TITLE
Stop suggestions for Tailwind CSS classes

### ISSUE THREAD

**Issue by junaidanjum** [codota/TabNine#356]
**System Information:**	
 - OS version: Windows	
 - Editor: VS Code
 - Editor version:	
 - Programming language: JS	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
TabNine overwrites Tailwind CSS suggestions (Extension installed) for classes. Until TabNine understands it completely, it should not suggest any classes if Tailwind is installed. I have to delete the element and rewrite it to hope that this time, Tailwind comes ahead of TabNine.  
![Screenshot 2021-03-19 143320](https://user-images.githubusercontent.com/52190067/111756346-1c032a80-88c0-11eb-9549-7202287a28eb.jpg)

**Comment by shaiahr** [comment]
Hi
By 'overwrites' do you mean that Tabnine suggestions appear above Tailwind (i.e. Tailwind suggestions are down the list) or that Tabnine suggestions appear instead of Tailwind suggestions (i.e. Tailwind suggestions don't appear at all when Tabnine is running)?

**Comment by junaidanjum** [comment]
Hi @shaiahr,

It does not follow a particular pattern. Most of the times, Tailwind suggestions do not appear at all, while sometimes, they precede or succeed TabNine suggestions.

**Comment by shaiahr** [comment]
Currently, there's no option for the user to define where Tabnine suggestions should appear. We always try to place them first but sometimes the IDE might change that.
In no situation, do we try to hide or remove other, non Tabnine,  suggestions.
Are you able to reproduce some case where you see Tailwind suggestions when Tabnine is disabled and don't see them when it's enabled?
Can you post an example?

**Comment by junaidanjum** [comment]
The suggestions are really mixed. I am not able to detect a case where these follow a particular pattern. These precede or succeed over one another randomly.

**Comment by Kumirei** [comment]
I am having the same issue. With Tabnine enabled no Tailwind suggestions show up

**Comment by Andreas-Halemba** [comment]
Was here any solution found? I am willing to buy pro if tailwindcss autocomplete is working with tabnine.

**Comment by bell-software** [comment]
@Andreas-Halemba I don't think there has been any update from Tabnine or Tailwind regarding this.

**Comment by junaidanjum** [comment]
@Andreas-Halemba Sorry but no solution yet!
