### ISSUE TITLE
Cloud Model: Enabled Local Model: **Initializing...**     tried removing the extensions folder 

### ISSUE THREAD

**Issue by DmitriyMalayev** [codota/TabNine#357]
**please complete the following information:**	
 - OS version: Mac Catalina  Mac Meni M1
 - Editor: [VS Code]	
 - Editor version:	latest
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

DEEP COMPLETIONS
Model Strength:
Pro
Cloud Model: Enabled
Local Model: **Initializing...**     tried removing the extensions folder 

INSTALLATION
IDE:
vscode
Plugin Version:
3.2.13
Engine Version:
3.3.96-32

**Comment by shaiahr** [comment]
Hi @DmitriyMalayev 
Thanks for reporting this. A PR with a fix is ready and will be released with the next engine version.
