### ISSUE TITLE
I get "Click here for better completions using our stronger model!" warning in VSCode (but I am on a Pro plan)

### ISSUE THREAD

**Issue by corysimmons** [codota/TabNine#359]
**please complete the following information:**	
 - OS version: Mac Big Sur
 - Editor: vscode
 - Editor version: 1.54.3
 - Programming language: ts
 - TabNine extension version: 3.2.13
 - Engine version (could be located within Tabnine Hub): 3.3.98-40

**Issue Details:**

![image](https://user-images.githubusercontent.com/224636/112375984-49821680-8cba-11eb-8b42-9aa6c88fbb2f.png)

![image](https://user-images.githubusercontent.com/224636/112376028-56066f00-8cba-11eb-9080-86348c019cee.png)

What am I doing wrong? I am using Cloud instead of Local.

**Comment by shaiahr** [comment]
Hi @corysimmons 
This is a bug. You shouldn't see these messages since, as a pro user, you are already using the stronger model.
Thanks for reporting this. It will be fixed in the upcoming version.

**Comment by corysimmons** [comment]
Thanks for the quick response! It is kind of distracting so I'm excited for the next version. Have a nice day! :)
