### ISSUE TITLE
VSCode DevContainer

### ISSUE THREAD

**Issue by StummeJ** [codota/TabNine#360]
**please complete the following information:**	
 - OS version: macOS Big Sur
 - Editor: vscode
 - Editor version: 1.54.3
 - Programming language: All
 - TabNine extension version: v3.2.13
 - Engine version (could be located within Tabnine Hub): Unknown

**Issue Details:**
I am currently trying to get tabnine to work in a vscode dev container.  I am unable to open the settings and having multiple windows open, port 5555 on the local machine is already used by the native tabnine server.  VS Code will forward the port to 5556, but the following errors are produced
![image](https://user-images.githubusercontent.com/3059647/112398889-54d94000-8cc2-11eb-853c-e196d1d3e238.png)

**Comment by bilucodota** [comment]
Hi @StummeJ 
Apologies for the late response.
Just to make sure I understand your question - 
Is port 5556 being forwarded to port 5555 on the remote machine?

**Comment by StummeJ** [comment]
Container is 5555, host machine is 5556

**Comment by bilucodota** [comment]
So host:5556 is forwarded to remote:5555?

**Comment by StummeJ** [comment]
So I guess it's best to say in the docker container it's 5555, but when it's forwarded to the host it's on 5556 since another native instance of tabnine is running on 5555

**Comment by dopecoder** [comment]
Im having the same issue.

**Comment by anoop-rehman** [comment]
I'm having the exact same issue too

**Comment by Shellbye** [comment]
same issue

**Comment by Auggiezhu** [comment]
you can install version 3.2.8 TabNine extension in devcontainer
![20221020010833](https://user-images.githubusercontent.com/112937174/196758856-01d427d5-07a7-4f00-8efd-883f02580506.png)

**Comment by anoop-rehman** [comment]
> you can install version 3.2.8 TabNine extension in devcontainer ![20221020010833](https://user-images.githubusercontent.com/112937174/196758856-01d427d5-07a7-4f00-8efd-883f02580506.png)

Yupp now it seems to work for me too! Thanks for adding this functionality TabNine team :D

**Comment by raedwa01** [comment]
Not working for me.

**Comment by thalesfsp** [comment]
Since Jun 23, still not working.

**Comment by appcoders** [comment]
Please support aarch64 linux for working in devcontainers. There are many devs with Apple M1/M2 which cannot use Tabnine because of missing support.

**Comment by imran-charania-alida** [comment]
Same here cannot use within devcontainer

**Comment by appcoders** [comment]
@ksylvan Thanks for your great work. I'm still hoping for a native ARM build soon.

**Comment by phil-zd** [comment]
same issue

**Comment by appcoders** [comment]
Not stale.

**Comment by appcoders** [comment]
@amirbilu AArch64 by Ampere Altra is mainstream on hosting providers. Apple AArch64 in VSCode devcontainers or Linux VMs. It's been nearly F O U R years now... still, do not understand why aarch64 is not on the roadmap yet?

**Comment by jaques-sam** [comment]
Same here, I can't get it working. Planning to stop my subscription if this keeps happening (already weeks without being able to login! Give my money back...).

**Comment by thalesfsp** [comment]
Forget TabNine. Copilot much better.

**Comment by appcoders** [comment]
Not Stale. Fix this please.

**Comment by appcoders** [comment]
Not Stale. Fix this please.

**Comment by amirbilu** [comment]
Hi @appcoders you may use CTRL+SHIFT+P  `Tabnine: sign in using auth token` now

**Comment by jaques-sam** [comment]
Needs to be fixed!!On 18 Nov 2023, at 12:53, Amir Bilu ***@***.***> wrote:﻿
Hi @appcoders you may use CTRL+SHIFT+P  Tabnine: sign in using auth token now

**Comment by amirbilu** [comment]
@jaques-sam did manage to sign in using auth token?

**Comment by jaques-sam** [comment]
It seems so but no reply is sent back to the container.This works perfectly on Linux (fedora), but not on Windows…Op 18 nov. 2023 om 13:50 heeft Amir Bilu ***@***.***> het volgende geschreven:﻿
@jaques-sam did manage to sign in using auth token?

**Comment by appcoders** [comment]
Hi @amirbilu,
in devcontainer on MacOS sign in using auth token:

![CleanShot 2023-11-20 at 09 02 38@2x](https://github.com/codota/TabNine/assets/4519870/95dac668-16d6-4466-ba8e-20ed6bd38209)

Status:

![CleanShot 2023-11-20 at 09 07 59@2x](https://github.com/codota/TabNine/assets/4519870/13778956-fa99-4196-bdc0-fe5a8a781f82)

**Comment by appcoders** [comment]
Version: 
![CleanShot 2023-11-20 at 09 11 06@2x](https://github.com/codota/TabNine/assets/4519870/f9ecf825-f240-42eb-807f-d7d1b98a74b2)

**Comment by amirbilu** [comment]
Hi @appcoders unfortunately devcontainer on m1 is not supported atm

**Comment by amirbilu** [comment]
> It seems so but no reply is sent back to the container.This works perfectly on Linux (fedora), but not on Windows…Op 18 nov. 2023 om 13:50 heeft Amir Bilu ***@***.***> het volgende geschreven:﻿ @jaques-sam did manage to sign in using auth token? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

We found a bug in the current version. A fix will be released soon.

**Comment by jaques-sam** [comment]
> Hi @appcoders unfortunately devcontainer on m1 is not supported atm

Btw, there is already an M1, so Apple Silicon is the right terminology I guess ;-) nhf

**Comment by appcoders** [comment]
@amirbilu Thanks - but this moment already lasts about 2 years. Apple Silicon is in its 3rd iteration now. So my understanding of this is limited.

**Comment by radanskoric** [comment]
Not stale!

Still a problem, version 3.69.0 :

<img width="273" alt="Screenshot 2024-02-14 at 10 32 37" src="https://github.com/codota/TabNine/assets/1065097/10d07967-6f98-4d36-bf18-9460258dea11">

**Comment by appcoders** [comment]
@radanskoric  No one at TabNine is interested in fixing this obviously... this ticket is open for nearly 3 years now...

**Comment by radanskoric** [comment]
> @radanskoric No one at TabNine is interested in fixing this obviously... this ticket is open for nearly 3 years now...

@appcoders, unfortunately, I noticed. Quite depressing. This might actually be the thing that gets me to buy a Copilot subscription instead. Working inside a container is more important for my dev workflow than using Tab9 specifically.
