### ISSUE TITLE
VScode Extension Name

### ISSUE THREAD

**Issue by asubramanian08** [codota/TabNine#363]
I am using VScode and the name of the tabnine extention is 
> Tabnine Autocomplete AI: JavaScript, Python, TypeScript, PHP, Go, Java, Ruby, C/C++, HTML/CSS, C#, Rust, SQL, Bash, Kotlin, React

This is way too long and I think it can be condensed to Tabnine Autocomplete AI. The languages that you have can be listed in the description.

**Comment by Eransho** [comment]
Thanks for the feedback.
We found it makes it easier to find the extension in the search
