### ISSUE TITLE
Enhancement Request: I need support for multiple GitHub accounts integrated into my Tabnine local instance ;;;; most probably I will be able to buy any, including maximum pricetags, plans of Tabnine if it proves to be COOL FOR A CAPITALIST DEVELOPER =)

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [codota/TabNine#366]
**please complete the following information:**	
 - OS version: ALL
 - Editor: ALL
 - Editor version: ALL
 - Programming language: ALL
 - TabNine extension version: It's Your business
 - Engine version (could be located within Tabnine Hub): It's Your business

**Issue Details:**
See the Issue Headline

Let's cooperate and collaborate =)

**Comment by boaz-codota** [comment]
Why would you need this? You can use the same account for multiple projects...
