### ISSUE TITLE
Support for semantic completion with Microsoft Python Language Server

### ISSUE THREAD

**Issue by tsoernes** [codota/TabNine#367]
Is it possible to use this LSP backend https://github.com/microsoft/python-language-server
instead of Palantirs?

**Comment by boaz-codota** [comment]
Hey @tsoernes ,

Yes it is- see the instructions under https://www.tabnine.com/semantic

Do note that if you are using VSCode or Jetbrains' products you *do not* need to enable semantic completions and they make zero difference in the suggestions you get from Tabnine.

**Comment by tsoernes** [comment]
Does this look reasonable?

```
[language.python]
command =
"/home/torstein/doom-emacs/.local/etc/lsp/mspyls/Microsoft.Python.LanguageServer"
```

**Comment by boaz-codota** [comment]
I think so, not sure about how to run the Microsoft python language server.

**Comment by tsoernes** [comment]
How to check if  its working?
