### ISSUE TITLE
TabNine should NOT complete upon hitting enter

### ISSUE THREAD

**Issue by taraskuzyk** [codota/TabNine#369]
**please complete the following information:**	
 - OS version: MacOS Big Sur 11.1
 - Editor: PyCharm
 - Editor version: 2020.2.2
 - Programming language: Python
 - TabNine extension version: 0.3.4
 - Engine version (could be located within Tabnine Hub):  3.3.101-40

**Issue Details:**

There should either be an option to NOT complete upon hitting enter, or that should be disabled entirely. I only want to complete things with Tab. When I get to the end of the line and there's a completion suggestion, when I want to go to the next line and hit Enter, I instead get the proper string replaced with a suggestion, stuck at the same line.

Before hitting Enter:

![Screen Shot 2021-03-31 at 11 40 07 AM](https://user-images.githubusercontent.com/46264158/113187235-d9bddf80-9215-11eb-89fc-8584941bb13c.png)

After hitting Enter:

![Screen Shot 2021-03-31 at 11 40 29 AM](https://user-images.githubusercontent.com/46264158/113187281-e6dace80-9215-11eb-970a-f52a0def11e9.png)

Adding an option to disable this sounds like an optimal solution. Thanks!

**Comment by boaz-codota** [comment]
Hey,

This has got nothing to do with Tabnine. You can configure which key apply a suggestion in Jetbrains products: https://www.jetbrains.com/help/idea/configuring-keyboard-and-mouse-shortcuts.html

Thanks
