### ISSUE TITLE
Reason support for .re files

### ISSUE THREAD

**Issue by chenglou** [codota/TabNine#37]
Hi! I'm a maintainer of Reason. Currently, tabnine seems to use ocaml-language-server. For Reason, we now have a new language server more suited to it [here](https://github.com/jaredly/reason-language-server).

cc @jaredly

Thanks!

**Comment by albertorestifo** [comment]
A problem that I see is that there is no platform-independent way to install the language server and currently, every language server which comes pre-configured, is automatically installed on first use.

**Comment by jaredly** [comment]
@albertorestifo the reason-vscode plugin bundles binaries for osx, windows, and linux, for what it's worth

**Comment by zxqfl** [comment]
Can you provide an `install` command like the one for ocaml-language-server? https://github.com/zxqfl/TabNine/blob/35d6416c25a7708447db4218afe03e82d39ab74e/TabNine.toml#L26

**Comment by jaredly** [comment]
does it have to be a global installation?
