### ISSUE TITLE
Tabnine appears on top of documentation

### ISSUE THREAD

**Issue by exapsy** [codota/TabNine#370]
- OS version: Linux Manjaro 5.10.2-2
- Editor: vscode
- Editor version: 1.55.0
- Programming language: any
- TabNine extension version: 3.2.16

**Issue Details:**

No keybindings were introduced.

To reproduce this you just simply enter the "parentheses" which trigger the documentation panel but also triggers tabnine at the same time exactly on top of the documentation window.

![image](https://user-images.githubusercontent.com/9019120/113414779-745d2080-93c6-11eb-8f41-7615fa758dd9.png)

I found no way to avoid this.

**Comment by boaz-codota** [comment]
Clicking escape doesn't close the suggestions panel?

**Comment by boaz-codota** [comment]
The bottom line this is vscode's behaviour, you might want to raise that issue in their repository

**Comment by exapsy** [comment]
> Clicking escape doesn't close the suggestions panel?

It does, but this solution is troubling when you use `Vim` as an extension, as it uses Escape for other reason. I guess this is "my issue" but this behavior shouldn't happen imo to begin with.

> The bottom line this is vscode's behaviour, you might want to raise that issue in their repository

Yeah, from the way I see it now I think I agree. I guess the issue is that the documentation should always appear bellow not under the intellisense dialog. Do you agree that would be the most appropriate solution?

Ill post it there then, I'll close this issue I guess unless you think we can fix this somehow with tabnine. I'm not really fluent with VSCode's plugin open library.
