### ISSUE TITLE
tabnine responsive performance issue

### ISSUE THREAD

**Issue by Shams-Raju** [codota/TabNine#371]
- OS version: Win 10
 - Editor: vscode
 - Editor version: 1.55.0
 - TabNine extension version: 3.2.16
 - Engine version (could be located within Tabnine Hub): 

When I'm open vscode editor there showing tabnine extension initializing. When I follow vscode inside bell icon then there showing 1 issue and this is tabnine performance issue. Moreover some days ago when I am open vscode there showing tabnine logo in vscode panel but right now there not showing tabnine logo. 

Please quickly fix tabnine performance issue...

**Comment by boaz-codota** [comment]
This seems like a duplicate (same cause) as https://github.com/codota/TabNine/issues/372

Please follow the instructions there and report back if that didn't work. Thanks.

**Comment by boaz-codota** [comment]
Lets follow up here @Shams-Raju .

Please provide some screenshots that further explains the problem, as well as the engine version (write `tabnine::config` anywhere in your code to open Tabnine Hub, and scroll down).

**Comment by Shams-Raju** [comment]
> Lets follow up here @Shams-Raju .
> 
> Please provide some screenshots that further explains the problem, as well as the engine version (write `tabnine::config` anywhere in your code to open Tabnine Hub, and scroll down).

![Screenshot_86](https://user-images.githubusercontent.com/63977867/113503364-33464700-9553-11eb-8700-be6691b87008.png)

see

**Comment by boaz-codota** [comment]
Yep I see, are you getting any suggestions from Tabnine?

**Comment by Shams-Raju** [comment]
> Yep I see, are you getting any suggestions from Tabnine?

No man. :(
I included this problem but no response. :)

**Comment by boaz-codota** [comment]
Are you sure you have Tabnine installed? Can you send me a picture (so I can validate that this is in fact the correct extension)?

If you did, please send us a screenshot of the extension logs (see https://stackoverflow.com/a/44196165/2420354). Thanks.

**Comment by Shams-Raju** [comment]
> Yep I see, are you getting any suggestions from Tabnine?

![Screenshot_86](https://user-images.githubusercontent.com/63977867/113503511-342ba880-9554-11eb-8d78-316829b32ae9.png)

When I opening vscode then showing this. It has never been shown before tabnine works perfectly.

**Comment by Shams-Raju** [comment]
> Yep I see, are you getting any suggestions from Tabnine?

![Screenshot_88](https://user-images.githubusercontent.com/63977867/113503573-88cf2380-9554-11eb-9df5-65dab5c5b867.png)

When I opening vscode then showing this. It has never been shown before tabnine works perfectly.

**Comment by Shams-Raju** [comment]
![Uploading Screenshot_89.png…]()

**Comment by Shams-Raju** [comment]
![Screenshot_89](https://user-images.githubusercontent.com/63977867/113503707-53770580-9555-11eb-9d8e-86205027dd43.png)

original.

**Comment by boaz-codota** [comment]
> > Yep I see, are you getting any suggestions from Tabnine?
> 
> ![Screenshot_88](https://user-images.githubusercontent.com/63977867/113503573-88cf2380-9554-11eb-9df5-65dab5c5b867.png)
> 
> When I opening vscode then showing this. It has never been shown before tabnine works perfectly.

Well is it working now?
