### ISSUE TITLE
Tabnine still "STARTING" (for hours)

### ISSUE THREAD

**Issue by filasik** [codota/TabNine#372]
- OS version: Win 10	
 - Editor: vscode-stable
 - Editor version: March 2021 (version 1.55)	
 - Programming language: js, php	
 - TabNine extension version: v3.2.16
 - Engine version (could be located within Tabnine Hub): cannot open

**Issue Details:**
I have a problem with tabnine for 2 days, it's only "starting" when I run VSCODE:
![image](https://user-images.githubusercontent.com/20371409/113502485-e780a700-952c-11eb-9292-6f674cc915cc.png)

But in Jetbrains PHP Storm it works fine. 

I made no changes, no settings, nothing. Only things I ussually do is to open VSCODE, there is update very often and then all my extensions load.

I tried to restart every app, disable enable extension, reinstall extension, restart PC - nothing work

- My coworker with macOS has the same issue

**Comment by boaz-codota** [comment]
We had an issue that could cause this in the engine version 3.3.103. It is possible that you are stuck in that version. 

Please remove tabnine & its folder under vscode (which is under `%USERPROFILE%\.vscode\extensions`) and reinstall.

Let me know if that didn't work for you.

**Comment by filasik** [comment]
> We had an issue that could cause this in the engine version 3.3.103. It is possible that you are stuck in that version.
> 
> Please remove tabnine & its folder under vscode (which is under `%USERPROFILE%\.vscode\extensions`) and reinstall.
> 
> Let me know if that didn't work for you.

I confirm, this works.
![image](https://user-images.githubusercontent.com/20371409/113502937-4f37f180-952f-11eb-8a44-9eec35987880.png)

Thanks :-)

**Comment by Shams-Raju** [comment]
> We had an issue that could cause this in the engine version 3.3.103. It is possible that you are stuck in that version.
> 
> Please remove tabnine & its folder under vscode (which is under `%USERPROFILE%\.vscode\extensions`) and reinstall.
> 
> Let me know if that didn't work for you.

Hey, I can't clear your solution. Please explain that. :( My vscode editor inside not showing tabnine logo and there create a responsive performance issue. How can I fix it?

**Comment by reedDESIGNgit** [comment]
Great
