### ISSUE TITLE
TabNine spikes to 100% CPU usage

### ISSUE THREAD

**Issue by koreno** [codota/TabNine#373]
- OS version: Ubuntu 16.04
 - Editor: Sublime Text
 - Editor version: 3.2.2.3211
 - Programming language: Python
 - TabNine extension version: 3.1.0
 - Engine version: 3.3.104-0

My fans start throttling up and I know it's TabNine. If I can make it to htop, I'll kill the tabnine process to regain control over my machine.
This seems to be correlated to switching branches.
This has been a recurring issue since forever - please provide a way to limit the number of CPUs tabnine can use!

**Comment by boaz-codota** [comment]
Is this a temporary raise or a constant one?

Tabnine indexes and build some models upon new project (or changing branches) which is high in CPU consumption. But if within few minutes it doesn't stop we have a self kill mechanism.

**Comment by koreno** [comment]
It seems temporary, but it makes the entire machine completely unusable (partially-frozen). I can't really afford to wait a few minutes.

**Comment by boaz-codota** [comment]
Can you please send some screenshots of the behaviour with your activity monitor (not sure what it is called in Linux) along with logs from tabnine (write `tabnine::logs` anywhere in your code to receive a path of the logs dump) to support@tabnine.com ?

**Comment by probablykasper** [comment]
I'm having this issue in VSCode. I have VSCode running in the background, and every now and then the fans will ramp up and I'll notice a TabNine process running at 100%.

**Comment by ofek** [comment]
I'm having the same problem in PyCharm and memory shoots up, triggering "run heap dump" recommendation.
