### ISSUE TITLE
TabNine downloading files from my OneDrive

### ISSUE THREAD

**Issue by pinholucas** [codota/TabNine#375]
- OS version: Win10	
 - Editor: VSCode
 - Editor version: 1.55
 - Programming language: js
 - TabNine extension version: 3.2.17
 - Engine version (could be located within Tabnine Hub): ?

20 minutes ago, TabNine started to download random files from my OneDrive without my authorization. 

![image](https://user-images.githubusercontent.com/5108881/113967010-84ca2c80-9806-11eb-81a0-3bbec0ff2371.png)
![image](https://user-images.githubusercontent.com/5108881/113967024-8a277700-9806-11eb-9a52-a6f9796becc0.png)

Excuse my French, but what the fuck is happening?!

**Comment by shaiahr** [comment]
Hi @pinholucas 
Thanks for reporting this to us. It is indeed a bug. The local model tries to learn your local project and it seems like it followed some external links to your one drive. 
These files were only downloaded to your machine, and used by the local model, so **at no time was any of this data externalized out of your machine**.
Still, this obviously should not happen and we will fix it asap.
Meanwhile, you can use a .Tabnineignore file to exclude these files or folders. See more information [here](https://www.tabnine.com/faq#mercurial_repo).
Does your project contain any symbolic links to onedrive?

Shai

**Comment by pinholucas** [comment]
No, no links to anything in OneDrive (It's a Next.JS project btw)... It's strange that it tried to read AutoCAD & txt files.
I think that it should be better to let the user choose what folders TabNine can access.

**Comment by shaiahr** [comment]
We're trying to keep things as simple as possible, so we don't want to force users to configure accessible folders.
Tabnine, by default, scans all folders up to the project root. It identifies that root based on version control settings (e.g. git).
Usually this is good enough, but when it's not, the user can configure what files and folders to exclude using ignore files.
Are you working on a git project (i.e. is there a .git folder at the root of your project)?

**Comment by pinholucas** [comment]
Yes, it's a git project.

**Comment by shaiahr** [comment]
That is strange. I'd like to ask for your tabnine logs files.
Can you please open a ticket with our support and we'll continue there?

**Comment by pinholucas** [comment]
Sorry for the delay, yes no problem. How can I do this?

**Comment by shaiahr** [comment]
Sorry, my bad for not posting the address. 
Please send an email to support@tabnine.com
Mention this issue in the email so we'll know how to refer to it.

**Comment by PlayerYao** [comment]
I also encountered a bug today where tabnine automatically downloads OneDrive files
I have the plugin installed on both my idea and vscode
idea opened a Java project (version control using git), but not in the OneDrive directory
vscode just opened a few temporary files
It was downloading files from OneDrive for about two hours, downloading a lot of my next cloud backup data (.php files)

**Comment by PlayerYao** [comment]
I encountered a bug today where tabnine automatically downloads OneDrive files
I have both idea and vscode with plugins installed
idea opened a Java project (version control using git), but the project path is not in the OneDrive directory
vscode just opens a few temporary files
It downloads files from OneDrive for about two hours and downloads a lot of my next cloud backup data (.php files)

**Comment by thrivingproject** [comment]
I was just working in VSCode when I got a windows notification that said Tabnine was downloading files from my OneDrive. It was able to download a few before I stopped it, and I'm not sure which files it downloaded, but I do have have personal files on my OneDrive that I do not want extensions to access. I also don't recall giving permission for this extension to access files in my OnDrive

**Comment by yahave** [comment]
@thrivingproject very interested in reproducing it. Does the project you're working on have a `.git` directory? 
Tabnine looks for the project root by climbing the directory structure, and this sounds like a bug that makes it climb too far.

**Comment by thrivingproject** [comment]
Hi, the project does not have a `.git` directory. The directory path is `/c/Users/thrivingproject/Documents/business` and my onedrive path is `/c/Users/thrivingproject/OneDrive`. But that doesn't really explain why it chooses to go into the `OneDrive` directory, as there are directories with `.git` subdirectories in `Documents` directory, so if it's looking for a `.git` directory it doesn't need to go all the way back to the `thrivingproject` directory.

**Comment by yahave** [comment]
Looking at the code, what seems to be happening is:
1.  Tabnine starts at `/c/Users/thrivingproject/Documents/business` and identifies that it is not a project root. It has no `.git` directory or other indications of project root (`Cargo.toml`,`.tabnine_root`, etc.)
2. Tabnine starts climbing the directory tree looking for said indications of a project root. There is a bug in the code that does the climbing, and it does not stop climbing until it finds "indications of project root" or reaches the top-level directory. 
3. Once it establishes the top-level directory as `thrivingproject` it tries to explore everything under it and see what it needs to take into account for inference. 

I'll take it to the team, but until we release a fix, can you please check if adding a `.tabnine_root` file under `/c/Users/thrivingproject/Documents/business` prevents Tabnine from climbing beyond that directory (and in particular to your OneDrive)?

@yonip23 @dimacodota

**Comment by hwndmaster** [comment]
@yahave It seems like the problem isn't only about the root folder, because in my case Tabnine was accessing files on a different drive, where I don't have any code. The problem still persists, and it is really annoying. Had to stop using Tabnine until further investigation.
