### ISSUE TITLE
It is not possible to click on Register and login using WSL2

### ISSUE THREAD

**Issue by alvaroico** [codota/TabNine#377]
**please complete the following information:**	
 - OS version: [Win 10 - WSL2 Ubuntu]	
 - Editor: [vscode,]	
 - Editor version:	
 ![image](https://user-images.githubusercontent.com/59286021/114117191-822a0e80-98bc-11eb-9526-a6cfda68e0a2.png)
 - Programming language: [All]	
 - TabNine extension version: 3.2.17
 
![image](https://user-images.githubusercontent.com/59286021/114117234-a0900a00-98bc-11eb-86fc-6614d5dc9c18.png)

 - Engine version (could be located within Tabnine Hub):  3.3.104-40

**Issue Details:**
**It is not possible to click on Register and login using WSL2 not generating the link to open in the browser**

![TabNine](https://user-images.githubusercontent.com/59286021/114117561-59564900-98bd-11eb-9cce-c2f5ab08a50b.gif)

**Comment by maya-tabnine** [comment]
Hi can you send the log? open Tabnine extension settings and enter a path in ‘Tabnine: Log File Path’
Then restart the IDE and wait for the problem to happen

**Comment by Staninna** [comment]
Hi i wanted to share the problem is still present but however there is a work around i will post a youtube link soon

**Comment by Staninna** [comment]
@alvaroico @maya-tabnine 

a workaround i found in 5-10 minutes 

https://youtu.be/rRx98j4To0k

**Comment by Houbsi** [comment]
Hi there, 

i had the same issues. The workaround from @Staninna really worked without any issues! :)

**Comment by soodohcool** [comment]
> @alvaroico @maya-tabnine
> 
> a workaround i found in 5-10 minutes
> 
> https://youtu.be/rRx98j4To0k

Successfully used this workaround on Ubuntu 20 as well. Thank you @Staninna

**Comment by billzhuang** [comment]
> end the log? open Tabnine extension settings and enter a path in ‘Tabnine: Log File Path’
> Then restart the IDE and wait for the problem to happen

saved my life, thank you!

**Comment by owittek** [comment]
This issue still persists, had to use the workaround mentioned above.

**Comment by wdpza** [comment]
Ran into this issue now. Workaround helped, thanks!

**Comment by 767829413** [comment]
> Referen

Dude you are awesome!

**Comment by ngonngay** [comment]
> Staninna 
Thank you a lots

**Comment by crewone** [comment]
Jeez. Is it this hard to fix, tabnine? Workaround should not be nessecary.

**Comment by bjmageto** [comment]
Had this issue trying to log in to Tab9 on VS Code today. Also seeing a lot of GET request errors on port localhost:1123 that went away after following @Staninna guide (https://youtu.be/rRx98j4To0k) for pasting the link to login directly into browser from Dev Tools.

To summarize:
1. Navigate to Tab9 from VS Code (I'm using WSL - Ubuntu 23.04)
2. Test links (most likely broken if you are here)
3. Launch DevTools (Help > Toggle Developer Tools)
4. Navigate to Network tab
5. Filter by string "event"
6. Click on "Register / Login" in the Tab9 Hub
7. The most recent event should now have a "Request URL" that you can copy directly to a browser to take you to the locally hosted Tab9 server (http://127.0.0.1:1123/sec-gvsldpoznlbgfgxsrrsx/event in my case but yours will be different)
![image](https://github.com/codota/TabNine/assets/133256982/dce9c640-270b-45bc-b3e1-40ad37a2887c)
8. Login via the web GUI for the application
9. Code with Tab9 AI assistance! (bottom status bar no longer has "tabnine starter")

**Comment by Luifr** [comment]
Issue still persist on WSL2, workaround works

**Comment by yyflightwatcher** [comment]
i tried this but got response "invalid secret", is there anyone met the same question?
