### ISSUE TITLE
Constant CPU usage

### ISSUE THREAD

**Issue by exapsy** [codota/TabNine#378]
- OS version: Linux Manjaro 5.10.26-1
- Editor: vscode
- Editor version: 1.55.0
- Programming language: any
- TabNine extension version: 3.2.17

**Issue Details:**

I'm concerned, or curious is the right word, over Tabnine constantly using my machine's CPU, when I'm idle doing nothing. But if it's justified I guess its okay, I'm just checking to see if it's something that could be improved.

https://user-images.githubusercontent.com/9019120/114316106-c579bc80-9b0a-11eb-96b1-11416c422383.mp4

I'm curious over what's the loop here that is constantly going over this cycle. It's peaking at 1-20% CPU usage every 5 seconds and it goes back to low CPU usage.

**Comment by dimacodota** [comment]
@exapsy - are you getting any Tabnine suggestions?  
can you please send your tabnine_config.json file to [support@tabnine.com](mailto:support@tabnine.com)?
the file should be located at `$XDG_CONFIG_HOME` or `$HOME/.config`

**Comment by exapsy** [comment]
@dimacodota FYI Just sent the config file at the email. Feel free to ask me for any additional information if needed.
