### ISSUE TITLE
Nullish Operator of JavaScript

### ISSUE THREAD

**Issue by Cishenn** [codota/TabNine#379]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: vscode
 - Editor version: 1.55.1
 - Programming language: js	
 - TabNine extension version: 3.3.0
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
The Wrong Modification from Nullish Coalescing Operator **??** of JavaScript to **? ?**
![image](https://user-images.githubusercontent.com/45890023/114556996-d0b02200-9c9b-11eb-9bd5-470e3073b34a.png)

**Comment by dimacodota** [comment]
Hi @Cishenn  - are you sure you are using Tabnine? i do not see the Tabnine label in your status bar
<img width="1603" alt="Screen Shot 2021-04-13 at 16 22 18" src="https://user-images.githubusercontent.com/60742964/114559533-810a3000-9c74-11eb-934e-930b77a8a29c.png">
