### ISSUE TITLE
Disable with certain file extensions or specific files

### ISSUE THREAD

**Issue by broAhmed** [codota/TabNine#38]
I use my text editor for both editing code and taking notes in `.txt` files. I'd love a feature where TabNine suggestions could be turned off when editing certain file extensions e.g. `.txt` or in specific files, e.g. `notes.txt`.

P.S. Thank you for the amazing product. Bought it right away.

**Comment by zxqfl** [comment]
Thanks for the suggestion. What editor are you using?

**Comment by broAhmed** [comment]
Sublime Text 3.

**Comment by qufanqi** [comment]
I'm curious if this feature is still under development? I need this too
