### ISSUE TITLE
cannot unsubscrible

### ISSUE THREAD

**Issue by qx** [codota/TabNine#382]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**  cannot unsubscrible, email not replay,login with github

**Comment by dimacodota** [comment]
handled via support@tabnine
