### ISSUE TITLE
Can not download local Model

### ISSUE THREAD

**Issue by woyin** [codota/TabNine#385]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 Windows 10 20H2
 - Editor: [e.g. vscode, intelij, sublime]
 VSCode	
 - Editor version:
 1.55.2	
 - Programming language: [e.g. js, ts, c++]
 All	
 - TabNine extension version:
 3.4.3
 - Engine version (could be located within Tabnine Hub): 
3.3.108-32
**Issue Details:**
``
There seems to be an issue downloading the deep model:
error sending request for url (https://api.tabnine.com/model_metadata/v1): error trying to connect: unexpected EOF during handshake
If you fail to fix the error above, contact support at support@tabnine.com.
``

When I visited the URL( https://api.tabnine.com/model_metadata/v1 ), I got a 404 error.

**Comment by dimacodota** [comment]
@woyin, are you running behind a proxy server? if  yes, please set the  `http_proxy` and `https_proxy` environment variables.

**Comment by woyin** [comment]
Solved.
It was caused by the proxy. When I close the proxy, everything ran well.
