### ISSUE TITLE
WSL2 Issue with TabNine::config

### ISSUE THREAD

**Issue by Peredery** [codota/TabNine#386]
**please complete the following information:**	
 - OS version: Win10
 - Editor: vscode remote under WSL2 (ubuntu 20.10)
 - Editor version: 1.55.2
 - Programming language: Ruby
 - TabNine extension version: 3.4.3
 - Engine version: -

TabNine::config page always be blank when I try to open it from Vscode in wsl2 ubuntu 20.10

**Comment by Peredery** [comment]
Suggestions work fine, but cannot open TabNine Hub 
![image](https://user-images.githubusercontent.com/41237931/115552395-f7321680-a2b4-11eb-9b89-663074d53cf1.png)

**Comment by dimacodota** [comment]
@Peredery, can you please forward port 5555 as explained [here](https://www.tabnine.com/faq#could_not_start_browser)?

**Comment by Peredery** [comment]
> @Peredery, can you please forward port 5555 as explained [here](https://www.tabnine.com/faq#could_not_start_browser)?

It's possible for vscode remote ssh, but not for WSL. Doesn't have an option for port forwarding or I don't know how to do it for Remote WSL. Usual remote ssh have PORT TAB in Vscode, but WSL plugin doesn't have it

![image](https://user-images.githubusercontent.com/41237931/115591576-e85e5a80-a2da-11eb-97ed-1c7786816e7d.png)

**Comment by Peredery** [comment]
I think TabNine should tell Vscode which port to open

![image](https://user-images.githubusercontent.com/41237931/115591838-3bd0a880-a2db-11eb-95ea-fba4034dd370.png)

**Comment by vedantmgoyal2009** [comment]
TabNine has issues with remote coding... The same issue has also been seen in GitHub Codespaces.
I contacted TabNine support and they have prioritized my request. Waiting for a fix to be rolled out soon.

**Comment by KbyteTutu** [comment]
> TabNine hub opens for me, settings can be changed, but Sign Up/Sign In buttons do nothing. Thus I can only use local model. In SSH sessions, everything works well.

I have the same issue, but i got a solution...
just call the setting page of tabnine, then press middle button( the mouse wheel) on "sign in" link, thus the page will open in your default browser. Every function works here.

**Comment by darkjedeye** [comment]
> > TabNine hub opens for me, settings can be changed, but Sign Up/Sign In buttons do nothing. Thus I can only use local model. In SSH sessions, everything works well.
> 
> I have the same issue, but i got a solution... just call the setting page of tabnine, then press middle button( the mouse wheel) on "sign in" link, thus the page will open in your default browser. Every function works here.

you are a life saver mate...... works 100%

**Comment by phuctoan197** [comment]
Has anyone had a solution to this problem?
