### ISSUE TITLE
How to avoid the recommended Suggestions ?

### ISSUE THREAD

**Issue by UdayKiranPadhy** [codota/TabNine#389]
**please complete the following information:**	
 - OS version: Windows 10 
 - Editor: Visual Studio Code
 - Editor version: Latest
 - Programming language: Python	
 - TabNine extension version: Recentely Installed Expecting the latest one
 - Engine version (could be located within Tabnine Hub): Installed Recentely latest engine

**Issue Details:**
How can i avoid the recommended suggestions.
I have written what i have written and when i want to go to next line i press my down arrow button or enter button
But when i press any of those my written code gets replaced by Tab nine recommendatation. 
Even when i press space to get rid of the present recommendadtion still it doesnt leave me. 
How can i leave the suggestion in that cases ???

**Comment by dimacodota** [comment]
Hi @UdayKiranPadhy, can you please share a screen recording of the issue?

**Comment by UdayKiranPadhy** [comment]
https://user-images.githubusercontent.com/58071209/117097759-2acb7100-ad8a-11eb-91d7-786a855c21b0.mp4

**Comment by UdayKiranPadhy** [comment]
Some times i want to close the suggestations for one time like i showed in video . I try by pressing space bars to skip but it doesnt stop recommendations . Any key that can stop suggestation for one time ??

**Comment by UdayKiranPadhy** [comment]
Anyone there for my help ? Or i need to close this issue here ??

**Comment by UdayKiranPadhy** [comment]
Disgusting Experience from Tab Nine. No response. I know developers are busy but they are responsive to. I opened this issue 5 days ago and after giving appropriate response for the questions and required details , no response from your side . At least you could have told me "wait our team is working on it " or "No it is not possible in tab nine", I daily come here to github to check any response from your side . I even bookmarked this issue page for regular and easy access . Sorry for saying Tab Nine is a very good software I did liked it but all the goodness gets compensated with it customer service. Had a worst experience from here. Definitely I would share this issue with my friends and collegues .

**Comment by dimacodota** [comment]
Hi @UdayKiranPadhy, sorry for the late response, is there a limit to using the escape key? Are you using any extension  that blocks you from using the escape key?

**Comment by UdayKiranPadhy** [comment]
Ok thank you. Sorry I didn't know that escape key closes the suggestations , now I came to know that escape key closes the suggestations for once. I searched in tab nine how to close that for once but could not get that . Thanks this solved my issue.

**Comment by ThaiTran31** [comment]
@UdayKiranPadhy Have you solved this problem? Please show me how? thanks in advance!
