### ISSUE TITLE
TabNine sometimes autofils the word and prevents me deleting the letters of the word in edit mode

### ISSUE THREAD

**Issue by NikosEfthias** [codota/TabNine#39]
here in this gif when i try to write exists after exi tabnine just inserts `e` and wont let me delete it. this is really annoying also for some reason it inserted `o` after exist in the gif . 
Is there any way to disable autofil in tabnine and allow only to fill using <c-n> or <c-p> ?

![p](https://user-images.githubusercontent.com/9097437/49964006-eb8af400-ff32-11e8-8dc6-661201c0f0e9.gif)

**Comment by Shougo** [comment]
What is your environment?

**Comment by NikosEfthias** [comment]
osx and tmux @Shougo
