### ISSUE TITLE
Useless completion in Layout files

### ISSUE THREAD

**Issue by ernestp** [codota/TabNine#391]
- OS version: macOS Big Sur
 - Editor: Android Studio
 - Editor version:	4.2
 - Programming language: xml
 - TabNine extension version:  0.3.8
 - Engine version (could be located within Tabnine Hub): 3.4.2-18

Completion in Android layout code not make sense 99% of the time.
Mostly because it cuts out 'android:' prefix
Is there way to turn it off for layout files?

**Comment by yonip23** [comment]
Hi @ernestp,
Thanks for reaching out!
Allowing users to turn off Tabnine in certain files is not yet supported unfortunately, although it is planned in the near future - so stay tuned 😃 

Best regards,
Yoni
