### ISSUE TITLE
Tab completion counts not showing, and auto_complete from other sources

### ISSUE THREAD

**Issue by samuelvanderwaal** [codota/TabNine#393]
- OS version: PopOS 20.10
 - Editor: Sublime Text 3	
 - Editor version: 3.2.2, build 3211
 - Programming language: Rust
 - TabNine extension version: Unknown
 - Engine version (could be located within Tabnine Hub): 3.4.9-39

**Issue Details:**
An older version of TabNine (Engine 3.4.9-0, Plugin 3.1.0) has number of tab completions displayed (Tab+Tab, Tab+3, etc):

![Selection_557](https://user-images.githubusercontent.com/1684605/118030587-fae41680-b311-11eb-99b3-2344bb19ad48.png)

The current version (Engine 3.4.9-39, Unknown Plugin) does not and also includes auto-completes from sources other than TabNine. 

![~-Coding-timecard-src-cli-bin-main rs • (timecard) - Sublime Text_001](https://user-images.githubusercontent.com/1684605/118030857-4ac2dd80-b312-11eb-87a6-b6ff8ba0201f.png)

I've tried setting "auto_complete" to "false" in the Sublime User settings, but TabNine always overwrites it to "true" when you reopen Sublime:

![Selection_018](https://user-images.githubusercontent.com/1684605/118031108-a0978580-b312-11eb-9873-54d23574fb01.png)

**Comment by dimacodota** [comment]
Hey @samuelvanderwaal, you can disable the current "Native Auto Complete" behavior by setting the `native_auto_complete` Tabnine User setting to `false`

**Comment by samuelvanderwaal** [comment]
> Hey @samuelvanderwaal, you can disable the current "Native Auto Complete" behavior by setting the `native_auto_complete` Tabnine User setting to `false`

Thanks!  That appears to solve that issue. Do you know if there's any way to get the tab completion counts back? (Tab+Tab, Tab+2, etc.)

**Comment by dimacodota** [comment]
> > Hey @samuelvanderwaal, you can disable the current "Native Auto Complete" behavior by setting the `native_auto_complete` Tabnine User setting to `false`
> 
> Thanks! That appears to solve that issue. Do you know if there's any way to get the tab completion counts back? (Tab+Tab, Tab+2, etc.)

unfortunately no, this functionally is not yet supported in the "native auto complete" mode.

**Comment by samuelvanderwaal** [comment]
> > > Hey @samuelvanderwaal, you can disable the current "Native Auto Complete" behavior by setting the `native_auto_complete` Tabnine User setting to `false`
> > 
> > 
> > Thanks! That appears to solve that issue. Do you know if there's any way to get the tab completion counts back? (Tab+Tab, Tab+2, etc.)
> 
> unfortunately no, this functionally is not yet supported in the "native auto complete" mode.

I don't really understand what is "native auto complete" mode and if I have it set to false why the tab completion counts are gone. Is there someway to roll back to the older version of the engine that supports the tab completion counts?

**Comment by samuelvanderwaal** [comment]
Even after setting 

```
{
 "native_auto_complete": false
}
```
 
 in TabNine User settings, I'm still getting odd auto-completion settings:
 
![Selection_019](https://user-images.githubusercontent.com/1684605/118045390-4ef7f680-b324-11eb-80e7-2ae5d402975c.png)

and having to arrow key down to them is really cumbersome.

**Comment by dimacodota** [comment]
Sorry it wasn't clear enough - 
 - the "native auto complete" is a better integration with Sublimes built into the auto-complete mechanism (which means it will cooperate with other auto-complete extensions) but still does not support the multi tab completion feature (tab counter) in this mode.
 - the "old" mode of Tabnine is completely overriding Sublime's auto-complete dialog( witch mean you will get only Tabnine suggestions)
 
in order to disable the new mode:
 - set the `native_auto_complete` in Tabnine User settings to `false`
 - open the Tabnine Configuration (command palette ->  `⌬ tabnine: Open Configuration`)
 - copy the `Config file path` at the bottom of the page
 - open the  the tabnine_config.json file for editing and change the `generation` field to 39

**Comment by samuelvanderwaal** [comment]
I have followed the steps listed above and still get non-TabNine autocomplete suggestions:

![Selection_044](https://user-images.githubusercontent.com/1684605/120369977-807b3680-c2c0-11eb-8e3f-0581ef863d21.png)

**Comment by lithiumjs** [comment]
Set the `generation` field to 34 instead.

**Comment by samuelvanderwaal** [comment]
> Set the `generation` field to 34 instead.

That is the magic number, apparently. I'm back to having only TabNine as suggestions and I even get my tab completion counts back! THANK YOU!
