### ISSUE TITLE
How to close other language suggestion eg. css、python

### ISSUE THREAD

**Issue by xlzy520** [codota/TabNine#394]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#977

**Comment by Tabnineteam** [comment]
We are working on creating such a feature that will allow you to choose when Tabnine completions are on. Stay tuned!
<br><p><em><small>°°°</small></em></p>
