### ISSUE TITLE
Support for C#/F# dotnet conventions as TabNine consistently proposes the wrong options

### ISSUE THREAD

**Issue by thomasd3** [codota/TabNine#395]
In my experience, TabNine slows down development with C#/F# by proposing auto-completion choices that come straight out of the JS/Python world and will not exist in the dotnet languages if one follows the casing conventions.

Here is a F# example:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/14313218/118306506-d6429700-b4e9-11eb-8d33-50c125b5d4b6.png">

TabNine proposes: "cancelAllOrders" as a method name for an auto complete suggestion.

The standard convention for C#/F# is to have method names with PascalCasing, but TabNine systematically proposes options in camelCasing.

I do understand that TabNine originates from languages with different conventions, but we're talking about casing here and the IDE already knows if the completion list is for a method or not for example. Therefore I assume that it wouldn't be too challenging to adapt the suggestions to match the language being used.

This is just one example, but the issue with the dotnet languages is constant across the board.

gz#880

**Comment by Eransho** [comment]
Hi @thomasd3, thanks for reporting.
I'm adding it to our backlog, we need to have a look on that

**Comment by thomasd3** [comment]
> Any news on this? I'm having the same issue preventing me from subscribing to the pro version.

In the meantime, I stopped using TabNine as it didn't make sense. But I would really love this simple thing to be implemented.

**Comment by csShowingtime** [comment]
Yeah, I tried it on C#, leaves a lot to be desired. The default VS and Jetbrains intellisense is often way more accurate than TabNine. Maybe its better on other languages

**Comment by Alexei000** [comment]
I have also noticed this behavior while working with TabNine in Visual Studio 2019.  The only workaround would be to start typing with a capital letter, but this is quite annoying since it is different from what I am used to (type without caps and get the correct autocompletion).

What is worse is that this happens while using Team Learning (I have a paid license) and I expect to get more relevant completions mostly based on the solution's code.

If I force myself to start with capital letters, completions seem to be better over time, so I would really like to see this implemented. Any roadmap to see this implemented? 

Thanks.

**Comment by thomasd3** [comment]
Is this issue somewhere on the roadmap? or are C#/F# not considered a priority?

**Comment by byilmaz** [comment]
I have the same issues and it's not working well as their promoted languages. I am going to cancel my subscription too since they don't have any progress since 1.5 years.

**Comment by yonip23** [comment]
@byilmaz We're sorry to hear about your dissatisfaction with the product.
Can you please disable `local_indexing` and give it another try? We suspect that in your case, this local indexing is overshadowing the advanced completions - thus causing the overall experience to feel not as great as it could be.

Disabling `local_indexing`:
1. Open your config file - Its path is shown in the Hub -> Support -> General Info -> Config file path
2. Edit it - `"local_indexing": null,` -> `"local_indexing": false,`
3. Restart your IDE

Kind regards

**Comment by byilmaz** [comment]
@yonip23 I tried that but nothing changed. It gives suggestions but they are not accurate enough. It suggests something else which is not relevant with my code. I remove suggestions and correct it. I decided use to increase my speed but it makes me even slower.
