### ISSUE TITLE
command 'TabNine.statusBar' not found

### ISSUE THREAD

**Issue by lupin4** [codota/TabNine#399]
**please complete the following information:**	
 - OS version: Win 10	
 - Editor: vscode, 	
 - Editor version: 1.56.2
 - Programming language: c++	
 - TabNine extension version: ??????Have no idea
 - Engine version (could be located within Tabnine Hub): ???? Will not open

**Issue Details:**
I have had serious issues with tabnine since McAfee quarantined the extension. Sometimes Pro is not turning on. The AI  Suggestions have been gone for a month now and the Status bar can NEVER be opened. Really starting to feel like a waste of money. 2 months down with no use. 

gz#1295

**Comment by maya-tabnine** [comment]
Did you look at our FAQ? check it out here: [https://www.tabnine.com/faq#windows_tabnine_starting](url)

**Comment by maya-tabnine** [comment]
If your McAfee quarantined the extension, you need to exclude the { \extensions\tabnine.* } directory from the malware protection. Did you try to exclude the extension path? 
The path on Win10 should be C:\Users\<user>\.vscode\extensions\tabnine.tabnine-vscode-3.4.4\

**Comment by Stoom** [comment]
I've done this, but on windows 11 it still refuses to start.  It works fine in a debian dev container though.
