### ISSUE TITLE
Have TabNine delegate requests for a lanaguage server

### ISSUE THREAD

**Issue by idanarye** [codota/TabNine#40]
TabNine can launch a language server for semantic completion. But language servers do much more than mere completion - they provide linting, code navigation, documentation, code actions etc.

If I launch a language server I want access to all these things, and many LSP clients provide them, but if TabNine is the one launching the server I can only use it for completion - and nothing else.

Is it possible to have TabNine simply delegate messages from the client to the language server and from the language server to the client? If it gets completion requests/responses it does its magic, but everything else it should just let pass through. That way I can just set my LSP client to launch TabNine and get completion from TabNine+language server and everything else from the language server.

**Comment by zxqfl** [comment]
Why can't you use your LSP client and TabNine at the same time? i.e. run your language server and TabNine as separate processes that aren't aware of each other?

**Comment by idanarye** [comment]
Some language servers [which I won't mention here](https://github.com/eclipse/eclipse.jdt.ls) can get pretty heavy and quite intrusive. If my LSP client is going to run one instance of that server, and TabNine is going to run another instance to get semantic completions, that's two heavy servers that need to index the entire project. And if one said servers decide they need change the code (e.g. - add an `import` statement when you complete something that wasn't previously imported) cause ensures.

**Comment by zxqfl** [comment]
Makes sense. Seems related to https://github.com/zxqfl/tabnine-vscode/issues/13 -- might want to implement it by having TabNine connect to an existing language server

**Comment by idanarye** [comment]
Maybe if you add command line flags for TabNine to connect to the language server, that will override the ones set in the TOML configuration file, the LSP client will be able to set them to redirect TabNine to the language server it already runs?

**Comment by jc00ke** [comment]
> Makes sense. Seems related to [zxqfl/tabnine-vscode#13](https://github.com/zxqfl/tabnine-vscode/issues/13) -- might want to implement it by having TabNine connect to an existing language server

How would one configure `TabNine` to connect to an existing LS?

I'm seeing 32 `beam` processes for 4 open files in `neovim`
![image](https://user-images.githubusercontent.com/18191/54706716-cb07a280-4afc-11e9-98c6-7e3af6b90218.png)
and I'm pretty sure I only need one.
