### ISSUE TITLE
Not happy :( Its not working and it disables all the extension

### ISSUE THREAD

**Issue by rajendra-pun** [codota/TabNine#400]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#1369

**Comment by maya-tabnine** [comment]
What is your IDE?

Please send your config file. It should be located at:
window: {FOLDERID_RoamingAppData}\TabNine
mac : $HOME/Library/Preferences/TabNine
linux: $XDG_CONFIG_HOME/TabNine or $HOME/.config/TabNine
