### ISSUE TITLE
What are the recommended settings for pro account?

### ISSUE THREAD

**Issue by OozingStarDust** [codota/TabNine#402]
- OS version: MacOS Big Sur 11.4
 - Editor: vscode
 - Editor version: 1.57.0
 - Programming language: ts, html, css
 - TabNine extension version: 3.4.5
 - Engine version: 3.4.29-40

**Issue Details:**

Could you please clarify which are the recommended settings for best autocompletion results?

Should the deep cloud **and** local model be turned on? Or only the cloud model?
What will be the difference?

I also have an older Win PC for work, which settings are best for a slower machine (i5 2,6ghz, 8gb ram)?

(Please add the recommended settings to your FAQ I googled so much and couldn't find any recommendations)

gz#1655

**Comment by maya-tabnine** [comment]
The cloud version eliminates 90% of CPU consumption and 70% of memory consumption.
The main difference is that the local model works offline and the cloud model is not. 
There is no need for both cloud and local to be on. If you have a stable internet connection - I recommend the cloud version.
