### ISSUE TITLE
Signing in from within VSCode doesn't work

### ISSUE THREAD

**Issue by looeee** [codota/TabNine#403]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: VSCode
 - Editor version: 1.57.0
 - Programming language: N/A
 - TabNine extension version: 3.4.5
 - Engine version (could be located within Tabnine Hub): 3.5.2-11

**Issue Details:**

Attempting to sign in to TabNine Hub within VSCode:

1. open the hub by clicking "tabnine" in the status bar at the bottom of the VSCode window
2. Click "sign in" in the Tabnine Hub page. 
3. This opens "https://my.tabnine.com/login" in Firefox and displays the login form - even if I was already logged in on the website. 
4. Click "login with GitHub". This successfully logs me in on the website. However, nothing changes in VSCode. 

I can repeat steps 1-4 any number of times. Each time I am presented with the login form and log in again, even if I was previously logged in (on the website) successfully. There seems to be no way to login within VSCode. 

gz#1667

**Comment by maya-tabnine** [comment]
Hi can you send to our support@tabnine.com a live video of the issue?
And do you work behind a proxy of some kind?

**Comment by albert-ying** [comment]
@maya-tabnine I encountered the same problem in vscode-remote. It was not that annoying before, as it still allows me to use the API key. But the student pro doesn't provide API key and I had to log in.

**Comment by cheneysan** [comment]
Was there any update on this issue? I'm having the exact same behavior trying to login to active the pro features on my account from VS Code and Intellij.
