### ISSUE TITLE
Disable suggestions

### ISSUE THREAD

**Issue by c0dezer019** [codota/TabNine#404]
**please complete the following information:**	
 - OS version: Pop!_OS	
 - Editor: Intellij]	
 - Editor version: latest
 - Programming language: Markdown
 - TabNine extension version: Latest
 - Engine version (could be located within Tabnine Hub): Latest

**Issue Details:**

Markdown and Text (or similar extensions) file suggestions should be ignored by default. Disable suggestions should not be a pro config option.

gz#1687

**Comment by maya-tabnine** [comment]
For now, the option to disable Tabnine in specific extensions, etc. is a pro feature. 
But I appreciate your feedback and will pass it on.
