### ISSUE TITLE
Also include Import statements whenever neccessary

### ISSUE THREAD

**Issue by burdoto** [codota/TabNine#408]
**Issue Details:**
(not a bug, not including system related information)

Hi there! first of all, i'm absolutely in LOVE with this project and it KEEPS helping me like crazy.
Tho, my issue is that (particularly in languages like Java), TabNine does not include import statements, but still suggests the target class:
https://user-images.githubusercontent.com/42473485/122768589-09740500-d2a4-11eb-9659-f384a62e8903.mp4

There really isn't much more to say about this, other than "please add import statements" to your magic code. Cheers!

EDIT: I noticed that TabNine also has its problems with capitalization, which is equally of an annoyance :I 
I keep receiving the suggestion `getlogger()` even though I keep using `getLogger()`

gz#2113

**Comment by maya-tabnine** [comment]
We are currently working on making that happen! 
Thanks for the suggestions and stay tuned.
