### ISSUE TITLE
Suggesting non-existent methods

### ISSUE THREAD

**Issue by Insprill** [codota/TabNine#409]
**please complete the following information:**	
 - OS version: Windows 10	
 - Editor: IntelliJ	
 - Editor version: 2021.1.2	
 - Programming language: Java	
 - TabNine extension version: 0.4.1
 - Engine version: 3.5.5-42

**Issue Details:**
TabNine often suggests methods & fields that just don't exist. Example: 
![image](https://user-images.githubusercontent.com/52843537/123012087-9a73da80-d38f-11eb-8925-cd1ae6804d82.png)
Coming from Codota, one of the reasons I loved it so much was that it *didn't* do this. It's very distracting having to filter through multiple suggestions of non-existent methods to find ones that actually exist.

gz#2185

**Comment by Baruch4413** [comment]
I don't think there is a simple solution to this.
Maybe you want a traditional IDE completion?
