### ISSUE TITLE
Please truncate the status bar context menu entry string to a maximum of five words in length.

### ISSUE THREAD

**Issue by manojbaishya** [codota/TabNine#410]
### System Details
  - OS version:
  ```bash
  λ lsb_release -a
  LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
  Distributor ID:	Linuxmint
  Description:	Linux Mint 20.1
  Release:	20.1
  Codename:	ulyssa
  ``` 	
 - Editor: Visual Studio Code	
 - Editor version: 1.57.1
 - Programming language: Python, Plain Text
 - TabNine extension version: v3.4.9
 - Engine version (could be located within Tabnine Hub): 3.5.6-34

### Issue Details

![image](https://user-images.githubusercontent.com/28330014/123095120-5514e300-d44b-11eb-80eb-d81cc700e645.png)

Many thanks for the extension. The "Tabnine" entry on the Status Bar context menu (right click menu) is extremely long, leading to the menu encroaching the entire screen space on my 15" laptop.  Other menu entries range from one to five words in length and do not cause the issue. 

### Patch Required:
Please truncate the status bar context menu entry string to a maximum of five words in length. For example:
1. Tabnine AI Code Autocompletion (Extension)
2. Tabnine AI Code Completion (Extension)
3. Tabnine (Extension)

This will result in a better UX of the extension.

**Comment by meherranjan** [comment]
Completely agree. The status bar is such a mess :D 

<img width="1502" alt="Screenshot 2021-07-07 at 6 50 09 PM" src="https://user-images.githubusercontent.com/589596/124766287-68987180-df54-11eb-8c79-2815daa7542d.png">
