### ISSUE TITLE
Uninstalling should mean uninstalling. Why do you think you are special?

### ISSUE THREAD

**Issue by fritzfr** [codota/TabNine#414]
How come, that when after I uninstall the VSCode extension + restarts, there is still processes running on my machine and killing them just leads to them spawning right back up?

```
sudo lsof -i -P | grep TabNine   
```

```bash
TabNine   27613          felix   11u  IPv4 0xf7b1b47dd947419d      0t0    TCP localhost:52717->localhost:49152 (ESTABLISHED)
TabNine   27613          felix   12u  IPv4 0xf7b1b47dd947419d      0t0    TCP localhost:52717->localhost:49152 (ESTABLISHED)
TabNine-d 41065          felix    9u  IPv4 0xf7b1b47dd8d455cd      0t0    TCP localhost:49152 (LISTEN)
TabNine-d 41065          felix   16u  IPv4 0xf7b1b47dc756d5cd      0t0    TCP localhost:49152->localhost:52717 (ESTABLISHED)
TabNine-d 41065          felix   17u  IPv4 0xf7b1b47dc756d5cd      0t0    TCP localhost:49152->localhost:52717 (ESTABLISHED)
```

Why do you think you are special?

The process is even called `deep-local`. What are you guys doing on my machine after I uninstalled you?

I can't find clear instructions anywhere on how to uninstall this completely. **The fact alone** that I have to look for instructions on how to do so is enough for me to not just stop using this, but I will actively warn others to not use this.

**Comment by fritzfr** [comment]
```
rm -rf ~/Library/Application\ Support/TabNine
rm -rf ~/Library/Application\ Support/Code/User/globalStorage/tabnine.tabnine-vscode
```

This is still not enough, the processes are still spawning back up and the folders are being recreated. I'm getting seriously pissed.

**Comment by amircodota** [comment]
Hi @fritzfr 

Once you uninstall and TabNine is deactivated - within a few seconds all TabNine processes should exit.

Can you specify what editor you are using?
Is it possible there's another window of the editor running or that you have another editor with the TabNine plugin running?

**Comment by fritzfr** [comment]
> Once you uninstall and TabNine is deactivated - within a few seconds all TabNine processes should exit.

Then we would not be sitting here. I only used it with VSCode and uninstalled it days ago, only today I noticed it still has processes open and I started playing the cat and mouse game with it.

I somehow managed to get rid of it now, after deleting the folders a bunch of times and restarting VSCode in some combination.

**Comment by amircodota** [comment]
Glad to hear it is not happening anymore.

Just for the record - the processes run by Tabnine are only ever used for producing autocomplete suggestions.
If they do not exit after uninstall - it is a bug. There's nothing intentional going on.

You mentioned `TabNine-deep-local` - it is the process we use to load the our deep model locally and run inference on it.

I'm closing this issue for now - please feel free to re-open if the issue re-surfaces.
