### ISSUE TITLE
Double-backslash is collapsed into one

### ISSUE THREAD

**Issue by kylecoffey1999** [codota/TabNine#416]
- OS version: [e.g. Win 10, Mac Catalina] Fedora Linux
 - Editor: [e.g. vscode, intelij, sublime] VS Code
 - Editor version:	1.57.1
 - Programming language: [e.g. js, ts, c++]	C
 - TabNine extension version: 3.4.12
 - Engine version (could be located within Tabnine Hub): 3.5.14-32

**Issue Details:**
When completing an AI suggestion with double backslash such as:
```c
int sawEsc = input->data[0] == '\\';
```
the backslashes are reduced to one. I assume this is due to some improper escape sequence handling somewhere.

gz#3121

**Comment by maya-tabnine** [comment]
Hi, thanks for pointing this out to us! It was added to our backlog, and we will fix it.

**Comment by abdelrahman-aboelnour** [comment]
is there any work around to this issue ?
