### ISSUE TITLE
AVG reporting that TabNine.exe was tryin to access your passwords in google chrome

### ISSUE THREAD

**Issue by rahularyan** [codota/TabNine#417]
![image](https://user-images.githubusercontent.com/916764/124718834-235c4b80-df24-11eb-8adc-316391086914.png)

gz#3150

**Comment by maya-tabnine** [comment]
Hi can you click on "See details"?
Tabnine does authentication by opening a browser and asking the user to log in.
We will investigate further why AVG blocks us - it will help a lot if you share the details with us.

**Comment by rahularyan** [comment]
Sorry, I have already uninstalled TabNine so cannot help you with that.
Cheers
