### ISSUE TITLE
Monthly support option (e.g. Patreon)

### ISSUE THREAD

**Issue by broAhmed** [codota/TabNine#42]
I'm using TabNine daily at work and would like to support TabNine's continued development/maintenance.  I like your current business model of one-time payment, but it'd be nice for those who wish to continue to support you beyond the one-time payment to have the option of doing so.

Thank you.

**Comment by zxqfl** [comment]
Thanks very much, I'm glad you like the software! I'll consider your suggestion.

**Comment by amircodota** [comment]
We now support paying for a professional license.

See [this](https://tabnine.com/subscribe).
