### ISSUE TITLE
Support socks5 proxy

### ISSUE THREAD

**Issue by yonip23** [codota/TabNine#421]
Tabnine doesn't respect `http_proxy` and `https_proxy` if its `socks5`.
refs:
https://github.com/seanmonstar/reqwest/blob/8e5af459e58163d76332207107a5584bb79db173/src/connect.rs#L298
https://github.com/seanmonstar/reqwest/pull/609/files
https://docs.rs/reqwest/0.10.0/reqwest/struct.Proxy.html

gz#3667

**Comment by Gandalf-** [comment]
Thanks for filing the issue! Having this implemented would be nice. In the mean time there's a work around for Linux via Privoxy 
https://neoctobers.readthedocs.io/zh_CN/latest/rpi/socks_to_http.html

**Comment by yonip23** [comment]
Did you try it and it worked for you?

**Comment by Gandalf-** [comment]
Yes, I configured privoxy with the steps above on my Ubuntu installation to use the internal SOCKS5 proxy, set `/etc/environment` to point to privoxy, and was able to download the new model and have my API key confirmed 👍 everything seems back to normal

**Comment by yonip23** [comment]
That's awesome, thanks for helping us out!
We'll add this issue to our backlog, and in the meanwhile we now know what to do thanks to you 🙂
