### ISSUE TITLE
Why bind port on 5555

### ISSUE THREAD

**Issue by xiaobaiyey** [codota/TabNine#422]
- OS version: [ Win 10,]	
 - Editor: [intelij]	
 - Editor version:	
 - Programming language: [ c++]	
 - TabNine extension version:0.4.3
 - Engine version (could be located within Tabnine Hub): 3.5.27-42

**Issue Details:**
Local 5555 port will be mistaken for emulator by android adb
![image](https://user-images.githubusercontent.com/12838376/125779261-42f0e4aa-75ec-4ebf-816d-0fe85d4dfabe.png)
![image](https://user-images.githubusercontent.com/12838376/125779369-29fbc1c4-8508-49e0-a176-9656baa74ea4.png)
![image](https://user-images.githubusercontent.com/12838376/125779406-2331da13-a68b-4aca-a872-63460e05551b.png)

Or can I set the port for Tabnine？

gz#3734

**Comment by bilucodota** [comment]
Hi @xiaobaiyey 
Tabnine's spawns a local http server bounded to port 5555 (unless taken, in which case it randomly selects an available port) to serve its configuration UI (Tabnine Hub)

Currently there's no way to configure the port of this server.

**Comment by xiaobaiyey** [comment]
> Hi @xiaobaiyey
> Tabnine's spawns a local http server bounded to port 5555 (unless taken, in which case it randomly selects an available port) to serve its configuration UI (Tabnine Hub)
> 
> Currently there's no way to configure the port of this server.

Can you change the port in the next version

**Comment by abc45628** [comment]
at 2022.04.28, is any way to change this port? random port or custom

**Comment by bilucodota** [comment]
Hi guys, custom port will be supported in the next release. Will update once available.

**Comment by bilucodota** [comment]
Available now in BETA.
Under `tabnine_config.json`, set `tabnine_hub_port` to your liking
