### ISSUE TITLE
Does Not Work In Intellij Idea Ultimate, Horrible Experience

### ISSUE THREAD

**Issue by Haidar0096** [codota/TabNine#424]
**please complete the following information:**	
 - OS version: Linux ubuntu 20.04	
 - Editor: intellij idea ultimate 2021	
 - Editor version: 2021.1.3
 - Programming language: java
 - TabNine extension version: 0.4.4
 - Engine version (could be located within Tabnine Hub): I can't even open the hub

**Issue Details:**

Clicking the tabnine icon in the status bar in the editor does not do anything, one time only after restarting the editor multiple times i could open the hub, but once I closed it(the hub), I was not able to open it again. And in that one time i could access it, it says forever initializing,,,

This is not even the worst part, the memory usage is very high that after few minutes all my 16GB ram memory is eaten by tens of TabNine processes

Can someone explain what is happenning and how to solve this? On the plugin page it says it works right out of the box with no need for any configuration!

Here is a screenshot of the task manager
![image](https://user-images.githubusercontent.com/49842031/126383208-caf81d73-a813-4983-9482-53b57f64555f.png)

gz#3984

**Comment by Haidar0096** [comment]
The issue of memory was solved after alot of tries of killing and restarting the processes and waiting for long time
and the ram usage is still high somehow (about 1 ~ 1.5 GB)

**Comment by bilucodota** [comment]
HI @Haidar0096 can you please send your `~/.config/TabNine/tabnine_config.json` to support@tabnine.com ?

**Comment by Haidar0096** [comment]
@bilucodota  Hello, ok I will do it
