### ISSUE TITLE
[Bug] TabNine keep downloading itself making it unusable with compe-tabnine Neovim plugin

### ISSUE THREAD

**Issue by pidgeon777** [codota/TabNine#425]
**General Informations:**

 - OS version: Windows 10 x64 Pro build 1809
 - Editor: Neovim + [compe-tabnine](https://github.com/tzachar/compe-tabnine) 
 - Editor version: NVIM v0.6.0-dev+14-gdf33f30e8
 - Programming language: all
 - TabNine extension version: TabNine
 -  3.4.29 (x86_64-pc-windows-gnu)
 - Engine version (could be located within Tabnine Hub): N/A

**Issue Details:**

My **compe-tabnine** plugin folder is structured as follows:

`C:\Users\MyUsername\AppData\Local\nvim-data\site\pack\packer\start\compe-tabnine\binaries`

Inside of the `binaries` folder, the following executables are placed:

- TabNine_Windows.exe
- TabNine-deep-cloud.exe
- TabNine-deep-local.exe
- WD-TabNine.exe

The fact is that often, new files are created by **TabNine** when it updates itself, for example in this folder:

- `C:\Users\MyUsername\AppData\Local\nvim-data\site\pack\packer\start\3.5.31\binaries`

After the automatic update process, the newly created folder will contain:

- TabNine.exe
- TabNine-deep-cloud.exe
- TabNine-deep-local.exe
- WD-TabNine.exe

As a result, the originally started process `TabNine_Windows.exe` will keep crashing because of the newly released **TabNine** update, which should be run instead. **compe-tabnine** plugin will detect `TabNine_Windows.exe` crash and it will try to start it again, in an endless loop. In the end, this makes **Neovim** unusable.

I only see three solutions for this annoying behaviour:

- Disable **TabNine** automatic update with a command-line flag: in no way **TabNine** should crash itself when a new edition is released unless instructed to do so.
- Instruct the **compe-tabnine** plugin to always point at the new `TabNine.exe` downloaded executable, and run that instead, unless a new version is released, and if so point again at the new executable location.
- Allow a way to update **TabNine** by letting it stop its execution, deleting itself and downloading the new executable at the same path as the original one, possibly maintaining the same filename too.

I would like to hear your opinion about this, and how could this be fixed. Until that, **TabNine** is not usable in Windows with the **Neovim** client.

gz#4179

**Comment by pidgeon777** [comment]
https://github.com/tzachar/compe-tabnine/issues/32

**Comment by Eransho** [comment]
Need to make sure the plugin behaves properly when a new Tabnine version is downloaded, see our [guidelines](https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md#setting-up-tabnine-within-an-editor-plugin). 
According to the link you attached, it seems that Windows is currently not supported by **compe-tabnine**
