### ISSUE TITLE
TabNine keeps suggesting whatever but "do" to pass a block to a method

### ISSUE THREAD

**Issue by syakovyn** [codota/TabNine#428]
**Env details:** 
- OS version: macOS Big Sur 11.5
 - Editor: RubyMine
 - Editor version: 2021.2, 2021.1.3
 - Programming language: ruby
 - TabNine extension version: 0.4.4
 - Engine version (could be located within Tabnine Hub): 3.5.31-41

**Issue Details:**
![image](https://user-images.githubusercontent.com/417162/127308765-f0ef049d-3c0a-45db-82d0-f43809c1446f.png)

gz#4372

**Comment by anlek** [comment]
Same issue with Sublime Text and Ruby code.
