### ISSUE TITLE
CLion puugin cannot login

### ISSUE THREAD

**Issue by PhoenixChenLu** [codota/TabNine#430]
**please complete the following information:**	
 - OS version: [ Win 10,]	
 - Editor: [Clion]	
 - Editor version:	#CL-212.4746.93
 - Programming language: [any]	
 - TabNine extension version:0.4.4
 - Engine version (could be located within Tabnine Hub): 3.3.104-40

**Issue Details:**

cannot login in the Tabninehub

gz#4545

**Comment by bilucodota** [comment]
Hi @PhoenixChenLu 
Thanks for reaching out
Can you please share some screenshots/video? Add more details?

**Comment by PhoenixChenLu** [comment]
@bilucodota Here's the video trying login.

https://user-images.githubusercontent.com/11763714/127752601-83d2f99d-404d-4826-a008-60a923a584df.mp4

**Comment by PhoenixChenLu** [comment]
@bilucodota 
I also tried in Jetbrains Rider, it seems login doesn't work for all jetbrains IDE

**Comment by bilucodota** [comment]
@PhoenixChenLu any chance you're using proxy? if so - can you please set `http_proxy` / `https_proxy` env vars?

**Comment by PhoenixChenLu** [comment]
yes I am using clash for windows with the following settings:
![image](https://user-images.githubusercontent.com/11763714/127920834-ced3489b-9bf6-4d9a-a039-a336d0eab56c.png)
set http_proxy and https_proxy like this:
![image](https://user-images.githubusercontent.com/11763714/127920935-98e7da93-1f4b-4900-9250-218341deebcc.png)
does not work for me
I've tried use direct connection, including close clash, tried use systemwide global proxy.....

**Comment by PhoenixChenLu** [comment]
@bilucodota do I config the proxy environment variables correctly?

**Comment by dimacodota** [comment]
@PhoenixChenLu  can you please try to define them as `User variables` ?

**Comment by PhoenixChenLu** [comment]
@dimacodota @bilucodota  the problem has gone somehow, I didn't change anything after setting system environment variables, maybe the system variables need time to take effect? I think it is setting environment variables working......
