### ISSUE TITLE
Full Line completions - user feedback 

### ISSUE THREAD

**Issue by dimacodota** [codota/TabNine#433]
Please share your experience with the `Full Line completions` feature

gz#4743

**Comment by maikol-solis** [comment]
I can't enable this feature in my machine. The checkbox doesn't work.  

![image](https://user-images.githubusercontent.com/4078489/129391902-87174ea1-295a-4b25-abab-8cad8320b035.png)

**Comment by yonip23** [comment]
Can you try doing the following?
- Turn off all of your ides in which Tabnine is installed
- Kill all Tabnine processes - these are their names: `TabNine`, `TabNine-deep-local`, `TabNine-deep-cloud`, `WD-TabNine`
- Make sure no Tabnine processes are running
- Re-open your ide and try checking the checkbox again

**Comment by maikol-solis** [comment]
> Can you try doing the following?
> 
>     * Turn off all of your ides in which Tabnine is installed
> 
>     * Kill all Tabnine processes - these are their names: `TabNine`, `TabNine-deep-local`, `TabNine-deep-cloud`, `WD-TabNine`
> 
>     * Make sure no Tabnine processes are running
> 
>     * Re-open your ide and try check the checkbox again

I did all the steps and still I cannot enable the option.

**Comment by yonip23** [comment]
Can you attach herr you config file? I.e `Config file path` from you installation info

**Comment by maikol-solis** [comment]
```
{
  "version": "3.3.96",
  "hide_promotional_message": false,
  "beta_enabled": "Yes",
  "ignore_all_lsp": false,
  "creation_time": "2021-03-17T11:47:02.637538848Z",
  "guuid": "2585b9c76df90bfb52c1690b2b722912af9e6253b6b5db7d66c9f35930b76749",
  "semantic_status": {
    "org": "Suppressed"
  },
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "hosted_deep_completions_enabled": "Enabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 3,
  "line_suggestions": false,
  "multiline_suggestions": true,
  "omit_prefix_suggestions": true,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Yes",
  "disable_local_when_using_battery": true,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": true,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 40,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null,
  "last_service_level": "Cloud",
  "override_beams": null,
  "override_context_length": null,
  "onboarding": {
    "model_type": null,
    "skipped_login": false,
    "completed": false
  },
  "has_git_repos": null,
  "gusr": {
    "dgc": "2585b9c76df90bfb52c1690b2b722912af9e6253b6b5db7d66c9f35930b76749"
  },
  "exclude_file_masks": null,
  "inline_suggestions_mode": true
}
```

**Comment by yonip23** [comment]
Let's try to set `line_suggestions` to `true` and re-open the hub, this is the property that's behind the full lines checkbox. 

Thank you for your cooperation btw, appreciate it!

**Comment by maikol-solis** [comment]
Setting the option manually worked 

![image](https://user-images.githubusercontent.com/4078489/129447099-49792e76-b72d-4676-9a57-88253693070b.png)

Thanks for the help.

**Comment by Toqu95** [comment]
I never get full lines even if it is enabled and I don't know why.

**Comment by yonip23** [comment]
> Setting the option manually worked 
> 
> ![image](https://user-images.githubusercontent.com/4078489/129447099-49792e76-b72d-4676-9a57-88253693070b.png)
> 
> Thanks for the help. 

Looks like its a bug in the UI somewhere. We'll handle it asap, thanks for pointing it out!

**Comment by yonip23** [comment]
> I never get full lines even if it is enabled and I don't really know why.

Don't you see any difference when you turn on/off the full line completions?

Can you share your experience in a bit more details?

**Comment by maikol-solis** [comment]
For the moment I haven't seen any big difference. Maybe my opinion is a little biased because I write mostly prose.

**Comment by gadelkareem** [comment]
How to accept the full line suggestion? The forward arrow key is not working on mac...

**Comment by RichardBosworth** [comment]
I can't seem to see this makes a huge difference to my React Typescript project - it's definitely not as impressive as the demo image on the recent email.
It also seems quite hit and miss. Immediately after activation it seems to predict a whole line, then the very next time you "dot" the db, it suggests a much smaller scale:
Just after ticking the full line box:
![Just after activation](https://user-images.githubusercontent.com/7050026/131859973-f4f44e73-a2ec-47a5-bfef-6e2da00e91c0.png)
Next time you try to "dot" the db var:
![Next dot](https://user-images.githubusercontent.com/7050026/131859972-221a51a3-1f82-4758-815b-e2fa867f7458.png)

Just after disabling:
![Disabled](https://user-images.githubusercontent.com/7050026/131859971-f1580068-3b18-402d-b238-98a877073bf1.png)

Next time you dot the db var with full line disabled:
![Dsiabled after next dot](https://user-images.githubusercontent.com/7050026/131859969-e703cf7f-18b9-4226-b83a-ef067289aac8.png)

My settings
![My settings](https://user-images.githubusercontent.com/7050026/131860280-5b53a124-1e7d-4eb8-8eea-be9f259aedd4.png)

Any ideas why this is so finicky?

**Comment by yonip23** [comment]
Thank you for your feedback, really helps us get better!

> 1. Never got usefull full line suggestion. Using it since feature introduction in 2 150k+ lines projects on a daily basis.

Could you please provide us with your machine spec as well as the information presented in the "installation info" section in the hub?

> 2. always gets as first in the list of suggestions, hindering usage of shorter but at least somewhat useful suggestions.

What would you define as a better experience in that sense? Ordering Tabnine's suggestions differently? Seeing the full line suggestions separately from the regular ones somehow? (Maybe with a different icon / even different keybind)

> 4. inserts line breaks, structure(e.g. dict/obj) endings(like `}`), making your file jump where you didn't expect it to. Also doesn't let you finish the structure yourself.

I'm not sure I fully understand what you mean by jumping where you wouldn't expect, if you could provide us with screenshots / more detailed explanation we'd appreciate it.

Again, thanks for reaching out, have a good one :)

**Comment by yonip23** [comment]
@RichardBosworth I'm so sorry for not getting back to you in a month, your reply is very helpful!

I see that you got a pretty long suggestion in you first "dot", and if I understood correctly you're _deleting_ the "." and typing it again, right?

If so, this behaviour is to be expected from Tabnine the way it works currently, but your feedback is touching an ongoing discussion we currently have in the dev team. So thanks again for your input!

**Comment by iMakedonsky** [comment]
@yonip23 
> Could you please provide us with your machine spec as well as the information presented in the "installation info" section in the hub?
IDE 1: https://gyazo.com/53612e6c35cf887a65dfb004ad344b78
IDE 2: https://gyazo.com/3d8e1a8c314d4fe8eb18f3c43926a5f5
Macbook pro 15" 2018, i7 6cores-12 threads, 16gb ram.  Cloud model enabled.

> > 1. always gets as first in the list of suggestions, hindering usage of shorter but at least somewhat useful suggestions.
> What would you define as a better experience in that sense? Ordering Tabnine's suggestions differently? Getting the full line suggestions separately from the regular ones somehow? (Maybe with a different icon / even a different keybind)

So, usually, experience looked like that: I start typing some line, then I want to finish enum member usage via autocomplete, tabnine at first gives you his simple guesses which look correct, then when I press enter to use the first one – there's a gap in time between suggestion seen and "return" pressed. During this gap full line suggestion appears as 1st suggestion, resulting in using not what I expected.


The result is some more code at the end of the line I didn't need + line breaks(e.g. `\n + };` etc), which I now have to correct, wait for suggestions, and select a plain one from IDE.

Imho, full line suggestions should be in a separate block of suggestions, used via a different hotkey than plain "return". Also, you never see the whole thing tabnine is going to add to your code. Only simple 1-2 words. Then you get a whole bunch of code you didn't expect it to add.



> > 1. inserts line breaks, structure(e.g. dict/obj) endings(like `}`), making your file jump where you didn't expect it to. Also doesn't let you finish the structure yourself.
> 
> I'm not sure I fully understand what you mean by jumping where you wouldn't expect, if you could provide us with screenshots / more detailed explanation we'd appreciate it.
https://gyazo.com/9a4af944f0688ad689a0b75dbc6288ca

1) Tabnine just adds a line break between the wrapper block and child block(say if-else + their bodies) – it doesn't match the indentation level you have. Also, it doesn't add commas for (for methods/properties) of an object in javascript
Result is: after using a suggestion you end up with everything being red, offset and sometimes broken braces. Now you have to carefully look at the code to fix that, or press cmd-Z to type everything yourself.

**Comment by yonip23** [comment]
@iMakedonsky 

I'm not familiar with the behaviour you described regarding the "gap in time" in which more suggestions are added to your completion pop-up - if you can record your screen and reproduce it so I can see exactly what's going on there that'd be great.

As for the wrong indentation / line breaks - Tabnine shouldn't suggest you line breaks (and thus neither indentations) unless you enable multiline suggestions.
Can you share your config file here? (Feel free to censor out every information you don't feel comfortable sharing here)

Also, the screenshots you provided of the installation info are missing the active model hash you're using - if you could share those here too that'd be great

Thanks a lot!

**Comment by CoolOppo** [comment]
Hi just wondering what the difference is between this and the other setting, "Take a long shot: Longer code predictions for a faster workflow". Do they both work together or does one override the other? And what are the other differences actually?

**Comment by paulocwb** [comment]
Being serious, I haven't noticed any difference in more than a month using this feature (only the RAM and CPU eater) , also enabled beta versions. 
using Typescript, the projects aren't giant, but still have some considerable lines of code.

**Comment by RealSaltyFish** [comment]
Is there any documentation for the API for this? I use neovim and coc.nvim doesn't support this. I'm considering implementing it myself but I couldn't figure out how.
