### ISSUE TITLE
Shorten extension name?

### ISSUE THREAD

**Issue by nick-at-work** [codota/TabNine#435]
**please complete the following information:**	
 - OS version: Win10
 - Editor: vscode
 - Editor version: 1.59.0
 - Programming language: js/ts
 - TabNine extension version: 3.4.22
 - Engine version (could be located within Tabnine Hub): 3.5.37-40

**Issue Details:**

![image](https://user-images.githubusercontent.com/73852955/128726384-e1667601-e6a6-47e7-865b-2e519ecbbdfc.png)

Can you make the name (or whatever this field is that shows here) smaller?

gz#4954

**Comment by maya-tabnine** [comment]
Thank you for the feedback.
It is like that since we found it makes it easier to find the extension in the search.
