### ISSUE TITLE
TabNine keeps adding a notification element to my IDE's status bar

### ISSUE THREAD

**Issue by anbuc** [codota/TabNine#436]
- OS version: Ubuntu 21.04
 - Editor: PhpStorm
 - Editor version: 2021.2
 - TabNine extension version: 0.4.7
 - Engine version (could be located within Tabnine Hub): 3.5.37-40

**Issue Details:**
This icon keeps reappearing in my status bar, regardless of if the actual tabnine element is there or not. It vanishes if I click on it, but is back a minute or so later
![image](https://user-images.githubusercontent.com/7095060/128844601-9a7bf21c-c6af-4ccd-8b1b-e025aeffb6da.png)

And as it doesn't seem to do anything different than the actual status bar element, I don't understand why it exists in the first place.

gz#4989

**Comment by sicarul** [comment]
How can we disable it?
Thanks
