### ISSUE TITLE
Turn off snake case recommendations

### ISSUE THREAD

**Issue by alarinel** [codota/TabNine#437]
I need more customization options for how it recommends things because always the first item in every list is snake case, and it ends up slowing me down a LOT since 99% of all recommendations are garbage. I have had to completely turn it off for most file types because honestly the basic recommendations from intellij are lightyears above this. I tried every one of the basic settings and ended up just turning it off across the board because it's done nothing but make my life harder.

Or I should be able to say 'drop tabnine recommendations down the list' because it always take the first n slots and the recommendations always suck.

I wouldn't be so annoyed except codota was wayyyy better and I paid for the premium, so the fact that the recommendations are actively making things more difficult makes it not fun.

gz#5053

**Comment by avichay77** [comment]
Thanks for this feedback.
Can you share which IDE and language you've used in Codota?

Did you try to enable full line completions?
We believe it will improve your experience with Tabnine.

**Comment by aStudyMachine** [comment]
I am a Java developer and I use Intelij 2021.2 as an IDE. I feel the same way with this guy. Snake case always appears as the preferred prompt and puts back the correct prompt for Intelij. 
I wish I could configure the code style suggested by Tabnine.
