### ISSUE TITLE
Is tabnine really that useful ?

### ISSUE THREAD

**Issue by zz541843** [codota/TabNine#438]
I don't think tabnine has any advantage over webstorm's automatic prompt
This is my configuration, Am I wrong?
![自动截图21-8-12_09 26 10](https://user-images.githubusercontent.com/72638366/129124063-1c05e9a9-dcac-4560-a14d-229a04594780.png)
![自动截图21-8-12_09 26 30](https://user-images.githubusercontent.com/72638366/129124088-b17f6e85-76dd-4a39-adcf-0f38e25fe519.png)

gz#5064

**Comment by YotamFromCodota** [comment]
Hey @zz541843 

The configuration seems fine :)
Can you please elaborate on this issue? We'd love to hear more.

Thanks,
Yotam
Tabnine Team

**Comment by bichikim** [comment]
I think so too.
Sometimes It rather disturbs me. 

You guys should look into this problem deeply 

40% suggestions  is not what I want

**Comment by maya-tabnine** [comment]
Would you try enabling the Full Line Completions?
Perhaps you'll find them more useful.
<img width="572" alt="Full line completions" src="https://user-images.githubusercontent.com/82452749/130050663-f19d8206-85d2-41e5-a443-15e8bdf762a7.png">
