### ISSUE TITLE
Cross-Project AI Learning?

### ISSUE THREAD

**Issue by DenysAshikhin** [codota/TabNine#441]
Hi,

I just have a question regarding how the cloud learning works. If I have the deep completion cloud turned on and I am signed in (free license) and use this extension in VScode across various projects on different repositories, does the AI remember its learning from each project to tailor to me, or is it learning and optimising per project?

Thanks,

gz#5367

**Comment by Tabnineteam** [comment]
Hello Denys,

Thanks for reaching out. We never train our models on user code. We do use your context (such as your current file) to provide suggestions which are specific to your context. You can read more about how exactly that works here:

https://www.tabnine.com/code-privacy

I hope this answers your question and if not please don't hesitate to reach out again.

Enjoy the rest of your week,

Nimrod Astarhan
Core Engineer
<br><p><em><small>°°°</small></em></p>
