### ISSUE TITLE
full cpu use

### ISSUE THREAD

**Issue by abc45628** [codota/TabNine#443]
**please complete the following information:**	
 - OS version: [Win 10]	
IDE:
IntelliJIDEA
Plugin Version:
0.4.7
Engine Version:
3.5.49-40
 - Programming language:java
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
I use tabnine in Intranet，and everyone need to use proxy to access internet, and the proxy may return warning page when some website block.
I open the intellij, and I see many tabnine.exe and use 100% cpu, and i cannot open tabnine by click the right bottom button in intellij.
when i use normal internet,everything is ok, and it only appear in work office

gz#5378

**Comment by JarynXu** [comment]
same situation

**Comment by JarynXu** [comment]
it has already taken me 18g of my pc memory

**Comment by maya-tabnine** [comment]
Hi!
When you experience that extensive memory usage, do you have the deep completions cloud or the local enabled?
On Tabnine Hub, you can set and see what model is enabled.

Also, can you update the plugin version to 0.4.9? We just released it.

**Comment by kitety** [comment]
This is a great extension, but the CPU usage is too high.
