### ISSUE TITLE
Multiline suggestions indentation is not done correctly due to which I can't enable the option

### ISSUE THREAD

**Issue by waleedrana777** [codota/TabNine#445]
Win 10
VS Code v1.59.1
Language Javascript Node JS
Extension version: 3.4.22
Engine Version: 3.5.54-12
**Issue Details:**

So the snippet suggested always has one tab more indentation after the next line starts and since my formatter doesn't format, it takes more time to correct the indentation than to write all by yourself!

gz#5462

**Comment by waleedrana777** [comment]
Win 10
VS Code v1.59.1
Language Javascript Node JS
Extension version: 3.4.22
Engine Version: 3.5.54-12

**Comment by ekesdf** [comment]
@dimacodota @YotamFromCodota 
Ubuntu 20.04
VS Code v3866c355 (latest/stable)
Language Python
Extension version 3.4.26
Engine Version 3.5.54-40

I have the similar problem with the model making a newline in front of the line it predicts on.

![Bildschirmfoto von 2021-09-02 13-44-47](https://user-images.githubusercontent.com/64316659/131837966-0a99d820-0928-432f-830d-8b8bceeb174b.png)

**Comment by CharlonTank** [comment]
Same here
Mac OS 11.5
VS Code: 1.61.0-insider (Universal)
Language: elm
Extension: Pro version - Last updated 01/09/2021, 13:14:46
