### ISSUE TITLE
After starting tabnine, I can't use tab to indent code.

### ISSUE THREAD

**Issue by 876870023** [codota/TabNine#446]
How to solve this problem?

gz#5473

**Comment by 3xiaoxiao3** [comment]
same problem

**Comment by Eransho** [comment]
Hi, we are sorry for the trouble, this is a bug indeed and we will release a fix ASAP
In the meanwhile, you can locally fix it by changing the shortcut key for a new action called _Accept Inline Completion_ (which is currently set with the tab key).

**Comment by Eransho** [comment]
New version [0.4.9](https://plugins.jetbrains.com/plugin/12798-tabnine-ai-code-completion-js-java-python-ts-rust-go-php--more/versions/stable/133830) has been released to the JB's marketplace.
Closing this one but you can reopen if the problem reoccurs
