### ISSUE TITLE
I cant use tab in android studio after I upgrade tabnine

### ISSUE THREAD

**Issue by 3xiaoxiao3** [codota/TabNine#447]
**please complete the following information:**	
 - OS version: WIN 10
 - Editor: Android Studio 
 - Editor version: Arctic Fox | 2020.3.1 Patch 1
 - Programming language: java
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 3.5.54-42

**Issue Details:**I cant use tab shortcut when I use tabnine in android studio
and I cant open Tabnine Setting,Always loading!

gz#5474

**Comment by Eransho** [comment]
See my reply in #446. Will keep update there, closing this one
