### ISSUE TITLE
Keymapping problem

### ISSUE THREAD

**Issue by mYmNeo** [codota/TabNine#448]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

OS version: Mac bigsur 1.15.2
Editor: intelij

Since the new version of TabNine supports using TAB to complete code, but for TAB as delimiter situation, I can't insert TAB  into files. 

gz#5485

**Comment by Eransho** [comment]
Hi @mYmNeo , until the fix will be released, see the workaround solution and updates in #446
