### ISSUE TITLE
Output error cue to closing bracket "}"

### ISSUE THREAD

**Issue by ihateyouaswell** [codota/TabNine#449]
- MacOS Bigsir	
 - vscode 
 - 1.59.1	
 - C++	
 - Free?
 - 3.5.54-42

When trying to run simple text program. The closing brackts for the int main() outputs an error.

Im new to this so help would be gratefully appreciated!
 
![Screen Shot 2021-08-30 at 5 42 13 PM](https://user-images.githubusercontent.com/89624982/131415117-6457c776-35a5-409a-930c-2cddbd6441fa.png)

gz#5847

**Comment by bilucodota** [comment]
Hi @ihateyouaswell 
This is not issue originated in Tabnine. 
`g++` is saying your'e missing return statement at line 9.
