### ISSUE TITLE
I had pro for 1 month but it wasn't working?

### ISSUE THREAD

**Issue by ahmetkca** [codota/TabNine#451]
I had pro version for month and i realized in vs code it was still displaying like i have free. This is bs. In the website it shows me i have pro but in vscode i is free ???

i tried to logout and login again but now i can't even log in. The webpage says "You are now authenticated with Tabnine
You may close this window and return to your IDE" but in IDE i am still now logged in ????

gz#6016

**Comment by maya-tabnine** [comment]
Hi, would you email us at support@tabnine.com and elaborate on your subscription email and the email you signed up with?
We will sort this out and make it right!
