### ISSUE TITLE
Tabnine Extension was unable to download its dependencies

### ISSUE THREAD

**Issue by ShaneTian** [codota/TabNine#453]
**please complete the following information:**	
 - OS version: Linux
 - Editor: VS Code
 - Editor version:
 - Programming language:
 - TabNine extension version: v3.4.26
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
I use VS Code remote on Linux. After installing TabNine, the status bar always show `tabnine: Starting`.
Maybe it is because the remote machine can't connect to the network to download files.
![image](https://user-images.githubusercontent.com/42370681/132824006-1cc28ba3-033f-44d8-9a69-72d5d1dd6f26.png)
![image](https://user-images.githubusercontent.com/42370681/132824064-29bed2ab-f543-47e4-b8da-e42265ba766b.png)

And `Tabnine::config` doesnot work for me.

gz#6305

**Comment by maya-tabnine** [comment]
Can you uninstall Tabnine? Then remove the folder's content of the binary files,
It should be located at 
/home/{UserName}/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/
And after that, reinstall Tabnine.
If it fails again with this error, perhaps try to reinstall the dependencies using a visx file from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/TabNine/vsextensions/tabnine-vscode/3.4.26/vspackage 

Would you please let me know if that works?

**Comment by mbartelsm** [comment]
Running into this issue, tried the suggested fix and got this running the .VISX file:

> Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Metadata' has attribute 'DisplayName' with value 'Tabnine - Code Faster with the All-Language AI Assistant for Code Completion, autocomplete JavaScript, Python, TypeScript, PHP, Go, Java, node.js, Ruby, C/C++, HTML/CSS, C#, Rust, SQL, Bash, Kotlin, React, Swift, Scala, Sass, Perl, Objective C, Node JS, Matlab, Haskell, Dart, Angular' whose length is greater than maximum value of 100.

Like... come on

**Comment by joelstransky** [comment]
Getting this error but we are behind a proxy with pretty much everything blocked. What domains would we need to whitelist in order for this to finish install?

The failure message included 'Source: Tabnine AI (Extension)'

**Comment by babzo007** [comment]
> Getting this error but we are behind a proxy with pretty much everything blocked. What domains would we need to whitelist in order for this to finish install?
> 
> The failure message included 'Source: Tabnine AI (Extension)'

Hello, please let me know if you succeeded to make it work since ? I'm facing the same issue. Thanks!
