### ISSUE TITLE
Allow application to work with Ale vim completion

### ISSUE THREAD

**Issue by superDross** [codota/TabNine#454]
I noticed ale was not on the list of compatible completion plugins. I was wondering if TabNine could be developed to work alongside it?

https://github.com/dense-analysis/ale

gz#6417

**Comment by bilucodota** [comment]
Hi @superDross 
What vim client are you using?

**Comment by superDross** [comment]
Not sure what you mean by vim client. Vim Vs NeoVim? If so, just regular old vim.

**Comment by bilucodota** [comment]
Oh, Tabnine offers few vim Integrations.. wondered what you're using.. anyway, I haven't tried it myself.. but I see Ale can integrate with Deoplete, and Tabnine also has this integration.. so this can be a solution
https://github.com/tbodt/deoplete-tabnine
