### ISSUE TITLE
Auto Completion

### ISSUE THREAD

**Issue by ToastedMice** [codota/TabNine#455]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: vscode
 - Editor version: latest
 - Programming language: py	
 - TabNine extension version: 3.4.27
 - Engine version (could be located within Tabnine Hub): 3.7.1-45

**Issue Details:**
using the inline completions experimental mode
when I press tab it always autocompletes to the text written even I selected a different option in the drop-down menu.
![image](https://user-images.githubusercontent.com/90034421/133533454-d0e38ae1-8047-43fb-a113-3b2d7807df20.png)

gz#6536

**Comment by bilucodota** [comment]
Hi @ToastedMice 
Inline completions are handled separately to the dropdown completions.
To see the inline completion keybindgs, simply hover on the inline suggestion. See https://github.com/codota/TabNine/issues/432#issuecomment-897183815
