### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by A3939** [codota/TabNine#456]
**please complete the following information:**	
 - OS version: Win 10	
 - Editor:  vscode
 - Editor version: Letest	
 - Programming language: JavaScript
 - TabNine extension version: Pro student
 - Engine version (could be located within Tabnine Hub):  3.7.1-42

**Issue Details:**

Inline completions is not working i restart many times and also restart the computer but still it is not woking.

gz#6616

**Comment by maya-tabnine** [comment]
Did you activate the inline completions on Tabnine Hub?

**Comment by A3939** [comment]
Now it's working fine
