### ISSUE TITLE
how to install it to code-server(vscode on web)

### ISSUE THREAD

**Issue by ES-Yukun** [codota/TabNine#457]
I want to know, how to install tabnine to code-server running with archlinux.

gz#6765

**Comment by loupzeur** [comment]
Hello,
it appears that you can install it, and it will "work" (do completions, ...), but you won't be able to configure it (sign in, change parameters), because it's serve it's configuration page with a server that run on 127.0.0.1, so you won't be able to access it remotely.

**Comment by maya-tabnine** [comment]
We use $BROWSER to open the browser, check out one of the answers [on this link](https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux)
That can make it work.

**Comment by Ekkone** [comment]
> We use $BROWSER to open the browser, check out one of the answers [on this link](https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux) That can make it work.

Thank you !!!!! 
`update-alternatives --install "bin/host_chrome" "chrome" "/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" 1`
`export BROWSER=host_chrome`
It work !
