### ISSUE TITLE
Inline: Issue with git commit message

### ISSUE THREAD

**Issue by sevenc-nanashi** [codota/TabNine#460]
**please complete the following information:**	
 - OS version: Win10
 - Editor: VSCode
 - Editor version: 1.60.2
 - Programming language: (Git commit message)
 - TabNine extension version:3.4.27
 - Engine version (could be located within Tabnine Hub): 3.7.5-40

**Issue Details:**

Inline completion appears in editor while I'm typing git commit message.

https://user-images.githubusercontent.com/59691627/134654866-f9c456cc-40c7-45ff-a18c-b5bdcf46526f.mp4

gz#6872

**Comment by bilucodota** [comment]
Hi @sevenc-nanashi 
Thanks for submitting the issue! https://github.com/codota/tabnine-vscode/pull/644/files should fix this.
Make sure your plugin is updated to the latest version - 3.4.29.
Let us know should you have any other issues!
