### ISSUE TITLE
PyCharm - Tabnina hints - incorrect indentation

### ISSUE THREAD

**Issue by Aldmors** [codota/TabNine#461]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
      Win 10
 - Editor: [e.g. vscode, intelij, sublime]	
 PyCharm 2021.1.3 (Professional Edition)
Build #PY-211.7628.24, built on June 30, 2021

**Issue Details:**

When I used, short, long, full line suggestions. They are created without indentation in the code, which must then be corrected manually

gz#7180

**Comment by maya-tabnine** [comment]
Hi, can you attach a video of it? Or examples?
Thanks :)
