### ISSUE TITLE
student plan issue on linux mint

### ISSUE THREAD

**Issue by ihsanbudiman** [codota/TabNine#462]
- OS version: linux mint 20.4
 - Editor: vscode
 - Editor version: 1.56.0
 - Programming language: all
 - TabNine extension version: 3.4.20
 - Engine version (could be located within Tabnine Hub): 3.7.5-46

i already registered with student plan, linux mint still detect me as basic model..
but when i try on windows 10 vscode detect my account as pro model 

gz#7212

**Comment by bilucodota** [comment]
Hi @ihsanbudiman,

Can you `tar` your `~/.config/TabNine `dir and send it to `support@tabnine.com`?

**Comment by DavidRojoM** [comment]
Same issue on Manjaro Linux
Editor: WebStorm 2021.2.2 and PhpStorm 2021.2.2
Kernel: 5.13.19-2-MANJARO

already sended `tar` to `support@tabnine.com`

**Comment by ihsanbudiman** [comment]
> Hi @ihsanbudiman,
> 
> Can you `tar` your `~/.config/TabNine `dir and send it to `support@tabnine.com`?

ok i already sent it

**Comment by PureWhiteWu** [comment]
same issue here on Debian 10

**Comment by Tabnineteam** [comment]
Hi ihsanbudiman,

Thanks for your patience!

The bug was resolved and should work for you now.
Would you restart your IDE and let me know it is showing you as Pro on Tabnine Hub?

Thank you,

Maya Pohes
Tabnine Support
<br><p><em><small>°°°</small></em></p>

**Comment by DavidRojoM** [comment]
Working fine on Manjaro Linux

**Comment by maya-tabnine** [comment]
The problem was fixed.
It should be resolved now :)

**Comment by ihsanbudiman** [comment]
> The problem was fixed. It should be resolved now :)

thank you so much
