### ISSUE TITLE
Not autologging in. Have to manually login every time I open a new window of vscode

### ISSUE THREAD

**Issue by DoNotResuscitate** [codota/TabNine#468]
**please complete the following information:**	
 - OS version: Mac Big Sur 11.6
 - Editor: vscode
 - Editor version: 1.61.1
 - Programming language: N/A
 - TabNine extension version: 3.4.30
 - Engine version (could be located within Tabnine Hub): 3.7.12-46

**Issue Details:**
Tabnine does not auto login anymore. Anytime I open/close a vscode window I have to login separately. If I already am logged in on one window, and open a new one, I am not logged in.

gz#7715

**Comment by DooNotResuscitate** [comment]
@bilucodota I am not. I am just editing files locally on my computer. I have emailed a video as requested.

**Comment by Tabnineteam** [comment]
We will follow up on the email sent to us
<br><p><em><small>°°°</small></em></p>

**Comment by sahuyash1103** [comment]
I have the same issue, it's so irritating every time I reload my vs-code workstation. Can it be fixed. So I can concentrate over my work instead of signing again and again.

**Comment by oneeyedreaper** [comment]
I'm facing the same issue. Is there any progress? @bilucodota

**Comment by bilucodota** [comment]
Hi @oneeyedreaper 
What is your exact setup?

**Comment by oneeyedreaper** [comment]
OS version: Windows 10 21H2
Editor: vscode
Editor version: 1.63.2
Programming language: N/A
TabNine extension version: 3.5.15

**Comment by bilucodota** [comment]
@oneeyedreaper are you using wsl2/ssh/docker?

**Comment by oneeyedreaper** [comment]
> @oneeyedreaper are you using wsl2/ssh/docker?

No.
Just working on local repos with react and node.

**Comment by bilucodota** [comment]
@oneeyedreaper did it use to work before? Or was it always not persisting?

**Comment by oneeyedreaper** [comment]
> @oneeyedreaper did it use to work before? Or was it always not persisting?

This started yesterday. At first I thought it was nothing , but after it seemed to be persistent, I searched for the issue and ended up here.

**Comment by bilucodota** [comment]
Okay. I will look into it tomorrow. Please send your tabnine_conig.json (location can be found in Tabnine Hub) to support@tabnine.com

**Comment by oneeyedreaper** [comment]
> Okay. I will look into it tomorrow. Please send your tabnine_conig.json (location can be found in Tabnine Hub) to support@tabnine.com 

Thank you for your assistance. Have a good one.

**Comment by jimsynz** [comment]
Hey there.  I'm having the same issue, however I do alternate between local/devcontainer/ssh/ssh+devcontainer environments, so I just assumed that was the source of my woes.

OS macOS Monterey 12.1 (21C52)
VS Code 1.64.1
TabNine Extension 3.5.24

also happening on

OS Pop_OS! 21.10 x86_64
VS Code 1.64.1
TabNine Extension 3.5.24

I am a TabNine Pro subscriber.

**Comment by VidarDev** [comment]
Same here Just working on local repos and GitHub repos.

Windows 11
VS Code 1.64
newest TabNine extension

**Comment by wojcraftinho** [comment]
I have the same problem working in WSL2.

Windows 11
VSCode 1.69
probably newest TabNine version

**Comment by mehak-kalia** [comment]
Having the same issue

mac os
newest version

**Comment by AchwaqKhalid** [comment]
9 months later and still no fix 🙆🏻‍♂️

**Comment by vuongvu01** [comment]
I'm having the same issue, any fix?

**Comment by caffeinated-pixels** [comment]
This keeps happening to me too in VS Code with a Github sign in, it's very annoying and it's happening on both Mac and Windows.

**My Mac config:**
Intel MacBook Pro
MacOS Ventura 13.0
VS Code 1.73
Tabnine Pro version 3.6.19

**PC config:**
Windows 10 Pro (22H2 OS build 19045.2193)
VS Code 1.73
Tabnine Pro version 3.6.19

**Comment by yahave** [comment]
Apologies for the inconvenience, we are investigating and will roll out a fix ASAP.

**Comment by ofshellohicy** [comment]
alwys need to login first....

**Comment by Maashad** [comment]
Experiencing this issue as well. Have to login every time vs code opens.

**Comment by RobiFerentz** [comment]
Same issue. :(

**Comment by bartschliam** [comment]
Same issue on Windows and Mac.

**Comment by timmyjose** [comment]
Looks like this issue will never be fixed.

**Comment by R0GUE-A5H** [comment]
Why not someone fix it?

**Comment by elias-soykat** [comment]
@Tabnineteam 

same issue exists

**Comment by ZoranNikolov** [comment]
Same issue. 

Ubuntu 23.10.

**Comment by ellmc2** [comment]
Same issue.

**Comment by enclosser** [comment]
Same issue too.

**Comment by garri1105** [comment]
Same. Considering switching to Copilot only for this reason

**Comment by csanjay99** [comment]
Same issue. i don't think they will fix it ever.

**Comment by skoniks** [comment]
macOS Sonoma
Same issue too

**Comment by ilpredo** [comment]
macOS Sequoia, same issue

**Comment by lim-kim930** [comment]
Same here,
the latest Windows 11 system, the latest VS Code

**Comment by gitmit1tbcopters** [comment]
Same problem. Please fix this

**Comment by mika7days** [comment]
I am using VS Code extension on my Mac, I still have the same issue. Every time I have to Log in

**Comment by onurdoker** [comment]
Same problem, fix this please

**Comment by amirbilu** [comment]
Hi everyone, confirming this is fixed in `tabnine-vscode v3.203.0`. Apologies for the inconvenience.

**Comment by taras-bl** [comment]
> **please complete the following information:**	
>  - OS version: Mac Big Sur 11.6
>  - Editor: vscode
>  - Editor version: 1.61.1
>  - Programming language: N/A
>  - TabNine extension version: 3.4.30
>  - Engine version (could be located within Tabnine Hub): 3.7.12-46
> 
> **Issue Details:**
> Tabnine does not auto login anymore. Anytime I open/close a vscode window I have to login separately. If I already am logged in on one window, and open a new one, I am not logged in.
> 
> gz#7715
