### ISSUE TITLE
Unable to use Pro version

### ISSUE THREAD

**Issue by mztlive** [codota/TabNine#471]
OS version: Win10 Wsl2-Ubuntu20.x
Editor: vscode
Programming language: PHP

Issue Details:

I have already subscribed to the PRO version, but I can't use it.
account: mzt.live@live.com

![image](https://user-images.githubusercontent.com/13467892/139467380-c8614d21-e1b4-483e-9d7d-dda7e12e007f.png)

gz#8153

**Comment by ryu1255** [comment]
Try Refresh

**Comment by ryu1255** [comment]
Try to Refresh

**Comment by mztlive** [comment]
> Try to Refresh

I tried to log in, but I can't log in after logout in.

![image](https://user-images.githubusercontent.com/13467892/139818335-59f0cb9b-ef2a-458c-b637-741996639525.png)

Click Sign in no response

![image](https://user-images.githubusercontent.com/13467892/139818430-9ef463a6-afa3-45d2-ac97-f92cb983b268.png)

浏览器无法访问127.0.0.1:5555

**Comment by maya-tabnine** [comment]
Did you set the `BROWSER` variable? see [this](https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux)
If that still does not work, try uninstalling Tabnine, delete the tabnine folder, and reinstall
