### ISSUE TITLE
Deep model cannot be downloaded due to the self signed certificate in chain

### ISSUE THREAD

**Issue by TomaszG** [codota/TabNine#472]
**please complete the following information:**	
 - OS version: Mac Catalina
 - Editor: vscode
 - Editor version: 1.61.2
 - Programming language: js, ts
 - TabNine extension version: 3.4.33
 - Engine version (could be located within Tabnine Hub): 3.7.25-45

**Issue Details:**

Deep model cannot be downloaded due to the self signed certificate in chain:

<img width="702" alt="Screenshot 2021-11-04 at 12 41 15" src="https://user-images.githubusercontent.com/873114/140307869-9a4c2a4e-2311-47ed-8d29-287e8cfd3085.png">

This is a very common problem in my organization where there's a need to use VPN. Usually, it ends with temporarily disabling SSL/Cert validation (e.g. with strict-ssl set to false for npm and NODE_TLS_REJECT_UNATHORIZED=0 for node). Please add an option, e.g. to tabnine config so the check can be disabled.

gz#8339

**Comment by bilucodota** [comment]
HI @TomaszG, thanks for reaching out!
Would having a `TABNINE_TRUSTED_ROOT_CER=/path/to/pem-file` be a good solution to your need?

**Comment by TomaszG** [comment]
Hi @bilucodota. Unfortunately I don't have access to the pem file of this cert, the only way that worked for other tools was to disable SSL.

**Comment by maya-tabnine** [comment]
Hi @TomaszG 
Would you try to download the model manually?
Download the deep-learning model, type "Tabnine::config" in your IDE to open Tabnine Hub.
According to the message, install the required model manually from:
https://update.tabnine.com/models/MODEL
for example https://update.tabnine.com/models/abcd1234

Add a ".tabninemodel" extension to the downloaded file and place the file in the following path on MacOS: /Users/{UserName}/Library/Application Support/TabNine/models/

Then restart your IDE.
Would you let us know that worked for you?
