### ISSUE TITLE
Add support for *.resource file types for Robot Framework

### ISSUE THREAD

**Issue by Andyspickle** [codota/TabNine#473]
**please complete the following information:**	
 - OS version: Win 10	
 - Editor: vscode
 - Editor version: Version 1.62.0
 - Programming language: .py, .robot	
 - TabNine extension version: 3.4.33
 - Engine version (could be located within Tabnine Hub):  3.7.25-41

I am using Robot Framework 4.0+ and I can see that ***.robot** filetypes are supported.

Is there any chance that their new file type ***.resource** can be added to the list?

Thanks in advance 

gz#8365

**Comment by yonip23** [comment]
Hey @Andyspickle
Unfortunately, Tabnine can only offer partial support for `.resource` files - you should get tabnine suggestions in such files, but Tabnine just didn't train on enough `.resource` files to provide any better support.
Thanks for the feature request anyway!

Best regards,
Yoni
