### ISSUE TITLE
feat: synchronize settings for pro and business plans

### ISSUE THREAD

**Issue by aka-bash0r** [codota/TabNine#475]
This is a feature request for the paid plans. Similar to https://github.com/codota/TabNine/issues/344, I'm using GitHub Codespaces and Remote Containers. Therefore, there is no tabnine_config.json in my newly created containers. Every time I create a new container, I have to define my settings for TabNine. I would prefer to log into my account and see my settings restored. My current approach via dotfile synchronization in VS Code feels pretty hacky.

**Comment by avichay77** [comment]
Thanks for the feedback.
Makes sense to keep the preference for the logged in users, especially in the mentioned case. 

I'm adding this to our list.
