### ISSUE TITLE
The TabNine can't install with Visual Studio 2022 Current

### ISSUE THREAD

**Issue by ZZZCNY** [codota/TabNine#476]
**please complete the following information:**	
 - OS version: Microsoft Windows 11 家庭中文版
 - Editor: Microsoft Visual Studio Community 2022 (64 位) - Current
 - Editor version:版本 17.0.0
 - Programming language: 	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
2021/11/15 下午 6:32:04 - Microsoft VSIX Installer
2021/11/15 下午 6:32:04 - -------------------------------------------
2021/11/15 下午 6:32:04 - vsixinstaller.exe version:
2021/11/15 下午 6:32:04 - 17.0.5226-preview5
2021/11/15 下午 6:32:04 - -------------------------------------------
2021/11/15 下午 6:32:04 - Command line parameters:
2021/11/15 下午 6:32:04 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ZZZCNY\Downloads\TabNineVisualStudio.vsix
2021/11/15 下午 6:32:04 - -------------------------------------------
2021/11/15 下午 6:32:04 - Microsoft VSIX Installer
2021/11/15 下午 6:32:04 - -------------------------------------------
2021/11/15 下午 6:32:04 - Initializing Install...
2021/11/15 下午 6:32:04 - 扩展详细信息...
2021/11/15 下午 6:32:04 - 	Identifier         : tabnine-visual-studio
2021/11/15 下午 6:32:04 - 	Name               : Tabnine-VisualStudio
2021/11/15 下午 6:32:04 - 	Author             : TabNine
2021/11/15 下午 6:32:04 - 	Version            : 0.1.23
2021/11/15 下午 6:32:04 - 	Description        : Tabnine - Code Faster with the All-Language AI Assistant for Code Completion, autocomplete JavaScript, Python, TypeScript, PHP, Go, Java, Ruby, C/C++, HTML/CSS, C#, Rust, SQL, Bash, Kotlin, React, Swift, Scala, Sass, Perl, Objective C, Node JS, Matlab, Haskell, Dart, Angular
2021/11/15 下午 6:32:04 - 	Locale             : en-US
2021/11/15 下午 6:32:04 - 	MoreInfoURL        : 
2021/11/15 下午 6:32:04 - 	InstalledByMSI     : False
2021/11/15 下午 6:32:04 - 	SupportedFrameworkVersionRange : [4.5,)
2021/11/15 下午 6:32:04 - 
2021/11/15 下午 6:32:04 - 	SignatureState     : Unsigned
2021/11/15 下午 6:32:04 - 	支持的产品              : 
2021/11/15 下午 6:32:04 - 		Microsoft.VisualStudio.Community
2021/11/15 下午 6:32:04 - 			Version : [16.0,17.0)
2021/11/15 下午 6:32:04 - 			ProductArchitecture : x86
2021/11/15 下午 6:32:04 - 
2021/11/15 下午 6:32:04 - 	引用                 : 
2021/11/15 下午 6:32:04 - 	系统必备               : 
2021/11/15 下午 6:32:04 - 		-------------------------------------------------------
2021/11/15 下午 6:32:04 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2021/11/15 下午 6:32:04 - 		Name         : Visual Studio core editor
2021/11/15 下午 6:32:04 - 		Version      : [16.0,17.0)
2021/11/15 下午 6:32:04 - 
2021/11/15 下午 6:32:04 - 签名详细信息...
2021/11/15 下午 6:32:04 - 	Extension is not signed.
2021/11/15 下午 6:32:04 - 
2021/11/15 下午 6:32:04 - 正在搜索适用的产品...
2021/11/15 下午 6:32:04 - 找到的已安装产品 - 全局位置
2021/11/15 下午 6:32:04 - 找到的已安装产品 - Visual Studio Community 2022 Current
2021/11/15 下午 6:32:05 - VSIXInstaller.NoApplicableSKUsException: 此扩展不能安装在任何当前安装的产品上。
   在 VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable\`1& skuData)
   在 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable\`1& skuData)
   在 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   在 VSIXInstaller.App.Initialize()
   在 System.Threading.Tasks.Task`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

gz#8758

**Comment by maya-tabnine** [comment]
Hi!
Currently, Tabnine exists for Visual Studio 2019.
However, we do plan to expand to VS 2022. If we'd see enough interest from the community, we will make sure such a plugin exists.

**Comment by r-sayar** [comment]
> Hi! Currently, Tabnine exists for Visual Studio 2019. However, we do plan to expand to VS 2022. If we'd see enough interest from the community, we will make sure such a plugin exists.

Is it possible to opt-in for getting notified via email if there is a version for 2022?

**Comment by neoprana** [comment]
**I hope it will be released some day.**

**Comment by WindingWinter** [comment]
Yes, please add it to VS 2022 for C# and C++ language especially.

**Comment by llodiaking** [comment]
Hello do have a date for VS2022

**Comment by RobinS-S** [comment]
Is this still on the radar? VS2022 has been out for more than 6 months.

**Comment by rnjv** [comment]
Looking forward to the release

**Comment by zaiby** [comment]
please add it for 2022

**Comment by goldsziggy** [comment]
Piling on here -- now that CoPilot is paid, I am also in the same dilemma and am looking for a paid solution.  Since CoPilot I've ran TabNine and CoPilot side-by-side in nvim for work, but only CoPilot in my Visual Studio 2022 for my personal projects (Unity).  Not offering it for VS 2022, simply edges out paid solution options to only CoPilot

**Comment by Amit-JoYo** [comment]
Unfortunately, without support in VS2022, we can't work with Tabnine, and we wish to add Tabnine to our toolset, 
Please add 2022 support.

**Comment by JoelVerm** [comment]
Coming from VSCode, I am sad I can't use Tabnine in VS2022. It is a very useful tool for speeding up development, so please add an extension for VS2022!

**Comment by phaussl** [comment]
TabNine support for VS2022 would be great! So please add me on your list of interested ones, please

**Comment by blueskycloud137** [comment]
Will you offer tabnine support for vs 2022?

**Comment by geramarenco** [comment]
![image](https://user-images.githubusercontent.com/47601701/218175660-132b3383-c813-41c7-8668-1b254690287f.png)

**Comment by maj113** [comment]
> However, we do plan to expand to VS 2022. If we'd see enough interest from the community, we will make sure such a plugin exists.

so then where is it, id say there's enough interest especially when VS 2019 is 4 years old

**Comment by MartinHock** [comment]
I am currently on a trail that ai will never be able to use because im using VS2022 Enterprise.
Pleas add VS 2022 support.

**Comment by LeanZo** [comment]
please add suport to VS 2022

**Comment by john-savepoint** [comment]
![image](https://user-images.githubusercontent.com/77978325/224082540-7f962eaf-fbd6-4e72-8182-703488168499.png)

**Comment by LemonNoCry** [comment]
please add suport to VS 2022

**Comment by kloklojul** [comment]
Our group will migrate to VS2022 soon and unfortunately we will be forced to move away from tabnine.

**Comment by TCNOco** [comment]
Yeah, I don't think this is happening. I have cancelled my subscription and with I could get the remaining balance back.
GitHub Copilot it is, and GitHub Copilot X in the future, I assume.

There are more and more AI coding assistant plugins weekly.

**Comment by dwerner-d** [comment]
I'm also waiting for VS2022 support of Tabnine. I'm involved in kind of AI benchmark and I can't consider Tabnine as long as it can't be integrated into VS2022.

**Comment by Przemek2122** [comment]
+ 1

**Comment by weiss-johannes** [comment]
Please Add it.

**Comment by hussain2dm** [comment]
You might be able to install it in VS 2022, follow these instructions: https://www.youtube.com/watch?v=R8IdXeCqtRk

**Comment by evgeshkastrong** [comment]
> [](https://www.youtube.com/watch?v=R8IdXeCqtRk)

dont waste time - this not working

**Comment by TzufTabnine** [comment]
As promised, VS 2022 extension is now available as a Beta. See [here](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-visual-studio). Please do share your thoughts with us.

**Comment by amolwankhede** [comment]
![Screenshot 2023-08-09 173759](https://github.com/codota/TabNine/assets/2176575/355e8540-dbb5-4da5-bffc-5e7289c52398)

**Comment by amolwankhede** [comment]
what are the prequisites?

**Comment by amolwankhede** [comment]
![image](https://github.com/codota/TabNine/assets/2176575/441a4074-d70d-49c8-8816-90e00cfd4ba0)

**Comment by amolwankhede** [comment]
from the logs 
![image](https://github.com/codota/TabNine/assets/2176575/6f0eda5a-ce73-4d72-b085-da514d6dca46)

**Comment by amolwankhede** [comment]
![image](https://github.com/codota/TabNine/assets/2176575/52e4beb9-6102-49f4-9cda-c835903cfbf9)
