### ISSUE TITLE
Estimates are wrong

### ISSUE THREAD

**Issue by durancanyilmaz** [codota/TabNine#477]
- OS version: Win 10
 - Editor: Atom editor
 - Editor version:	1.58
 - Programming language: php, html, js
 - TabNine extension version: 4.0.7
 - Engine version (could be located within Tabnine Hub):   4.0.4-46

Estimates are wrong. For example, when I want to create a div, it gives ridiculous results or completes the codes incompletely. So I have to write more code. Is the pro version like this too?

![image](https://user-images.githubusercontent.com/33418107/141777439-e61de25a-919b-4eff-b027-cc40fb9a3bdd.png)
![image](https://user-images.githubusercontent.com/33418107/141777538-8836bdf4-0a22-4e83-bafb-44b5ba44bc07.png)

![image](https://user-images.githubusercontent.com/33418107/141777789-d0c2d7e7-6030-4edc-87bf-c57ca033cf6a.png)
atom editor default foreach
![image](https://user-images.githubusercontent.com/33418107/141777846-750425f4-cb8d-49ce-8d6b-04d9188ffc8a.png)

gz#8762

**Comment by yonip23** [comment]
Hi @durancanyilmaz 
We're Sorry for the poor experience!
Looks like you're not receiving Tabnine's **deep** (i.e AI generated) completions, but only our "vanilla" completions - which can be thought of as a fallback source of completions. 
It can happen if you're working on a very small project / single file / file with no extension (i.e `.js` etc.) - is that the case by any chance?

In addition, to better understand what's going on, would be great if you could provide us with the following:
- Tabnine logs:
To get Tabnine’s log, in your IDE, open: Help -> Edit Custom Properties...
and insert:
`TABNINE_LOG_FILE_PATH=<some path to a file>`
Then restart IDE and wait for poor completions to re-appear.
After that, you should find the log file in the location you configured, in the following format: 
`<file name>_rCURRENT<extension>-<pid>` (for example, if my path is `/path/to/logs/log.txt`, I should find a file named `log_rCURRENT.txt-24360`)
- A screenshot of your "installation info" section from the Hub
- Your config file - the path of which can be found in the Hub->installation info->config file path

Kind regards,
Yoni

**Comment by durancanyilmaz** [comment]
Hi @yonip23 ,
```
Tabnine logs:
To get Tabnine’s log, in your IDE, open: Help -> Edit Custom Properties...
and insert:
TABNINE_LOG_FILE_PATH=<some path to a file>
```
Did you mean "config.cson" ? I dont have Edit Custom Properties in Atom editor.
![image](https://user-images.githubusercontent.com/33418107/141972705-a982d936-f041-4a79-9462-ba07fec406f8.png)

**Comment by yonip23** [comment]
@durancanyilmaz sorry for the wrong instructions, can you check if there are log files now in the path you set?
