### ISSUE TITLE
New transformer

### ISSUE THREAD

**Issue by LifeIsStrange** [codota/TabNine#480]
https://paperswithcode.com/paper/gn-transformer-fusing-sequence-and-graph

gz#8865

**Comment by maya-tabnine** [comment]
Hi!
I'm not sure I fully understand your request,
It would be great if you could provide some more info :)

**Comment by LifeIsStrange** [comment]
Well tabnine/codota is using neural networks to give smart autocompletion.
This paper is a new transformer in town that could improve accuracy.
Although the priority would be to use GPT-3
https://paperswithcode.com/sota/language-modelling-on-penn-treebank-word

Related: https://venturebeat.com/2021/11/18/openai-makes-gpt-3-generally-available-through-its-api/
