### ISSUE TITLE
Organic suggestions removed when TabNine is active

### ISSUE THREAD

**Issue by Foxhoundn** [codota/TabNine#483]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina] GitPod
 - Editor: [e.g. vscode, intelij, sublime]	VSCode Insiders
 - Editor version:	1.63.0-insider
 - Programming language: [e.g. js, ts, c++]	TypeScript
 - TabNine extension version: 3.5.1
 - Engine version (could be located within Tabnine Hub): 4.0.12-45

**Issue Details:**

Lately it's been very difficult to access organic suggestions from VSCode because the only suggestions coming up are TabNines (which have lately been very very bad, mostly one word random suggestions).

How can I make it so that the suggestions box has TabNine's suggestions also with organic VSCode suggestions.

As seen in the video below, the spread object has 4 known properties, which would be suggested by vscode, but unless [ESC] is pressed multiple times, they are supressed.

https://media.foxhoundn.me/EnObJ3KwHyGUCTd9jJM0

gz#9115

**Comment by Foxhoundn** [comment]
Here is a very **good** example:

There is clearly unused variable `retry` and I typed `r` - **retry** it should be the first thing I get - having to deal with simple stuff like that is not making my workflow faster by any chance. 

I am on the PRO plan, with the AI set to "Strength".

![CleanShot 2021-11-25 at 13 57 11](https://user-images.githubusercontent.com/8861481/143446287-d13fc0a5-6f63-4d0f-b06b-1b2c23b8200b.png)

**Comment by Foxhoundn** [comment]
Another example, but that just doesn't seem right...

![CleanShot 2021-11-26 at 11 33 22](https://user-images.githubusercontent.com/8861481/143567363-56fb57d9-86b1-461e-af82-674a2d12f033.png)

**Comment by Foxhoundn** [comment]
Nothing?

**Comment by maya-tabnine** [comment]
Hi! Sorry for the late response here
First, I am sorry to hear that you are not satisfied with the suggestions. What other settings do you have enabled in the hub?
And to your issue, did you try our inline suggestions feature? I think that can help.

**Comment by Foxhoundn** [comment]
> Hi! Sorry for the late response here
> First, I am sorry to hear that you are not satisfied with the suggestions. What other settings do you have enabled in the hub?
> And to your issue, did you try our inline suggestions feature? I think that can help.

Hi, sorry for the late reply - I tried every single possible setting - inline suggestions worked the best I think but I highlighted other problems with inline suggestions in the Feedback issue, problems that make it very hard to use inline suggestions.

**Comment by josersleal** [comment]
crap.. literally
I want my money back..

**Comment by matthew-plusprogramming** [comment]
I have the same issue
