### ISSUE TITLE
Shows partial support due to lack of FMA instructions support, but in the Tabnine Hub shows everything is fine

### ISSUE THREAD

**Issue by munchkindev** [codota/TabNine#484]
**please complete the following information:**	
 - OS version: Win 10	
 - Editor: VSCodium (that is open source VSCode)	
 - Editor version: 1.62.3
 - Programming language: C# (Razor page)	
 - TabNine extension version: 3.5.1
 - Engine version (could be located within Tabnine Hub):  4.0.9-46

**Issue Details:**
I have a i7-3720QM CPU which has no FMA or AVX2 instructions support. When I start VSCodium the taskbar after loading shows up with Partial support, click to resolve, but when I click on it it says inside the Tabnine Hub that it's ready to use.

gz#9174

**Comment by maya-tabnine** [comment]
Hi, would you attach a screenshot of your Tabnine Hub?

**Comment by munchkindev** [comment]
Hi, yes, of course. In the taskbar I see the following:
![grafik](https://user-images.githubusercontent.com/62607227/143868300-6740336c-4398-498c-961c-ac7a2bf7d511.png)
In the TabNine Hub:
![grafik](https://user-images.githubusercontent.com/62607227/143868445-1f5e3aa9-8ab5-4317-8399-e0252eda677e.png)

**Comment by maya-tabnine** [comment]
On the Coreinfo, it says it does not support FMA and AVX2?
You can try and use this link I found online to make sure: https://superuser.com/questions/1251865/is-there-a-way-to-tell-if-my-hardware-supports-specific-instructions 

Anyway, you can use the cloud model instead of the local if your instructions do not support them.

**Comment by munchkindev** [comment]
Both instructions are apparently not supported according to Coreinfo...

Isn't the cloud model for Pro users only and doesn't it share my code?

**Comment by maya-tabnine** [comment]
If you choose to use Tabnine Cloud, Tabnine will send blocks of code from your edited files to our server, allowing us to provide deep completion suggestions. 
These blocks of code will **Never** be stored - they are used to calculate predictions and then immediately discarded.

Also, it is a basic feature too! You have to sign in to use it, but you can be a free user.

**Comment by munchkindev** [comment]
I see, thank you!
