### ISSUE TITLE
Cyber Monday spam

### ISSUE THREAD

**Issue by braaannigan** [codota/TabNine#485]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
I've got a cyber monday thing flashing at me in VS code. I don't want to be marketed at like this when I'm trying to work, will remove tabnine if this happens again.

gz#9277

**Comment by maya-tabnine** [comment]
Hi
I apologize for the annoyance you experienced. That was not our intention.
I will pass on your complaint to our team right away! 
Thank you for reaching out to us about it.

**Comment by justinkruit** [comment]
And on Monday it was Cyber Monday, and now it's a bright yellow text "See Tabnine Insights". Stop this advertisement and let me work in peace. I even have pro for students and keep getting annoyed with these deals and CTAs.
