### ISSUE TITLE
TabNine does not work

### ISSUE THREAD

**Issue by Foxhoundn** [codota/TabNine#490]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	GitPod
 - Editor: [e.g. vscode, intelij, sublime] GitPod
 - Editor version: GitPod
 - Programming language: [e.g. js, ts, c++] TypeScript
 - TabNine extension version: 
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

TabNine does not work since ~ friday afternoon

![CleanShot 2021-12-05 at 12 28 00](https://user-images.githubusercontent.com/8861481/144744639-71202e1f-d7ee-464d-9e68-7a126fffca94.png)

no matter what project I open in GitPod, there are no suggestions from TabNine anywhere.

Tbh, it's been very very hard for me to justify what exactly I am getting for the $15 a month.

gz#9567

**Comment by bilucodota** [comment]
Hi @Foxhoundn thanks for reaching out. Sorry for the inconvenience. We're looking into it and will get back to you shortly.

**Comment by bilucodota** [comment]
@Foxhoundn seemed like we indeed had an issue on the beta channel. Can you please try to restart your `GitPod` workspace and see if it works now?

**Comment by Foxhoundn** [comment]
> @Foxhoundn seemed like we indeed had an issue on the beta channel. Can you please try to restart your `GitPod` workspace and see if it works now?

Will do, brb. Thanks.

**Comment by Foxhoundn** [comment]
@bilucodota Still looks the same.

**Comment by bilucodota** [comment]
The team is checking. At the meantime, shoot us an email to `support@tabnine.com` to get a compensation on the lost days.

**Comment by Foxhoundn** [comment]
> The team is checking. At the meantime, shoot us an email to `support@tabnine.com` to get a compensation on the lost days.

Thanks, I am not looking for compensation.

**Comment by yonip23** [comment]
Hi @Foxhoundn 
We're very sorry for this accident, we released a fix that goes as follows:
- refresh your ide once and you'll get a notification asking you to update to `9999.9999.9999-alpha.20211205132637`, which itself contains the desired fix. hit `reload` and:
- you'll get another notification asking you to update to `3.5.2` - once you hit the `reload` there you should be good to go.

Please let us know how did it go for you, and again, we're very sorry for all the hustle.
Kind regards

**Comment by yonip23** [comment]
@Foxhoundn after further checking we noticed that this process will not work for gitpod environment, only for a local one. we're still working on a fix for that, will update you asap.

Kind regards.

**Comment by Foxhoundn** [comment]
> @Foxhoundn after further checking we noticed that this process will not work for gitpod environment, only for a local one. we're still working on a fix for that, will update you asap.
> 
> Kind regards.

Hey, ok, waiting for instructions.

**Comment by yonip23** [comment]
@Foxhoundn We requested openvsx to remove version `9999.9999.9999` from the marketplace, unfortunately until then there's nothing much we can do about it.
In the meanwhile, If you'll disable inline suggestions you'll get Tabnine completions. We remember this issue you opened: https://github.com/codota/TabNine/issues/483 where inline suggestions was the solution we provided, but unfortunately this is the best solution we can offer at the moment.

We'll update here once this version is removed from the marketplace, so please follow here for updates.

Once again, we're very sorry for the inconvenience, and you're welcome to contact `support@tabnine.com` and get a compensation if you'll change your mind.

Kind regards

**Comment by Foxhoundn** [comment]
> @Foxhoundn We requested openvsx to remove version `9999.9999.9999` from the marketplace, unfortunately until then there's nothing much we can do about it. In the meanwhile, If you'll disable inline suggestions you'll get Tabnine completions. We remember this issue you opened: #483 where inline suggestions was the solution we provided, but unfortunately this is the best solution we can offer at the moment.
> 
> We'll update here once this version is removed from the marketplace, so please follow here for updates.
> 
> Once again, we're very sorry for the inconvenience, and you're welcome to contact `support@tabnine.com` and get a compensation if you'll change your mind.
> 
> Kind regards

I got the 3.5.2 version, worked for a little while and then again the `9999....` after a reload.

**Comment by Foxhoundn** [comment]
> > @Foxhoundn We requested openvsx to remove version `9999.9999.9999` from the marketplace, unfortunately until then there's nothing much we can do about it. In the meanwhile, If you'll disable inline suggestions you'll get Tabnine completions. We remember this issue you opened: #483 where inline suggestions was the solution we provided, but unfortunately this is the best solution we can offer at the moment.
> > We'll update here once this version is removed from the marketplace, so please follow here for updates.
> > Once again, we're very sorry for the inconvenience, and you're welcome to contact `support@tabnine.com` and get a compensation if you'll change your mind.
> > Kind regards
> 
>Today  I got the 3.5.2 version, worked for a little while and then again the `9999....` after a reload.

**Comment by SimSimY** [comment]
Hey @Foxhoundn 

Just letting you know that we are still waiting for the [removal of the version](https://github.com/EclipseFdn/open-vsx.org/issues/776) from the marketplace. 

I understand your frustration, and would really like to refund you for the month, however I don't have your email address in order to do so. Please send us an email with the email you've used for TabNine's pro account and I'll personally take care of that.

**Comment by Foxhoundn** [comment]
@SimSimY 

Hey, yeah I know I've been checking it myself. 

The email I used for TabNine is `dive-01-guided@icloud.com`

**Comment by SimSimY** [comment]
@Foxhoundn 

I've just got ping that the broken plug in version was removed, So a restart to the GitPod should resolve the issue 🤞

Also, I would be happy to know if this helps with your other issue - https://github.com/codota/TabNine/issues/483

Check your email regarding the refund.

**Comment by Foxhoundn** [comment]
> @Foxhoundn
> 
> I've just got ping that the broken plug in version was removed, So a restart to the GitPod should resolve the issue 🤞
> 
> Also, I would be happy to know if this helps with your other issue - #483
> 
> Check your email regarding the refund.

Hey,

I can confirm I was able to get the 3.5.5 version, thank you very much.

Regarding #483, I turned on Inline Suggestions with empty line suggestions etc, and I can confirm that it kind of improved the workflow. Inline suggestions bring other complexities though', which I reported in the Inline Suggestions feedback issue (mainly when I select something from the suggestion box that is not TabNine, it should be accepted, not the inline TabNine suggestion).

You can check this video I just made, which explains it better than my English, I believe:
https://media.foxhoundn.me/REhP1Gqc7ySqjlshuKI1

**Comment by Foxhoundn** [comment]
I replied to every email but it seems my emails have not been getting through? @SimSimY 

![image](https://user-images.githubusercontent.com/8861481/145998766-ff5544ce-755f-46f0-9c57-221d0313424f.png)

**Comment by maya-tabnine** [comment]
Hi @Foxhoundn , your emails must not have gotten through to us.
You can contact me at tabnine.team@gmail.com, and we will sort it out there.

**Comment by josersleal** [comment]
craaaaaaap!
