### ISSUE TITLE
How to remove tabnine recommendations

### ISSUE THREAD

**Issue by daveteu** [codota/TabNine#491]
How to remove,  e.g. useless completion like this?

<img width="829" alt="image" src="https://user-images.githubusercontent.com/18649392/144982453-279b43de-0ee1-4dc3-864e-be6550374a50.png">

PS: couldn't find the right place to ask (StackOverflow doesn't get any replies either).

OS: macOS
Application: VS Code

gz#9644

**Comment by maya-tabnine** [comment]
Hi!
In VSCode, you should be able to disable "comments" suggestions 
by adding the following configuration  to your vscode settings.json file:

```
"editor.quickSuggestions": {
 "other": true,
 "comments": false,
 "strings": true
 },
```

Does it solve your issue?

**Comment by daveteu** [comment]
unfortunately not..

**Comment by maya-tabnine** [comment]
That should work for VSCode in general.. I looked online for other options and found this https://github.com/microsoft/vscode/issues/9504 , maybe it can be helpful.

Anyway, You can try disabling Tabnine in lines that contain specific strings.
You need to define Disable_line_regex in Tabnine plugin settings
![image](https://user-images.githubusercontent.com/82452749/146178393-3a27291a-436e-4dae-9170-8c1e7c1524af.png)

**Comment by hardianlawi** [comment]
I'm having similar issue here.

It's really annoying when you need to write long comments/strings and need to keep pressing escape before enter. 😥

Tried the solution above but not working

**Comment by ricardo-coverwallet** [comment]
Every time I'm writing a python function, just after typing ":" I receive this recommendation "\n". I really don't know why and it's very annoying. It would be awesome to be able to tag specific recommendations to don't appear anymore.

**Comment by deZak** [comment]
> Every time I'm writing a python function, just after typing "):" I receive this recommendation "\n". I really don't know why and it's very annoying. It would be awesome to be able to tag specific recommendations to don't appear anymore.
> 
> This is an example: `def function(param1, param2): "\n"`

VS Code was suggesting suggestions for React in non-React projects. Below option resolved my issue.
Settings >  Suggestions > Word Based Suggestions Mode > select "current document" from dropdown.

**Comment by alaminuixd** [comment]
There are Tabnine suggestions above each line of code.
suggestions: tabnine:test | explain | document | ask
Can I turn this off?

**Comment by AhmadNadeemS** [comment]
> abnine:test | explain | document | ask

Did you find a way?

**Comment by SamuelOliveiraa** [comment]
Guys i know how to turn off the suggestions above each line code in Vs Code.

i found this website that explains: https://support.tabnine.com/hc/en-us/articles/20951637600273-Enable-Disable-Code-Lens-in-VS-Code-and-JetBrains

But is simples, is only goes to your configurations of Vs Code and search for Code lens and check/uncheck the box.

**Comment by skarnl** [comment]
> Guys i know how to turn off the suggestions above each line code in Vs Code.
> 
> i found this website that explains: https://support.tabnine.com/hc/en-us/articles/20951637600273-Enable-Disable-Code-Lens-in-VS-Code-and-JetBrains
> 
> But is simples, is only goes to your configurations of Vs Code and search for Code lens and check/uncheck the box.

Yes, this works in PhpStorm (Jetbrains)! I had already unchecked that box ... but you have to reopen the file you are working in... otherwise the suggestions stay visible 🤔

**Comment by 67abraham** [comment]
Enter setting and disabled the Code Lens Enabled  options.
U are good to go.

![Image](https://github.com/user-attachments/assets/6100c817-a690-47c8-a77a-43829eedfd71)

**Comment by msarfrazk** [comment]
Ok
