### ISSUE TITLE
Model Status Download always Pending

### ISSUE THREAD

**Issue by NeoHBz** [codota/TabNine#492]
**please complete the following information:**	
 - OS version: MacOS Monterey (MBA M1)
 - Editor: vscode
 - Editor version: VSCode Version: 1.62.3 (Universal)
 - Programming language: js
 - TabNine extension version: 3.5.3
 - Engine version (could be located within Tabnine Hub): 4.0.23-46

**Issue Details:**
TabNine Model Status download is always pending. I plug-in my laptop and it disappears but when my laptop is not charging, it appears back again.
PS: I'm on a 100MBPS connection and my laptop is on plugged in for at least 2-3 hours every 2-3 days.

![image](https://user-images.githubusercontent.com/56602090/145085359-102b6828-b4c1-4c77-b87a-01121113b06f.png)

gz#9671

**Comment by maya-tabnine** [comment]
Hi!
Can you try to install the model manually from:
https://update.tabnine.com/models/ce94127b
Add a ".tabninemodel" extension to the downloaded file and place the file in the following path on MacOS: /Users/{UserName}/Library/Application Support/TabNine/models/

Then restart your IDE.
Let me know if that works for you.

**Comment by NeoHBz** [comment]
> Hi! Can you try to install the model manually from: https://update.tabnine.com/models/ce94127b Add a ".tabninemodel" extension to the downloaded file and place the file in the following path on MacOS: /Users/{UserName}/Library/Application Support/TabNine/models/
> 
> Then restart your IDE. Let me know if that works for you.

Hi, I'm not able to open your given link, it link opens a browser tab and closes without triggering any action/warning/download.
Thank you for your time.

**Comment by maya-tabnine** [comment]
Are you sure? I just checked the link.
Try opening it in a new window, and then refresh the page.
It should download the model file for you.
And of course, we are here to help! Let me know if that works for you.

**Comment by NeoHBz** [comment]
> @NeoHBz Are you sure? I just checked the link. Try opening it in a new window, and then refresh the page. It should download the model file for you. And of course, we are here to help! Let me know if that works for you.

Ah, my bad, it did start downloading in incognito, however, when I opened the specified TabNine/models folder, there was already a file with the same filename+extension+size that you made me download. Regardless, I replaced it, and I'll report it in a while.
Thank you for your help :)

**Comment by NeoHBz** [comment]
> @NeoHBz Are you sure? I just checked the link. Try opening it in a new window, and then refresh the page. It should download the model file for you. And of course, we are here to help! Let me know if that works for you.

okay so I did just that and, 
![image](https://user-images.githubusercontent.com/56602090/145717621-780af9b0-16cf-499f-a237-8341e3e91293.png)

btw, I noticed that TabNine has updated itself 
![image](https://user-images.githubusercontent.com/56602090/145717640-8865cb97-e484-48de-8d4f-e0a5b6e7fecd.png)

**Comment by maya-tabnine** [comment]
Hi, thanks for the attached screenshots that helps a lot
Will you try to disable the Deep Completions Local, restart your VSCode, and then enable it?

Another quick question, do you use WSL with VSCode?

**Comment by akvsak** [comment]
> Hi! Can you try to install the model manually from: https://update.tabnine.com/models/ce94127b Add a ".tabninemodel" extension to the downloaded file and place the file in the following path on MacOS: /Users/{UserName}/Library/Application Support/TabNine/models/
> 
> Then restart your IDE. Let me know if that works for you.

Hi, As of 26 JUN 2022, is the above link still applicable for the latest model or has it changed? Thanks.
