### ISSUE TITLE
unable to log in

### ISSUE THREAD

**Issue by olets** [codota/TabNine#493]
**please complete the following information:**	
 - OS version: macOS 11.6.1 (20G224)
 - Editor: VS Code
 - Editor version:
    Version: 1.63.0-insider
    Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
 - Programming language: any
 - TabNine extension version: 3.5.3
 - Engine version (could be located within Tabnine Hub): 4.0.23-40

**Issue Details:**

Just realized I'm not logged in. Didn't know that I might get logged out silently. Don't know how many billing cycles I've been using the free version for — I might have been logged out minutes after I first upgraded to a paid account.

When I try to log in I get a variety of errors:
- in Chrome the loading animation sometimes runs forever
- in Chrome I sometimes get "Seems like we are having trouble loading your configuration"
    ![image](https://user-images.githubusercontent.com/3282350/145118952-bba96dfb-bfab-4d80-a6f8-d7153bd7e4f6.png)
- in Firefox I sometimes get the styled error "NetworkError when attempting to fetch resource." in the login box
    ![image](https://user-images.githubusercontent.com/3282350/145119102-6af56a8e-7be2-47c3-beb1-060d587b0fc0.png)
- in Chrome and Firefox if I get a "login" button it doesn't work
- in Chrome and Firefox I get many console errors

<details><summary>Click to see sample Firefox console errors</summary>
<pre><code>
Some cookies are misusing the recommended “SameSite“ attribute 15
XHRGEThttps://sa.tabnine.com/api/secure-access/frontegg/metadata?entityName=adminBox
[HTTP/2 502 Bad Gateway 0ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/metadata?entityName=adminBox. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

failed to get admin portal metadata TypeError: NetworkError when attempting to fetch resource. 655.production.d3935b26d480e95a033e.chunk.js:2:780610
getSSOPublicConfiguration() 655.production.d3935b26d480e95a033e.chunk.js:2:780610
getVendorPublicInfo() 655.production.d3935b26d480e95a033e.chunk.js:2:780610
refreshToken() 655.production.d3935b26d480e95a033e.chunk.js:2:780610
getSocialLoginProviders() 655.production.d3935b26d480e95a033e.chunk.js:2:780610
getVendorConfig() 2 655.production.d3935b26d480e95a033e.chunk.js:2:780610
XHROPTIONShttps://sa.tabnine.com/api/secure-access/frontegg/identity/resources/sso/v1
CORS Missing Allow Origin

Error: The domain APP.TABNINE.COM is not authorized to show the cookie banner for domain group ID 7bc3da84-600f-46a0-be06-15c33fe2dfac. Please add it to the domain group in the Cookiebot Manager to authorize the domain. 655.production.d3935b26d480e95a033e.chunk.js:2:780610
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 2
The resource at “https://app.tabnine.com/da9b71fb77bddc90b29d536878e724ba.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/38d9dbe3269d8e9efbfbc368773cd71c.woff” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/68d0a92d6427b1a61a66e4b450706109.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/a9c55cacbc92846fcbc8b44466407068.woff” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/4c55c64340ba1a5e21138914f61df73b.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/4518430c6c718e8fe0806859f4a5ff75.woff” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/afe83b5ce3ed735aa803ee8bd2bed11d.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
The resource at “https://app.tabnine.com/17996c6a7da05dd84a4127d7f4b8ffc9.woff” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. login
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/sso/v1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/sso/v1. (Reason: CORS request did not succeed).

XHRGEThttps://sa.tabnine.com/api/secure-access/frontegg/metadata?entityName=saml
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/metadata?entityName=saml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

TypeError: NetworkError when attempting to fetch resource. 655.production.d3935b26d480e95a033e.chunk.js:2:780610
XHRGEThttps://sa.tabnine.com/api/secure-access/frontegg/team/resources/sso/v2/configurations/public
CORS Missing Allow Origin

TypeError: NetworkError when attempting to fetch resource. 655.production.d3935b26d480e95a033e.chunk.js:2:780610
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/team/resources/sso/v2/configurations/public. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

XHRPOSThttps://sa.tabnine.com/api/secure-access/frontegg/identity/resources/auth/v1/user/token/refresh
[HTTP/2 502 Bad Gateway 14412ms]

XHRGEThttps://sa.tabnine.com/api/secure-access/frontegg/vendors/public
[HTTP/2 404 Not Found 0ms]

failed to getVendorPublicInfo -  Error: The requested URL was not found on this server.
    o https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    u https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    a https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    promise callback*u https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    a https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    promise callback*u https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    a https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    promise callback*u https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    a https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    promise callback*u https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    n https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    n https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    u https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    l https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    n https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    n https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    l https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    getVendorPublicInfo https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    n https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    n https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    getVendorPublicInfo https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    b https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    g https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    U https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    a.C https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    c https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    h https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    7/D[a.A]/< https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    a.A https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
    c https://app.tabnine.com/655.production.d3935b26d480e95a033e.chunk.js:2
655.production.d3935b26d480e95a033e.chunk.js:2:780610
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/auth/v1/user/token/refresh. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

XHROPTIONShttps://sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public. (Reason: CORS request did not succeed).

XHRGEThttps://sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public
[HTTP/2 404 Not Found 11981ms]

GEThttps://c.1password.com/richicons/images/login/120/my.tabnine.com.png
[HTTP/2 404 Not Found 242ms]

The resource at “moz-extension://5d8efaf7-34cc-8447-86f3-691ecdd53ba2/inline/fonts/Inter-italic.var.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. menu.html
GEThttps://c.1password.com/richicons/images/login/120/my.tabnine.com.png
[HTTP/2 404 Not Found 149ms]

login() 655.production.d3935b26d480e95a033e.chunk.js:2:780610
XHRPOSThttps://sa.tabnine.com/api/secure-access/frontegg/identity/resources/auth/v1/user
[HTTP/2 502 Bad Gateway 20869ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/auth/v1/user. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
</code></pre>
​</details>

<details><summary>Click to see sample Chrome console errors</summary>
<pre><code>
X-Frame-Options may only be set via an HTTP header sent along with a document. It may not be set inside <meta>.
655.production.d3935b26d480e95a033e.chunk.js:2 Error: The domain APP.TABNINE.COM is not authorized to show the cookie banner for domain group ID 7bc3da84-600f-46a0-be06-15c33fe2dfac. Please add it to the domain group in the Cookiebot Manager to authorize the domain.
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
overrideMethod @ VM346 react_devtools_backend.js:2540
(anonymous) @ consent.cookiebot.co…e&forceshow=false:1
o522159.ingest.sentry.io/api/5633241/envelope/?sentry_key=62ea7eaf6289479ebc294e88fdc80c4f&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 ()
8The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
sa.tabnine.com/api/secure-access/frontegg/identity/resources/auth/v1/user/token/refresh:1 Failed to load resource: the server responded with a status of 401 ()
sa.tabnine.com/api/secure-access/frontegg/vendors/public:1 Failed to load resource: the server responded with a status of 404 ()
655.production.d3935b26d480e95a033e.chunk.js:2 failed to getVendorPublicInfo -  Error: The requested URL was not found on this server.
    at 655.production.d3935b26d480e95a033e.chunk.js:2
    at Generator.next (<anonymous>)
    at a (655.production.d3935b26d480e95a033e.chunk.js:2)
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
overrideMethod @ VM346 react_devtools_backend.js:2540
b @ 655.production.d3935b26d480e95a033e.chunk.js:2
g @ 655.production.d3935b26d480e95a033e.chunk.js:2
u @ 655.production.d3935b26d480e95a033e.chunk.js:2
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
login:1 Access to fetch at 'https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/public' from origin 'https://app.tabnine.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/public:1 Failed to load resource: net::ERR_FAILED
login:1 Access to fetch at 'https://sa.tabnine.com/api/secure-access/frontegg/team/resources/sso/v2/configurations/public' from origin 'https://app.tabnine.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
sa.tabnine.com/api/secure-access/frontegg/team/resources/sso/v2/configurations/public:1 Failed to load resource: net::ERR_FAILED
655.production.d3935b26d480e95a033e.chunk.js:2 TypeError: Failed to fetch
    at 655.production.d3935b26d480e95a033e.chunk.js:2
    at 655.production.d3935b26d480e95a033e.chunk.js:2
    at Generator.next (<anonymous>)
    at a (655.production.d3935b26d480e95a033e.chunk.js:2)
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
overrideMethod @ VM346 react_devtools_backend.js:2540
Pt @ 655.production.d3935b26d480e95a033e.chunk.js:2
g @ 655.production.d3935b26d480e95a033e.chunk.js:2
u @ 655.production.d3935b26d480e95a033e.chunk.js:2
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
655.production.d3935b26d480e95a033e.chunk.js:2 Error: metadata not found: saml
    at 655.production.d3935b26d480e95a033e.chunk.js:2
    at Generator.next (<anonymous>)
    at a (655.production.d3935b26d480e95a033e.chunk.js:2)
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
overrideMethod @ VM346 react_devtools_backend.js:2540
Tt @ 655.production.d3935b26d480e95a033e.chunk.js:2
g @ 655.production.d3935b26d480e95a033e.chunk.js:2
u @ 655.production.d3935b26d480e95a033e.chunk.js:2
(anonymous) @ 655.production.d3935b26d480e95a033e.chunk.js:2
sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public:1 Failed to load resource: the server responded with a status of 404 ()
login:1 Access to fetch at 'https://sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public' from origin 'https://app.tabnine.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
sa.tabnine.com/api/secure-access/frontegg/identity/resources/configurations/v1/captcha-policy/public:1 Failed to load resource: net::ERR_FAILED
bc-v3.min.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
box-a1ae2079824d1c48aa9ce06efb256f18.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
login:1 Unchecked runtime.lastError: The message port closed before a response was received.
</code></pre>

gz#9680

**Comment by maya-tabnine** [comment]
Hi!
Is the issue still happening?

**Comment by olets** [comment]
I am now able to log in!

Do you have any way to tell how long I was logged out?

**Comment by maya-tabnine** [comment]
We had an issue that was fixed. It was a matter of a few hours until it was resolved :)

**Comment by olets** [comment]
I think that's how long manual log in attempts weren't working, right? Do you have any way to tell when I was first logged out?

I don't think I've looked at the plugin preferences window since upgrading. That was in April. Now that I know it's possible to be logged out involuntarily, I wonder how long I've been paying for the pro level but only getting the free level.

Related, in VS Code currently the "Accounts" feature shows me as logged into tabnine, but then it also is prompting me to sign in with tabnine.

**Comment by MarkoShiva** [comment]
I have same issue @maya-tabnine as I specified in the email corespondence.

**Comment by olets** [comment]
Couple weeks later, still wondering about this. Thanks!

**Comment by olets** [comment]
Hi @maya-tabnine hoping to resolve this.

Do you folks have any way to tell when between April and December TabNine logged me out?

Please let me know the process for disputing payment.

**Comment by VidarDev** [comment]
So if i klick here

![fUMhjUF](https://user-images.githubusercontent.com/98586665/155382753-1352bff8-3ccb-4a69-be06-d38f87b7d039.png)

its dont stop loading Site

![l5mdErm](https://user-images.githubusercontent.com/98586665/155382892-b9051b9b-e626-4c8f-b4a1-efa33a75bfc8.png)

if i klick here

![OWuAU86](https://user-images.githubusercontent.com/98586665/155383127-91cc2f54-d788-406a-b756-00c183535f51.png)

then i'am logged in

![WjgajKf](https://user-images.githubusercontent.com/98586665/155382981-428cb335-2fe3-4bf9-a6e3-06a0a715c773.png)

Confused!?

**Comment by olets** [comment]
Still haven't heard anything. I've followed up with billing@tabnine.com

**Comment by KiligFei** [comment]
我也有同样的问题，登录不上
![image](https://user-images.githubusercontent.com/69230517/155917202-6085ba6b-a8d5-4b6f-b196-2fd04f25fd5a.png)
点击这里没法登录

**Comment by olets** [comment]
This was resolved quickly when I switched to emailing billing@tabnine.com instead of waiting for a response in GitHub, thanks Maya!

Sounds like email hasn't worked for everyone who's tried (https://github.com/codota/TabNine/issues/493#issuecomment-994487564), but it's worth trying.
