### ISSUE TITLE
When will the Chinese translation version be released?

### ISSUE THREAD

**Issue by one-zen** [codota/TabNine#494]
**please complete the following information:**	
 - OS version: [Mac Bigsur]	
 - Editor: [vscode]	
 - Editor version:	1.63
 - Programming language: [js, ts, html, css]	
 - TabNine extension version: 3.5.4
 - Engine version (could be located within Tabnine Hub): 4.0.23-42

**Issue Details:**
I am a front-end developer from China and a paying user of yours. This is the smartest code prompt completion plugin I have ever used. Given that there are a large number of developers in China, when will a Chinese translation version be released?

gz#9783

**Comment by maya-tabnine** [comment]
Hi
We’re not working on that, and it may not happen, but I’ll pitch it to the team and see what they think.
If you have any other questions, I’ll be happy to help.
