### ISSUE TITLE
Tabnine Hub preferences: checkbox labels not linked to checkboxes

### ISSUE THREAD

**Issue by micgro42** [codota/TabNine#495]
**please complete the following information:**	
 - OS version: N/A
 - Editor: N/A
 - Editor version:	N/A
 - Programming language: N/A
 - TabNine extension version: 0.5.3
 - Engine version (could be located within Tabnine Hub): 4.0.30-42

**Issue Details:**
Clicking the labels of options on the preferences page does not toggle the associated checkboxes. Those things:
![image](https://user-images.githubusercontent.com/7372507/146204193-5dbd47e3-de53-4611-b980-7cf574499fe4.png)

The reason is that you put the text next to the actual label in your HTML. The `<span>` belongs _inside_ the `<label>`:

![image](https://user-images.githubusercontent.com/7372507/146204326-af00cdbc-6163-43d3-819a-f717cd3d0245.png)

You can read more about this here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

gz#10025

**Comment by micgro42** [comment]
What exactly is the meaning of `gz#10025` that was appended to the description of this issue by @Tabnineteam?

**Comment by bilucodota** [comment]
Thanks for reaching out. I'll add it to the backlog.
The ticket number you see is added automatically by our ticketing management system.
