### ISSUE TITLE
Does tabnine require AVX512 support?

### ISSUE THREAD

**Issue by nukewarrior** [codota/TabNine#496]
Does tabnine require AVX512 support?
I run into some problems while installing tabnine for my jupyterlab instance on my mini-server(with Intel G5420)

gz#10128

**Comment by bilucodota** [comment]
Hi @nukewarrior 
Tabnine requires AVX2 instruction set. As far as I understand, the `G5420` lacks of this support.
Note that as a registered user, you can activate Tabnine Deep Completions Cloud which offloads the computation to Tabnine GPU accelerated servers.

**Comment by nukewarrior** [comment]
> Hi @nukewarrior Tabnine requires AVX2 instruction set. As far as I understand, the `G5420` lacks of this support. Note that as a registered user, you can activate Tabnine Deep Completions Cloud which offloads the computation to Tabnine GPU accelerated servers.

Thx for the reply:)
