### ISSUE TITLE
Inline Completions Set Visual Mode on Vim

### ISSUE THREAD

**Issue by matthew-plusprogramming** [codota/TabNine#497]
**please complete the following information:**	
 - OS version: Win 10 WSL	
 - Editor: vscode	
 - Editor version:	
 - Programming language: ts	
 - TabNine extension version: 3.5.11
 - Engine version (could be located within Tabnine Hub): 4.0.37-39

**Issue Details:**
Whenever I hit tab on an inline completion, it turns my VSCode vim mode from Normal to Visual requiring me to hit esc multiple times to start editing again. This issue has been cited by many individuals in many different instances. The conflicting extension is also very widespread within the vscode community with over 3,000,000 downloads.

Conflicting Extension:
https://marketplace.visualstudio.com/items?itemName=vscodevim.vim 

gz#10247

**Comment by matthew-plusprogramming** [comment]
Other cited instances:
> it seems will quit edit mode and turn to visual mode with vsocde vim in some cases
> _Originally posted by @xuzhanhh in https://github.com/codota/TabNine/issues/432#issuecomment-904526849_

> same for me, but almost all time
> _Originally posted by @lastgosumatt in https://github.com/codota/TabNine/issues/432#issuecomment-906199227_

> Yes, almost all the time here too.
> _Originally posted by @Mattiaslndstrm in https://github.com/codota/TabNine/issues/432#issuecomment-906377070_

> What I personally noticed is that the inline completetions aren't really compatible with the vscode vim plugin (`vscodevim.vim`). When using a suggested completion by pressing tab, the vim plugin will go into visual mode, the vim cursor stays at the last typed character but a "normal", thin cursor will appear at the end of the completed code. This is quite an annoyance as you can't keep typing but instead need to spam esc to get back into normal mode and then move your cursor to the end again and go into insert mode before you can start typing again.
> _Originally posted by @hugohabicht01 in https://github.com/codota/TabNine/issues/432#issuecomment-908231878_

> Same here
> _Originally posted by @AliXEagle in https://github.com/codota/TabNine/issues/432#issuecomment-930157331_

**Comment by maya-tabnine** [comment]
Hi! We received a few complaints regarding this error, and it is being fixed now by our developers.
Once a fix is released, we will update at https://github.com/codota/TabNine/issues/432

**Comment by matthew-plusprogramming** [comment]
This is a temporary workaround: https://github.com/codota/TabNine/issues/432#issuecomment-1064936875

**Make sure to install the multi-command extension**

**Comment by LeshemNoa** [comment]
Hey @matthew-plusprogramming, 
We just released a fix for this issue with version 3.5.49. We'd appreciate it if you could try it out and let us know what you think.

**Comment by matthew-plusprogramming** [comment]
On an unrelated issue, my tabnine is constantly glitching out vscode which is making it unusable. Whenever I start typing, the cursor starts jumping around and deleting random text. This occurs with or without the vim extension enabled

**Comment by milesxu** [comment]
> Hey @matthew-plusprogramming, We just released a fix for this issue with version 3.5.49. We'd appreciate it if you could try it out and let us know what you think.

I use the version of 3.6.14 which has the exactly same issue.

**Comment by JoabBelmont** [comment]
> I use the version of **3.6.14** which has the exact same issue.

Same problem.

**Comment by drye** [comment]
3.6.15 still has this issue.

**Comment by wl-junlin** [comment]
> Hey @matthew-plusprogramming, We just released a fix for this issue with version 3.5.49. We'd appreciate it if you could try it out and let us know what you think.

still have the issue, when using Tabnine in ssh remote, and vim in local editor

**Comment by Lukashku** [comment]
How is this still an issue? I have the newest VSCode, Tabnine, and VIM extensions and still have the annoying tab complete issue that switches from insert to visual mode every single time

**Comment by hiber-niu** [comment]
> > I use the version of **3.6.14** which has the exact same issue.
> 
> Same problem.

Same problem.

**Comment by VictorBelikov** [comment]
**v3.6.31** still has this issue.

**Comment by gldanoob** [comment]
TabNine closes the autosuggestion widget by triggering the escape key, so it also goes out of Vim's insert mode.
Add this to your `keybindings.json` to disable it:
```json
{
        "key": "tab",
        "command": "-tabnine.tab-override",
        "when": "suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
},
```

**Comment by tommdq** [comment]
Any update on this issue?

**Comment by ZhenWZ** [comment]
I was having the same problem and I tried the solution [#432 (comment)](https://github.com/codota/TabNine/issues/432#issuecomment-1064936875) but with no results. So I modified it to the following and added them to `keybinding.json`, which worked for me. 

```
{
    "key": "tab",
    "command": "extension.multiCommand.execute",
    "args": {
      "sequence": [
        "toggleVim",
        "tabnine.tab-override",
        "toggleVim",
        "extension.vim_insert",
      ],
      "interval": 50, 
    },
    "when": "vim.active && suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
},
{
    "key": "tab",
    "command": "-tabnine.tab-override",
    "when": "vim.active && suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
},
```
**Note that the multi-command extension is required.**

Hope it helps!

**Comment by paulopicasso** [comment]
> I was having the same problem and I tried the solution [#432 (comment)](https://github.com/codota/TabNine/issues/432#issuecomment-1064936875) but with no results. So I modified it to the following and added them to `keybinding.json`, which worked for me.
> 
> ```
> {
>     "key": "tab",
>     "command": "extension.multiCommand.execute",
>     "args": {
>       "sequence": [
>         "toggleVim",
>         "tabnine.tab-override",
>         "toggleVim",
>         "extension.vim_insert",
>       ],
>       "interval": 50, 
>     },
>     "when": "vim.active && suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
> },
> {
>     "key": "tab",
>     "command": "-tabnine.tab-override",
>     "when": "vim.active && suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
> },
> ```
> 
> **Note that the multi-command extension is required.**
> 
> Hope it helps!

Thanks! It worked.

**Comment by alghenab** [comment]
> I was having the same problem and I tried the solution [#432 (comment)](https://github.com/codota/TabNine/issues/432#issuecomment-1064936875) but with no results. So I modified it to the following and added them to `keybinding.json`, which worked for me.
> 
> ```
> {
>     "key": "tab",
>     "command": "extension.multiCommand.execute",
>     "args": {
>       "sequence": [
>         "toggleVim",
>         "tabnine.tab-override",
>         "toggleVim",
>         "extension.vim_insert",
>       ],
>       "interval": 50, 
>     },
>     "when": "vim.active && suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
> },
> {
>     "key": "tab",
>     "command": "-tabnine.tab-override",
>     "when": "vim.active && suggestWidgetHasFocusedSuggestion && suggestWidgetVisible && tabnine.tab-override && textInputFocus"
> },
> ```
> 
> **Note that the multi-command extension is required.**
> 
> Hope it helps!

Thanks, this worked for me.
