### ISSUE TITLE
Feature Request: Client Cookies

### ISSUE THREAD

**Issue by tzachar** [codota/TabNine#498]
Hi.

I am the author of [tzachar/cmp-tabnine](https://github.com/tzachar/cmp-tabnine).
As `nvim-cmp` is asynchronous, the communication with the TabNine process can get out of sync sometimes, especially when `nvim-cmp` fires many consecutive completion requests, without waiting for results.

For now, we try to ignore all but the last, but the implementation is flaky. A better solution would be if TabNine would accept a user supplied cookie (a string), and return the same cookie when giving suggestions.

For example, the following API change will completely solve the problem:
```
AutocompleteArgs {
  before: string,
  after: string,
  filename: string | null,
  region_includes_beginning: bool,
  region_includes_end: bool,
  max_num_results: int | null,
  client_cookie: string   <---- new addition
}

AutocompleteResponse {
  old_prefix: string,
  results: ResultEntry[],
  user_message: string[],
  client_cookie: string  <---- new addition
}
```

where `client_cookie` should match between a request and an answer.

Any client not interested in the cookie can just ignore it and not set it.
What do you guys think? Any chance getting something like this merged?

gz#10347

**Comment by dimacodota** [comment]
Hi @tzachar 👋 , it is already supported, you can use the `correlation_id` field which will be  returned in the response. Great job with the cpm-tabnine 💪  feel free to contact  us for any further questions

**Comment by tzachar** [comment]
Amazing :)

Is this documented anwhere?

**Comment by dimacodota** [comment]
documentation added [here](https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md#api-types)

**Comment by tzachar** [comment]
Thank you 👍
