### ISSUE TITLE
Tabnine is not able to function properly.

### ISSUE THREAD

**Issue by suuforest** [codota/TabNine#501]
Tabnine is not able to function properly. Error on PHPStorm. 
----
Exceptions:

Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:64)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.capabilities.CapabilitiesService.fetchCapabilities(CapabilitiesService.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:64)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.lifecycle.BinaryNotificationsLifecycle$poll$1.run(BinaryNotificationsLifecycle.kt:26)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:64)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.statusBar.StatusBarUpdater.requestStatusBarMessage(StatusBarUpdater.kt:38)
	at com.tabnine.lifecycle.BinaryPromotionStatusBarLifecycle$poll$$inlined$timerTask$1.run(Timer.kt:149)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

gz#10702

**Comment by maya-tabnine** [comment]
Hi! This is probably a bug.

Can you fill out the following information needed in the ticket: 
OS version, Editor, Editor version,Programming language: [e.g. js, ts, c++], TabNine extension version, Engine version.
And a question, do you have inline completion enabled?

Also, can you share your plugin and binary logs? And your config file too?
Go to help > show log in finder/explorer to get your IDE log file. 

For binary logs, please open: Help -> Edit Custom Properties... and insert:
`TABNINE_LOG_FILE_PATH=<some path to a file>`
Then restart IDE and wait for the problem to happen.
Then, you’ll find a file named `filename_rCURRENT.ext-<pid>` in the given directory.

**Comment by suuforest** [comment]
Current i can not access into settings of Tabnine.
I run on PHPStorm 2021.3.1. OS Win 11. Tabnine version 0.5.11

Logs

INFO [auth::token] [2022-01-10:11:26:39 TabNine.exe INFO] token path: C:\Users\tavan\AppData\Roaming\TabNine\tabnine.token
INFO [auth::token] [2022-01-10:11:26:39 TabNine.exe INFO] token path: C:\Users\tavan\AppData\Roaming\TabNine\tabnine.refresh_token
INFO [TabNine::main_utils] [2022-01-10:11:26:39 TabNine.exe INFO] C:\Users\tavan\.tabnine\4.0.44\x86_64-pc-windows-gnu\TabNine.exe --client PhpStorm --no-lsp true --log-file-path E:/Programs/logs/ --client-metadata pluginVersion=0.5.11 clientIsUltimate=false clientChannel=production pluginUserId=09ba4294-b0af-455e-84ba-9dad8597c02d clientVersion=2021.3.1 clientApiVersion=PS-213.6461.83 ide-restart-counter=0
INFO [auth::user] [2022-01-10:11:26:39 TabNine.exe INFO] Loading user...
WARN [auth::user] [2022-01-10:11:26:39 TabNine.exe WARN] Could not load user from cache, Falling back to authentication against Tabnine's services. error: User cache expired
INFO [watchdog_api::wd_client] [2022-01-10:11:26:39 TabNine.exe INFO] Initializing watchdog client...
INFO [watchdog_api::wd_client] [2022-01-10:11:26:39 TabNine.exe INFO] Starting watchdog...
INFO [watchdog_api::wd_client] [2022-01-10:11:26:39 TabNine.exe INFO] Starting watchdog...
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:39 TabNine.exe INFO] trying to start tabnine version Some("4.0.47")
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:39 TabNine.exe INFO] expected path is "C:\\Users\\tavan\\.tabnine\\4.0.44\\x86_64-pc-windows-gnu\\../../4.0.47\\x86_64-pc-windows-gnu\\TabNine.exe"
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:39 TabNine.exe INFO] spawning tabnine with args ["C:\\Users\\tavan\\.tabnine\\4.0.44\\x86_64-pc-windows-gnu\\../../4.0.47\\x86_64-pc-windows-gnu\\TabNine.exe", "--client", "PhpStorm", "--no-lsp", "true", "--log-file-path", "E:/Programs/logs/", "--client-metadata", "pluginVersion=0.5.11", "clientIsUltimate=false", "clientChannel=production", "pluginUserId=09ba4294-b0af-455e-84ba-9dad8597c02d", "clientVersion=2021.3.1", "clientApiVersion=PS-213.6461.83", "ide-restart-counter=0", "--no_bootstrap"]
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:39 TabNine.exe INFO] started tabnine process pid 28212 version Some("4.0.47"), desired version was Some("4.0.47") this version is Some("4.0.44")
INFO [auth::capabilities] [2022-01-10:11:26:40 TabNine.exe INFO] User changed. Refreshing capabilities
INFO [auth::capabilities] [2022-01-10:11:26:40 TabNine.exe INFO] Refreshing capabilities
INFO [auth::user] [2022-01-10:11:26:40 TabNine.exe INFO] Storing user in cache
INFO [auth::user] [2022-01-10:11:26:40 TabNine.exe INFO] User token validation succeeded
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:40 TabNine.exe INFO] child process 28212 exited...
INFO [bootstrapper::bootstrapper_lib] [2022-01-10:11:26:41 TabNine.exe INFO] current version is Some(Version { major: 4, minor: 0, patch: 44, pre: [], build: [] }), spawned version is Some(Version { major: 4, minor: 0, patch: 47, pre: [], build: [] }), remote version is Version { major: 4, minor: 0, patch: 47, pre: [], build: [] }
INFO [bootstrapper::bundle] [2022-01-10:11:26:41 TabNine.exe INFO] lock is at "C:\\Users\\tavan\\.tabnine\\0.0.1\\x86_64-pc-windows-gnu\\bundle.lock"
INFO [bootstrapper::bundle] [2022-01-10:11:26:41 TabNine.exe INFO] local bundle is valid so not downloading BundleContents { version: "4.0.47", files: [FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\TabNine-deep-cloud.exe", hash: "f99023a1cc6dc2eae8e6a0fc7f2576321a948e5c30c3d5ff0752b94f633beb53" }, FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\TabNine-deep-local.exe", hash: "446e2821ec716698f84940836f0d3c2e7ef12b93debe69f1f701deae6129d970" }, FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\TabNine.exe", hash: "1303f5464b2614b7dd85c9fc0c19d0a9e50192e15954ed1907ad005cc210164a" }, FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\WD-TabNine.exe", hash: "ef49fce1ffbe860e856429a2c11b8401997ce892134001edd8779cd6c039a4fd" }] }
WARN [bootstrapper::bundle] [2022-01-10:11:26:41 TabNine.exe WARN] relinquishing lock at path "C:\\Users\\tavan\\.tabnine\\0.0.1\\x86_64-pc-windows-gnu\\bundle.lock"
INFO [auth::token] [2022-01-10:11:26:51 TabNine.exe INFO] token path: C:\Users\tavan\AppData\Roaming\TabNine\tabnine.token
INFO [auth::token] [2022-01-10:11:26:51 TabNine.exe INFO] token path: C:\Users\tavan\AppData\Roaming\TabNine\tabnine.refresh_token
INFO [TabNine::main_utils] [2022-01-10:11:26:51 TabNine.exe INFO] C:\Users\tavan\.tabnine\4.0.44\x86_64-pc-windows-gnu\TabNine.exe --client PhpStorm --no-lsp true --log-file-path E:/Programs/logs/ --client-metadata pluginVersion=0.5.11 clientIsUltimate=false clientChannel=production pluginUserId=09ba4294-b0af-455e-84ba-9dad8597c02d clientVersion=2021.3.1 clientApiVersion=PS-213.6461.83 ide-restart-counter=1
INFO [auth::user] [2022-01-10:11:26:51 TabNine.exe INFO] Loading user...
WARN [auth::user] [2022-01-10:11:26:51 TabNine.exe WARN] Could not load user from cache, Falling back to authentication against Tabnine's services. error: User cache expired
INFO [watchdog_api::wd_client] [2022-01-10:11:26:51 TabNine.exe INFO] Initializing watchdog client...
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:51 TabNine.exe INFO] trying to start tabnine version Some("4.0.47")
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:51 TabNine.exe INFO] expected path is "C:\\Users\\tavan\\.tabnine\\4.0.44\\x86_64-pc-windows-gnu\\../../4.0.47\\x86_64-pc-windows-gnu\\TabNine.exe"
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:51 TabNine.exe INFO] spawning tabnine with args ["C:\\Users\\tavan\\.tabnine\\4.0.44\\x86_64-pc-windows-gnu\\../../4.0.47\\x86_64-pc-windows-gnu\\TabNine.exe", "--client", "PhpStorm", "--no-lsp", "true", "--log-file-path", "E:/Programs/logs/", "--client-metadata", "pluginVersion=0.5.11", "clientIsUltimate=false", "clientChannel=production", "pluginUserId=09ba4294-b0af-455e-84ba-9dad8597c02d", "clientVersion=2021.3.1", "clientApiVersion=PS-213.6461.83", "ide-restart-counter=1", "--no_bootstrap"]
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:51 TabNine.exe INFO] started tabnine process pid 27984 version Some("4.0.47"), desired version was Some("4.0.47") this version is Some("4.0.44")
INFO [auth::capabilities] [2022-01-10:11:26:51 TabNine.exe INFO] User changed. Refreshing capabilities
INFO [auth::capabilities] [2022-01-10:11:26:51 TabNine.exe INFO] Refreshing capabilities
INFO [auth::user] [2022-01-10:11:26:51 TabNine.exe INFO] Storing user in cache
INFO [auth::user] [2022-01-10:11:26:51 TabNine.exe INFO] User token validation succeeded
INFO [TabNine::bootstrap_support] [2022-01-10:11:26:52 TabNine.exe INFO] child process 27984 exited...
INFO [bootstrapper::bootstrapper_lib] [2022-01-10:11:26:52 TabNine.exe INFO] current version is Some(Version { major: 4, minor: 0, patch: 44, pre: [], build: [] }), spawned version is Some(Version { major: 4, minor: 0, patch: 47, pre: [], build: [] }), remote version is Version { major: 4, minor: 0, patch: 47, pre: [], build: [] }
INFO [bootstrapper::bundle] [2022-01-10:11:26:52 TabNine.exe INFO] lock is at "C:\\Users\\tavan\\.tabnine\\0.0.1\\x86_64-pc-windows-gnu\\bundle.lock"
INFO [bootstrapper::bundle] [2022-01-10:11:26:52 TabNine.exe INFO] local bundle is valid so not downloading BundleContents { version: "4.0.47", files: [FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\TabNine-deep-cloud.exe", hash: "f99023a1cc6dc2eae8e6a0fc7f2576321a948e5c30c3d5ff0752b94f633beb53" }, FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\TabNine-deep-local.exe", hash: "446e2821ec716698f84940836f0d3c2e7ef12b93debe69f1f701deae6129d970" }, FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\TabNine.exe", hash: "1303f5464b2614b7dd85c9fc0c19d0a9e50192e15954ed1907ad005cc210164a" }, FileChecksum { path: "C:\\Users\\tavan\\.tabnine\\4.0.47\\x86_64-pc-windows-gnu\\WD-TabNine.exe", hash: "ef49fce1ffbe860e856429a2c11b8401997ce892134001edd8779cd6c039a4fd" }] }
WARN [bootstrapper::bundle] [2022-01-10:11:26:52 TabNine.exe WARN] relinquishing lock at path "C:\\Users\\tavan\\.tabnine\\0.0.1\\x86_64-pc-windows-gnu\\bundle.lock"

**Comment by maya-tabnine** [comment]
We released a new binary version 4.0.49 to beta which should resolve the issue.
@suuforest  Would you try it and tell us if it worked?

**Comment by suuforest** [comment]
great
