### ISSUE TITLE
Adding settings feature "tabnine.enable_file_regex"

### ISSUE THREAD

**Issue by Rishang** [codota/TabNine#503]
Device: Manjaro Linux
IDE: Vscode

Tabnine supports "tabnine.disable_file_regex" for files where we want to diable tabnine

But i want to enable tabnine only for specific languages like yaml, HCL, bash
Thus making a long list of file extension i have tokeep at  "tabnine.disable_file_regex" list

Please add option like "tabnine.enable_file_regex" also for vscode

gz#10781

**Comment by maya-tabnine** [comment]
Hi!
I think that’s a cool idea! 
We’re not working on that at the moment, but I’ll pitch it to the team and see what they think.

**Comment by Rishang** [comment]
any updates on this ?

**Comment by Rishang** [comment]
any updates on this ?
