### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by modz2014** [codota/TabNine#506]
hi i was wondering if this could be built for notepad++ python at all

gz#10867

**Comment by maya-tabnine** [comment]
Hi Notepad++ is on our backlog. If we see enough interest from the community, we will work on it.
As you saw on https://github.com/codota/TabNine/issues/23 you can start developing such a plugin yourself!
Here is the guide: https://github.com/codota/TabNine/blob/master/HowToWriteAClient.md

**Comment by modz2014** [comment]
Well this doesn't tell me much about creating it myself also if you look at notepad++ a lot of people still use it would be very good and on that post it says enough demand you will push piroty

**Comment by vsiegel** [comment]
I'd like to give the suggestion to change the title to something more specific. If you expect this issue will exist for a long time, that makes it more important. And if somebody would want to work on notepad++ integration, he has explicit reason not to check this issue.
And if you can and want to do it yourself, as you implied, I trust you will find the documentation. (That, of course, is often the hardest part of development.)
