### ISSUE TITLE
Where is the "Deep Completion" option for student program?

### ISSUE THREAD

**Issue by Zero0one1** [codota/TabNine#507]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: vscode
 - Editor version: 1.63.2
 - Programming language: python
 - TabNine extension version: 3.5.16
 - Engine version (could be located within Tabnine Hub): 4.0.44-41

**Issue Details:**
I want to try "Deep Completion" but cannot find that option on my Tabnine Hub. Here are the screenshots. Could you help me with it? Thank you so much!
![image](https://user-images.githubusercontent.com/29177314/149911275-275e884e-7ba4-4b2b-9cf3-2a83254b4aa6.png)
![image](https://user-images.githubusercontent.com/29177314/149911420-2f6a5fdf-cd03-4c63-af21-1cbe85cae6a9.png)

gz#10971

**Comment by yonip23** [comment]
Hi @Zero0one1 
We had some changes in the Hub's UI, what you're referring to is now called "Enable Cloud Model" / "Enable Local Model" - these are the "Deep completions" in the old UI

Kind regards

**Comment by Zero0one1** [comment]
Got it. So the deep completion is turned on by default?

**Comment by yonip23** [comment]
> Got it. So the deep completion is turned on by default?

The local model is enabled by default, you can enable the cloud model too if you want 🙂

**Comment by yonip23** [comment]
Closing the issue, as its solved
