### ISSUE TITLE
[Ask for help] Is there an entrance to delete my account?

### ISSUE THREAD

**Issue by Dragon1573** [codota/TabNine#508]
## Environments

 - OS version: Windows 10 Professional China 21H2 (19044.1466)
 - Editor: Microsoft Visual Studio Code
 - Editor version: v1.63.2
 - Programming language: Python 3 (with Pylance), Scala 2.13 (with Metals), Java 17, C/C++ (via CMake)
 - TabNine extension version: v3.5.16
 - Engine version: v4.0.59-47

## Issue Details

I'm currently switching from Tabnine to other AI completion service and delete my Tabnine account at the same time. I previously logged in to Tabnine Hub with GitHub OAuth.

Is there a way to delete my Tabnine models and account forever? I can't find it in my account "Details" on official site. Is it just simply revoke the authentication to Tabnine from my GitHub account?

Thank you!

gz#11028

**Comment by maya-tabnine** [comment]
Hi @Dragon1573 please get in touch with us through support@tabnine.com using your account email.
You can ask for a deletion of your account there, and we will process it for you.

**Comment by Dragon1573** [comment]
> Please get in touch with us through support@tabnine.com using your account email.
> You can ask for a deletion of your account there, and we will process it for you.

Excuse me @maya-tabnine , I've sent the email for a several days. But I haven't got a response. Could you please help me verify if my account is successfully deleted?

Thank you!

**Comment by Dragon1573** [comment]
@maya-tabnine Excuse me again. I still haven't got any response from support@tabnine.com . I've revoke the authorization of Tabnine OAuth App.

Did my account successfully deleted? Thank you!
