### ISSUE TITLE
[Ask for help] why I can't get my account reset  password?

### ISSUE THREAD

**Issue by salanhess** [codota/TabNine#509]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

why I can't get my account reset  password?
any help ?

gz#11063

**Comment by maya-tabnine** [comment]
Did you sign up before at https://app.tabnine.com/signup?
Did you activate your account already?

**Comment by salanhess** [comment]
it's ok now. thx
