### ISSUE TITLE
Prespecified dictionary of tokens for particular languages

### ISSUE THREAD

**Issue by zxqfl** [codota/TabNine#51]
Ideally, user-configurable

**Comment by RhysU** [comment]
Was this closed as fixed or wontfix?  I just updated TabNine and see the same behavior that I initially reported to Jacob back in January 2019...

In addition to TabNine, I would like to add a dictionary of keyword completions like so: https://github.com/RhysU/dotfiles/blob/master/.vim/after/ftplugin/scheme.vim.  The use case is looking up APIs that I know exist prior to their first usage within a given project.  I do see these completions appear within vim but not as I'd expect.  Concretely and referring to attached images s{1,2,3,4}.png:

s1.png) Within a scheme file I type '(st' and I see string/sqrt/substring/list.  Typing Control-N cycles through these 4 choices.
s2.png) I continue typing 'ring' and see both string/substring.  Typing Control-N cycles through these 2 choices.
s3.png) I type '-' and now see no completions available.
s4.png) I type Control-N once and my dictionary becomes active.

![s1](https://user-images.githubusercontent.com/85419/77228049-ff240200-6b5a-11ea-93e8-dc9f7fbb8ff3.png)
![s2](https://user-images.githubusercontent.com/85419/77228051-ff240200-6b5a-11ea-9fea-2b0cc79c96ad.png)
![s3](https://user-images.githubusercontent.com/85419/77228048-fe8b6b80-6b5a-11ea-9b54-f692244abb3a.png)
![s4](https://user-images.githubusercontent.com/85419/77228050-ff240200-6b5a-11ea-992d-d0e3f69a8bff.png)

I expected the dictionary completions to somehow be "incorporated" during steps s{1,2,3}.  In those screenshots, the dictionary extension was `.dict` but I see the same behavior after moving to `.ss` per https://github.com/RhysU/dotfiles/commit/5e07d23e4abe28f942fa0c82662da9fffa21d47e.  Jacob said that having a global dictionary was not supported at the time and filed this tracking ticket.

**Comment by amircodota** [comment]
@RhysU 

Sorry for not writing more. Since this was opened by @zxqfl, I assumed this was something he filed for his own tracking - was not aware that it was due to a user request.

We closed it as a "wontfix". We have other idea as to how to support specific languages, but we do not plan to add pre-specified dictionary of tokens - at least not in the foreseeable future.

**Comment by RhysU** [comment]
Thank you for the explanation. The root reason for this feature request wasn't to support a particular language but rather to ease working in a particular setting.

For example, here I had wanted to use a token dictionary containing everything known to Chez Scheme (https://github.com/RhysU/dotfiles/blob/master/.vim/after/ftplugin/chezscheme.ss). Other folks might, e. g., want to augment Lua with identifiers for their scripting setting. 

As a workaround, @zxqfl had recommended copying that dictionary into each project.

All of which I mention just to provide more context. Thank you your work on TabNine.

**Comment by amircodota** [comment]
Thank you for that feedback.

I'm re-opening and marking as enhancement.
Will evaluate it with out other priorities.
