### ISSUE TITLE
Change TabNine executable folder on Windows for Intellij

### ISSUE THREAD

**Issue by dylan-brackett** [codota/TabNine#518]
**please complete the following information:**	
 - OS version: Win10
 - Editor: PyCharm/Clion
 - Editor version: 2022.1 EAP
 - Programming language: Python, Rust
 - TabNine extension version: 0.5.22
 - Engine version (could be located within Tabnine Hub): N/A

I am currently trying to run Tabnine on Pycharm/Clion, but the computer I work on has a rule that almost any .exe file trying to run inside a user's folder is blocked. So when trying to run Tabnine (which is located at C:/User/Username/.tabnine) it will not run. In Pycharm and Clion when I click on the "Tabnine" icon, nothing happens. I have tried uninstalling, reinstalling, and adding the executables to my path. Oddly enough Tabnine runs fine within my VSCode instance, but that might be due to my group policy.

Is there a way I can tell Tabnine where to look for it's files so I can move it in to a folder it can run from? I tried looking at environment variables it might look up, but I couldn't find any.

gz#12337

**Comment by maya-tabnine** [comment]
Hi @dylan-brackett , I can help provide the paths Tabnine uses. 
I see you are on Win10. Can you list me all the IDEAs you use with Tabnine? Are there any non-JetBrains too?

**Comment by maya-tabnine** [comment]
@dylan-brackett Would try to uninstall Tabnine?
Try removing the files at:
C:\Users\{UserName}\.tabnine
C:\Users\{UserName}\AppData\Roaming\TabNine

And then reinstall Tabnine on these JetBrains ideas.
Would you let me know if that works?

**Comment by maya-tabnine** [comment]
@dylan-brackett Did you try following the instructions I sent? Did it help?

**Comment by dylan-brackett** [comment]
Yes I tried that, and I still received the same issues.

**Comment by maya-tabnine** [comment]
@dylan-brackett I will need logs to investigate your case. Would you email us at support@tabnine.com? I will provide specific instructions.
