### ISSUE TITLE
 Inline completions does not take effect

### ISSUE THREAD

**Issue by KiligFei** [codota/TabNine#519]
- OS version: macOS Monterey
 - Editor: vscode	
 - Editor version: 1.65.0
 - Programming language: [ js, ts]	
 - TabNine extension version: 3.5.26
 - Engine version (could be located within Tabnine Hub): 4.1.15-35
 - 
Issue Details:

Inline completions does not take effect

![image](https://user-images.githubusercontent.com/69230517/156998302-b486dbbf-4a21-4f84-ab7b-8938217e4109.png)

![image](https://user-images.githubusercontent.com/69230517/156998376-0f749e82-f773-405a-80f9-e2a7e3177330.png)

gz#12459

**Comment by yonip23** [comment]
@KiligFei Did you try to restart the IDE?

**Comment by KiligFei** [comment]
> @KiligFei Did you try to restart the IDE?

yes ,l do

**Comment by maya-tabnine** [comment]
Hi @KiligFei, I see you closed the issue. If you need any further help, email us at support@tabnine.com
