### ISSUE TITLE
how to cancel subscription

### ISSUE THREAD

**Issue by johncming** [codota/TabNine#520]
Hi, I purchased the service a year ago and I don't want to use it now, but I can't find a way to cancel my subscription and my bank has informed me that I have to deduct the money.

This is my Plan & Subscription, I can't find any button to cancel my subscription.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/11719334/158009057-7e7ed11d-ebae-44c1-8808-7076fe53f1d7.png">

gz#12615

**Comment by maya-tabnine** [comment]
Hi, we received your email and helped you in canceling your account.
This was due to a problem with your account record, which we fixed right away before the cancellation.

**Comment by OpenTechConsult** [comment]
> Hi, we received your email and helped you in canceling your account. This was due to a problem with your account record, which we fixed right away before the cancellation.

I also want to cancel my subscription but I don't know how to proceed.
My email is opentech.consult@gmail.com

Thank you

**Comment by YasirFarhan** [comment]
Hi I also want to cancel my subscription before the trial ends. Please cancel it. Thanks
