### ISSUE TITLE
 Cannot run local model: AVX2 instructions not supported

### ISSUE THREAD

**Issue by JoeBravo123** [codota/TabNine#524]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina] Ubuntu 18.04 LTS
 - Editor: [e.g. vscode, intelij, sublime]	vscode
 - Editor version: 1.66.2	
 - Programming language: [e.g. js, ts, c++]	C++
 - TabNine extension version: 3.5.42
 - Engine version (could be located within Tabnine Hub): 4.4.1-47

**Issue Details:**
![image](https://user-images.githubusercontent.com/48083404/163773417-697a68bf-28e6-43fb-a0ed-99d27ec55bbb.png)
![image](https://user-images.githubusercontent.com/48083404/163773511-c5ff0ae3-d5a2-4f25-befc-c25c7d61a503.png)
![image](https://user-images.githubusercontent.com/48083404/163773599-9e355f59-269f-4f27-b2bb-455e70395798.png)
INFO [TabNine::main_utils] [2022-04-18:15:20:11 TabNine INFO] /data1/bravo/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.1/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --log-file-path=/data1/bravo/-61006 --client-metadata clientVersion=1.66.2 pluginVersion=3.5.42 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=ssh-remote vscode-extension-kind=2 vscode-theme-name=Community Material Theme Ocean vscode-theme-kind=Dark vscode-machine-id=87724771f3702d5b4dbe02a0a0a850413e1ac2b911ce8c04a70c6be891ee89b1 vscode-is-new-app-install=false vscode-session-id=a852419e-3734-4611-a5f6-2145806a70021650266394697 vscode-language=zh-cn vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0
WARN [lunar_connection::local_lunar_connection] [2022-04-18:15:20:12 TabNine WARN] Cannot run local model: AVX2 instructions not supported

INFO [watchdog_api::wd_client] [2022-04-18:15:20:12 TabNine INFO] Initializing watchdog client...
INFO [watchdog_api::wd_client] [2022-04-18:15:20:12 TabNine INFO] Starting watchdog...
INFO [watchdog_api::wd_client] [2022-04-18:15:20:12 TabNine INFO] Starting watchdog...
INFO [TabNine::bootstrap_support] [2022-04-18:15:20:12 TabNine INFO] trying to start tabnine version Some("4.4.1")
INFO [TabNine::bootstrap_support] [2022-04-18:15:20:12 TabNine INFO] spawning tabnine with args ["/data1/bravo/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.1/x86_64-unknown-linux-musl/TabNine", "--client=vscode", "--no-lsp=true", "--log-file-path=/data1/bravo/-61006", "--client-metadata", "clientVersion=1.66.2", "pluginVersion=3.5.42", "t9-vscode-AutoImportEnabled=true", "t9-vscode-TSAutoImportEnabled=true", "t9-vscode-JSAutoImportEnabled=true", "vscode-telemetry-enabled=true", "vscode-remote=true", "vscode-remote-name=ssh-remote", "vscode-extension-kind=2", "vscode-theme-name=Community Material Theme Ocean", "vscode-theme-kind=Dark", "vscode-machine-id=87724771f3702d5b4dbe02a0a0a850413e1ac2b911ce8c04a70c6be891ee89b1", "vscode-is-new-app-install=false", "vscode-session-id=a852419e-3734-4611-a5f6-2145806a70021650266394697", "vscode-language=zh-cn", "vscode-app-name=Visual Studio Code", "vscode-beta-channel-enabled=false", "vscode-status-customization=unknown", "ide-restart-counter=0", "--no_bootstrap"]
INFO [TabNine::bootstrap_support] [2022-04-18:15:20:12 TabNine INFO] started tabnine process pid 61293 version Some("4.4.1"), desired version was Some("4.4.1") this version is Some("4.4.1")
INFO [TabNine::main_utils] [2022-04-18:15:20:12 TabNine INFO] /data1/bravo/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.1/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --log-file-path=/data1/bravo/-61006 --client-metadata clientVersion=1.66.2 pluginVersion=3.5.42 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=ssh-remote vscode-extension-kind=2 vscode-theme-name=Community Material Theme Ocean vscode-theme-kind=Dark vscode-machine-id=87724771f3702d5b4dbe02a0a0a850413e1ac2b911ce8c04a70c6be891ee89b1 vscode-is-new-app-install=false vscode-session-id=a852419e-3734-4611-a5f6-2145806a70021650266394697 vscode-language=zh-cn vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown ide-restart-counter=0 --no_bootstrap
INFO [watchdog_api::wd_client] [2022-04-18:15:20:12 TabNine INFO] Initializing watchdog client...
INFO [auth::capabilities] [2022-04-18:15:20:12 TabNine INFO] User changed. Refreshing capabilities
INFO [auth::capabilities] [2022-04-18:15:20:12 TabNine INFO] Refreshing capabilities
ERROR [auth::capabilities] [2022-04-18:15:20:12 TabNine ERROR] Failed to fetch user capabilities - reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/capabilities/v2", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
WARN [bootstrapper::register] [2022-04-18:15:20:12 TabNine WARN] got an error reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
WARN [bootstrapper::register] [2022-04-18:15:20:12 TabNine WARN] got an error. trying again
INFO [process_setup::command_ext] [2022-04-18:15:20:12 TabNine INFO] child exited with status exit status: 0
WARN [bootstrapper::register] [2022-04-18:15:20:12 TabNine WARN] got an error reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
WARN [bootstrapper::register] [2022-04-18:15:20:12 TabNine WARN] got an error. trying again
INFO [frontend] [2022-04-18:15:20:12 TabNine INFO] LSP disabled
WARN [bootstrapper::register] [2022-04-18:15:20:12 TabNine WARN] got an error reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
WARN [bootstrapper::bootstrapper_lib] [2022-04-18:15:20:12 TabNine WARN] failed registering to server: with error Server
WARN [bootstrapper::bootstrapper_lib] [2022-04-18:15:20:12 TabNine WARN] user belongs to default experiment so calling cloud front server fallback
ERROR [analytics::send_queue] [2022-04-18:15:20:12 TabNine ERROR] Failed to send analytics event, maximizing send backoff policy: Permanent(Error(Http(reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("notify.tabnine.com")), port: None, path: "/notify/v1", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }))
ERROR [analytics::send_queue] [2022-04-18:15:20:12 TabNine ERROR] Failed to send analytics event, maximizing send backoff policy: Permanent(Error(Http(reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("notify.tabnine.com")), port: None, path: "/notify/v1", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }))
INFO [auth::capabilities] [2022-04-18:15:20:12 TabNine INFO] User changed. Refreshing capabilities
INFO [auth::capabilities] [2022-04-18:15:20:12 TabNine INFO] Refreshing capabilities
ERROR [auth::capabilities] [2022-04-18:15:20:12 TabNine ERROR] Failed to fetch user capabilities - reqwest::Error { kind: Request, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/capabilities/v2", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }
INFO [recommend_tabnine_extension] [2022-04-18:15:20:12 TabNine INFO] registering recommender
INFO [recommend_tabnine_extension::vscode_recommended_extensions] [2022-04-18:15:20:12 TabNine INFO] not activating recommendation engine
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] No private model found
INFO [lunar_connection::model_chooser] [2022-04-18:15:20:12 TabNine INFO] current private model is None
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] Starting private model update thread
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] Checking if private model changed
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] active private model is None
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] removing private models from cache
ERROR [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine ERROR] Failed to remove private models from cache: No such file or directory (os error 2)
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] private model is same
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] sleeping for 3600s
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] Checking if private model changed
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] active private model is None
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] removing private models from cache
ERROR [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine ERROR] Failed to remove private models from cache: No such file or directory (os error 2)
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] private model is same
INFO [lunar_connection::connection_choosers::private_models::state] [2022-04-18:15:20:12 TabNine INFO] sleeping for 3600s
INFO [lunar_connection::model_chooser] [2022-04-18:15:20:12 TabNine INFO] using initial model Model {
    model_hash_override: None,
    model_size: Small,
    base_url: "https://update.tabnine.com",
}
INFO [lunar_connection] [2022-04-18:15:20:12 TabNine INFO] lunar settings update thread started (Local(Public) default local)
INFO [lunar_connection::local_lunar_connection] [2022-04-18:15:20:12 TabNine INFO] starting default model pre-loader DownloadSettings {
    api_key: None,
    meta_data_base_url: "https://api.tabnine.com",
    model: Model {
        model_hash_override: None,
        model_size: Small,
        base_url: "https://update.tabnine.com",
    },
}
INFO [lunar_connection::project_model_override_installer] [2022-04-18:15:20:12 TabNine INFO] project model override feature is disabled
INFO [lunar_connection::model_chooser_connections] [2022-04-18:15:20:12 TabNine INFO] Started model connection config watcher loop.
INFO [lunar_connection] [2022-04-18:15:20:12 TabNine INFO] lunar settings update thread started (Remote cloud)
INFO [lunar_connection] [2022-04-18:15:20:12 TabNine INFO] lunar settings update thread started (Local(Public) default local)
WARN [lunar_connection::local_lunar_connection] [2022-04-18:15:20:12 TabNine WARN] Cannot run local model: AVX2 instructions not supported

WARN [lunar_connection::local_lunar_connection] [2022-04-18:15:20:12 TabNine WARN] not running pre loader
INFO [frontend::initialize] [2022-04-18:15:20:12 TabNine INFO] Started.
WARN [lunar_connection::cloud_availability] [2022-04-18:15:20:12 TabNine WARN] Cannot connect to cloud: pinging to: host=cloud.tabnine.com, port=443
Failed to connect to cloud ()

INFO [team_ai::data_handling] [2022-04-18:15:20:12 TabNine INFO] Initialized team ai database successfully at: /data1/bravo/.local/share/TabNine/team_learning/data_dir/sdb
INFO [team_ai] [2022-04-18:15:20:12 TabNine INFO] Initialized team ai learning successfully
INFO [team_ai::data_handling] [2022-04-18:15:20:12 TabNine INFO] Cleaned 0 old data rows from team ai local database.
INFO [team_ai::data_handling] [2022-04-18:15:20:12 TabNine INFO] Cleaned 0 old metadata rows from team ai local database.

gz#13583

**Comment by Tabnineteam** [comment]
<i>(related to <a href='https:///agent/tickets/13583'>Zendesk ticket #13583</a>)</i>

**Comment by maya-tabnine** [comment]
Hi if you followed the instructions at https://www.tabnine.com/faq#fma_instructions and saw it is not supported,
you can enable the cloud advanced model instead of the local one.
