### ISSUE TITLE
Unable to sign in to TabNine behind corporate proxy/vpn

### ISSUE THREAD

**Issue by zmeir** [codota/TabNine#526]
**please complete the following information:**	
 - OS version: macOS Monterey 12.2.1
 - Editor: PyCharm	
 - Editor version: 2022.1
 - Programming language: python
 - TabNine extension version: 0.5.23
 - Engine version (could be located within Tabnine Hub): 4.4.4-48

**Issue Details:**
When launching the TabNine hub from PyCharm, then trying to Sign In, the page tries to redirect to https://app.tabnine.com/auth/sign-in for the sign in process, but then nothing happens and the page redirects back to the hub URL (in http://127.0.0.1:5555) and just hangs there indefinitely with a blank page.  
This only happens when operating inside of a corporate VPN. When I turn off the VPN I can sign in just fine.

This doesn't seem to be a duplicate of https://github.com/codota/TabNine/issues/181, as the suggested solution there is to update the `http_proxy` and `https_proxy` environment variables. However, since in this case TabNine is running from PyCharm, the same approach doesn't apply.

gz#13739

**Comment by maya-tabnine** [comment]
Hi can you make sure Tabnine is whitelisted then?
For tabnine to operate properly, it needs to be able to communicate with several hosts:
[api.tabnine.com](http://api.tabnine.com/), [www.tabnine.com](http://www.tabnine.com/), [cloud.tabnine.com](http://cloud.tabnine.com/), [sa.tabnine.com](http://sa.tabnine.com/).

**Comment by BKDev99** [comment]
The problem is still working. After adding to the whitelist, I get a new message "Could not authenticate."

**Comment by zmeir** [comment]
> Hi can you make sure Tabnine is whitelisted then?
> For tabnine to operate properly, it needs to be able to communicate with several hosts:
> [api.tabnine.com](http://api.tabnine.com/), [www.tabnine.com](http://www.tabnine.com/), [cloud.tabnine.com](http://cloud.tabnine.com/), [sa.tabnine.com](http://sa.tabnine.com/).

What do you mean by that? I have no control over our corporate VPN or firewall settings, but I can access all those hosts through our proxy. The problem is there are no proxy settings for the plugin anywhere (or at least nowhere I could find).

**Comment by maya-tabnine** [comment]
I looked it up online, and perhaps you need to set the proxy settings in PyCharm. Look at [this guide](https://www.locaproxy.com/technical-configuration/how-to-configure-proxy-in-programming-ide-for-py-charm)
Let us know if that resolved it!

**Comment by raphaelbiermann** [comment]
I have the same problem with all tabnine subdomains whitelisted

**Comment by zmeir** [comment]
> I looked it up online, and perhaps you need to set the proxy settings in PyCharm. Look at [this guide](https://www.locaproxy.com/technical-configuration/how-to-configure-proxy-in-programming-ide-for-py-charm)
> Let us know if that resolved it!

Ive set the proxy settings in both PyCharm and Safari/Chrome but still can’t sign in

**Comment by raphaelbiermann** [comment]
Please activate the api key signin again

**Comment by zmeir** [comment]
> Please activate the api key signin again

Can you please elaborate?

I see no such option in my [user profile](https://app.tabnine.com/profile). Did you mean I should enter an API key in the Tabnine Hub preferences here?  
![image](https://user-images.githubusercontent.com/33152084/172144123-8c97294f-89be-473e-b6f8-251537e8d220.png)  
If so - I don't know how to get this key. My account was activated via email invitation to a Tabnine Team.

I also checked to see if my account is active as shown [here](https://github.com/codota/TabNine/issues/79) and it seems ok:  
![image](https://user-images.githubusercontent.com/33152084/172143868-75cc4623-8e44-4aec-b91c-f7a45cddfb55.png)

**Comment by zmeir** [comment]
Issue is still present in latest version of PyCharm and TabNine

**Comment by ksylvan** [comment]
The tabnine web code should be changed to use something like {baseURL_/proxy/5555 instead of 127.0.0.1:5555 for the tabnine hub, since this PR went into the base code-server: https://github.com/coder/code-server/pull/5624

**Comment by jsjoeio** [comment]
Let us know how we can help!

**Comment by ksylvan** [comment]
This issue is still occurring with the latest TabNine and code-server

**Comment by BKDev99** [comment]
This issue is still occurring with the latest TabNine and code-server

**Comment by anazar2001** [comment]
Still having this issue. Now tabnine does not work under VPN at all. In the logs I can see the requests are getting timed out or getting some error:

n_app_messaging::internal] [2023-03-14:13:01:18 TabNine ERROR] Error while fetching messages. reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/in-app-messaging/notifications/1651877031980239000", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) }
DEBUG [lunar_local::downloader] [2023-03-14:13:01:24 TabNine-deep-local DEBUG] LunarLocalModelRelatedData { model_hash: "ce94127b", models_dir: Some("/Users/andrei.nazarenka/Library/Application Support/TabNine/models") }
DEBUG [triggers::trigger_manager::analytics_observer] [2023-03-14:13:01:24 TabNine DEBUG] trigger manager observer digesting...
DEBUG [lunar_local::downloader] [2023-03-14:13:01:25 TabNine-deep-local DEBUG] LunarLocalModelRelatedData { model_hash: "ce94127b", models_dir: Some("/Users/andrei.nazarenka/Library/Application Support/TabNine/models") }
DEBUG [triggers::trigger_manager::analytics_observer] [2023-03-14:13:01:25 TabNine DEBUG] trigger manager observer digesting...
DEBUG [lunar_local::downloader] [2023-03-14:13:01:34 TabNine-deep-local DEBUG] LunarLocalModelRelatedData { model_hash: "ce94127b", models_dir: Some("/Users/andrei.nazarenka/Library/Application Support/TabNine/models") }
DEBUG [triggers::trigger_manager::analytics_observer] [2023-03-14:13:01:34 TabNine DEBUG] trigger manager observer digesting...
DEBUG [lunar_local::downloader] [2023-03-14:13:01:34 TabNine-deep-local DEBUG] LunarLocalModelRelatedData { model_hash: "ce94127b", models_dir: Some("/Users/andrei.nazarenka/Library/Application Support/TabNine/models") }
DEBUG [triggers::trigger_manager::analytics_observer] [2023-03-14:13:01:34 TabNine DEBUG] trigger manager observer digesting...
ERROR [in_app_messaging::internal] [2023-03-14:13:01:36 TabNine ERROR] Error while fetching messages. reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/in-app-messaging/notifications/1651877031980239000", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) }
DEBUG [lunar_local::downloader] [2023-03-14:13:01:44 TabNine-deep-local DEBUG] LunarLocalModelRelatedData { model_hash: "ce94127b", models_dir: Some("/Users/andrei.nazarenka/Library/Application Support/TabNine/models") }
DEBUG [triggers::trigger_manager::analytics_observer] [2023-03-14:13:01:44 TabNine DEBUG] trigger manager observer digesting...
DEBUG [lunar_local::downloader] [2023-03-14:13:01:44 TabNine-deep-local DEBUG] LunarLocalModelRelatedData { model_hash: "ce94127b", models_dir: Some("/Users/andrei.nazarenka/Library/Application Support/TabNine/models") }
DEBUG [triggers::trigger_manager::analytics_observer] [2023-03-14:13:01:44 TabNine DEBUG] trigger manager observer digesting...

**Comment by anazar2001** [comment]
Or this one:

WARN [cloud_health] [2023-03-14:13:44:24 TabNine WARN] got error response from cloud health check. failures_counter: 9, e: error sending request for url (https://c2.p.tabnine.com/health): operation timed out
ERROR [midline] [2023-03-14:13:44:25 TabNine-deep-cloud ERROR] Failed to query cloud v2 midline error sending request for url (https://c2.p.tabnine.com/infer): operation timed out

**Comment by nvlinh99** [comment]
Still error

**Comment by jaques-sam** [comment]
Issue is still happening. Everything looks fine, and all the other links seem to work. My docker is running with --net=host, my firewall is disabled and I have no VPN. It doesn't work at home or at work.
