### ISSUE TITLE
Bug: TabNine locks a folder of a project, even though the IDE doesn't have the project opened anymore

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [codota/TabNine#527]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
Windows 11
 - Editor: [e.g. vscode, intelij, sublime]	
 Android Studio
 - Editor version:	
 Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
 - Programming language: [e.g. js, ts, c++]	
 Kotlin
 - TabNine extension version:
0.6.0
 - Engine version (could be located within Tabnine Hub): 
4.4.6-49

**Issue Details:**
Sometimes I create a new project to test something, and then I close it and want to delete it when I'm finished with it.
The plugin seems to lock the folder, so I can't remove it, even though the IDE doesn't have the project opened anymore.
I need to forcefully unlock to delete the folder:

![image](https://user-images.githubusercontent.com/5357526/165710871-e493eb3a-1681-4c6d-8954-fcc18aa37623.png)

**Comment by maya-tabnine** [comment]
Hi, did you try closing the IDE and then trying to delete the folder?

**Comment by AndroidDeveloperLB** [comment]
@maya-tabnine I don't know when this occurs (doesn't always occur), but I guess that it won't be locked after closing all instances of the IDE.

**Comment by AndroidDeveloperLB** [comment]
@maya-tabnine Attached logs file of the IDE when I got it reproduced:

[studio-logs-20220505-213755.zip](https://github.com/codota/TabNine/files/8633784/studio-logs-20220505-213755.zip)

 
As for your question, after closing the IDE, it has let me to delete the folder.
