### ISSUE TITLE
Bug:TabNine and VIM extension may conflict

### ISSUE THREAD

**Issue by AutoColin** [codota/TabNine#528]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
  Win 11
 - Editor: [e.g. vscode, intelij, sublime]	
  vscode
 - Editor version:	
  Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
 - Programming language: [e.g. js, ts, c++]	
  cuda
 - TabNine extension version:
  v3.5.45
 - Engine version (could be located within Tabnine Hub): 
  4.4.6-49

**Issue Details:**
I install vim plugin on vscode. So when I input "glob..." waiting Tabnine complete it to "\_\_global\_\_", I push "Tab" and the word completed successfully but vim turns to VISUAL model. But if I push "ENTER", it still stays in INSERT model.

gz#14046

**Comment by boaz-codota** [comment]
Hey @AutoColin , thank you for contacting us! @LeshemNoa is working on a solution, and we would love to have you validate it as soon as possible.

**Comment by bilucodota** [comment]
Hey @AutoColin! My name's Noa and I'm part of the Tabnine developer team.
I just released a fix for Vim's mode switching and incorrect cursor positioning after accepting an inline completion from Tabnine. The fix is available in version number 3.5.49.
I'd appreciate it if you could try it out and let us know what you think.

Thanks again for reaching out!
Noa
<br><p><em><small>°°°</small></em></p>

**Comment by AutoColin** [comment]
> k.

Hi Noa, thank for your effort. I have tried the new release and I think the bug before has been corrected. 
And also i wonder if your team will make Cuda support of Tabnine. For example, "cufftComplex" is a variable type of cufft library and this variable wont show auto-completion in Tabnine.

**Comment by bilucodota** [comment]
Hey,

Thanks for the useful feedback, we'll definitely take Cuda into consideration for additional technologies to support.

Have a great day!
Noa
<br><p><em><small>°°°</small></em></p>
