### ISSUE TITLE
Add Clojure as a supported language?

### ISSUE THREAD

**Issue by MaterialFuture** [codota/TabNine#529]
Feature request: Adding Clojure as one of the languages supported.

There's quite a lot of repositories on GitHub that contain Clojure code, so I'm sure you could train the model based on that data alone, however there are other resources and codebases online for Clojure code.

Since you already support Java I feel like this would be next level to have when working on Clojure+Java projects. With that said, it may also be worth looking into training the models on other Lisp languages as well such as Common Lisp, Scheme, etc..

Thanks for all the awesome work,

gz#14165

**Comment by maya-tabnine** [comment]
We’re not working on that at the moment, but I’ll pitch it to the team and see what they think.
It will be added to our list, and if we'd see enough interest from the community, we will make it happen :)
