### ISSUE TITLE
seemingly random partial code deletes on lines of partal auto completion

### ISSUE THREAD

**Issue by MarsAndBeyond** [codota/TabNine#532]
**please complete the following information:**	
 - OS version: Windows 11
 - Editor: VS code	
 - Editor version:	1.67.2
 - Programming language: Python
 - TabNine extension version: plug in version: 3.5.42
 - Engine version (could be located within Tabnine Hub):  4.4.12-49

When I have the beta setting on, parts of the line that I am editing disappear. It only seems to happen when I do partial completion of lines. 

gz#14559

**Comment by maya-tabnine** [comment]
Can you share a video of this phenomenon? I will pass it on to our team.
