### ISSUE TITLE
tabnine.inlineHintColor don't take effect 

### ISSUE THREAD

**Issue by KiligFei** [codota/TabNine#533]
**please complete the following information:**	
 - OS version: macOS Monterey 12.4
 - Editor:  vscode
 - Editor version:   1.67.2
 - Programming language: tsx
 - TabNine extension version: 1.67.2
 - Engine version (could be located within Tabnine Hub): 1.67.2

**Issue Details:**
"tabnine.inlineHintColor": "#00ffcc",
Don't take effect 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/69230517/172432608-3a1f3018-1858-41e4-9469-2178c94a824f.png">

gz#14884

**Comment by maya-tabnine** [comment]
Hi, did you try restarting your IDE after changing the color setting? If not, would you try and tell me if it helped? Was the setting saved or went back to default?

**Comment by bilucodota** [comment]
Hi KiligFei,

We haven't heard back from you in a while.

Would you please let me know if you still need my assistance?

Thank you,

Tabnine Support
<br><p><em><small>°°°</small></em></p>

**Comment by KiligFei** [comment]
No, thank you. It doesn't have much effect on me。It could also be that I turned on GitHub Copilot and caused the conflict
