### ISSUE TITLE
i can't remove tabnine from idea 20221.1

### ISSUE THREAD

**Issue by lnbiuc** [codota/TabNine#534]
- OS version: macOS 12.4 M1
 - Editor: idea
 - Editor version:	2022.1.1
 - Programming language: java js

Installing this plug-in is an mistack mistaken,because once you install, you can't uninstall again unless you reinstall idea.
When I uninstall this plugin in idea，but after I restart idea it is still in my plugin list,I tried many ways and still can't delete it.

This plugin makes my computer overheat，And most of the auto-completion codes are shit。

fk you tabnine

gz#15235

**Comment by lnbiuc** [comment]
I don't know.maybe it works,but I have reinstall my idea,and I will never use it again.Maybe the programmer of tannine should think why tabnine still load in idea after I uninstall it in the idea plugins setting.

**Comment by domano** [comment]
I have been trying to uninstall tabnine from my Goland IDEA IDE for months now, to no avail. Every time i restart the IDE it is back.

TabNine is malware for me now and if anybody mentions it i will strongly encourage them to not use it.

**Comment by maya-tabnine** [comment]
Hi Guys!
We found and fixed the uninstall bug some of you experienced. This is resolved now and won't happen again in the new release (version 0.7.10). I apologize for the trouble you went through.
