### ISSUE TITLE
TabNine is still unavaliable in VS2022

### ISSUE THREAD

**Issue by twoone-3** [codota/TabNine#537]
Hi!
Currently, Tabnine exists for Visual Studio 2019.
However, we do plan to expand to VS 2022. If we'd see enough interest from the community, we will make sure such a plugin exists.

_Originally posted by @maya-tabnine in https://github.com/codota/TabNine/issues/476#issuecomment-968785085_

gz#15917

**Comment by twoone-3** [comment]
I see the issue last year, but till now Tabnine is not in VS2022's markplace, I really want to try it in VS2022

**Comment by maya-tabnine** [comment]
Hi! You are correct. I get many requests for VS 2022, which is considered to be supported.
I am sorry I don't have any concrete news about that since a year ago. When we do add it, I will make sure to publish it here!
