### ISSUE TITLE
Can't uninstall tabnine from jupyter-lab

### ISSUE THREAD

**Issue by smarianimore** [codota/TabNine#540]
**please complete the following information:**	
 - OS version: macOS Big Sur 11.6.7 (20G630)
 - Editor: jupyter-lab
 - Editor version: jupyterlab v3.2.4, jupyter server 1.12
 - Programming language: Python
 - TabNine extension version: @tabnine/jupyterlab v0.0.24
 - Engine version (could be located within Tabnine Hub): don't know

**Issue Details:**
Apparently there is no way to uninstall tabnine from jupyter-lab or notebook

Origin of the issue is that I disabled tabnine from jupyterlab GUI but I see in console logs of jupyter server plenty of lines with `[W 2022-07-19 11:20:10.871 ServerApp] 404 POST /tabnine?1658222410865 (::1) 1.77ms referer=[omitted]`

I run `jupyter-labextension  list` to confirm whether tabnine is installed and got `/Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/labextensions
        @tabnine/jupyterlab v0.0.24 enabled  X (python, jupyterlab_tabnine)`

I then run `jupyter-labextension uninstall tabnine` and got `No labextension named "tabnine" installed`
I tried `jupyter-labextension uninstall jupyterlab_tabnine` and got the same
I then tried `jupyter-labextension uninstall @tabnine/jupyterlab` and got `JupyterLab cannot uninstall this extension. Use your Python package manager (pip, conda, etc.) to uninstall the package jupyterlab_tabnine`

Then I proceeded with `python3.9 -m pip uninstall jupyterlab_tabnine` and got `WARNING: Skipping jupyterlab_tabnine as it is not installed.`
I also tried `python3.9 -m pip uninstall tabnine` and `python3.9 -m pip uninstall jupyterlab-tabnine` with the same result

Finally I tried running `jupyter-nbextension list` and there is no tabnine indicated
Same for `jupyter-serverextension list`

I do not know anymore what to do....

gz#16394

**Comment by maya-tabnine** [comment]
Hi, can you try running `pip3 uninstall jupyterlab-tabnine` or `pip uninstall jupyterlab-tabnine`?

**Comment by smarianimore** [comment]
Hi @maya-tabnine , thanks for your kind reply.

Hi got the same `WARNING: Skipping jupyterlab_tabnine as it is not installed.` message.

**Comment by maya-tabnine** [comment]
Do you remember how you installed it? What command did you use? Was it in a conda envriment? 
Can you please send me the full output of `pip list`? Do you have the Jupyter Notebook plugin there by mistake maybe?

**Comment by maya-tabnine** [comment]
Also see this - https://stackoverflow.com/questions/66833296/how-to-prevent-jupyterlab-to-load-deleted-extensions?noredirect=1#comment118161760_66833296

**Comment by smarianimore** [comment]
yes I tried those specific things before posting an issue :)

**Comment by maya-tabnine** [comment]
Oh, I see, sorry then!
I am looking at this message online since it looks like it is not something related to Tabnine specifically but a general issue that occurs.
I found https://stackoverflow.com/questions/33412974/how-to-uninstall-a-package-installed-with-pip-install-user and https://superuser.com/questions/1718306/cannot-uninstall-ansible-with-pip-or-brew-on-mac-osx 
Maybe your solution will be on there?

**Comment by smarianimore** [comment]
Will try, many thanks for your assistance
