### ISSUE TITLE
Preferences settings are not showing

### ISSUE THREAD

**Issue by shasherazi** [codota/TabNine#541]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	 Windows 10
 - Editor: [e.g. vscode, intelij, sublime]	vscode
 - Editor version:	1.69.2
 - Programming language: [e.g. js, ts, c++]	All
 - TabNine extension version: 3.6.4
 - Engine version (could be located within Tabnine Hub): 4.4.81-57

**Issue Details:**
I don't like the inline suggestions of tabnine. I use github copilot for those. I used to just go to preferences of tabnine and turn off the inline suggestions and then I'd get tabnine suggestions in popups (idk the exact word for those) and copilot suggestions inline. I can't seem to find the preferences settings now, so I'm getting tabnine suggestions inline only which isn't what I want.

gz#16534

**Comment by bilucodota** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/16534'>Zendesk ticket #16534</a>)</i>

**Comment by shasherazi** [comment]
Link is broken for me

**Comment by DennySORA** [comment]
I have the same question as you

**Comment by mewforest** [comment]
Same question for me!
The option "Inline Completions" is gone from settings:

<img width="815" alt="Screenshot 2022-07-27 at 11 35 08" src="https://user-images.githubusercontent.com/15357833/181201402-b739cc9f-bdb9-44b8-8f93-9f0eaa1dbc88.png">

But it should be like in previous versions:


![](https://user-images.githubusercontent.com/60742964/128625904-da021af1-dbd9-48f8-907e-d2713486ea36.png)

**Comment by mewforest** [comment]
> Zendesk ticket #16534

Not found.

**Comment by maya-tabnine** [comment]
Hi guys!
For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion. 
This is the only manual way available now, but I think we will add an option on Tabnine Hub itself soon.

**Comment by Nerzal** [comment]
Heyho everyone, 
i'm unable to use TabNine, as I cannot stand the inline suggestions. 
The TabNine config file does not even exist in the documented paths.

How can I deactivate that behavior?

**Comment by oldmansutton** [comment]
> Hi guys! For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location) Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion. This is the only manual way available now, but I think we will add an option on Tabnine Hub itself soon.

Since instead of a nice preferences page like we used to have, we are forced to manually edit a .json config file, it would be helpful to have some sort of information about what all the options available in the config file do, as well as valid values to assign to these options.  I've been searching all morning, and can not find any information about what is actually in the config file.

**Comment by Nerzal** [comment]
Why is this closed? 
I still consider this an open issue. 

Removing configuration options and put them into more or less undocumented config files is not the best experience.
