### ISSUE TITLE
Please, Is there a way to disable inline suggestions and get old pop up multiple options? :'(

### ISSUE THREAD

**Issue by RAFALAMAO** [codota/TabNine#545]
**please complete the following information:**	
 - OS version: [Ubuntu 20]	
 - Editor: [vscode]	
 - Editor version:	
 - Programming language: [js, ts, python]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#16787

**Comment by maya-tabnine** [comment]
Hi see https://github.com/codota/TabNine/issues/541

For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion.

**Comment by RAFALAMAO** [comment]
:O!! Thank you very much!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RAFALAMAO** [comment]
Thank you!
