### ISSUE TITLE
PLZ GIVE US THE RIGHTS TO DISABLE INLINE SUGGESTIONS!!!

### ISSUE THREAD

**Issue by Zxis233** [codota/TabNine#546]
**please complete the following information:**	
 - OS version: [Win 11]	
 - Editor: [VSCODE]	
 - Editor version:	
 - Programming language: [python]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#16788

**Comment by maya-tabnine** [comment]
Hi! see https://github.com/codota/TabNine/issues/541

For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion.

**Comment by Zxis233** [comment]
ths a lot my friend! U R so helpful.
