### ISSUE TITLE
Please Recover the Classical Suggestion Widget Based Auto Completion

### ISSUE THREAD

**Issue by txaty** [codota/TabNine#547]
- OS version: macOS Monterey 12.5
 - Editor: Goland
 - Editor version: 2022.2
 - Programming language: Golang
 - TabNine extension version: 0.7.13
 - Engine version (could be located within Tabnine Hub): 4.4.98-46

Firstly I would like to thank Tabnine for providing such an excellent tool that helps us improve our productivity.
I have been using Tabnine Pro for more than half a year.
After upgrading to the latest version of Tabnine a few days ago, I found the trigger of inline completion disappeared in Tabnine Hub. I am pretty comfortable with the previous auto-completion and feel the inline completion is not easy to control sometimes. Maybe my Tabnine model hasn't been trained with sufficient data. It sometimes pops out related but not really useful completions, and they are refreshing quickly. This frustrated me a lot.
I really hope we can have the classical suggestion-widget auto-completion back and make it an option for us to choose more advanced completion features.
I will keep the plugin disabled until the feature rollbacks.

gz#16791

**Comment by maya-tabnine** [comment]
Hi! see https://github.com/codota/TabNine/issues/541

For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion.
This is the manual way available now.

**Comment by oldmansutton** [comment]
This is not good enough, as the dropdown suggestions have been crippled, and only suggest one word at a time now.  The functionality within the dropdown suggestions has been downgraded, which is unacceptable.
