### ISSUE TITLE
Please add back the old version config options

### ISSUE THREAD

**Issue by Cow258** [codota/TabNine#548]
**please complete the following information:**	
 - OS version: Mac Monterey 12.5 (21G72)
 - Editor: VSCode
 - Editor version: v1.70.0-insider
 - Programming language: js
 - TabNine extension version: v3.6.8-alpha.20220802084303
 - Engine version: 4.4.106-47

**Issue Details:**
### 1. Accidentally full multi-line guess when empty line,
Since the config option has been removed,
I can't change it to be guess single line only,
Please add back the option!
![image](https://user-images.githubusercontent.com/14261588/183304219-7190f8e1-5e59-4652-87ad-45d8da16d3ba.png)

### 2. Used too many RAM memory
Since the config option has been removed,
I can't config the usage of RAM,
Please add back the option!
![image](https://user-images.githubusercontent.com/14261588/183304335-cda91522-c172-4a87-82c4-acb4e41bceec.png)

gz#16883

**Comment by maya-tabnine** [comment]
Hi I would be happy to help.
1. I appreciate your feedback and will pass it on to the team.
Also, know that for now, if you want to go back to the popup short completions, you can by editing the config file. 
See https://github.com/codota/TabNine/issues/541
2. You can still control the model serving type - local machine / hybrid / cloud.
Please choose the cloud and see if the RAM usage is going back to normal.

**Comment by amirbilu** [comment]
Why don't add back the `GENERAL PREFERENCES` ? Any reason?
<br><p><em><small>°°°</small></em></p>

**Comment by uni-kim** [comment]
Please add back the options !!!!!!!

**Comment by maya-tabnine** [comment]
@uni-kim We discuss the subject and consider every request or feedback you guys share
