### ISSUE TITLE
Use Question

### ISSUE THREAD

**Issue by asassadsaf** [codota/TabNine#549]
Can tabnine set the prompt method of code in JetBrains IDEA? similar to method of cotada, select in the prompt list instead of directly displaying in gray font.

gz#17124

**Comment by maya-tabnine** [comment]
See https://github.com/codota/TabNine/issues/541 
For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion.
