### ISSUE TITLE
tabnine extension hides the code snippet list in Visual Studio 2019

### ISSUE THREAD

**Issue by to-osaki** [codota/TabNine#550]
**please complete the following information:**	
 - OS version: Windows 11
 - Editor: Visual Studio Community 2019
 - Editor version: Version 16.11.18
 - Programming language: C++, C#
 - TabNine extension version: 0.1.28
 - Engine version (could be located within Tabnine Hub): 4.4.107-11

**Issue Details:**

With tabnine extention, the code snippet list is empty.
Snippet > Insert snippets / Surround with

![with_tabnine](https://user-images.githubusercontent.com/47356931/185503508-8605155d-74c3-4f40-8d52-7262b16dc3cd.png)

To disable tabnine extension, it appears.

![disabled_tabnine](https://user-images.githubusercontent.com/47356931/185503523-f065bf35-f191-4aaa-989a-3a8266d04329.png)

gz#17185

**Comment by maya-tabnine** [comment]
When you type tabnine::config, does it open Tabnine hub?

**Comment by to-osaki** [comment]
Sure, type tabnine::config then open Tabnine hub.

**Comment by maya-tabnine** [comment]
Can you try to reinstall Tabnine? Perhaps this will resolve this.
And send us the logs from %homepath%/.tabnine

**Comment by to-osaki** [comment]
I did reinstall not only tabnine, but also Visual Studio, too.
But still snippets is not work.
(Disable/uninstall tabnine extention, then this problem is fixed.)
