### ISSUE TITLE
No option to disable inline completion as it was before

### ISSUE THREAD

**Issue by dreambit** [codota/TabNine#552]
**please complete the following information:**	
 - OS version: [MAC]	
 - Editor: [vscode]	
 - Editor version: last stable	
 - Programming language: [ts]	
 - TabNine extension version: last stable

**Issue Details:**
It is not possible to see suggestions in popup, inline is used instead, no option to disable it as it was before.

gz#17247

**Comment by maya-tabnine** [comment]
See https://github.com/codota/TabNine/issues/541
For now, you can edit the config file located at [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location)
Please set “inline_suggestions_mode” to false. Then Tabnine will work without inline suggestions but with the dropdown suggestion.

**Comment by dreambit** [comment]
Done, but no tabnine suggestions in the popup
