### ISSUE TITLE
How to use the functions of the old version

### ISSUE THREAD

**Issue by augushong** [codota/TabNine#555]
IDE:
vscode
Plugin Version:
3.6.14
Engine Version:
4.4.127-47

**Issue Details:**

I have enabled the new version, but it is not as good as the previous version.
But I can't find how to close the new version, and I don't know how to set it to the old version.
How should I set it?

gz#17566

**Comment by maya-tabnine** [comment]
What functions do you want back? We appreciate your feedback and would love to hear it.

**Comment by augushong** [comment]
I use vscode. Now the prompt function only has the prompt like copilot, and there is no automatic completion of the drop-down selection box.
I prefer auto completion with drop-down selection.
The current completion method can only complete words simply, and rarely complete effective intelligent prompts.
In addition, when using the drop-down box method, multiple cursors can also complete filling, but not now.

I prefer the usage in the screenshot below。

![图片](https://user-images.githubusercontent.com/31880431/189559611-9f4f1be0-76cf-4bd9-a1c0-72b02c3a40ff.png)

**Comment by maya-tabnine** [comment]
You should stay tuned for the dropdown returning to vscode (as an optional behavior) :) 
Also, see https://github.com/codota/TabNine/issues/541

**Comment by augushong** [comment]
but  there is no way to set anying.

![图片](https://user-images.githubusercontent.com/31880431/189637651-f9213e5b-ee47-47c0-9ef7-fb1caaec17fd.png)
![图片](https://user-images.githubusercontent.com/31880431/189637978-1f30479a-db21-43e0-9333-7be309e4009a.png)
![图片](https://user-images.githubusercontent.com/31880431/189638232-d5173bb3-e28b-4d11-9e16-48b3e45b5ca1.png)

**Comment by maya-tabnine** [comment]
It is not released yet. We are working on it.

**Comment by Sushil-kafle** [comment]
bring back old-style completion with drop-down selection only feature
