### ISSUE TITLE
Incorrect tabnine config path of Linux in the official website

### ISSUE THREAD

**Issue by linonon** [codota/TabNine#557]
**please complete the following information:**	
 - OS version: [Linux ubuntu 20.22 (WSL2)]	
 - Editor: [Vscode]	
 - Editor version: 1.7.0
 - Programming language: [None]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
#541 showed an URL about [Config file location](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location) , but the path of `Linux` in  the website seems wrong.

In my WSL2 , I found the tabnine config path in `~/.config/TabNine/tabnine_config.json`

gz#17658

**Comment by maya-tabnine** [comment]
Thank you!! We fixed it so other users will check both paths.
We appreciate you for writing this to us :)
