### ISSUE TITLE
missing cancel subscription link 

### ISSUE THREAD

**Issue by cazterk** [codota/TabNine#559]
I'm unable to cancel my subscription

gz#17969

**Comment by maya-tabnine** [comment]
Hi, you should be able to manage your subscription at https://app.tabnine.com/profile/subscription.
<img width="222" alt="Screen Shot 2022-09-14 at 16 01 31" src="https://user-images.githubusercontent.com/82452749/190160974-a67cf712-1c55-4dc6-bf59-4822782dc713.png">

If you have trouble there, email us at support@tabnine.com using your account email address and we'll help!
