### ISSUE TITLE
Cannot login from Tabnine Hub due to CORS.

### ISSUE THREAD

**Issue by stevenhay** [codota/TabNine#562]
**please complete the following information:**	
 - OS version: Mac Big Sur
 - Editor: tries neovim, vscode, and IntelliJ
 - Editor version: 0.8.0,  insiders
 - Programming language: [e.g. js, ts, c++]	N/A
 - TabNine extension version: 4.4.149
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/26744309/194349810-2a0b2450-e06d-4f66-abbe-adb71d859873.png">

**Comment by stevenhay** [comment]
And a lot of the time I end up on a page that looks like this:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/26744309/194364725-0ed3e7ee-468e-48b0-9f70-225edbe42aa6.png">

**Comment by KbyteTutu** [comment]
how did you fix this？im facing the same problem
