### ISSUE TITLE
Can not login on remote dev machine.

### ISSUE THREAD

**Issue by nansongyi96** [codota/TabNine#564]
**please complete the following information:**	
 - OS version: Mac Monterey 12.6, Ubuntu 22
 - Editor: vscode
 - Editor version:
 - Programming language: python
 - TabNine extension version: 3.6.15
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

My local machine is mac m1, dev machine is a gcp vm - Ubuntu 22.
Can not login Tabnine on remote dev machine.
I cannont open `Tabnine Hub` page inside vscode. (blank page)
When I try to click here: 
![image](https://user-images.githubusercontent.com/61266668/195145278-1c3c56a8-da05-47c3-b05a-bde158ca7932.png)
It just showed me a blank page.

gz#18581

**Comment by damix96** [comment]
same problem, cant login from remote machine. pro plan.

**Comment by FranklinYu** [comment]
It seems the same problem as in #360: the local instance occupied 5555, so the remote one cannot use the same port. It should probably make the port configurable so that users can specify something like 5556 or 5000.
