### ISSUE TITLE
Tabnine takes over localhost:5555, messing with other services

### ISSUE THREAD

**Issue by andrealmeidagit** [codota/TabNine#568]
Tabnine on VSCode is taking over localhost:5555, I can't run my own server on it. Why is it doing that anyway? Please remove this ~~bug~~ feature.

gz#19091

**Comment by JakubGIT** [comment]
The same here, it is very annoying indeed

**Comment by ksylvan** [comment]
Looks like this was fixed here: https://github.com/codota/TabNine/issues/422
