### ISSUE TITLE
Auto-complete becomes case-sensitive after installing TabNine

### ISSUE THREAD

**Issue by moeshinyo** [codota/TabNine#569]
- Editor: Intelij
 - Programming language: Golang
 - TabNine extension version: Latest （11/18/2022）

It would be nice to have a configuration item to enable/disable case-sensitivity. 

gz#19329

**Comment by dimacodota** [comment]
Hey @moeshinyo , can you share a screen recording of the issue?

**Comment by moeshinyo** [comment]
Hi @dimacodota , Sorry I can't reproduce it now. I will reopen this issue next time if I could provide more detail.
