### ISSUE TITLE
Unable to login within VS Code Dev Container

### ISSUE THREAD

**Issue by SofianeDjellouli** [codota/TabNine#573]
**please complete the following information:**	
 - OS version: [MX Linux (Debian)]	
 - Editor: [vscode]	
 - Editor version:	1.73.1
 - Programming language: [ts]	
 - TabNine extension version: 3.6.31
 - Engine version (could be located within Tabnine Hub): Not in  Tabnine Hub

**Issue Details:**
The link provided to login in Dev Container redirects to localhost which doesn't work. 

Looks like https://app.tabnine.com/auth/sign-in?tabnineUrl=http%3A%2F%2F127.0.0.1%3A5555%2Fsec-aubcluqkdorhpzfyslxd&sync=false&hubSiteUrl=http%3A%2F%2F127.0.0.1%3A5555%2Fsec-aubcluqkdorhpzfyslxd&queryData=...

It used to work before.

I'm on the paid version.

gz#19842

**Comment by TzufTabnine** [comment]
@dimacodota @amirbilu

**Comment by SofianeDjellouli** [comment]
Now working in latest version

**Comment by TzufTabnine** [comment]
@SofianeDjellouli Glad to hear that we are closing the issue.
