### ISSUE TITLE
Tabnine hub r.map is not a function

### ISSUE THREAD

**Issue by Stevemoretz** [codota/TabNine#574]
**please complete the following information:**	
 - OS version: Mac Catalina
 - Editor: intelij
 - Editor version: 2022.3
 - Programming language: [php]	
 - TabNine extension version: 0.7.32
 - Engine version (could be located within Tabnine Hub): Well I can't get there can I? :)

**Issue Details:**

When I open http://localhost:1234/preview?tabnineUrl=http%3A%2F%2Flocalhost%3A1234%2F (I changed the port from 5555 to 1234, seriously guys change the default port that port is one more than ADB port causing a headache for everyone who will ever be using ADB and tabnine along each other, took me 2 days to realize that and change that) anyways when I open that for a second I see the page load some stuff then suddenly it's gone, a white screen, there are a couple of errors in the console:

<img width="526" alt="Screen Shot 1401-09-14 at 19 03 28" src="https://user-images.githubusercontent.com/27680142/205677170-b733e8db-eb4f-4610-89bd-19a1369eb664.png">

It was working like until last night, today I got a notification in Intellij mentioning that Tabnine was updated successfully so that probably is related to the issue.

If I open home (http://localhost:1234/home?tabnineUrl=http%3A%2F%2Flocalhost%3A1234%2F) I get a slightly different error

<img width="534" alt="Screen Shot 1401-09-14 at 19 05 47" src="https://user-images.githubusercontent.com/27680142/205677676-361926bc-7818-43c7-99a5-15d63df611d2.png">

gz#19857

**Comment by assapir** [comment]
Also, in your network tab, can you please find a GET call to `/wow_moments` and send the response?

**Comment by Stevemoretz** [comment]
> Also, in your network tab, can you please find a GET call to `/wow_moments` and send the response?

Sure thanks for responding.

```html
<!doctype html><html lang="en"><head><script>!function(e,t,a,n,g){e[n]=e[n]||[],e[n].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});var m=t.getElementsByTagName(a)[0],r=t.createElement(a);r.async=!0,r.src="https://www.googletagmanager.com/gtm.js?id=GTM-PCHTQ8Z",m.parentNode.insertBefore(r,m)}(window,document,"script","dataLayer")</script><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#e032ee"/><meta name="description" content="Tabnine hub"/><link rel="apple-touch-icon" href="/logo256.png"/><link rel="manifest" href="/manifest.json"/><title>Tabnine Hub</title><script defer="defer" src="/static/js/main.c76266d1.js"></script><link href="/static/css/main.51306a6f.css" rel="stylesheet"></head><body style="overflow-y:auto"><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PCHTQ8Z" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><noscript>You need to enable JavaScript to run this app.</noscript><script>document.addEventListener("keydown",(e=>{const t={altKey:e.altKey,code:e.code,ctrlKey:e.ctrlKey,isComposing:e.isComposing,key:e.key,location:e.location,metaKey:e.metaKey,repeat:e.repeat,shiftKey:e.shiftKey};window.parent.postMessage({type:"keydown",event:t},"*")})),document.addEventListener("click",(e=>{let t=e.target;for(;t.parentElement;){if("a"===t.localName&&"_blank"===t.target)return void window.parent.postMessage({type:"link-click",href:t.href},"*");t=t.parentElement}}))</script><div id="root"></div></body></html>
```

Full request response:

```curl
curl 'http://localhost:1234/wow_moments' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: _gcl_au=1.1.111741836.1670253298' \
  -H 'DNT: 1' \
  -H 'Referer: http://localhost:1234/home?tabnineUrl=http%3A%2F%2Flocalhost%3A1234%2F' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --compressed
```

**Comment by assapir** [comment]
Hey
The fix should now be in the latest release of the Tabnine binary. Please make sure you are using the 4.4.200 version.

**Comment by assapir** [comment]
Yes, it should be updated automatically.

**Comment by Stevemoretz** [comment]
Thanks
