### ISSUE TITLE
I used to see  the Tabnine Pro icon in Webstorm is not longer there.  I don't know if it is running or not.  

### ISSUE THREAD

**Issue by tadsn3w** [codota/TabNine#575]
- OS version: WIN10
 - Editor: WebStorm
 - Version: 2922.3 Build #WS-223.7571.168
 - Programming language: JS and React
I don't see the tabnine hub in WebStorm.  I went to site and I cannot find that information 

**Issue Details:**
I used to see the tabnine HUB, but last night I clicked on it and updated the plugin.  The icon is gone.  I rebooted, restart IDE, removed the plugin, installed it again. The Tabnine Pro icon is gone.

gz#20009

**Comment by TzufTabnine** [comment]
@amirbilu

**Comment by amirbilu** [comment]
Hi @tadsn3w is this is still happening? if so - can you please send your [Tabnine logs](https://support.tabnine.com/hc/en-us/articles/5283541356689-JetBrains) to support@tabnine.com?
