### ISSUE TITLE
Unable to add team members, unable to purchase.

### ISSUE THREAD

**Issue by qzhly1234567** [codota/TabNine#576]
- OS version: Mac	
 - Editor: webstorm
 - Programming language: js

Issue Details:
I want to invite others to join my team, but I can't buy it. I debugged it and found that your interface has been reporting errors! Is this the reason?
![image](https://user-images.githubusercontent.com/33216507/206973165-e242822d-95f4-4e32-81ae-6936b09f408d.png)

gz#20075

**Comment by yanir-codota** [comment]
Hi, 
Thanks for reporting this. 
Our team is investigating the issue. It appears to be an integration issue with our payment provider and some of the digital wallets. 
Will update once it had been resolved.

**Comment by yanir-codota** [comment]
Hi again, 
Following up on this issue. seems this is specifically related to your payment method.
Please contact support at support@tabnine.com (please provide a reference to this issue) for assistance in resolving this matter.
