### ISSUE TITLE
Lot of delay and buffering in the suggestions

### ISSUE THREAD

**Issue by i-ice-bear** [codota/TabNine#577]
**Here, are my information about my specs:**	
 - Os version: Windows 10 Home Single Language version: 22h2
 - Editor: Microsoft vscode, Intellij Idea
 - Editor version:	Latest
 - Programming language: Reactjs, Javascript, Java	
 - TabNine extension version: Present

**Issue Details:**
### Delay in the code recommendations also affects emmet,
Usually, when I do programming into react.js and any other programming language via vscode The recommendation didn't work as much as it could and also affected emmet when I uninstalled tab-nine from vscode the inbuilt emmet started working effectively. The same problem also occurs in other ide's Please work on the optimization of tab-nine to make it more efficient 

gz#20223

**Comment by i-ice-bear** [comment]
Okay, I'll provide you with a short screen recording, it will definitely explain everything about the malfunctions. 

I'm sending you two videos one is without tab nine and another one is with tab nine in vscode javascript.

It's a sneak peek of without tabnine
https://user-images.githubusercontent.com/108215633/208523916-7261d72f-3fac-49e2-a4be-fa4337f3f2f8.mp4

It's a sneak peek of tabnine 
https://user-images.githubusercontent.com/108215633/208524276-469b0634-948c-456a-bc24-3f3b80ad0067.mp4

And, sometimes when I'll work in reactjs and nextjs frameworks, suggestions almost stopped working during the sessions.

**Comment by TzufTabnine** [comment]
@yairco1990
