### ISSUE TITLE
Inline suggestion disabled causes no suggestion anymore (VS Code, last v)

### ISSUE THREAD

**Issue by florin-botea** [codota/TabNine#578]
this is related to: 
https://github.com/codota/TabNine/issues/552

My first experience with tabnine was great because it was only popup suggestions. Now, after some updates, I get only inline suggestions which I find glitchy, confusing and hard to apply. I want to disable inline suggestions but to put them in popup suggestions. I changed inline_suggestion_mode from null to false,  but now tabnine seems to do nothing... What would be the propper settings for this?

gz#20401

**Comment by TzufTabnine** [comment]
@florin-botea
Please see https://github.com/codota/TabNine/issues/581, to see if it fixes the issue.

**Comment by php-templates** [comment]
You can close this.
I'done the following:
-uninstall tabnine
-deleted %appdata%/tabnine
-searched TabNine in %appdata% (cache) and deleted anything I have found
-reinstalled TabNine, seted to Hybrid model
-changed inline_suggestions in tabnine_config.json to false
now its work like a charm!
Please take in consideration to not remove popup suggestions in the future, else we will be very sad :( . Thanks!
