### ISSUE TITLE
no suggestions or autocomplete for .svelte files aka script tag or style tag content

### ISSUE THREAD

**Issue by WYousefSaid** [codota/TabNine#579]
**please complete the following information:**	
 - OS version: [linux mint 21]	
 - Editor: [Webstorm]	
 - Editor version:	2022.3.1
 - Programming language: [js,html,css, svelte]	
 - TabNine extension version: newest
 - Engine version (could be located within Tabnine Hub): 
4.4.210-60

**Issue Details:**
no autocomplete or suggestion works in simple plain .svelte file with vanilla js in script tag but in normal .js files works perfectly is it not supported or i need to edit config somewhere in order to make it work? 

gz#20408

**Comment by TzufTabnine** [comment]
@amirbilu

**Comment by TzufTabnine** [comment]
@dimacodota

**Comment by TzufTabnine** [comment]
Hi @WYousefSaid 
JS is fully supported, and supporting .svelte is under process.

**Comment by TzufTabnine** [comment]
Hi @WYousefSaid 
We are supporting  **.svelte** now.
