### ISSUE TITLE
 Whole-line code completions not working

### ISSUE THREAD

**Issue by medskill** [codota/TabNine#580]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina] Linux
 - Editor: [e.g. vscode, intelij, sublime] PhpStorm
 - Editor version:	2021.1.2
 - Programming language: [e.g. js, ts, c++] js (nodejs)	
 - TabNine extension version:  0.8.5
 - Engine version (could be located within Tabnine Hub):  4.4.210-60

**Issue Details:**
Whole-line code completions not working on Pro version
![Screenshot 2022-12-28 08 37 04](https://user-images.githubusercontent.com/7580219/209776177-931a5124-9e35-491e-ac2f-f60450a71e19.png)

gz#20451

**Comment by TzufTabnine** [comment]
@dimacodota

**Comment by TzufTabnine** [comment]
@amirbilu

**Comment by amirbilu** [comment]
Hi @medskill 
Thanks for reaching out. 

Can you elaborate on what you're experiencing? a video would be great

**Comment by medskill** [comment]
Hello @amirbilu,

in a Starter plan the code wasn't complete and i can understand that, but in in Pro plan i was expecting to see the code completed, but got the same result (but maybe i understood wrong the `whole-line & full-function code completions` limitations between the 2 plans).

A simple command like "Make a PUT request using requests lib" should give an example of making a PUT request using requests library, something like

```js
const request = require('request');

const options = {
  url: 'http://www.example.com/api/resource/1',
  method: 'PUT',
  json: {
    name: 'John',
    age: 30
  }
};

request(options, function(error, response, body) {
  if (!error && response.statusCode == 200) {
    console.log(body);
  }
});
```

In my example, the request isn't complete, there's only an incomplete object `options`. The `request` library is not used at all. I have the same result on Mac.

**Comment by amirbilu** [comment]
Hi @medskill 

Sorry for the confusing. I get the misunderstanding.

The completions you're seeing are of PRO subscription. Reason why you're seeing them in starter plan is since every user gets 2 weeks preview of PRO subscriptions.

As for the completion itself - we're working on tuning the results to return complete blocks. Will keep you posted here on the progress.
