### ISSUE TITLE
Provide information on valid config file options and values

### ISSUE THREAD

**Issue by oldmansutton** [codota/TabNine#582]
**please complete the following information:**	
 - OS version: Ubuntu 20.04	
 - Editor: vscode
 - Editor version:	1.74.3
 - Programming language: js, php
 - TabNine extension version: 3.6.36
 - Engine version (could be located within Tabnine Hub): 4.4.225-60

**Issue Details:**
Since the removal of the user-friendly preferences option (a backwards move imo), we are left with having to edit  the tabnine_config.json file manually.  Ok, we're programmers, no problem, right?  Well, the problem comes that we don't know what all the options necessarily do within this config file, nor what the valid values for the options are.  Since this is now our only way to configure most Tabnine preferences, it would be helpful if this information was readily available and easily accessible, somehow.  A help page on the website, a wiki page in GitHub, something.

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/20996'>Zendesk ticket #20996</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/20996'>Zendesk ticket #20996</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/20996'>Zendesk ticket #20996</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @oldmansutton 

Our product team would like to understand what exactly would you like to configure/change in Tabnine. Can you please attend a 15 minutes session with Daniel from our product team? If so, please make your appointment [here](https://calendly.com/daniel-2010/tabnine-feedback-session?month=2023-01)

**Comment by oldmansutton** [comment]
Highly unlikely that I can take time out from my workday.  The issue isn't that I'm looking to change something specifically, the issue is that I have no idea what I CAN change, what the various options (keys in the JSON file) DO, or what the available values for these keys ARE.  The product USED to have a user friendly configuration, now people are pointed to the .json file to configure TabNine, but the .json file is a black box.

**Comment by TzufTabnine** [comment]
@oldmansutton Thanks. At the moment, Tabnine configuration is only via the Hub. In the past, we let users change some keys in the config file only for technicality, but it is not available anymore. We encourage you to meet with our product manager to help us understand your exact needs from Tabnine.

**Comment by oldmansutton** [comment]
@TzufTabnine I'm sorry, but Tabnine configuration is NOT only via the Hub, please reference [Issue 541](https://github.com/codota/TabNine/issues/541#issuecomment-1406560463) for example, where we are required to use the config file to change basic options.

Since we are forced to manually update the config file, I really don't think it's asking a whole heck of a lot to know what is in that file.
