### ISSUE TITLE
`tabnine starter` takes up too much room in the VSCode status bar

### ISSUE THREAD

**Issue by lacymorrow** [codota/TabNine#583]
Affects anyone using the VSCode extension.

The VSCode app has limited room in the status bar (the blue bar at the bottom of the IDE). 
Currently, out of every extension and add-on I have running, `tabnine starter` is taking up more room than any other status menu.
See image:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1311301/216476395-67d7aca6-9e72-48ed-a6f3-d78c99c77365.png">

This is especially frustrating on smaller screens or window sizes, since some status icons become hidden. Other extensions are very conservative of their space usage, for example: Github Co-pilot uses a single character icon
See image:

<img width="89" alt="image" src="https://user-images.githubusercontent.com/1311301/216476454-304da998-70ec-437d-9438-5861f1101616.png">

Even more, TabNine as a name lends itself _perfectly_ to shortened versions. For example, instead of `tabnine starter` you could use `t9`. You can differentiate premium from starter users with a star or other visual element (Maybe `T9`!).

Please be respectful of users' IDEs, or you will have to work harder to find more users.

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21115'>Zendesk ticket #21115</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21115'>Zendesk ticket #21115</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @lacymorrow, Thanks for the feedback.
We will look into that.
