### ISSUE TITLE
vscode tabnine macos using massive amount of memory

### ISSUE THREAD

**Issue by amouratoglou** [codota/TabNine#584]
**please complete the following information:**	

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	8 (6 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1
  Serial Number (system):	PXV2NH7PF4
  Hardware UUID:	BBDFD01F-F1D6-5D82-B6CC-A22976C422F7
  Provisioning UDID:	00006000-000828CA3438801E
  Activation Lock Status:	Disabled

Tabnine process was using massive amount of memory and making vscode work very slow.
Deleted and all works well.

gz#21141<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21141'>Zendesk ticket #21141</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21141'>Zendesk ticket #21141</a>)</i>

**Comment by TzufTabnine** [comment]
@amouratoglou 

Can you please send us the config file to support@tabnine.com? See [here](https://support.tabnine.com/hc/en-us/articles/5232194870673-Config-file-location) how to find it.

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21141'>Zendesk ticket #21141</a>)</i>

**Comment by TzufTabnine** [comment]
<i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21141'>Zendesk ticket #21141</a>)</i>
