### ISSUE TITLE
Unable to change email address

### ISSUE THREAD

**Issue by thatoddshade** [codota/TabNine#586]
**TabNine** Web Site is telling me to verify my email, but I lost the one I used to sign in. 
![image](https://user-images.githubusercontent.com/115649477/218268781-10cb38cc-896b-4786-99da-a8ae6b9b35d7.png)

I checked the **My Profile** section to see if I could replace the current email address... but it seems like there is no option to do this. 
![image](https://user-images.githubusercontent.com/115649477/218269052-ecaa8ee8-8396-4c96-be98-5a4721df1d35.png "​        
blurred the email just to act like if i was a professional photoshop user
        ​")

Do I have to delete and recreate an account only to change that email address ?

###### please help me

gz#21279<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21279'>Zendesk ticket #21279</a>)</i>

**Comment by TzufTabnine** [comment]
@thatoddshade 
Please contact support@tabnine.com and we will handle your request.

**Comment by TzufTabnine** [comment]
@thatoddshade 
Were you able to sign in with your new email address?

**Comment by thatoddshade** [comment]
> @thatoddshade Were you able to sign in with your new email address?

No, I tried my new email address but it did not work. Logging in using GitHub still works.

**Comment by TzufTabnine** [comment]
@thatoddshade 
 I deleted your old account's email. You can sign up with your new email. Please let me know if it works

**Comment by thatoddshade** [comment]
Yes, it worked. Thanks for support.
