### ISSUE TITLE
Why is TabNine scanning my drives?

### ISSUE THREAD

**Issue by awsms** [codota/TabNine#587]
I can see in lsof TabNine scanned all the drives (and their full content) connected to my computer. Is there any relevant reason why it should?

gz#21434<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21434'>Zendesk ticket #21434</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @awsms 
Tabnine is not scanning all your drivers. Is there a reason you think it is?
Please read [here ](https://www.tabnine.com/code-privacy)for more information about our code privacy.

**Comment by awsms** [comment]
>Tabnine is not scanning all your drivers. Is there a reason you think it is?

Yes, I heard my mechanical hard drive rotating (it's literally never used in my system), so I did an lsof, then grepped the path to the drive because this made me suspicious.
Then I saw 20% of the files on it being read by the TabNine process as mentionned in OP.

**Comment by TzufTabnine** [comment]
@awsms 
Tabnine **ONLY** scanning your the open projects, nothing else.
