### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by inforithmics** [codota/TabNine#588]
**please complete the following information:**	
 - OS version: Windows 11	
 - Editor: Visual Studio 2022	
 - Editor version: 17.5	
 - Programming language: c#	
 - TabNine extension version: not applicable
 - Engine version not applicable 

Currently there is only Tabnine for Visual Studio 2019 available it would be fantastic to have Tabnine available for Visual Studio 2022 too.

Currently only Github Copilot is "usable" in Visual Studio 2022. The "usable" part is in high commas because I had some node.js Certification issues. While tabnine simply worked. (Tested it in Rider). And Tabnine reacts faster for simple suggestions, because parts of it run locally.

gz#21508<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21508'>Zendesk ticket #21508</a>)</i>

**Comment by TzufTabnine** [comment]
@inforithmics 

Thanks for contacting us.
 
Unfortunately, we are not supporting Visual Studio 2022 at the moment. It might change soon, so please follow us on [Facebook](https://www.facebook.com/TabnineInc/), [Linkedin](https://il.linkedin.com/company/tabnine), and [Twitter](https://twitter.com/tabnine) for any updates. For the best Tabnine experience, please use VSCode/Jetbrains.

Our Product Manager, Daniel, would love to speak with you. Please set your appointment [here](https://calendly.com/daniel-2010/tabnine-feedback-session?month=2023-01).

**Comment by NSouth** [comment]
I would just like to +1 this request. Visual Studio is a major IDE, especially for .NET developers. Tabnine could be one of the only competitors to GitHub Copilot for Visual Studio users if it added support.

**Comment by TzufTabnine** [comment]
As promised, VS 2022 extension is now available as a Beta. See [here](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-visual-studio). Please do share your thoughts with us.

**Comment by UkeHa** [comment]
@TzufTabnine, for me Tabnine doesn't recommend anything and clicking on the menu item in addons just leads to the entire UI hanging for roughly 5 seconds and then nothing happens. I don't get any recommendations and there is also no way to login etc.

Do you require some more info?

![grafik](https://github.com/codota/TabNine/assets/2254304/cb49eb93-5a2b-4650-96cb-fb2fbabf7fec)

System:
Latest x64 Win 11
Visual Studio x64 Version 17.6.5 (latest stable)

**Comment by TzufTabnine** [comment]
Hi @UkeHa,
Can you please send us the log files? See [here ](https://support.tabnine.com/hc/en-us/articles/5991785480337-Visual-Studio-2022-logs)how to do that

**Comment by UkeHa** [comment]
@TzufTabnine sure, i've sent the log.
