### ISSUE TITLE
Getting "invalid secret" when logging in

### ISSUE THREAD

**Issue by BladeMF** [codota/TabNine#590]
**please complete the following information:**	
 - OS version: Win 11 22H2
 - Editor: vscode
 - Editor version: 
```
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
 - Programming language: PHP
 - TabNine extension version: v3.6.41
 - Engine version (could be located within Tabnine Hub): 4.4.250-60

**Issue Details:**
When TabNine is run in Docker, when you log in, the login itself runs OK and I get this screen:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12109622/221660577-9c2d7697-7a5f-4b6d-9d7b-086cba1d8688.png">
I tried reinstalling. Rebuilt the whole container even. I am out of ideas.

gz#21667<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21667'>Zendesk ticket #21667</a>)</i>

**Comment by TzufTabnine** [comment]
@BladeMF 
Try follow the steps [here](https://support.tabnine.com/hc/en-us/articles/12218652562449-Generating-a-token-to-log-in-to-Tabnine-Hub). Make sure you close all other Tabnine instances
