### ISSUE TITLE
Disable Path Suggestion

### ISSUE THREAD

**Issue by Reckit075** [codota/TabNine#591]
**please complete the following information:**
 - OS version: [e.g. Win 10, Mac Catalina]	[Win 10]
 - Editor: [e.g. vscode, intelij, sublime]	[vscode]
 - Editor version:  the last one
 - Programming language: [e.g. js, ts, c++] [js]
 - TabNine extension version: 0.8.12
 - Engine version (could be located within Tabnine Hub):  4.4.210-60

**Issue Details:**
Is it possible to remove suggestions related to the path?
For now, tabNine gives me no appropriate suggestions.

gz#21884<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21884'>Zendesk ticket #21884</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @Reckit075,
Can you please give us some examples (screenshots/videos)?

**Comment by Reckit075** [comment]
@TzufTabnine Sure here -> 
![image](https://user-images.githubusercontent.com/47884779/223703984-b05448c4-35f6-4f62-a822-e445faadf218.png)
![image](https://user-images.githubusercontent.com/47884779/223704106-3c6dddee-13e1-4803-99f0-c64f0f49baf6.png)

**Comment by TzufTabnine** [comment]
@Reckit075 

We are working on that feature. At the moment, it's not possible.

**Comment by Reckit075** [comment]
@TzufTabnine ok, I'll be waiting for that then. Thanks
