### ISSUE TITLE
Ability to stop Welcome to TabNine / Getting Started popup with vscode settings

### ISSUE THREAD

**Issue by xangelix** [codota/TabNine#592]
- OS version: Linux Arch Rolling Release
 - Editor: Gitpod VSCode
 - Editor version:	1.76.0
 - Programming language: NA
 - TabNine extension version: v3.6.41
 - Engine version (could be located within Tabnine Hub): NA

**Issue Details:**

The extension works flawlessly with [Gitpod VScode](https://www.gitpod.io/), including automatic logins, however, the "Getting Started with TabNine" page shows on every startup.
Along with other extensions that may do this, it makes interacting with the environment on load difficult and frustrating, as popups grab interactivity away from the user.

Other extensions have fixed this issue in Gitpod and similar containerized environments by implementing settings that stop the popup on installation or update.
For example,

```
    "gitlens.showWelcomeOnInstall": false,
    "gitlens.showWhatsNewAfterUpgrades": false,
```

or

```
    "vsicons.dontShowNewVersionMessage": true,
```

Adding this functionality would be great for similar environments.

gz#21967<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/21967'>Zendesk ticket #21967</a>)</i>

**Comment by TzufTabnine** [comment]
@xangelix 

Unfortunately, we don't have this feature at the moment.
