### ISSUE TITLE
TabNine.exe Timeout how to fix 

### ISSUE THREAD

**Issue by souravh093** [codota/TabNine#593]
![Screenshot_13](https://user-images.githubusercontent.com/54834807/225300829-c58c6724-0ef4-4a2d-b1e3-01d2095ba8c5.png)
**please complete the following information:**	
 - OS version: 11
 - Editor:  vscode
 - Editor version: 1.76.1	
 - Programming language: JavaScript	
 - TabNine extension version: tabnine.ext timeout error in vs code dev tool
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#22065<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22065'>Zendesk ticket #22065</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @souravh093 

Can you run the command you see in the console window from a windows command prompt and see if it works?
