### ISSUE TITLE
Manually Trigger Inline Completion

### ISSUE THREAD

**Issue by sam-ulrich1** [codota/TabNine#594]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]
   linux
 - Editor: [e.g. vscode, intelij, sublime]	
   vscode & jetbrains suite
 - Editor version:
   lastes for both
 - Programming language: [e.g. js, ts, c++]	
   all
 - TabNine extension version:
   latest
 - Engine version (could be located within Tabnine Hub): 
  n/a

**Issue Details:**
Pretty often when using tabnine with intelligent editors i find the editor's internal behavior fighting with tabnine. Auto-indent is by far the biggest issue. Jetbrains will auto indent my next line and tabnine will not know to give a suggestion. Often times i find myself hitting shift+tab then tab to trigger the completions. Also in certain cases the completion runs out but there is more code to be written on that line.

If we had a key combo that effectively allowed us to manually request an inline completion the tool would perform much better in many of the cases I am running into

gz#22255<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22255'>Zendesk ticket #22255</a>)</i>

**Comment by SimSimY** [comment]
Hey @sam-ulrich1 

There is a key binding named `trigger.inline.suggestion` in VSCode which does that.

Let me check if JetBrains has a similar shortcut.

**Comment by SimSimY** [comment]
I've tried it before posting, so let me know if it work for you.

Regarding JetBrains, there isn't a shortcut at the moment but we are working on adding it, and I'll update here once we have it.

In addition, It would like to see some examples of TabNine collisions with your IDEs, as this seems to be the root issue and usually we can address such issues, if you can, please send short videos of the issue to support@tabnine.com

**Comment by sam-ulrich1** [comment]
Ya, I'll definitely send it over. Next time I run into it I'll take a few videos. Shouldn't be long
