### ISSUE TITLE
TabNine doesn't pick up Proxy Settings from IntelliJ

### ISSUE THREAD

**Issue by SkyProgs** [codota/TabNine#595]
**please complete the following information:**	
 - OS version: Windows 11
 - Editor: Intellij IDEA Ultimate
 - Editor version: 2023.1
 - Programming language: doesn't matter
 - TabNine extension version: 1.0.0
 - Engine version (could be located within Tabnine Hub): 4.4.273-60

**Issue Details:**
I was just about to set up TabNine on my new work computer. 

Unfortunately TabNine can't connect to the servers because a proxy must be used. This proxy is stored in the settings of IntelliJ and works there without any problems. 

But TabNine does not use these settings. 

Is there somewhere a possibility to set a proxy for TabNine? I can't set http_proxy and https_proxy variables globally on my work computer for various reasons. 

Thanks for your help in advance :-)

gz#22530<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22530'>Zendesk ticket #22530</a>)</i>

**Comment by TzufTabnine** [comment]
@SkyProgs 
We are working on a fix for the issue above.

**Comment by TzufTabnine** [comment]
In the meantime, can you try and add the Proxy values int the IDE settings? See example here:
![image](https://user-images.githubusercontent.com/121427912/229342460-5b10ff0c-dd7d-46fe-b17d-68b3fd5597b1.png)

**Comment by SkyProgs** [comment]
Hi @TzufTabnine,

thanks for the Update :) 

I added the Proxy Values inside the Path Variables, but I think it doesn't work, at least I don't see any different behaviour. The Login doesn't work and Tabnine also reports "there seems to be a problem downloading the model".

**Comment by SkyProgs** [comment]
I don't know if you have already changed something, but it seems to be working now. Maybe the Path Variables needed a few restarts to take effect, I don't know. 

Thanks for your help :)

**Comment by TzufTabnine** [comment]
@SkyProgs 
We fixed the issue. we are now getting the settings from IJ.
