### ISSUE TITLE
Tabnine is really slow to give me suggestion

### ISSUE THREAD

**Issue by imronpuji** [codota/TabNine#596]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
Tabnine is really slow to give me suggestion, i dont know what happen, i already upgrade to pro

gz#22604<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22604'>Zendesk ticket #22604</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @imronpuji,
Can you add here a video of the described behavior?

**Comment by imronpuji** [comment]
ohh emm sorry, my bad, the problem with my wifi network is slow, so this is affect to performance of tabnine
