### ISSUE TITLE
中文乱码 The annotation information in Chinese is garbled

### ISSUE THREAD

**Issue by runfengai** [codota/TabNine#600]
**please complete the following information:**	
 - OS version: Mac Catalina
 - Editor: android studio
 - Editor version:	electric Eel | 2022.1.1 patch 2
 - Programming language: kotlin
 - TabNine extension version:1.0.6
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

gz#22994<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/22994'>Zendesk ticket #22994</a>)</i>

**Comment by TzufTabnine** [comment]
@runfengai 
Can you share a screenshot of some examples?

**Comment by runfengai** [comment]
> @runfengai Can you share a screenshot of some examples?
![ERR](https://user-images.githubusercontent.com/23287016/236596746-bb1cdada-1703-449e-a4ca-df332d3e6706.jpeg)

sure， like this

**Comment by TzufTabnine** [comment]
@runfengai 
Thanks, we will add it to our backlog.

**Comment by jlhg** [comment]
I also had the same issue on Emacs plugin. It would be appreciated if you could fix it soon.

![未命名](https://github.com/codota/TabNine/assets/2265716/7448fa21-cd58-438c-a52b-d5dc79463d88)

Tabnine version: 4.4.200 and 4.4.322.

**Comment by 9p15p** [comment]
我也遇到了对应的情况

**Comment by sameal153** [comment]
最新版还是存在中文乱码的问题

**Comment by gt1226500986** [comment]
I'm also having the same issue, it's still the case in pycharm, it hasn't been resolved

**Comment by dxrun** [comment]
so am I

**Comment by hank9999** [comment]
same problem
