### ISSUE TITLE
Tabnine

### ISSUE THREAD

**Issue by emjenn** [codota/TabNine#601]
Linked to Zendesk issue 

gz#23235<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23235'>Zendesk ticket #23235</a>)</i>

**Comment by amirbilu** [comment]
Hi emjenn,

Thanks for using Tabnine!

I'm not sure I fully understand your request,
It would be great if you could provide some more info.

Thank you,

Tzuf Stokelman
Tabnine Support
<br><p><em><small>°°°</small></em></p>
