### ISSUE TITLE
VS 2022 support please

### ISSUE THREAD

**Issue by GunterGlad** [codota/TabNine#602]
**please complete the following information:**	
 - Windows 11
 - Visual Studio
 - Editor version:	2022
 - Programming language: ts, c#
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
Please add support for Visual Studio 2022

gz#23341<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23341'>Zendesk ticket #23341</a>)</i>

**Comment by TzufTabnine** [comment]
@GunterGlad 
We are planning to support VS 2022 soon.

**Comment by GunterGlad** [comment]
I am looking to implement an AI code assistant for our organization, but we all run VS 2022. So no support will be a deal breaker. Do you have any indication of when you will have support? Soo, as in 1 week, or soon as in 1 year?

**Comment by TzufTabnine** [comment]
@GunterGlad 

It will be available in Q3. 
Can I ask what organization you are working for?

**Comment by TCNOco** [comment]
We have been asking for a long time...
https://github.com/codota/TabNine/issues/476

I don't think support is ever coming, but I'm glad there are other products that support 2022 now :)

**Comment by TzufTabnine** [comment]
Hi @TCNOco ,
As I mentioned, we plan to support it next quarter in Q3. We are working on it.

**Comment by TzufTabnine** [comment]
@TCNOco @GunterGlad As promised, VS 2022 extension is now available as a Beta. See [here](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-visual-studio). Please do share your thoughts with us.
