### ISSUE TITLE
Sharing models between machines

### ISSUE THREAD

**Issue by LDenninger** [codota/TabNine#603]
Hey all,

First, great work, TabNine really boosts my everyday workflow. Still, I have a question for my use and I do not find another way to ask it.

I primarily use TabNine on my own laptop but I am also coding on remote machines. I see that the code completions on the remote machines are not as advanced and good as on my own machine (I use pro and the same settings as on my own machine). I assume that my local model is trained better over the course of the usage. Could someone clarify for me how the training and sharing between local and remote models work? And further maybe give me a hint or settings I have to change to have the same elaborated auto completions on the remote machines than on my own machine?

Some data about my settings:
Version: Pro
AI Model: Universal Model Advanced
Model Serving Mode: Hybrid

I would really appreciate some help here.

Greetings, Luis

gz#23576<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23576'>Zendesk ticket #23576</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @LDenninger 
When you are working on the remote machine, are you signed in (can you see 'tabnine pro' in your status bar)?
How is the internet connection (the advanced completions are coming from our cloud, so you need a decent internet connection)?

**Comment by LDenninger** [comment]
Hey, I have Pro activated, the machine has a very good internet connection (Faster than my notebook). Everything is the same but the code completions are way worse.

**Comment by TzufTabnine** [comment]
@LDenninger 
Can you please send us a video?

**Comment by TzufTabnine** [comment]
@LDenninger Can you please your remote log files?
See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by LDenninger** [comment]
@TzufTabnine Yes, sure. I recreated the same scenario as in the video.

[tabnine_logs-44714_rCURRENT.log](https://github.com/codota/TabNine/files/11479648/tabnine_logs-44714_rCURRENT.log)

**Comment by TzufTabnine** [comment]
@LDenninger 
Can you also send us a screenshot of the _Help->Toggle Developer Tools_?

**Comment by TzufTabnine** [comment]
@LDenninger Sorry I wasn't clear, Please send a screenshot of:
_Help->Toggle Developer Tools->Console_

**Comment by LDenninger** [comment]
@TzufTabnine . Ah okey, that mkes more sense. I appended the screenshot. Greetings


![Screenshot_20230518_103220](https://github.com/codota/TabNine/assets/64429074/4d5175e6-083d-41e3-a5b5-6463d1480ea1)

**Comment by LDenninger** [comment]
@TzufTabnine  ?

**Comment by TzufTabnine** [comment]
Hi @LDenninger 
Sorry for the late response.

Try to install the **latest** tabnine plugin for VSCode and replicate the issue. Please send us the _Help->Toggle Developer Tools->Console_ after you do that.
