### ISSUE TITLE
Insignificant characters appear in code completion

### ISSUE THREAD

**Issue by KnightYin** [codota/TabNine#604]
**please complete the following information:**	
 - OS version: Mac Ventura 13.2	
 - Editor: vscode
 - Editor version: 1.78.2 (Universal)
 - Programming language: Java
 - TabNine extension version: 3.6.46
 - Engine version (could be located within Tabnine Hub): 4.4.312-60

**Issue Details:**

The current code completion does not complete the code at all when it is a single line, it always completes a bunch of meaningless characters.

![image](https://github.com/codota/TabNine/assets/23274552/7bbbffa6-6950-484d-b533-0f1624cdc7dd)

gz#23595<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23595'>Zendesk ticket #23595</a>)</i>

**Comment by KnightYin** [comment]
I am a subscriber of the pro version. I've been running into this with one-line completions since sometime recently, and it's very annoying to use.

**Comment by TzufTabnine** [comment]
@KnightYin 
Please send it to support@tabnine.com

**Comment by KnightYin** [comment]
@TzufTabnine The email has been sent.
Additionally, when I tested on another Win10 system computer, I found that there was no problem with one-line completion. I'm going to test my Macbook again tomorrow.

**Comment by KnightYin** [comment]
@TzufTabnine 

Oh, I found out how to reproduce this situation. When that `if statement` is formatted and occupies 2 lines, there will be a completion problem below. 

If the `if statement` only occupies one line, there is no problem without indentation. But, When deleting one or more indents, there may also be problems completing a line.

**no delete, cursor position after 12 spaces:**

<img width="1065" alt="1" src="https://github.com/codota/TabNine/assets/23274552/188dcbe3-e0bc-4509-b664-887f90cd2449">

**delete 1 indent, cursor position after 8 spaces:**

<img width="1042" alt="3" src="https://github.com/codota/TabNine/assets/23274552/93516db6-1601-4019-bcf6-8235f5aa6993">

**delete 3 indent, cursor position after 0 spaces:**

<img width="1080" alt="2" src="https://github.com/codota/TabNine/assets/23274552/d1904335-6247-48be-bffa-7451c9703d36">
