### ISSUE TITLE
Why Tabnine scanning my other project code?

### ISSUE THREAD

**Issue by wx953999109** [codota/TabNine#605]
这是.net项目, 我把tabnine安装在idea开发工具里面的插件里, 
这个项目并没有用idea打开, 而tabnine在我的磁盘里面有一个TabNine.exe执行程序
在扫描我电脑里面的其他项目代码
我希望tabning停止这种行为
![未命名1684828340](https://github.com/codota/TabNine/assets/105601605/10372bc2-8cf1-4ee4-bf91-ed9503e5349c)

gz#23780<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23780'>Zendesk ticket #23780</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @wx953999109 
Tabnine ONLY scans your open projects, nothing else.

**Comment by wx953999109** [comment]
我截图的项目使用Visual studio打开, 而Tabnine使用idea插件安装, 为什么会被扫描?
