### ISSUE TITLE
Please stop advertising in my editor (2)

### ISSUE THREAD

**Issue by fmaiabatista** [codota/TabNine#606]
**please complete the following information:**	
 - OS version: MacOS Ventura 13.3.1 (a) (22E772610a)
 - Editor: VSCode
 - Editor version: April 2023 (version 1.78)	
 - Programming language: TS
 - TabNine extension version: 3.6.46
 - Engine version (could be located within Tabnine Hub): 4.4.321-60

**Issue Details:**
Related to https://github.com/codota/TabNine/issues/342 but I see you closed the issue so I'm creating a new one to reaffirm there are users very annoyed by the marketing practices.

![image](https://github.com/codota/TabNine/assets/1574224/3faacc9f-fb2d-4e48-842b-2daed0a41c2c)

For me it's annoying and disruptive to the point I'll uninstall the extension and give up its benefits altogether.

As developers you must be aware of the importance of focus and the harm of context switching or any distraction during a coding session. As an autocompletion tool, the goal of TabNine should be to help maximize developer productivity. Displaying an **INLINE**, **EMOJI-COLORED** marketing message defeats the purpose of helping developers be productive and stay in the flow.

I'm aware of the arguments you presented on #342 to keep the ads running but to me there are better ways to advertise a product's premium tier. **Direct inline ads** shouldn't be a way for a good product to convert free users into paying customers.

I'm thankful, even if only for the brief duration I used the extension, that you offer a free plan at all - but I strongly feel that you should review your marketing strategy and prioritize genuine productivity (as in, NOT PRESENT distracting ads/irrelevant messages in the editor area) more than pushing for sales at the user's most important viewing region.

I hope you can consider this critique and understand that I cared enough to write this feedback instead of simply uninstalling the extension and never looking back.

gz#23861<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23861'>Zendesk ticket #23861</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @fmaiabatista 

Thanks for the feedback.

We try to minimize these messages, but at the same time, these promos enable us to offer a good Free plan for all our users.
We want to find the optimal way to balance this need and your feedback. We will consider your suggestion.
