### ISSUE TITLE
Suggestion disappears when autocomplete opens

### ISSUE THREAD

**Issue by mbahnmiller** [codota/TabNine#607]
**please complete the following information:**	
 - OS version: Mac Ventura
 - Editor: vscode
 - Editor version: 1.78.2	
 - Programming language: all (generally PHP)
 - TabNine extension version: 3.6.51
 - Engine version (could be located within Tabnine Hub): 4.4.322-60

**Issue Details:**
I'll start typing and receive a suggestion from Tabnine. Before I have a chance to review and accept it, autocomplete opens, and the suggestion disappears, and I don't see an easy way to get it back. The "next" and "previous" suggestion shortcuts (stock or user-assigned) do not seem to work (separate issue, but prevents me from getting the suggestion back.)

gz#23965<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23965'>Zendesk ticket #23965</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @mbahnmiller 
Please send a screenshot/video of the issue.
Please add the log files after you reproduce the issue. See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by pranali18-Ai** [comment]
You can use tab key

**Comment by markg85** [comment]
This is still an issue.
My tabnine - especially when generating C++ code - just keeps disappearing after asking it something. It generates the response and mere seconds later the whole tabnine pane is just empty. I have to restart vscode to get it back.

Anything i can do to help debugging this?

**Comment by TzufTabnine** [comment]
Please send a screenshot/video of the issue.
Please add the log files after you reproduce the issue. See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.
