### ISSUE TITLE
why is it in my dock

### ISSUE THREAD

**Issue by JaminYe** [codota/TabNine#609]
**please complete the following information:**	
 - OS version: Mac 12.6.6 Intel 	
 - Editor: intelij
 - Editor version: 2022.3.3
 - Programming language: java
 - TabNine extension version:  1.0.16
 - Engine version (could be located within Tabnine Hub):  4.5.7-60

**Issue Details:**
why is it in my dock
<img width="762" alt="image" src="https://github.com/codota/TabNine/assets/45601795/31c0f5b8-5fa8-4032-a343-1644c36d6808">
<img width="1380" alt="image" src="https://github.com/codota/TabNine/assets/45601795/23732934-c0a1-4915-8409-d8d074a97546">

gz#24357<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24357'>Zendesk ticket #24357</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @JaminYe 
What exactly is the issue here?

**Comment by JaminYe** [comment]
> Hi @JaminYe
> What exactly is the issue here?
the 1.24.0 is tabnine,It sometimes shows up on my dock,I don't want it in my dock bar

**Comment by Gpicachu** [comment]
这个解决了吗

**Comment by Naturel1** [comment]
I have the same issue on my computer, a java programme called 1.24.0 is lunching multiple time on the dock while i'm programming.

**Comment by david0** [comment]
I have the same problem. Its pretty distracting to useless dock icon popping up there.

setting `apple.awt.UIElement` to true could help: https://www.b4x.com/android/forum/threads/how-to-hide-java-icon-from-dock-in-macos.116491/
