### ISSUE TITLE
TabNine version keeps flipping (Pro -> Starter -> Pro)

### ISSUE THREAD

**Issue by absantanna2412** [codota/TabNine#611]
**please complete the following information:**	
 - OS version: Win 11
 - Editor: intelij
 - Editor version:	Ultimate 2023.1.3
 - Programming language: Java and Angular
 - TabNine extension version: 1.0.16
 - Engine version (could be located within Tabnine Hub): 4.5.9-41

**Issue Details:**

I've purchased the Pro version and the TabNine version keep flipping between Starter and Pro version. Does not matter the language I'm using.

https://github.com/codota/TabNine/assets/20236895/a4b52755-f675-456d-bae2-6fb95ebc3529

gz#24407<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24407'>Zendesk ticket #24407</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @absantanna2412 
Are you behind Proxy/VPN/Firewall/Antivirus? Please follow the steps [here](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues).

**Comment by TzufTabnine** [comment]
Also, please send us the log files. See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that.
