### ISSUE TITLE
Tabnine switching between Pro and Starter edition

### ISSUE THREAD

**Issue by NumicDev** [codota/TabNine#612]
**please complete the following information:**	
 - OS version: [Win 11]	
 - Editor: [vscode]	
 - Editor version:1.79.2	
 - Programming language: [ts]	
 - TabNine extension version: 3.6.60

**Issue Details:**

I am also experiencing the same problem that someone else logged. My Tabnine starts in Pro but if I alt-tab or just leave the editor for a minute or 2 the it switches to Starter and then I have to restart the editor to get it back to Pro. This is very counterproductive. 

gz#24468<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24468'>Zendesk ticket #24468</a>)</i>

**Comment by TzufTabnine** [comment]
@NumicDev 
Are you behind Proxy/VPN/Firewall/Antivirus? Please follow the steps [here](https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues).
Also, please send us the log files. See [here](https://support.tabnine.com/hc/en-us/articles/5283541356689-Getting-Tabnine-logs-on-JetBrains) how to do that.

**Comment by NumicDev** [comment]
@TzufTabnine 

No I am not. I already sent the Log files to TabNine
