### ISSUE TITLE
Tabnine cannot be used on VSCode

### ISSUE THREAD

**Issue by Dlona-D** [codota/TabNine#613]
**please complete the following information:**	
 - OS version: win11
 - Editor: vscode	
 - Editor version:1.79.2	
 - Programming language:vue,js	
 - TabNine extension version:3.6.62

**Issue Details:**
Starting this morning, Tabnine seems to have failed on my VSCode. The status bar keeps displaying Tabnine start, but I am a Pro version and cannot open the TabnineHub by clicking on the status bar. I have tried installing an earlier version, but it still cannot solve the problem.

gz#24608<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/24608'>Zendesk ticket #24608</a>)</i>

**Comment by TzufTabnine** [comment]
@Dlona-D 
Please send here a screenshot/video of the issue. Please also send here the log files. See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by Dlona-D** [comment]
@TzufTabnine I seem to know where the problem lies. When I synchronize the tabnine plugin in vscode, it triggers this issue, but I am not sure why. When I try to install tabnine in an asynchronous manner, this issue is resolved

**Comment by TzufTabnine** [comment]
Thanks for letting us know. I am glad to hear that the issue has been resolved.
