### ISSUE TITLE
Constant reload information in WSL2

### ISSUE THREAD

**Issue by kapalkat** [codota/TabNine#614]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina] - Windows 11 Pro 22H2 / WSL2 - 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Editor: [e.g. vscode, intelij, sublime]	vscode
 - Editor version:	1.80.1
 - Programming language: [e.g. js, ts, c++]	all
 - TabNine extension version: 3.6.77
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
TabNine constant information about `Reload Required`.
The reload doesn't help. Neither uninstalling and back installing the extension. I have the same issue all the time.
Would like to attach the reload but the file is too big.
![reload_1](https://github.com/codota/TabNine/assets/26725074/472ed9d5-026a-4abd-8975-0c5bd28a918b)
![reload_2](https://github.com/codota/TabNine/assets/26725074/6d3f71fa-d02f-43f8-b2dd-1c423cd3ccb5)
![reload_3](https://github.com/codota/TabNine/assets/26725074/7062c652-fa9d-446f-9682-b84eae79d372)

gz#25335<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25335'>Zendesk ticket #25335</a>)</i>

**Comment by TzufTabnine** [comment]
@kapalkat 
Hi kapalkat,

Thanks for contacting us!

There can be problems working remotely indeed. Check [here ](https://support.tabnine.com/hc/en-us/articles/12218652562449-Generating-a-token-to-log-in-to-Tabnine-Hub) and here[Tabnine is not working on VSCode working remotely](https://support.tabnine.com/hc/en-us/articles/9658286108177-Tabnine-is-not-working-on-VSCode-working-remotely)
There are various issues.


Best,

Tzuf Stokelman
Tabnine Support
