### ISSUE TITLE
~/Library/Preferences/TabNine has so many entries that I can't even do an ls

### ISSUE THREAD

**Issue by pgib** [codota/TabNine#616]
- OS version: macOS Ventura 13.4.1
 - Editor: NeoVim
 - Editor version: 0.8.3
 - Programming language: ruby/js
 - TabNine extension version: 1.4.0
 - Engine version (could be located within Tabnine Hub): 4.5.25-10

`~/Library/Preferences/TabNine` has grown so large that I can't even do an `ls` or view the folder in the Finder. It seems like the bulk of these entries look like  `.atomicwrite.xtm541ALXx0Z/tmpfile.tmp`. I discovered this when looking into an issue with the backup utility I use (Backblaze). The logs from the daily backups show between 20,000 - 40,000 files being transmitted daily.

I am now excluding this folder from Time Machine and Backblaze, but it seems like there is some clean-up that is not happening.

gz#25519<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25519'>Zendesk ticket #25519</a>)</i>

**Comment by pgib** [comment]
I moved the folder away and recreated it. Hours later, there are almost 10,000 of this `.atomicwrite` folders:

```
% ls -al | grep -c atomicwrite
9444
```

**Comment by TzufTabnine** [comment]
Hi @pgib 
We fixed it in version  4.5.26. Please update and check

**Comment by pgib** [comment]
Thank you!
