### ISSUE TITLE
latest 4.5.25  with vim deoplete ends up with error

### ISSUE THREAD

**Issue by iicuken** [codota/TabNine#617]
Good day. I am using tabnine with vim plugin deoplete-tabnine. In recent days it stop working  with constant error:
[deoplete] TabNine exited with code 1  Use :messages / see above for error details

My latest tabnine binaries have  4.5.25 version.
When i roll back to version 4.4.305  for example  all works fine again.
I must admit that in 4.5.25 i cant turn on logging, no matter how i tried.
Thank you.

gz#25602<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25602'>Zendesk ticket #25602</a>)</i>

**Comment by amirbilu** [comment]
Hi @iicuken, I've issued a PR to fix this issue. https://github.com/tbodt/deoplete-tabnine/pull/65 - hoping to this will be merged soon.
On a different topic - if you happen to use Neovim - I urge you to try our official [nvim](https://github.com/codota/tabnine-nvim) plugin which offers Tabnine Pro features, such as multiline completions and Tabnine Chat.

**Comment by amirbilu** [comment]
Marking this as solved
