### ISSUE TITLE
Suggested code should use formatting preferences of the editor

### ISSUE THREAD

**Issue by vanowm** [codota/TabNine#618]
**please complete the following information:**
 - OS version: Windows_NT x64 10.0.19045	
 - Editor: vscode	
 - Editor version: 1.81.1
 - Programming language: js	
 - TabNine extension version: 3.8.4
 - Engine version (could be located within Tabnine Hub): 4.5.28-60

**Issue Details:**
The suggested code does not obey formatting preferences, i.e. indentation as tabs, opening brackets on new line, etc

gz#26154<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26154'>Zendesk ticket #26154</a>)</i>

**Comment by TzufTabnine** [comment]
@vanowm 
Can you please send us an example? (Screenshot/video)
Can you please try and update your Tabnine version?

**Comment by vanowm** [comment]
Well, that's kind of stupid if issues being closed due to inactivity...seriously???

**Comment by vanowm** [comment]
Ok, which one is it? wontfix or completed? It's definitely not fixed.
