### ISSUE TITLE
why this vscode-plugin keep update version EVERYDAY and keep asking to login EVEERYDAY

### ISSUE THREAD

**Issue by barclaycc** [codota/TabNine#619]
very annoying

gz#26537<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/26537'>Zendesk ticket #26537</a>)</i>

**Comment by TzufTabnine** [comment]
Can you please send us a screenshot/video of the issue?

**Comment by barclaycc** [comment]
sorry, just some grumbles

**Comment by FoXcodeZ** [comment]
I have the same issue. It is annoying when Tabnine keeps updating every day, in all my IDEs and code editors. (I'm using CLion, InteliJ, VS code).
![tab](https://github.com/codota/TabNine/assets/109001258/32fd82bb-d3ee-4fa5-a5fb-34ceaa6ba7fd)

**Comment by TzufTabnine** [comment]
Hi @FoXcodeZ ,
Every time a new version is installed, you need to update the plugin. If you don't want to upgrade the plugin to the latest version, you can disable the auto-update in your IDE. See [here ](https://code.visualstudio.com/docs/supporting/FAQ#:~:text=Opt%20out%20of%20extension%20updates,Settings%20editor%20(Ctrl%2B%2C).)

**Comment by FoXcodeZ** [comment]
> Hi @FoXcodeZ , Every time a new version is installed, you need to update the plugin. If you don't want to upgrade the plugin to the latest version, you can disable the auto-update in your IDE. See [here ](https://code.visualstudio.com/docs/supporting/FAQ#:~:text=Opt%20out%20of%20extension%20updates,Settings%20editor%20(Ctrl%2B%2C).)
I'll do that, but...
Is a new version of Tabnine deployed every day? If not, this is still an issue.

**Comment by TzufTabnine** [comment]
A new version can be deployed a couple of times a day. You can disable the auto-update option if you don't wish to have the latest version.
