### ISSUE TITLE
tabnine doesn't use context on C++ & VSCode

### ISSUE THREAD

**Issue by DeanIsMe** [codota/TabNine#621]
tabnine auto completions don't see to have any knowledge outside of the current file I'm working on.
I'm using C++ and VS Code, and tabnine pro.

Here's the simplest demonstration:

myHeader.hpp
```cpp
#pragma once
enum DeanEnum 
{
    dean_ok = 0,
    dean_error = 1,
    dean_out_of_memory = 2,
    dean_stopped_working = 3,
};
```
mytest.cpp
```cpp
#include "myHeader.hpp"

void foo(DeanEnum d)
{
    switch (d) {
        
    }
}
```

You can see that the auto completions aren't helpful:
![image](https://github.com/codota/TabNine/assets/4307776/facd2102-1fff-435b-a602-fbeaa16f7383)

gz#27229<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27229'>Zendesk ticket #27229</a>)</i>

**Comment by TzufTabnine** [comment]
You are correct. At the moment the open file is the only context Tabnine is "reading".

**Comment by DeanIsMe** [comment]
In that case, I think the documentation needs to be corrected to indicate that.

https://www.tabnine.com/blog/tips-and-tricks-to-best-coding-practices-with-tabnine/
_context could come from open and interacted files, installed libraries, as well as the code and comments you’ve authored_
