### ISSUE TITLE
4.26.0 broken in Ubuntu + Vim

### ISSUE THREAD

**Issue by dror-g** [codota/TabNine#622]
**please complete the following information:**	
 - OS version: Ubuntu 22.04	
 - Editor: Vim (foreveeeer!!!!)	
 - Editor version:	8.2
 - Programming language: python	
 - TabNine extension version: codota/deoplete-tabnine and tbodt/deoplete-tabnine
 - Engine version: 4.26.0 

**Issue Details:**
Getting `OS error 13: PermissionDenied` on cache/config/model folder `/home/user/.config/TabNine/model_api` .  
  
I know Vim is no longer supported, but everyhing seems to be working fine with binary version 4.24.0 .
Installed using codota deoplete-tabnine using vim-Plug.
Can force older version 4.24.0 by altering install.sh to use hardcoded version rather than fetching laters,
or copying/linking `~/.vim/plugged/deoplete-tabnine/binaries/4.24.0/` to `~/.vim/plugged/deoplete-tabnine/binaries/4.26.0/`.
Doing so TabNine works as always in Vim - getting completions and can open config using `TabNine:config` in buffer.
  
This holds for only a few moments though until the binary detects newer version and forces an update.
  
Checked all permissions on `.config/Tabnine` and `.vim/plugged/deoplete-tabnine` - all files owned by user.  
Binaries are set as executable in `.vim/plugged/deoplete-tabnine`.  
  
Any idea why this happens in 4.26 and not 4.24?  
Suggestion on how to pin to version 4.24 or disable auto-update perhaps?  
  
Thanks! huge fan.
 

gz#27255<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27255'>Zendesk ticket #27255</a>)</i>

**Comment by amirbilu** [comment]
Hi Dror, vim and deoplete are definitely not officially supported.. but let's see what we can do. Are you able to turn on logs on Tabnine binary? if so. please attach the logs here

**Comment by dror-g** [comment]
Hi @amirbilu ! was hoping you'll pick this up :)

Please find attached two logfiles found in `~/.vim/plugged/deoplete-tabnine/`
One tagged `-firstRun` is after PlugInstall and restart of vim for first time, notice `PermissionDenied` on `/home/nihil/.config/TabNine/models_api` - it does not exist (entire `.config/TabNine` folder was created by 4.26.0 binary on first run, not by deoplete-tabnine post-install script).

The one tagged `-secondRun` is after I shutdown vim, manually created the `models_api` folder, and restarted.
No effect though... still permissionDenied even though entire path is owned by user.

Thanks for your help! 
And keep in mind locking TabNine to version 4.24.0 is a valid solution as far as I'm concerned...

[tabnine_rCURRENT-firstRun.log](https://github.com/codota/TabNine/files/13113882/tabnine_rCURRENT-firstRun.log)

[tabnine_rCURRENT-secondRun.log](https://github.com/codota/TabNine/files/13113881/tabnine_rCURRENT-secondRun.log)

**Comment by dror-g** [comment]
I also tried setting the TabNine binary arguments to the ones found in codota/tabnine-nvim.
in file `~/.vim/plugged/deoplete-tabnine/rplugin/python3/deoplete/sources/tabnine.py` 
orginal:
`TabNine --client deoplete --log-file-path /home/nihil/.vim/plugged/deoplete-tabnine/tabnine.log`

modified to:
`TabNine --client nvim --client-metadata ide-restart-counter=0 pluginVersion=1.6.0 --log-file-path /home/nihil/.vim/plugged/deoplete-tabnine/tabnine.log`

No effect.. same permissionDenied error.

**Comment by dror-g** [comment]
Oh hey... it happens in NeoVim as well !

Just tried installing in NeoVim, using lazy.nvim as described in `codota/tabnine-nvim` readme,
Binaries downloaded and extracted, watchod is running and TabNine process running when nvim is open.

But `:TabNineStatus` is stuck at `Loading`, so looked at the log and same error! AccessDenied and log looks exactly like the 4.26.0 log in `deoplete-tabnine` attached above.

Could this be an Ubuntu 22.04 issue? Apparmor perhaps?

NeoVim log:
[TabNineLog_rCURRENT.log](https://github.com/codota/TabNine/files/13115499/TabNineLog_rCURRENT.log)

`ps -ef | grep TabNine` output:
[ps_out.txt](https://github.com/codota/TabNine/files/13115572/ps_out.txt)

`tree .` inside tabnine-nvim dir (which is in `~/.local/share/nvim/lazy/tabnine-nvim`:
[tabnine_tree.txt](https://github.com/codota/TabNine/files/13115782/tabnine_tree.txt)

Following tabnine-nvim closed issues at the moment, like [issue #33](https://github.com/codota/tabnine-nvim/issues/33)

**Comment by amirbilu** [comment]
Hi @dror-g .. I see something crashing in your logs. I'm running this through the team. Will keep you updated.

**Comment by dror-g** [comment]
Same crash on deprecated vim plugin, and supported neovim plugin,
But!
tabnine-nvim works if I run nvim as root and install it there (in `/root/.config/nvim/init.lua`).

Something in the OS is blocking it... the .config folders are all with 0770 permissions... :|

Thanks for your help!

**Comment by amirbilu** [comment]
@dror-g can you share the output of  ls -lrh ~/.local/share/TabNine ?

**Comment by dror-g** [comment]
`ls -lrh ~/.local/share/TabNine 
total 40K
-rw------- 1 root root  12K Oct 30  2021 Small.meta
-rw-r--r-- 1 root root    0 Oct 13 22:53 models_api_cache_dir_lock
drwxr-xr-x 2 root root 4.0K Oct 30  2021 models
-rw------- 1 root root  23K Dec 19  2020 Medium.meta
-rw-r--r-- 1 root root    0 Oct 13 22:53 get_models_cache_lock.lock
-rw-r--r-- 1 root root    0 Oct 30  2021 exit_signal
`

wow is that ment to be owned by root?!

**Comment by dror-g** [comment]
oh wow, yes! I actually removed tabnine in nvim Lazy, deleted ~/.local/share/TabNine folder and ~/.config/TabNine,
Then re-installed in nvim with Lazy..

It works!!!

So what created these files in ~/.local as root? maybe the deoplete-tabnine install?
I'll do a test to see if the vim version still works.

**Comment by dror-g** [comment]
Works in vim as well!! 
Removed deoplete-tabnine, PlugClean, added again, PlugInstall - back in business.

No idea what caused it to create those files as root... or that they even existed. The logfile errors kept complaining about .config/TabNine , looked again and there's no mention of .local/share/TabNine in them...

Sorry for the hassle! I know it's not supported anymore but you did fix it in both nvim and vim for me :D 
Thanks!

**Comment by dror-g** [comment]
Closing as the issue started with deoplete-tabnine which is no longer supported.
If you encounter this issue the fix is above, but it's not likely with the new tabnine-nvim plugin.
Might try to reproduce but doesn't seem worth it.

Thanks @amirbilu and team!

**Comment by amirbilu** [comment]
Thank you! appreciate your close engagement!
