### ISSUE TITLE
Hiding Other suggestion like intellisense

### ISSUE THREAD

**Issue by LOVKUSH9888** [codota/TabNine#624]
**Please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
![image](https://github.com/codota/TabNine/assets/99957868/51a39c75-d2b3-4d26-b4ea-612dd495274d)

gz#27437<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27437'>Zendesk ticket #27437</a>)</i>

**Comment by TzufTabnine** [comment]
@LOVKUSH9888  Can you elaborate what exactly is your issue?
