### ISSUE TITLE
Can't use within STM32CubeIDE

### ISSUE THREAD

**Issue by AntonBespalov** [codota/TabNine#625]
After I click Open settings in IDE, the browser opens and it shows that I'm not signed in:
![изображение](https://github.com/codota/TabNine/assets/9027038/dcceba0a-9445-4d38-b231-48442875c469)
I click Sign In and it suggest to use token in IDE command pallette, but there is no command pallette in STM32CubeIDE:
![изображение](https://github.com/codota/TabNine/assets/9027038/45136626-abc9-471e-a5fa-ffed4a7cdbe9)

 - OS version: Windows 7
 - Programming language: C
 - IDE: eclipse, STM32CubeIDE 1.13.1
 - Plugin Version: 0.7.0
 - Engine Version: 4.40.0-60

gz#27748<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27748'>Zendesk ticket #27748</a>)</i>

**Comment by TzufTabnine** [comment]
@AntonBespalov 
Unfortunately, it is not yet supported in Eclipse. However, please note that we have added it to our roadmap and will be working on implementing it soon.

**Comment by TzufTabnine** [comment]
Sign in with the auth token.

**Comment by TzufTabnine** [comment]
You can check our activation guide here https://docs.tabnine.com/tabnine-saas-docs/general/installing-tabnine-in-your-ide/setup-tabnine-in-eclipse

**Comment by AntonBespalov** [comment]
> Sign in with the auth token.

I'm successfully use tabnine in the same IDE on another PC in Windows 10. There were no issue with sign in.

**Comment by TzufTabnine** [comment]
We also support Win 10 (or newer). We do not support Win 7 -https://docs.tabnine.com/tabnine-saas-docs/general/tabnines-client-requirements
