### ISSUE TITLE
TabNine doesn't pick up Proxy from linux command line same as vscode

### ISSUE THREAD

**Issue by Maziar123** [codota/TabNine#626]
- Linux Ubuntu or Arch Linux and think of any other 
 - VSCODE: latest, any
 - TabNine extension version: 2023-11-13
 - Engine version (could be located within Tabnine Hub): 

  the tabnine doesn't get the http_proxy setting when vscode runs from the command line
  as rules vscode & any other similar extension do it 
  it must get proxy setting from vscode or set separately from config
  it bypasses the proxy setting 
  
  TabNine-deep-cloud is attempting to resolve cloud.tabnine.com via x.yy.zz.nn, UDP port 53
  
  

gz#27786<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/27786'>Zendesk ticket #27786</a>)</i>

**Comment by amirbilu** [comment]
Hi @Maziar123 , Thanks for reaching out to us! could you please :
- Tell us a bit more about your setup. Are you using VSCode remotely? (SSH/Docker etc)
- Send `~/.config/TabNine/tabnine_config.json `to support@tabnine.com
- Elaborate further on the DNS resolution? Tabnine only proxies HTTP requests (ports 80/443)

**Comment by Maziar123** [comment]
proxy env. The DNS is set in the environment, so why try a different access method via x.yy.zz.nn ??
export http_proxy=http://ZZ:8080/
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com,172.16.*.*,172.16.?.?"

**export dns_server="1.1.1.1,9.9.9.9,8.8.8.8"**


config :
{
  "version": "4.36.0",
  "hide_promotional_message": false,
  "beta_enabled": "No",
  "ignore_all_lsp": false,
  "creation_time": "xxxx",
  "guuid": "fxxxxx61b8ce316c922189ddd4e4028c55d02cf970feef66ee1fxxxxx",
  "semantic_status": {},
  "enable_telemetry": true,
  "user_understands_that_enabling_tabnine_cloud_sends_code_to_tabnine_servers": true,
  "deep_completions_work_mode": "Hybrid",
  "hosted_deep_completions_enabled": "Disabled",
  "tabnine_cloud_host": null,
  "tabnine_cloud_certificate_domain": null,
  "tabnine_cloud_port": null,
  "cloud_whitelist": [],
  "num_of_suggestions": 5,
  "line_suggestions": null,
  "rlhf": null,
  "omit_prefix_suggestions": null,
  "api_key": null,
  "api_base_url": null,
  "binary_update_interval_seconds": null,
  "local_enabled": "Unset",
  "disable_local_when_using_battery": false,
  "hide_deep_information_message": false,
  "enable_power_saving_mode": false,
  "rate_limit_interval_seconds": null,
  "rate_limit_amount": null,
  "generation": 60,
  "local_model_size": null,
  "model_hash_override": null,
  "local_indexing": null,
  "heartbeat_interval_seconds": null,
  "last_service_level": "FreeCloudRegistered",
  "override_beams": null,
  "override_context_length": null,
  "onboarding": null,
  "has_git_repos": true,
  "gusr": {
    "dgc": "fxxxxx461b8ce316c922189ddd4e4028c55d02cf970feef66xxxxxx"
  },
  "exclude_file_masks": null,
  "inline_suggestions_mode": true,
  "use_specialized_model_if_available": null,
  "snippets_enabled_v2": true,
  "inline_suggestions_mode_clients": null,
  "tabnine_hub_port": 1123,
  "manually_selected_model": null,
  "hybrid_rendering_mode": null,
  "force_local_hub": false
}

**Comment by TzufTabnine** [comment]
Can you elaborate further?
