### ISSUE TITLE
Bidefender Quarantines Whole Setup Upon Installing Extension

### ISSUE THREAD

**Issue by interstellarfrog** [codota/TabNine#628]
- OS version: Win 11
 - Editor: VSCodium (open source no telemetry version of vs-code)
 - Editor version: most recent stable build
 - TabNine extension version: most recent stable build

**Issue Details:**

I am using the latest version of Bitdefender Antivirus Free and when I installed the extension in the VSCodium store hundreds of files were flagged instantly as malicious including VSCodium itself which caused basically my whole development setup (cargo, rust-analyzer, python, clippy, git, rustc, trunk, prettier, LL-DB, EBTOML, Test Explorer etc.) to get marked as malicious which removed the files and put them into quarantine, thankfully I have reverted most of the quarantined files and added them as exceptions and all is working fine now.

gz#28157<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/28157'>Zendesk ticket #28157</a>)</i>

**Comment by amirbilu** [comment]
Hi @interstellarfrog, thanks for reaching out to us. How can we assist here?
