### ISSUE TITLE
Cannot sign-in on vscode

### ISSUE THREAD

**Issue by CHFernandes** [codota/TabNine#629]
**please complete the following information:**	
 - OS version: Fedora Linux 38
 - Editor: Vscode
 - Editor version: 1.85.0
 - Programming language: Javascript
 - TabNine extension version: 3.50.0
 - Engine version (could be located within Tabnine Hub): 4.53.0-60

**Issue Details:**

Similar to this issue: https://github.com/codota/TabNine/issues/627 but it is occurring on the newest version as well on linux

![image](https://github.com/codota/TabNine/assets/20386403/1dc79922-1ec2-4d69-bf29-5c0e9ae0f7d8)

![image](https://github.com/codota/TabNine/assets/20386403/86c82368-ead7-4324-896e-68449eb8be02)

![image](https://github.com/codota/TabNine/assets/20386403/187734b8-1057-412a-94a4-45f1e82fd8ff)

Steps to reproduce are the same on the closed issue:

1 - click sign in in vscode
2 - copy the code
3 - open tabnine hub in the ide
4 - paste the code in the support tab on the API Key Activation field
5 - The message still persists both in the current session and after closing and opening it again

gz#28405<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/28405'>Zendesk ticket #28405</a>)</i>

**Comment by TzufTabnine** [comment]
@CHFernandes Please follow the steps here - https://docs.tabnine.com/saas/install/sign-in/using-an-authentication-token

**Comment by CHFernandes** [comment]
Closing issue, I was looking in the wrong place, thank you.
