### ISSUE TITLE
mirrors.edge.kernel.org/pub/software/scm/cogito/ports/sha256sums.asc

### ISSUE THREAD

**Issue by jnewell7** [codota/TabNine#632]
"-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

aea97968cbae18dfc5fdc721e485f264fe1d67207383d826de9e762b307d450c  Portfile-0.13
d9c010c2cb9f2594894e542f59fd58c7c1effca56ec5fe2681e2cabc61cccec1  Portfile-0.14
8a6083b4851bff6dcde8bf246a9175db6747523f2e337817aa1de725f9f89e91  Portfile-0.14.1
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iQIcBAEBCAAGBQJkSEX2AAoJEGMtOgZYnaaxBbcQAKOk3G9kAEwmhL/b3nF+U4XQ
sUV804N8dV0geBUXRBT1dETT18i8kY1bzVemnD3Kdc6WjWfEIhVDM4crMW18g3p0
ZfGQWvRgO963ydKkmXIM8ADlrAYrSHcEMcjWb6KjiZ0fVctFjzLsXks3IrPH/UMb
JIPAbThWoFu2FGbZ5ezU0hbe2G750MRjoXKHpMskom5zZerqZCjYwjJCI6edLrM0
aEkDLdcX4Ar7WFo3v+l55DPn9xGEBJ8pUVsOUn7baiS1tjywrSvMRRr50WQNU79W
sg8M6GruTXTsZ0fOBv+vFsXxjJ7N5uEc+6UWPmbJC1UKy6IC9U3A8nHFdRDJF+DS
xPbMbcHPoZA3KSLElnm2ZSuimLWaSAWg9HuODDk8I8Q1yivU7gHtCXxoPHM12zXE
VVkOBAnmeovq5D4W+p7ikD0ky0rpfzUQLw5aVK15rOMrgSbM3DKZXP4q7K/v00HR
gHS1yD0qOAzvUrWcCITYLZKRY7kdlJ23bpYGQwYEXRbUbBGClXZle34ZmMImC74C
UudxdrXQKI115MAxAncRNnJwnbIgl+h0pnr3Ij5/aXltAvgdQV900OOF3CpsqD9f
Ny7BexhoJcXsKxOucZB9CHSc0Vq9RO+oOtoFOz8V+mi/n4ClSzzT/Bn1jNe4m5W2
pAW4MZ7mDgTFZjVT6zyK
=jmKG
-----END PGP SIGNATURE-----"
 https://mirrors.edge.kernel.org/pub/software/scm/cogito/ports/sha256sums.asc#:~:text=%2D%2D%2D%2D%2DBEGIN%20PGP%20SIGNED,END%20PGP%20SIGNATURE%2D%2D%2D%2D%2D

gz#28807<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/28807'>Zendesk ticket #28807</a>)</i>

**Comment by TzufTabnine** [comment]
@jnewell7 ?
