### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by robko23** [codota/TabNine#637]
OS version: `Linux 6.3.6-zen-gd787073602cf #4 ZEN SMP PREEMPT_DYNAMIC Wed Jun  7 12:36:20 CEST 2023 x86_64 unknown unknown GNU/Linux`
Editor: neovim and rustrover
Editor version: nvim: 0.9.2, rustrover: 2023.3
Programming language: rust, typescript
Command: 
```
../binaries/4.75.0/x86_64-unknown-linux-musl/TabNine --client nvim --client-metadata ide-restart-counter=4 pluginVersion=1.7.0 --no_bootstrap
```

**Issue Details:**
Tabnine allocates a ton of memory very frequently. On my laptop where I have 16GB ram it will happily eat 9GB and on my main computer (32GB) it eats as much as 28GB. I had to install earlyoom on both machines, because it froze my entire system. When I open studio, it's working "fine" for a like half an hour and the it goes off the rails and allocates the rest of free system memory in 1-2 minutes. Earlyoom kills it, tabnine restarts and now the cycle repeats. Sometimes it gets killed 10 times in span on 20 minutes. It's been like this for about 3-4 month but I hoped an update or changing IDEs would help, but no it didn't and it's becoming very annoying.

The logs I found were almost empty and contained nothing important. And I have tabnine pro if that helps somehow.

gz#29120<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/29120'>Zendesk ticket #29120</a>)</i>

**Comment by amirbilu** [comment]
Hi @robko23, apologies on that bad UX. if you're a pro user - can you try to switch to cloud-only mode? in Tabnine hubL
![image](https://github.com/codota/TabNine/assets/7681048/89da183a-a621-4013-b705-c56e65483369)

**Comment by robko23** [comment]
Yes, I have been using cloud only mode for the past month. I have tried hybrid before and it was the same.

**Comment by amirbilu** [comment]
What's you Tabnine Pro Id?

**Comment by robko23** [comment]
where can i find it?

**Comment by amirbilu** [comment]
Sorry if I wasn't clear.. your email

**Comment by robko23** [comment]
Oh... Of course :D
Is there any way I can send it to you privately?

**Comment by amirbilu** [comment]
Sure.. support@tabnine.com
