### ISSUE TITLE
Advanced completions don't work in sublime?

### ISSUE THREAD

**Issue by arunabhcode** [codota/TabNine#639]
**please complete the following information:**	
 - OS version: Ubuntu 20.04
 - Editor: sublime	
 - Editor version: 4	
 - Programming language: python	
 - TabNine extension version: 3.0.7
 - Engine version (could be located within Tabnine Hub):  4.89.0-34

**Issue Details:**
It seems like the advanced completions that work in vs code don't work in sublime?

gz#29483<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/29483'>Zendesk ticket #29483</a>)</i>

**Comment by TzufTabnine** [comment]
We do not provide support for Sublime as it only has community support.
