### ISSUE TITLE
Semantic completion for C#

### ISSUE THREAD

**Issue by dannyalan** [codota/TabNine#64]
Hey, it'd be awesome if you supported C# semantically. 

Hopefully this can be done?

**Comment by zxqfl** [comment]
Can you recommend an LSP server for C#?

**Comment by dotnetdanny** [comment]
I can't I'm afraid, but I'd be grateful if you replied to some of the issues we've tagged you in. These are more pressing

**Comment by antonioyon** [comment]
Here's one https://github.com/OmniSharp/csharp-language-server-protocol

**Comment by John0x** [comment]
Any updates on this? :)

**Comment by jarmo** [comment]
I tried to make C# semantic completion to work by using @OmniSharp csharp-language-server-protocol LSP server, but could not do it since I'm not too familiar of how these things should work. I expected that after building that project (which I succeeded) I would have an executable server, which I just need to configure appropriately, but didn't find that executable.

Anyone else ideas how to make it work with TabNine?

**Comment by jezus-nunez** [comment]
> I tried to make C# semantic completion to work by using @OmniSharp csharp-language-server-protocol LSP server, but could not do it since I'm not too familiar of how these things should work. I expected that after building that project (which I succeeded) I would have an executable server, which I just need to configure appropriately, but didn't find that executable.
> 
> Anyone else ideas how to make it work with TabNine?

Did you tried the Omnisharp Roslyn LSP from here >> https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Stdio.Driver/Program.cs

**Comment by jarmo** [comment]
Good tip! I managed to compile https://github.com/OmniSharp/omnisharp-roslyn however when configuring it in `TabNine.toml` like this (for Vim):

```
[language.cs]
command = "C:\\bin\\win7-x64\\OmniSharp.exe"
```

I just see "The language server exited unexpectedly" in TabNine code completion window in Vim. Is there anywhere I could see any log files of TabNine?

**Comment by jarmo** [comment]
I also tried `-lsp` switch (-lsp | --languageserver    Use Language Server Protocol.), like this:

```
[language.cs]
command = "c:\\bin\\win7-x64\\OmniSharp.exe"
args = ["-lsp"]
```

No difference.

**Comment by Shougo** [comment]
I think it should be asked in omnisharp repository.

**Comment by jarmo** [comment]
What part? If I execute OmniSharp.exe myself then it seems to work as expected so it seems to be more like a TabNine or its configuration problem. That's why I asked if I could see any logs created by TabNine.

**Comment by Shougo** [comment]
It is Tabnine related problem?
I think Omnisharp behavior is different from other LSP commands.

**Comment by Shougo** [comment]
Please test Omnisharp -lsp manually without Tabnine.

**Comment by jarmo** [comment]
Do you have any suggestions as to how could I test it manually? By just running it, it does not show any output and keeps running (does not crash) - I expect it does wait for some input to give me some output. Can I pipe something into it to test if it works as expected?

I'm sorry, but I don't know too much about inner workings of LSP-s and have previously only setup some to run with TabNine (basically just configuring TabNine.toml).

**Comment by Shougo** [comment]
So I should ask it on Omnisharp repository.
Omnisharp LSP behavior is not same with others.

**Comment by jarmo** [comment]
@Shougo do you know that this is the case or do you suspect that this is the case?

**Comment by Shougo** [comment]
Tabnine use stdin and stdout to communicate.
I think Omnisharp doesn't use the interface.

**Comment by jarmo** [comment]
Looking at the code at https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.Stdio.Driver/Program.cs and reading the name `OmniSharp.Stdio.Driver` imply that it should work over stdin/stdout.

**Comment by LambdaRan** [comment]
> ```
> [language.cs]
> command = "C:\\bin\\win7-x64\\OmniSharp.exe"
> ```

Use `scoop` to install `omnisharp` under windows system, and then configure `TabNine.toml` as follows(for emacs):
```
[language.csharp]
command = "omnisharp"
```
It work!
![image](https://user-images.githubusercontent.com/24838086/131772330-54504ab8-4cc6-4b1a-b0db-63e3731544a2.png)
