### ISSUE TITLE
The plugin does not support responding in the language set by the client

### ISSUE THREAD

**Issue by web-mobli** [codota/TabNine#642]
**please complete the following information:**	
 - OS version: win11	
 - Editor: vscode
 - Editor version: 1.87.2
 - Programming language: js、dart	
 - TabNine extension version: 3.83.0
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
My vscode is set to Simplified Chinese, but every time I use either fix code or explain code, it only answers in English. I need to input another sentence "Please answer in Chinese" to turn it into Chinese. Expect to reply based on the language set by the client

**Comment by TzufTabnine** [comment]
English is the only supported natural language. We do not officially support Chinese ( I guess you meant Mandarin)
