### ISSUE TITLE
Chinese Characters are not showing correctly 

### ISSUE THREAD

**Issue by lexnewgate** [codota/TabNine#646]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: 
JetBrainsRider
 - Editor version: 2024.1.1
 - Programming language:  csharp
 - TabNine extension version: 1.83.0
 - Engine version (could be located within Tabnine Hub):  4.159.0-62

**Issue Details:**
![image](https://github.com/codota/TabNine/assets/9143758/893a5f6f-90e7-4698-bd0e-ec43b14160f7)

gz#31400<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31400'>Zendesk ticket #31400</a>)</i>

**Comment by lexnewgate** [comment]
But when I hit tab, the autocomplete Chinese characters are showing correctly.

**Comment by TzufTabnine** [comment]
We don't officially support the Chinese. Only English
