### ISSUE TITLE
Super low resolution icon

### ISSUE THREAD

**Issue by Micnubinub** [codota/TabNine#648]
**please complete the following information:**	
 - OS version: MacOS 14.5
 - Editor: IntelliJ
 - Editor version: 2024.1.2
 - TabNine extension version: 1.87

Not a huge issue, but the small icons look terrible, the bigger ones on the side panels are great and high resolution, not sure what's going on with the smaller ones
<img width="420" alt="image" src="https://github.com/codota/TabNine/assets/4921356/bf2be14d-1eaf-49d9-8a5f-6dfa7c49268d">
All other icons look crispy
<img width="864" alt="image" src="https://github.com/codota/TabNine/assets/4921356/9fd42815-e242-4804-b852-66af60662fc0">

gz#31879<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/31879'>Zendesk ticket #31879</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @Micnubinub ,
When you say the small icons, do you mean the one in the status bar?

**Comment by Micnubinub** [comment]
@TzufTabnine 
Status bar and code block suggestions (check screenshots)

**Comment by TzufTabnine** [comment]
Ok, thanks for the feedback. We are working on changing the icons.
