### ISSUE TITLE
You've reached the rate limit for sending messages with the current model! This limit helps us ensure a high-quality experience for all users. Please wait a bit before attempting to send more messages.

### ISSUE THREAD

**Issue by zhangheng2022** [codota/TabNine#649]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

I'm on probation, why is this happening?

gz#32818<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/32818'>Zendesk ticket #32818</a>)</i>

**Comment by TzufTabnine** [comment]
We have a rate limit  to the different models (not to our protected model)
