### ISSUE TITLE
Tabnine extendtion use more than 40G memory on my MacOS

### ISSUE THREAD

**Issue by wait2035** [codota/TabNine#650]
**Tabnine extendtion use more than 40G memory on my MacOS**	
 - OS version: [Mac Sonoma 14.5]	
 - Editor: [vscode]	
 - Editor version: 
```
Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:54:35.075Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0

```
 - Programming language: [c/c++, python, multi-language project]	
 - TabNine extension version: 3.116.0
 - Engine version (could be located within Tabnine Hub):  4.174.0-45

**Issue Details:**

I'm a tabnine pro user, when i open my project in vscode, is worked fine, but after i active tabnine extention, it got stuck.
I open the task monitor, I saw a 'vdb' program using more than 40G memory, once i disabled the tabnine, it come back normal.

I know it will use my system resource to load tabnine backend program, but how can it be so amazing ? are u crazy ? 

gz#32886<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/32886'>Zendesk ticket #32886</a>)</i>

**Comment by TzufTabnine** [comment]
@wait2035 How big is your workspace? Do you want to index all of it? Try to limit what is being indexed ( https://docs.tabnine.com/main/welcome/readme/personalization/tabnines-personalization-in-depth#what-files-are-being-indexed) and check again

**Comment by wait2035** [comment]
> @wait2035 How big is your workspace? Do you want to index all of it? Try to limit what is being indexed ( https://docs.tabnine.com/main/welcome/readme/personalization/tabnines-personalization-in-depth#what-files-are-being-indexed) and check again

A lot of building objects, total 17G. I will try as you said above.
