### ISSUE TITLE
How to remove the shortcut `tabine: test | explain | document | ask`

### ISSUE THREAD

**Issue by matheustecchio** [codota/TabNine#652]
- OS version: Linux Mint 21
 - Editor: VS Code
 - Programming language: Go
 - TabNine extension version: Latest

How can I disable this line shortcut `tabine: test | explain | document | ask`?

![image](https://github.com/user-attachments/assets/8523c730-4d5e-476e-b306-733b834ce589)

Very annoying feature actually, I prefer not to have extensions polluting my code with those things. Thanks!

gz#33391<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/33391'>Zendesk ticket #33391</a>)</i>

**Comment by TzufTabnine** [comment]
https://support.tabnine.com/hc/en-us/articles/20951637600273-Enable-Disable-Code-Lens-in-VS-Code-and-JetBrains

**Comment by abdamah** [comment]
How can I disable this line shortcut tabine: test | explain | document | ask in VS Code editor?

![Screenshot 2025-01-03 at 12 07 29 PM](https://github.com/user-attachments/assets/0aefed30-9994-4a22-a01c-19b89cdb3105)

It is an annoying feature actually, I want not to have this silly suggestions. Please let me know if there is a way to disable ?

**Comment by TzufTabnine** [comment]
https://support.tabnine.com/hc/en-us/articles/20951637600273-Enable-Disable-Code-Lens-in-VS-Code-and-JetBrains
