### ISSUE TITLE
IntelliJ IDEA initialization error

### ISSUE THREAD

**Issue by Farami** [codota/TabNine#653]
**please complete the following information:**	
 - OS version: Mac Sonoma	
 - Editor: intellij IDEA
 - Editor version: IntelliJ IDEA 2024.1.4 (Community Edition)
 - Programming language: Java
 - TabNine extension version:1.113.0
 - Engine version (could be located within Tabnine Hub): 4.185.0-62

**Issue Details:**
After installing and logging in when opening the chat window I get spammed with the error `Something went wrong. Please try again`.
Autocomplete does not work either.
Opening the debug window reveals the following exception being thrown with every interaction:
```
202405180:205 TypeError: Cannot destructure property 'token' of '(intermediate value)' as it is undefined.
    at s (202405180:205:17726)
    at async Object.queryFn (202405180:205:18085)
```

I have tried uninstalling and reinstalling everything (including the `.tabnine` folder and both folders under `Library`). No change.

gz#33583<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/33583'>Zendesk ticket #33583</a>)</i>

**Comment by TzufTabnine** [comment]
Hi
Please send us the full logs

**Comment by Farami** [comment]
Hi,

please find attached all log files I can find.

[logs.zip](https://github.com/user-attachments/files/16411732/logs.zip)

**Comment by TzufTabnine** [comment]
@Farami 
Could you please update your plugin and verify if the issue still persists?

**Comment by Farami** [comment]
> @Farami Could you please update your plugin and verify if the issue still persists?

It works now after updating. Thank you for the quick response and fix.
