### ISSUE TITLE
Lost Connection After Latest Update

### ISSUE THREAD

**Issue by DsMachines** [codota/TabNine#654]
- OS version: Win 10	
 - Editor: vscode	
 - Editor version: 1.92	
 - Programming language: PHP
 - TabNine extension version: Can't check. I lost connection to Tabnine instantly after updating to the latest Tabnine 20 minutes ago.
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**
1- Right after updating to the latest Tabnine about 20 minutes ago. I have lost all connections to using Tabnine. I cant see any Ai model options anymore.
2- Thus, I log out from Tabnine and then tried to log in through GITHUB from the following URL; https://app.tabnine.com/signin with the following error message popped up: 'Unable to log in with the selected provider. If you signed up with an email and password, please use those credentials to log in'.
3- Since I've registered and logged in through GITHUB in the past, for me to now log in through email and password, i had to click lost password but then this message popped up when I click lost password 'Failed to send verification email for some reason. Please contact support.' 

I have tried to contact support from Tabnine website: https://www.tabnine.com/ and this message popped up; 'no healthy upstream'.

Can you assist to get this resolved..

Regards.

gz#33960<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/33960'>Zendesk ticket #33960</a>)</i>

**Comment by duckii021** [comment]
+1

**Comment by IRediTOTO** [comment]
+111111111 :D So funny with a BIG product, thousands of dev waiting for you

**Comment by Wellitonzs** [comment]
Waiting for a solution here too

**Comment by wikytam** [comment]
+1

**Comment by Biazza** [comment]
+1. I think they are having problems with their server. Their website is very slow.

**Comment by faelin** [comment]
Their entire service is down: 
![image](https://github.com/user-attachments/assets/76f3bfdb-7b18-4119-b543-74d10b54bbe8)

**Comment by faelin** [comment]
It's back up!
