### ISSUE TITLE
Apply for a refund because I did not know about the deduction

### ISSUE THREAD

**Issue by smileAllYears** [codota/TabNine#655]
I applied for a refund, because I did not know about the deduction of money, because I was asked to bind Alipay Huabai when using free, but the deduction was automatic and did not ask me

gz#33993<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/33993'>Zendesk ticket #33993</a>)</i>

**Comment by amirbilu** [comment]
Hi smileAllYears, this is ticket **33993**

Thanks for contacting us!

We couldn’t find a Tabnine account associated with the email smileallyears@tabnine.com. Could you please provide the email address you used when signing up for Tabnine Pro?

Additionally, if you have a copy of the invoice (including the invoice number), that would help us track the transaction more efficiently. Thank you!

Best regards,
Ramona Rodriguez
Tabnine Support
 ![](https://lh7-us.googleusercontent.com/vOTbrJsjfvm6EgqQbmheSd04t22FIKdXUs6VF9x2v5mujmovuFI9gobKTTaCOsXQOD60f11ZjxbIaFVwuKGspHy7MCUumTQbfqpwnM991xE2iCEHyJ7BWyqSKaMsltmCN4nCu7IAaeqk67J2s-VogxI)
<br><p><em><small>°°°</small></em></p>

**Comment by smileAllYears** [comment]
okk, z2368175@gmail.com

**Comment by smileAllYears** [comment]
> 嗨 smileAllYears，这是票 **33993**
> 谢谢您联络我们！
> 
> 我们找不到与电子邮件[smileallyears@tabnine.com](mailto:smileallyears@tabnine.com)关联的 Tabnine 帐户。您能否提供注册 Tabnine Pro 时使用的电子邮件地址？
> 
> 此外，如果您有发票副本（包括发票号码），这将有助于我们更有效地追踪交易。谢谢！
> 
> 谨致问候， Ramona Rodriguez Tabnine 支持 ![](https://camo.githubusercontent.com/d7570e480b45597361f06c416c2babfe3ccb75f919d39864137f0788c620e3d4/68747470733a2f2f6c68372d75732e676f6f676c6575736572636f6e74656e742e636f6d2f764f5462724a736a66766d3645677151626d68655364303474323246494b6458557336564639783276356d756a6d6f7675464939676f624b545461434f7358514f4436306631315a6a78624961465677754b4773704879374d4355756d545162667170776e4d39393178453269434548794a3742577971534b614d736c746d434e346e43753749416165716b36374a32732d566f677849)
> 
> _°°°_

okk, z2368175@gmail.com

**Comment by smileAllYears** [comment]
> Hi smileAllYears, this is ticket **33993**
> Thanks for contacting us!
> 
> We couldn’t find a Tabnine account associated with the email [smileallyears@tabnine.com](mailto:smileallyears@tabnine.com). Could you please provide the email address you used when signing up for Tabnine Pro?
> 
> Additionally, if you have a copy of the invoice (including the invoice number), that would help us track the transaction more efficiently. Thank you!
> 
> Best regards, Ramona Rodriguez Tabnine Support ![](https://camo.githubusercontent.com/d7570e480b45597361f06c416c2babfe3ccb75f919d39864137f0788c620e3d4/68747470733a2f2f6c68372d75732e676f6f676c6575736572636f6e74656e742e636f6d2f764f5462724a736a66766d3645677151626d68655364303474323246494b6458557336564639783276356d756a6d6f7675464939676f624b545461434f7358514f4436306631315a6a78624961465677754b4773704879374d4355756d545162667170776e4d39393178453269434548794a3742577971534b614d736c746d434e346e43753749416165716b36374a32732d566f677849)
> 
> _°°°_

okk z2368175@gmail.com

**Comment by amirbilu** [comment]
Hi smileAllYears, this is ticket **33993**

Thanks for giving Tabnine a try - we’re sorry to see you go.

I’ve taken care of your cancelation request and issued a refund. It'll be processed in the next 5-10 business days. You should get the refund receipt in your mailbox.

Thank you and best wishes,

Ramona Rodriguez
Tabnine Support
 ![](https://lh7-us.googleusercontent.com/vOTbrJsjfvm6EgqQbmheSd04t22FIKdXUs6VF9x2v5mujmovuFI9gobKTTaCOsXQOD60f11ZjxbIaFVwuKGspHy7MCUumTQbfqpwnM991xE2iCEHyJ7BWyqSKaMsltmCN4nCu7IAaeqk67J2s-VogxI)
<br><p><em><small>°°°</small></em></p>

**Comment by smileAllYears** [comment]
> Hi smileAllYears, this is ticket **33993**
> Thanks for giving Tabnine a try - we’re sorry to see you go.
> 
> I’ve taken care of your cancelation request and issued a refund. It'll be processed in the next 5-10 business days. You should get the refund receipt in your mailbox.
> 
> Thank you and best wishes,
> 
> Ramona Rodriguez Tabnine Support ![](https://camo.githubusercontent.com/d7570e480b45597361f06c416c2babfe3ccb75f919d39864137f0788c620e3d4/68747470733a2f2f6c68372d75732e676f6f676c6575736572636f6e74656e742e636f6d2f764f5462724a736a66766d3645677151626d68655364303474323246494b6458557336564639783276356d756a6d6f7675464939676f624b545461434f7358514f4436306631315a6a78624961465677754b4773704879374d4355756d545162667170776e4d39393178453269434548794a3742577971534b614d736c746d434e346e43753749416165716b36374a32732d566f677849)
> 
> _°°°_


Refund received
