### ISSUE TITLE
Can't get completions because Tabnine process is not started yet

### ISSUE THREAD

**Issue by q920447939** [codota/TabNine#656]
**please complete the following information:**	
 - OS version: WIN7 SP1
 - Editor: intelij idea
 - Editor version:	2023.1.7
 - Programming language: java
 - TabNine extension version: 1.125.0
 - Engine version (could be located within Tabnine Hub):  i know't not find zhe engine version 

**Issue Details:**
i restart my  intelij idea，i wish use Tabnine  tip some code ,
But the Tabnine doesn't react at all
i find the   intelij idea log

```
2024-08-26 10:13:43,175 [ 295687]   INFO - #com.tabnineCommon.binary.BinaryProcessRequesterProvider - Can't get completions because Tabnine process is not started yet.
2024-08-26 10:13:43,751 [ 296263]   INFO - #com.tabnineCommon.binary.BinaryProcessRequesterProvider - Can't get completions because Tabnine process is not started yet.
```

what do i need to do ?

gz#34454<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/34454'>Zendesk ticket #34454</a>)</i>

**Comment by q920447939** [comment]
My computer needs an agent to access the Internet , I configured the software agent , I used another software to make the transparent proxy (by regular domain  *tabnine* )

Still no response

**Comment by TzufTabnine** [comment]
Hi @q920447939, In order to use Tabnine, you will need a decent internet connection. See here https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
