### ISSUE TITLE
VS2022 Extension - cannot log in

### ISSUE THREAD

**Issue by mklasek** [codota/TabNine#657]
**please complete the following information:**	
 - OS version: Windows 11 Pro - 22631
 - Editor: Visual Studio 2022
 - Editor version: 17.11.5
 - TabNine extension version: 1.133.1
 - Engine version: 4.198.0-60
 - VS is running with admin privileges

**Issue Details:**
I've been using TabNine in VSCode for a few months without issues but in VS it has never worked on my PC, which is now beginning to be a problem. 

The "Login" button in Tabnine chat window doesn't do anything, messages in Tabnine output when it's pressed:
[Debug] [ChatCommunicator] {"id":"login6","command":"login"}
[Error] [ChatCommunicator] Error while handling message: Error HRESULT E_FAIL has been returned from a call to a COM component.
[Debug] [ChatCommunicator] execute command "window.postMessage({\"id\":\"login6\",\"payload\":{\"error\":\"Error HRESULT E_FAIL has been returned from a call to a COM component.\"}})"

Similarly
Extensions->Tabnine->Sign in using access token OR Open Hub
[Debug] [InternalExclusiveBinaryFacade] ValidToCallInit: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task execution")
[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")

Extensions->Tabnine->Sign in using access token also results in this exception in Extensions output:
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at TabNineVisualStudio2022.User.TabnineSettings.OpenManualAccessTokenPage()
   at TabNineVisualStudio2022.Commands.AccessTokenLoginCommand.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand.<>c__DisplayClass8_0.<<Execute>b__0>d.MoveNext()
   
   These 3 lines keep repeating in the Tabnine output periodically:
   [Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")
[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")
[Warning] [CapabilitiesManager] No response from the binary for capabilities request

Is there something wrong with the configuration of my VS? None of my colleagues encountered this issue

gz#35578<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/35578'>Zendesk ticket #35578</a>)</i>

**Comment by TzufTabnine** [comment]
What browser do you use? Try Chrome.
Try this - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues
If it is still an issue, try deleting the binary and try again -https://support.tabnine.com/hc/en-us/articles/5233246440337-Visual-Studio-2022-binary-locations

**Comment by mklasek** [comment]
So, I tried all that with no success, however, at one VS startup I noticed this line in Tabnine output: 
[Debug] [Util] Binary path is: C:\Users\KlasekM\.tabnine\4.75.0\x86_64-pc-windows-msvc\TabNine.exe

The extension then started to download TabNine.zip, which it did succesfully, into the folder 4.198.0 and then crashed again- System cannot find the path

Then I tried startup again, and it was still looking for the binary in the 4.75.0 folder, which was empty, downloaded again into 4.198.0 and crashed again, so naturally I tried copying the contents of the 4.198.0 folder into the 4.75.0 folder and the next startup seems to be succesful apart from one error and Tabnine now works: 

[Debug] [InternalExclusiveBinaryFacade] Binary lifecycle state change: "Uninitialized" => "Starting(reason=\"Initializing\")"
[Debug] [Util] Binary path is: C:\Users\KlasekM\.tabnine\4.75.0\x86_64-pc-windows-msvc\TabNine.exe
[Debug] [BinaryProcessStarter] Process command args: "--client \"visual-studio-2022\" --client-metadata pluginVersion=1.133.1 clientEdition=Community settingsProxyUrlSet=False settingsUseProxySet=True settingsIgnoreSSLErrorsSet=False reSharperInstalled=False --tls_config false"
[Debug] [BinaryProcessStarter] Started TabNine process
[Debug] [StartingStateHandler] Successfully started binary with path from [".active file"]
[Debug] [InternalExclusiveBinaryFacade] Binary lifecycle state change: "Starting(reason=\"Initializing\")" => "Running(consecutiveRequestFailures=0)"
[Error] [UserStateManager] Team is not available in SaaS mode
[Error] [UserStateManager] Team is not available in SaaS mode
[Error] [UserStateManager] Team is not available in SaaS mode
[Debug] [CapabilitiesManager] Got new capabilities response with telemetry, tabnine-lite, sublime.new-experience, promoteHub1, inline_suggestions_mode.vscode, inline_suggestions_feature_mode, should_open_welcome_in_hub, should_use_hub_new_design, is_preview_enabled, snippet_suggestions_is_enabled_by_generation, chat_is_enabled_by_generation, inline_suggestions_mode, plugin.feature.tabnine_chat, vscode_inline_v2, snippet_suggestions, snippet_suggestions_configurable, vscode.authentication, vscode.notifications-widget, vscode.tabnine-today-widget

So issue resolved for now I guess but it looks like a bug in where it's looking for the binary to me
