### ISSUE TITLE
Visual Studio workspace indexing and explore codebase command are not working for me.

### ISSUE THREAD

**Issue by jmeyer1980** [codota/TabNine#659]
**please complete the following information:**	
 - OS version: Windows 10	
 - Editor: Visual Studio 2022
 - Editor version:	
 - Programming language: C#
 - TabNine extension version: 1.142.1
 - Engine version (could be located within Tabnine Hub): 4.200.0-62

**Issue Details: I open my Unity project. I right click on an empty area within my project folder and open C# project. My project opens in Visual Studio. I open Tabnine chat. It shows ready and logged in. Unfortunately, workspace indexing never starts. It simply never begins. No errors. I have a Readme.md file in the project, but I have no idea if it is in the right location or if it includes what is needed by Tabnine, as attempting to explore the codebase returns an error telling me that it requires a package manager file or a readme to work.

In the end, because I can't find any information telling me how to correctly prepare a package manager file or readme file for Tabnine use, the responses to my chat requests are very poor. I have ended up having more success with Microsoft Copilot and will most likely end up canceling my Tabnine subscription because of this.**

gz#36071<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36071'>Zendesk ticket #36071</a>)</i>

**Comment by TzufTabnine** [comment]
Try closing the IDE, deleting the VDB folder ( https://support.tabnine.com/hc/en-us/articles/24781988831767-VDB-logs)
and try again.

**Comment by jmeyer1980** [comment]
Thank you. That reset things for me so I could create that .tabnine_root file I didn't know I was missing. Cheers!

**Comment by TzufTabnine** [comment]
Great!
