### ISSUE TITLE
Data not saving to the data base

### ISSUE THREAD

**Issue by kvijayarajan** [codota/TabNine#660]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]	
 - Editor: [e.g. vscode, intelij, sublime]	
 - Editor version:	
 - Programming language: [e.g. js, ts, c++]	
 - TabNine extension version:
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

<?php
// Enable error reporting for debugging
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

error_log(print_r($_POST, true)); // This will log the contents of the POST request

$servername = "localhost"; // Change if necessary
$username = "root"; // Change if necessary
$password = ""; // Change if necessary
$dbname = "mobile_pos"; // Change if necessary

// Connect to the database
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Generate invoice number
$invoice_number = "INV-" . uniqid(); // Example format INV-<unique_id>

// Fetch customer names from the database
$customers = [];
$sql = "SELECT id AS customer_id, name AS customer_name FROM customers";
$result = $conn->query($sql);

if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $customers[] = $row;
    }
} else {
    echo "<p>No customers found.</p>";
}

// Fetch items from the stock table
$items = [];
$sql = "SELECT barcode, item_name, cost_price FROM stock"; // Use cost_price from the stock table
$result = $conn->query($sql);

if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $items[] = $row;
    }
}
// Generate invoice number
function generateInvoiceNumber($conn) {
    $sql = "SELECT invoice_number FROM invoices ORDER BY id DESC LIMIT 1";
    $result = $conn->query($sql);
    if ($result->num_rows > 0) {
        $row = $result->fetch_assoc();
        $lastInvoiceNumber = $row['invoice_number'];
        $lastNumber = (int)substr($lastInvoiceNumber, 4);
        $nextNumber = $lastNumber + 1;

        if ($nextNumber > 999999) {
            $nextNumber = 1; // Reset to INV-000001 after reaching INV-999999
        }
        return "INV-" . str_pad($nextNumber, 6, "0", STR_PAD_LEFT);
    } else {
        return "INV-000001"; // First invoice
    }
}

$invoice_number = generateInvoiceNumber($conn);

// Fetch payment methods from the database
$payment_methods = [];
$sql = "SELECT id AS payment_id, method_name FROM payment_methods";
$result = $conn->query($sql);

if ($result && $result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        $payment_methods[] = $row;
    }
} else {
    echo "<p>No payment methods found.</p>";
}

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['customer'])) {
        $customer_id = $_POST['customer'];
        // $payment_details = json_decode($_POST['payment_details'], true);
        error_log(print_r($_POST, true)); // This will log the contents of the POST request

        // Validate customer selection
        if (empty($customer_id) || empty($payment_details)) {
            $error = "Please fill in all fields.";
        } else {
            // Fetch the customer's name based on the customer_id
            $customer_sql = "SELECT name FROM customers WHERE id = ?";
            $stmt = $conn->prepare($customer_sql);
            $stmt->bind_param("i", $customer_id);
            $stmt->execute();
            $result = $stmt->get_result();
            $customer = $result->fetch_assoc();
            $client_name = $customer['name'];

            // Insert into invoices
            $invoice_sql = "INSERT INTO invoices (invoice_number, customer_id, client_name, date) VALUES (?, ?, ?, NOW())";
            $stmt = $conn->prepare($invoice_sql);
            $stmt->bind_param("sis", $invoice_number, $customer_id, $client_name);
            if (!$stmt->execute()) {
                $error = "Error inserting invoice: " . $stmt->error;
            } else {
                // Get the last inserted invoice ID
                $invoice_id = $conn->insert_id;

                // Process invoice items
                for ($i = 0; $i < count($_POST['barcode']); $i++) {
                    $barcode = $_POST['barcode'][$i];
                    $item_name = $_POST['item_name'][$i];
                    $quantity = $_POST['quantity'][$i];
                    $item_price = $_POST['item_price'][$i];
                    $discount = $_POST['discount'][$i];

                    // Calculate line total
                    $line_total = ($item_price - $discount) * $quantity;

                    // Insert invoice items into the database
                    $invoice_item_sql = "INSERT INTO invoice_items (invoice_id, barcode, item_name, item_quantity, item_price, discount, line_total) VALUES (?, ?, ?, ?, ?, ?, ?)";
                    $stmt = $conn->prepare($invoice_item_sql);
                    $stmt->bind_param("issidsd", $invoice_id, $barcode, $item_name, $quantity, $item_price, $discount, $line_total);
                    if (!$stmt->execute()) {
                        $error = "Error inserting invoice item: " . $stmt->error;
                    }
                }
                
                // Handle payment details
                foreach ($payment_details as $payment) {
                    $payment_method = $payment['payment_method'];
                    $amount = $payment['amount'];

                    // Insert payment details into the database (assuming a payment table exists)
                    $payment_sql = "INSERT INTO payments (invoice_id, payment_method, amount) VALUES (?, ?, ?)";
                    $stmt = $conn->prepare($payment_sql);
                    $stmt->bind_param("isd", $invoice_id, $payment_method, $amount);
                    $stmt->execute();
                }

                // Clear form fields after submission
                $_POST = [];
            }
        }
    }

    // Handle AJAX request to fetch customer details
    if (isset($_POST['fetch_customer_details'])) {
        $customer_id = $_POST['customer_id'];
        $sql = "SELECT name, address, telephone, email FROM customers WHERE id = ?";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param("i", $customer_id);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows > 0) {
            $customer_details = $result->fetch_assoc();
            echo json_encode($customer_details);
        } else {
            echo json_encode(['name' => '', 'address' => '', 'telephone' => '', 'email' => '']);
        }
        exit(); // Exit to prevent further output
    }

    // Handle AJAX request to fetch item name and price based on barcode
    if (isset($_POST['fetch_item_details'])) {
        $barcode = $_POST['barcode'];
        $sql = "SELECT item_name, cost_price FROM stock WHERE barcode = ?";
        $stmt = $conn->prepare($sql);
        $stmt->bind_param("s", $barcode);
        $stmt->execute();
        $result = $stmt->get_result();
        
        if ($result->num_rows > 0) {
            $item = $result->fetch_assoc();
            echo json_encode($item);
        } else {
            echo json_encode(['item_name' => '', 'cost_price' => '']);
        }
        exit(); // Exit to prevent further output
    }
}

// Close database connection
$conn->close();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice Management System</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <style>
        .form-control {
            font-size: 0.8rem;
        }
        .form-label {
            font-size: 0.8rem;
        }
        .table th, .table td {
            font-size: 0.8rem;
        }
        #invoiceItemsTable {
            font-size: 0.8rem;
        }
        .form-row {
            display: flex;
            align-items: center;
            margin-bottom: 0.5rem;
        }
    </style>
</head>
<body>
<div class="container">
        <h1 class="text-center">Invoice Management System</h1>
        <h4 class="text-center">Invoice Number: <span id="invoice_number"><?php echo $invoice_number; ?></span></h4>

        
        <form method="POST" id="invoice-form">
            <div class="form-group">
                <label for="customer">Select Customer:</label>
                <select name="customer" id="customer" class="form-control" required>
                    <option value="">-- Select Customer --</option>
                    <?php foreach ($customers as $customer): ?>
                        <option value="<?= $customer['customer_id'] ?>"><?= $customer['customer_name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            
            <div id="customer-details" class="mb-3">
                <h4>Customer Details</h4>
                <p><strong>Customer Name:</strong> <span id="customer-name"></span></p>
                <p><strong>Address:</strong> <span id="customer-address"></span></p>
                <p><strong>Telephone:</strong> <span id="customer-telephone"></span></p>
                <p><strong>Email:</strong> <span id="customer-email"></span></p>
            </div>

            <h3 class="text-center">Invoice Items</h3>
            <table class="table" id="invoiceItemsTable">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Item Name</th>
                        <th>Quantity</th>
                        <th>Item Price</th>
                        <th>Discount</th>
                        <th>Line Total</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <select name="barcode[]" class="form-control barcode" required>
                                <option value="">Select Item</option>
                                <?php foreach ($items as $item): ?>
                                    <option value="<?php echo $item['barcode']; ?>"><?php echo $item['barcode']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </td>
                        <td><input type="text" class="form-control item_name" name="item_name[]" readonly></td>
                        <td><input type="number" class="form-control quantity" name="quantity[]" min="1" value="1" required></td>
                        <td><input type="number" class="form-control item_price" name="item_price[]" required></td>
                        <td><input type="number" class="form-control discount" name="discount[]" value="0" required></td>
                        <td><input type="number" class="form-control line_total" name="line_total[]" readonly></td>
                        <td><button type="button" class="btn btn-danger remove-item">Remove</button></td>
                    </tr>
                </tbody>
               
            </table>
            <button type="button" class="btn btn-primary" id="addItem">Add Item</button>

            <div class="container">
                    <div class="row">
                        <div class="col-md-6">

                        <div class="container">
    <div class="row">
    <div class="col-md-6 mt-2">
    <h3 class="text-start" style="font-size: 2rem; font-weight: bold;">Total</h3>
    
    <div class="form-group row ">
        <label class="col-sm-6 col-form-label text-start" style="font-size: 1rem;" for="subtotal">Subtotal:</label>
        <div class="col-sm-6 text-start ">
            <span id="subtotal" >0.00</span>
        </div>
    </div>

    <div class="form-group row">
        <label for="round_off_discount" class="col-sm-6 col-form-label text-start" style="font-size: 1rem;">Round Off Discount:</label>
        <div class="col-sm-6">
            <input type="number" class="form-control" id="round_off_discount" name="round_off_discount" value="0" >

        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-6 col-form-label text-start" style="font-size: 1rem;" for="grand_total">Grand Total:</label>
        <div class="col-sm-6 text-start"><label for=""></label>
            <span id="grand_total">0.00</span>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-sm-6 col-form-label text-start" style="font-size: 1rem;" for="balance">Balance:</label>
        <div class="col-sm-6 text-start">
            <span id="balance">0.00</span>
        </div>
    </div>
</div>
    </div>
</div>
                        </div>
                        <div class="col-md-6">
                        <h3 class="text-center">Payment Methods</h3>
            <div id="paymentMethodsContainer">
                <div class="form-row payment-row">
                    <label class="form-label" for="payment_method">Payment Method:</label>
                    <select name="payment_method[]" class="form-control payment_method" required>
                        <option value="">Select Payment Method</option>
                        <?php foreach ($payment_methods as $method): ?>
                            <option value="<?php echo $method['payment_id']; ?>"><?php echo $method['method_name']; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <label class="form-label" for="payment_amount">Amount:</label>
                    <input type="number" class="form-control payment_amount" name="payment_amount[]" value="0" required>
                </div>
            </div>
            <button type="button" class="btn btn-primary" id="addPaymentMethod">Add Payment Method</button>
                        </div>
                    </div>
                </div>

           

            <div class="text-center mt-3">
                <button type="submit" class="btn btn-success">Submit Invoice</button>
            </div>
        </form>
    </div>

    <script>
$(document).ready(function() {
    let totalPayments = 0;
    const $submitButton = $('.btn-success'); // Reference to the submit button
    const addedPaymentMethods = new Set(); // To keep track of selected payment methods

    function calculateTotals() {
        let subtotal = 0;
        $('#invoiceItemsTable tbody tr').each(function() {
            const quantity = $(this).find('.quantity').val();
            const itemPrice = $(this).find('.item_price').val();
            const discount = $(this).find('.discount').val();
            const lineTotal = (itemPrice - discount) * quantity;
            $(this).find('.line_total').val(lineTotal.toFixed(2));
            subtotal += lineTotal;
        });
        $('#subtotal').text(subtotal.toFixed(2));
        calculateGrandTotal(subtotal);
    }

    function calculateGrandTotal(subtotal) {
        const roundOffDiscount = parseFloat($('#round_off_discount').val()) || 0;
        const grandTotal = subtotal - roundOffDiscount;
        $('#grand_total').text(grandTotal.toFixed(2));
        calculateBalance(grandTotal);
    }

    function calculateBalance(grandTotal) {
        const balance = grandTotal - totalPayments;

        if (balance < 0) {
            alert("Balance cannot be less than zero.");
            $('#balance').text('0.00'); // Set balance to zero
        } else {
            $('#balance').text(balance.toFixed(2));
        }

        // Enable or disable the submit button based on the balance
        if (balance > 0) {
            $submitButton.prop('disabled', true); // Disable submit button
        } else {
            $submitButton.prop('disabled', false); // Enable submit button
        }
    }

    // Add item functionality
    $('#addItem').click(function() {
        const newRow = `
            <tr>
                <td>
                    <select name="barcode[]" class="form-control barcode" required>
                        <option value="">Select Item</option>
                        <?php foreach ($items as $item): ?>
                            <option value="<?php echo $item['barcode']; ?>"><?php echo $item['barcode']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td><input type="text" class="form-control item_name" name="item_name[]" readonly></td>
                <td><input type="number" class="form-control quantity" name="quantity[]" min="1" value="1" required></td>
                <td><input type="number" class="form-control item_price" name="item_price[]" required></td>
                <td><input type="number" class="form-control discount" name="discount[]" value="0" required></td>
                <td><input type="number" class="form-control line_total" name="line_total[]" readonly></td>
                <td><button type="button" class="btn btn-danger remove-item">Remove</button></td>
            </tr>`;
        $('#invoiceItemsTable tbody').append(newRow);
    });

    // Calculate totals when quantity, price, or discount changes
    $(document).on('change', '.quantity, .item_price, .discount', function() {
        calculateTotals();
    });

    // Remove item row
    $(document).on('click', '.remove-item', function() {
        $(this).closest('tr').remove();
        calculateTotals();
    });

    // Fetch customer details on customer selection
    $('#customer').on('change', function() {
            var customerId = $(this).val();
            $.post("", { fetch_customer_details: true, customer_id: customerId }, function(data) {
                var customer = JSON.parse(data);
                $('#customer-name').text(customer.name);
                $('#customer-address').text(customer.address);
                $('#customer-telephone').text(customer.telephone);
                $('#customer-email').text(customer.email);
            });
        });

    // Fetch item details based on barcode
    $(document).on('change', '.barcode', function() {
        const barcode = $(this).val();
        const row = $(this).closest('tr');
        $.post('', { fetch_item_details: true, barcode: barcode }, function(data) {
            const item = JSON.parse(data);
            row.find('.item_name').val(item.item_name);
            row.find('.item_price').val(item.cost_price);
            calculateTotals();
        });
    });

    // Round off discount change
    $('#round_off_discount').on('input', function() {
        const subtotal = parseFloat($('#subtotal').text()) || 0;
        calculateGrandTotal(subtotal);
    });

    // Add new payment method input
    $('#addPaymentMethod').click(function() {
        const selectedMethod = $('.payment_method').last().val(); // Get the last selected payment method
        const newPaymentMethod = `<select name="payment_method[]" class="form-control payment_method" required>
            <option value="">Select Payment Method</option>
            <?php foreach ($payment_methods as $method): ?>
                <option value="<?php echo $method['payment_id']; ?>"><?php echo $method['method_name']; ?></option>
            <?php endforeach; ?>
        </select>`;

        // Check if payment method already added
        if (addedPaymentMethods.has(selectedMethod)) {
            alert("Payment method already added, please select another payment method.");
            return; // Prevent adding the payment method
        }

        addedPaymentMethods.add(selectedMethod); // Mark this payment method as added
        const newPaymentRow = `
            <div class="form-row payment-row">
                <label class="form-label" for="payment_method">Payment Method:</label>
                ${newPaymentMethod}
                <label class="form-label" for="payment_amount">Amount:</label>
                <input type="number" class="form-control payment_amount" name="payment_amount[]" value="0" required>
            </div>`;
        $('#paymentMethodsContainer').append(newPaymentRow);
    });

    // Calculate total payments and update balance
    $(document).on('change', '.payment_amount', function() {
        totalPayments = 0;
        $('.payment_amount').each(function() {
            totalPayments += parseFloat($(this).val()) || 0;
        });
        const grandTotal = parseFloat($('#grand_total').text()) || 0;
        calculateBalance(grandTotal);
    });

    // Validate payment methods before form submission
    $submitButton.click(function(e) {
        const paymentMethods = [];
        $('.payment_method').each(function() {
            const method = $(this).val();
            if (method) {
                paymentMethods.push(method);
            }
        });

        const methodCounts = {};
        for (const method of paymentMethods) {
            methodCounts[method] = (methodCounts[method] || 0) + 1;
            if (methodCounts[method] > 1) {
                alert("Check the payment methods; each payment method can only be used once.");
                e.preventDefault(); // Prevent form submission
                return;
            }
        }

        // Proceed with validation for balance
        const totalPayments = parseFloat($('#balance').text());
        if (totalPayments > 0) {
            alert("Please ensure the balance is zero before submitting the invoice.");
            e.preventDefault(); // Prevent form submission
        }
    });
    

    // Initial check to disable submit button
    calculateBalance(0);
});
        function validateForm() {
            const totalPayments = parseFloat($('#balance').text());
            if (totalPayments > 0) {
                alert("Please ensure the balance is zero before submitting the invoice.");
                return false; // Prevent form submission
            }
            return true; // Allow form submission
        }
    </script>
</body>
</html>

gz#36275<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36275'>Zendesk ticket #36275</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @kvijayarajan, What is the issue here?
