### ISSUE TITLE
Tabnine not woking on WSL2 Ubuntu 22.04

### ISSUE THREAD

**Issue by phuctoan197** [codota/TabNine#662]
**please complete the following information:**	
 - OS version:  Ubuntu 22.04.4 LTS on WSL2
 - Editor: vscode
 - Editor version: 1.95.3
 - Programming language: PHP
 - TabNine extension version: 3.192
 - Engine version (could be located within Tabnine Hub): 4.203

**Issue Details:**
I logged in successfully but tabnine is not working.
Tabnine error log:
12:09:09 GMT+0700 (Indochina Time) [ERROR]: Error: Binary request timed out. {"State":{}} 
12:09:11 GMT+0700 (Indochina Time) [ERROR]: validating /home/toan/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.203.0/x86_64-unknown-linux-musl/TabNine timeout 
Engine log:
TabNine ERROR] Error while fetching messages. reqwest::Error { kind: Decode, source: Error("EOF while parsing a value", line: 1, column: 0) }
[2024-11-19:12:48:01 TabNine ERROR] Failed to load capabilities cache Bad signature

**Comment by TzufTabnine** [comment]
@phuctoan197 
Try closing the IDE, and deleting the folder:

1.  /home/toan/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/**binaries**
2. Try again.

Also check here - https://support.tabnine.com/hc/en-us/articles/5760725346193-Connectivity-possible-issues

**Comment by phuctoan197** [comment]
@TzufTabnine 
About Tabnine AI error not login.
![image](https://github.com/user-attachments/assets/8b21efc9-cc30-444b-8df8-e43e4bc185fa)

![image](https://github.com/user-attachments/assets/14d168c2-0ef7-4bfa-b1de-0dd4bec4b4b5)

I have logged in to my account but it seems Tabnine AI chat not working.
Thank for your help.

**Comment by TzufTabnine** [comment]
@phuctoan197 What exactly is not working? I can see indexing is not complete yet.

**Comment by phuctoan197** [comment]
@TzufTabnine 
Working page index not complete after than 8hours.
This is not error?
And I tried chatting with the AI. The AI ​​didn't respond.

**Comment by TzufTabnine** [comment]
Try closing the IDE, deleting the [VDB ](https://support.tabnine.com/hc/en-us/articles/24781988831767-VDB-logs)folder, and then try again. Also make sure you are indexing only what you need - https://docs.tabnine.com/main/welcome/readme/personalization/tabnines-personalization-in-depth#the-rag-index
