### ISSUE TITLE
Apply for a refund because I did not know about the deduction

### ISSUE THREAD

**Issue by 14C3F8** [codota/TabNine#663]
I applied for a refund, because I did not know about the deduction of money, because I was asked to bind Alipay Huabai when using free, but the deduction was automatic and did not ask me. Please help cancel my subscription after the refund.

My receipt number is 2099-8152
invoice number: B045BC62-0002
payment method: Alipay

gz#36714<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36714'>Zendesk ticket #36714</a>)</i>

**Comment by TzufTabnine** [comment]
Please send all the relevant information to support@tabnine.com and we will take care of you

**Comment by 14C3F8** [comment]
I have sent an email to ***@***.***&nbsp;and ***@***.*** Hoping for your reply.

&nbsp;&nbsp; 
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "codota/TabNine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月21日(星期四) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [codota/TabNine] Apply for a refund because I did not know about the deduction (Issue #663)





 
Please send all the relevant information to ***@***.***&nbsp;and we will take care of you
