### ISSUE TITLE
Apply for a refund：receipt from Tabnine, Inc. #2099-8152  email to support@tabnine.com was rejected

### ISSUE THREAD

**Issue by 14C3F8** [codota/TabNine#664]
I applied for a refund, because I did not know about the deduction of money. I was asked to bind Alipay Huabai when using free, but the deduction was automatic.

I tried to email to support@tabnine.com and billing@tabnine.com, but my message was rejected. "For more information, go to https://support.google.com/mail/answer/69585"

Receipt #2099-8152

**Comment by TzufTabnine** [comment]
Please write down your email that associated with Tabnine

**Comment by 14C3F8** [comment]
1179031961@qq.com

**Comment by 14C3F8** [comment]
> Please write down your email that associated with Tabnine

1179031961@qq.com
