### ISSUE TITLE
Unauthorized attempted charges from TabNine, no communication from support

### ISSUE THREAD

**Issue by agoulah** [codota/TabNine#666]
I've cancelled my account, and have contacted support multiple times through emails and have not heard back.  There has been 4+ attempted charges to my credit card, which are not authorized.  I cannot change any of the details on the admin panel/billing page.  This is ridiculous that there is non-existent support.

gz#37259<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37259'>Zendesk ticket #37259</a>)</i>

**Comment by TzufTabnine** [comment]
Hi, what is your email address? When did you send an email to support?

**Comment by agoulah** [comment]
On Nov 30, Dec 5, Dec 7 I sent e-mails, each after the attempted charges to my credit card.  andrew@goulah.ca is my e-mail.

**Comment by TzufTabnine** [comment]
We couldn't find any email from you at support@tabnine.com. We did cancel your account and refunded you. You will see that in the next ten working days.

**Comment by jedwardnorm** [comment]
I am literally going through the exact same thing!!! 
![image](https://github.com/user-attachments/assets/0b730ee6-53a6-4e60-9e17-65ab82aee714)
![image](https://github.com/user-attachments/assets/dd3ae931-ab77-439b-af26-48d9f071ee5d)
