### ISSUE TITLE
Can't login VS

### ISSUE THREAD

**Issue by Jirka135** [codota/TabNine#667]
Hi, Im using VS 2022 17.12.3 windows 11P and i cannot login into tabnine

I tried reinstalling tabnine, VS , turn of firewall nothing helped.

[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")
[Warning] [CapabilitiesManager] No response from the binary for capabilities request
[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")
[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")
[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")
[Debug] [InternalExclusiveBinaryFacade] ValidToCallInit: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task execution")
[Debug] [InternalExclusiveBinaryFacade] ValidToCallProcessRequest: State ["FailedRunningBinary"]: not valid (reason: "check before triggering task")

gz#37737<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37737'>Zendesk ticket #37737</a>)</i>

**Comment by amirbilu** [comment]
Hi Jirka,
Please try the following:

1. check if you have anything in your $HOME/.tabnine folder,
2. Which version of extension are you using? which version was the first one to cause the issue?
3. Can you please share more logs?
Thanks.
<br><p><em><small>°°°</small></em></p>
