### ISSUE TITLE
When do the TabNine support the latest LSP protocol?

### ISSUE THREAD

**Issue by shuxiao9058** [codota/TabNine#68]
It seems some LSP server not work, must configuration or init first, such as https://github.com/golang/go/issues/31178#issuecomment-480105549

**Comment by zxqfl** [comment]
To make sure I understand the issue, you're saying that gopls no longer works with TabNine?

**Comment by shuxiao9058** [comment]
Now gopls is compatible with this issue, you can get more info from the comment.

**Comment by amircodota** [comment]
Hi,

Not sure I understand the issue.

Can you provide steps to reproduce?
