### ISSUE TITLE
TabNine goes berserk when it runs out of file descriptors

### ISSUE THREAD

**Issue by dotdash** [codota/TabNine#69]
I was experimenting with a project that has problems when it runs out of file descriptors and reduced my open file limit to 64. This caused TabNine to go into a loop trying to accept connections, constantly failing to do so and using all available CPUs.

strace shows an endless stream of:

```
[pid 26959] <... accept4 resumed> 0x7eff357d3720, [128], SOCK_CLOEXEC) = -1 EMFILE (Too many open files)
[pid 26958] <... accept4 resumed> 0x7eff301a8720, [128], SOCK_CLOEXEC) = -1 EMFILE (Too many open files)
[pid 26959] accept4(11,  <unfinished ...>
[pid 26958] accept4(11,  <unfinished ...>
```

**Comment by 0xpr03** [comment]
Could be related to #24 as I also hit the file limit pretty easy when switching between 3 Projectfolders (and js vs rust). VSCode shows then that the limit is reached and probably tabnine also goes berserk, would explain why I've got to restart after that.
