### ISSUE TITLE
TabNine sometimes locks directories when they're moved into project dir.

### ISSUE THREAD

**Issue by fake-name** [codota/TabNine#74]
Basically, I have often run into issues when reorganizing folders when I have sublime + tabnine open.

TabNine appears to lock a directory as it scans it's contents, and sometimes can apparently be reluctant to release the lock, requiring me to close my editor to force tabnine to close before I can move the directory in question.

![image](https://user-images.githubusercontent.com/1401239/58138865-0140cb80-7bed-11e9-8c9b-57476080ab3c.png)

This is quite annoying when it happens, and I'm not sure why it's happening at all. I could see tabnine locking *files*, but I have no idea why it's locking an entire directory (note: `sndlib_swig` in the above screenshot *is a folder*).

It seems to me that the ideal operation is that it should never hold file-handles open, or at least everything should be opened in a non-blocking/non-locking mode, if at all possible.

Note that unlocking the directory via external tools (IOBit unlocker) doesn't appear to break anything, and autocompletion continues to work.

Platform: 
 - Windows 7  
 - Sublime Text 3.2.1  
 - TabNine 1.0.14

**Comment by zxqfl** [comment]
This is surprising -- indeed TabNine should not hold file handles open. My first thought when you say it locks directories is that it's a result of TabNine watching for filesystem events, but it seems that the directories are opened with sharing enabled ([link to source](https://github.com/passcod/notify/blob/8320d0681711cc3d533a2cdb57306f3eb5b03eb7/src/windows.rs#L179)).

- Did the problem appear within the last 5 days (i.e. since the release of TabNine 1.0.14)?
- Does typing `TabNine::restart` cause TabNine to release the lock?

The simplest fix would be to globally prevent TabNine from acquiring locks, but I can't find a way to do this.

**Comment by fake-name** [comment]
> Did the problem appear within the last 5 days (i.e. since the release of TabNine 1.0.14)?

I don't *think* so, but it's just been a thing that's happened a few times and if finally annoyed me enough to post an issue.  I think it's been happening for at least a few weeks, but between tabnine, tortoisegit (which also locks stuff sometimes), I'm not really able to say when it started.

> Does typing TabNine::restart cause TabNine to release the lock?

If I'm able to get the issue to reoccur, I'll give that a shot!

**Comment by zxqfl** [comment]
> Also, FWIW, tabnine is very nice (I do python & C++), it's quite handy.

Happy to hear it!

> Is there a page that lists magic strings somewhere?

I just made one: https://tabnine.com/faq#magic_strings

**Comment by fake-name** [comment]
Neat! Once I can come up with the money I'll definitely pick up a personal license.

**Comment by fake-name** [comment]
> Does typing TabNine::restart cause TabNine to release the lock?

It does release the lock.

**Comment by fake-name** [comment]
This is getting somewhat annoying:
![image](https://user-images.githubusercontent.com/1401239/58673355-deef3200-82ff-11e9-9bd9-8242b543cbce.png)


Is there anything I can do to help resolve this? I do do development on this machine, so I have full VS and other tools available. 

Attaching to the running tabnine process shows every thread is either in >	`ZwWaitForSingleObject()` or `NtWaitForKeyedEvent()`, though there is one potentially interesting stack:

![image](https://user-images.githubusercontent.com/1401239/58673569-ba478a00-8300-11e9-94b7-ad6631eec099.png)

**Comment by zxqfl** [comment]
I'm sorry for the trouble. I'm keeping this issue in mind, and I'll try to reproduce and fix it when I get the chance. Is there a sequence of actions I could perform which would reliably reproduce the bug?

**Comment by fake-name** [comment]
It seems to be somewhat-repeatably triggerable when I move a large directory of existing source files into the sublime text project directory.

Every time I've had this happen, it's been because I was adding a big chunk of an existing codebase into a new project. 

FWIW, this is really a pretty minor issue. I've had it happen maybe 3-4 times, and it's not exactly hard to deal with. Mostly, I thought it was interesting.

**Comment by mchesser** [comment]
It's possible that it is this issue from the underlying notify crate: https://github.com/passcod/notify/issues/206

**Comment by fake-name** [comment]
Ok, this is even weirder:

![image](https://user-images.githubusercontent.com/1401239/64059683-3d81b180-cb76-11e9-88a3-5a847a18a5d9.png)

I have no idea why tabnine is even looking at these directories, *they're not even selected in sublime text*. Additionally, this is on a different computer from the previous bug reports!

**Comment by Shougo** [comment]
Tabnine searches whole files in the current directory not even opening them by editor.

**Comment by fake-name** [comment]
Yeah, but I was moving files from a zip to a folder sublime text didn't know about at all. The only way I can see what happened happening is if it's watching all changes on the entire filesystem.

**Comment by amircodota** [comment]
Does it still reproduce?

**Comment by rherwig** [comment]
@amircodota Just reproduced it.
