### ISSUE TITLE
Is there a way to limit memory usage?

### ISSUE THREAD

**Issue by ciaoben** [codota/TabNine#75]
TabNine quickly ramps up to 1GB of Memory usage... is there a way to put a limit on it? I am using it with sublime text

**Comment by zxqfl** [comment]
There is a limit, but it is set so that TabNine uses around 1GB in most instances. It would be nice to make this configurable.

**Comment by jaybenaim** [comment]
Is there a way to configure this limit?

**Comment by AmirHosseinKarimi** [comment]
Any news after 1 year?
