### ISSUE TITLE
Use Semantic completion for Salesforce Apex

### ISSUE THREAD

**Issue by jefersonchaves** [codota/TabNine#76]
Hi - Could you help me to integrate TabNine with [Salesforce Apex Language Server](https://forcedotcom.github.io/salesforcedx-vscode/articles/apex/language-server#integrate-with-the-apex-language-server)? Thanks for this awesome tool (I bought it and I'm quite happy just want to expand it further)

This is the current config file I tried:
```
[language.apex]
command = "[fullPath]/java"
args = ["-cp", "[fullpath]/apex-jorje-lsp.jar", "-Ddebug.internal.errors=true", "-Ddebug.semantic.errors=false", "apex.jorje.lsp.ApexLanguageServerLauncher"]
synchronous_triggers = ["."]
synchronous_timeout_ms = 5000
num_server_instances = 1
always_prefer = true
```

**Comment by zxqfl** [comment]
What error does TabNine give? Does the server fail to start, or does it exit after starting?

The first thing I notice is that you're running a `.jar` file without passing the `-jar` flag. Does

```java -cp [fullpath]/apex-jorje-lsp.jar -Ddebug.internal.errors=true -Ddebug.semantic.errors=false apex.jorje.lsp.ApexLanguageServerLauncher```

work when you run it in your terminal?

**Comment by jefersonchaves** [comment]
It won't show any error in the terminal. I tried replacing `-cp` with `-jar` and still did not work.

This is the error:
![image](https://user-images.githubusercontent.com/1755734/58427859-b9acba80-8098-11e9-94ad-091f49fe0d19.png)

**Comment by zxqfl** [comment]
I will add config options to log LSP output to a file in the next TabNine release.

**Comment by RetekBacsi** [comment]
Hi, I'm trying to do the same. 
I'm not sure if the language server actually exited, 'ps' shows multiple child processes with the LSP of the TabNine process, all looks alive. 
Also tee-d the stdin and stdout to files, they look good.
Replaying the messages on the command line gives the same output as logged, and the process won't quit.
Let me know it I can assist you with this further.

**Comment by jefersonchaves** [comment]
Hey @RetekBacsi - With the latest version is not throwing any error but not sure if it is kicking in, have you got any success?

**Comment by RetekBacsi** [comment]
Hey @jefersonchaves - it still dies here, with the same message. (TabNine 2.1.11, latest apex-jorje-lsp.jar) 
Maybe the timeout is too short before considering it dead?

**Comment by jefersonchaves** [comment]
I tried with 5s (5000 on config file).

**Comment by RetekBacsi** [comment]
Tried with 5s too, still "exits unexpectedly".

**Comment by jefersonchaves** [comment]
Hey, @zxqfl - are you able to give us more support on this?

**Comment by ankutty** [comment]
Is there a way to train Tab nine on custom salesforce code or a design pattern that we give ?

**Comment by jefersonchaves** [comment]
Hey @dimacodota: is this something that you or anyone could us? I love the product and would like to use the semantic completion but it keeps crashing.

**Comment by dimacodota** [comment]
Hey @jefersonchaves can you please run the LSP command from your terminal and send us the output?

**Comment by jefersonchaves** [comment]
@dimacodota, of course, I'm on holidays but once I get back to my computer will give you more info.
If you need the logs of TabNine in VsCode, let me know and I also can provide you.

**Comment by jefersonchaves** [comment]
Hi @dimacodota : I executed the command below and it returned no result:
`/usr/bin/java -jar /Users/jefersonschaves/Downloads/apex-jorje-lsp.jar -Ddebug.internal.errors=true -Ddebug.semantic.errors=false apex.jorje.lsp.ApexLanguageServerLauncher`

The jar file can be found on Salesforce repo: https://github.com/forcedotcom/salesforcedx-vscode/blob/develop/packages/salesforcedx-vscode-apex/out/apex-jorje-lsp.jar

More info about their Language Server is at https://developer.salesforce.com/tools/vscode/en/apex/language-server/

Is there anything else that I could provide to help out?

I noticed that `.cls` extensions seem to be considered Visual Basic but in this case, is the Salesforce Apex (similar to Java).
This is one example of such of file: https://github.com/trailheadapps/ebikes-lwc/blob/master/force-app/main/default/classes/OrderController.cls

**Comment by jefersonchaves** [comment]
@dimacodota:  can you let me know if there is anything else I could do?

**Comment by jefersonchaves** [comment]
Hello @dimacodota : is there any update or assistance you guys can provide?
