### ISSUE TITLE
Pls support Xcode Platform

### ISSUE THREAD

**Issue by anywherego** [codota/TabNine#83]
Xcode is more powerful for iOSer, Pls support.

**Comment by matkatmusic** [comment]
yes, Xcode support and Visual studio support would be amazing for C++ work!!!!!

**Comment by liyongping** [comment]
expect as well...

**Comment by remembermyhentai** [comment]
+

**Comment by Wildchild9** [comment]
Any update on this?

**Comment by kennyroh** [comment]
Xcode support

**Comment by 3d4m-vladimir** [comment]
+1

maybe this document can lit a bit light on the exploration stage.  https://developer.apple.com/documentation/xcodekit/creating_a_source_editor_extension
