### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by sirn** [codota/TabNine#9]
It would be great if there's TabNine binary for FreeBSD platform. I mainly work on macOS and on FreeBSD, and I think it would be great if I could use TabNine on both platforms.

Thanks!

**Comment by Gandalf-** [comment]
I would also really like this!

**Comment by lcw** [comment]
For what it is worth, with FreeBSD's [Linux binary comparability][1] I have been able to run the
`x86_64-unknown-linux-gnu` version of `TabNine`.

[1]: https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/linuxemu-lbc-install.html

**Comment by jonatkinson** [comment]
I wrote a brief guide on how to set this up. For anyone else who stumbles upon this ticket: https://jonatkinson.co.uk/tabnine-on-freebsd
