### ISSUE TITLE
Support Dart and by extension Flutter.

### ISSUE THREAD

**Issue by Solido** [codota/TabNine#98]
Flutter is a UI DSL currently pushed by Google. It use the Dart programming language.
There are very very common patterns than can be easily identified and since commands can be recurring I see a perfect match here.

Dart is object oriented and is very close to java so we can expect some common points with other supported langs.

Also is had Language Server Protocol support and first class tooling for Intellij and VSCode.

Flutter is the Fastest-Growing Skill Among Software Engineers on Linkedin
https://adtmag.com/articles/2019/03/29/linkedin-skills.aspx

So we'd like to train the set on specific repos to generate and helping tools on best practices.

Thank you for considering this request !

**Comment by zxqfl** [comment]
Ok, we will aim to support Dart when Deep TabNine is retrained.

(Vanilla TabNine already supports Dart -- we have a default choice of language server [here](https://github.com/zxqfl/TabNine/blob/768e452d38238460d4a559006571255d4d9c058d/TabNine.toml#L45))

**Comment by flowpatterns** [comment]
I've been playing around with this for the past hour thinking I was making a mistake. Yes, thank you for adding Dart/flutter support.

Also, can you add support for Jupyter notebook/lab? I do a ton of testing on jupyter notebook and lab and I think a lot of AI/ML people would love it if they can get TabNine on Jupyter.

Thanks for your great work!

**Comment by Solido** [comment]
Hi @zxqfl 

Thank you for considering our request, we are very excited about this and how TabNine will change our every day coding process.

We can provide a filtered list of github Flutter repos to maximise the recognition because Flutter DSL is our real target, not Dart.

Let us know how we can help you 👍

**Comment by wenmin-wu** [comment]
@flowpatterns https://github.com/wenmin-wu/jupyter-tabnine

**Comment by vytautas-pranskunas-** [comment]
any updates on this? now when github copilot becomes not free I am keen to choose best alternative...
